### ISSUE TITLE
Transporter - Datadog

### ISSUE THREAD

**Issue by gkatsanos** [pinojs/pino#1001]
I added `pino` and tried to see my logs in Datadog unsuccessfully. Later I read the section regarding the limitations and design decisions of Pino [with regards to logging in process vs out of process](https://github.com/pinojs/pino/blob/master/docs/transports.md#in-process-transports).

I was wondering how this can work with regards to passing the transporter on the cl level (keys?). I'm afraid the impact of this design decision is that integrating the logger involves devops (instead of having everything at the code level).

Could you provide some insights? Do I have to use pino-multi-stream ? 

Thank you for your time :)

**Comment by mcollina** [comment]
What are you using to ship logs to DataDog?

**Comment by gkatsanos** [comment]
Hey Matteo, appreciate the quick feedback. 
Bear with me if I dont get the facts right but we have a dockerized app and from my understanding stdout/stderr is auto-magically piped to DD.  ( https://docs.datadoghq.com/agent/docker/log/?tab=containerinstallation ) . We don't do anything `manually`.

**Comment by jsumners** [comment]
DataDog natively supports Pino. Load `dd-trace` before you load `pino` and DD will instrument Pino. This will in turn ship your logs to DD via their sidecar.

**Comment by gkatsanos** [comment]
```js
const tracer = require('dd-trace')

export default function Datadog() {
  tracer.init({
    hostname: process.env.DD_AGENT_HOST,
    service: 'xxx',
    env: process.env.STAGE,
    logInjection: true,
  })
}
```
later..
```js
const logger = require('pino')()
$axios.onRequest((config) => {
    if (!config.url.includes('switcher.internal') && !config.url.includes('traffic-source')) {
      logger.info({
        // date: new Date().toISOString(),
        http: {
          params: config.params,
          baseURL: config.baseURL,
          referer: config.headers.common.referer,
          url: config.url,
          method: config.method
        },
      }, `[${config.method}] ${config.url}`)
    }
```

**Comment by jsumners** [comment]
> if DD natively supports Pino, why's pino-datadog necessary?

Such questions should be asked to the DD support team.


> I thought pino doesn't send logs anywhere unless you explicitely set it up to do so.

As of v6, Pino _never_ ships logs anywhere. That is completely the user's responsibility. What I said is that DD supports instrumenting the Pino logger. See https://docs.datadoghq.com/tracing/connect_logs_and_traces/nodejs/

**Comment by gkatsanos** [comment]
@jsumners can you elaborate on "instrumenting" ?

**Comment by jsumners** [comment]
It's outlined in the link I provided in my last reply. Additionally https://opentracing.io/docs/best-practices/instrumenting-frameworks/

**Comment by gkatsanos** [comment]
@jsumners ah yes , instrumenting is not the point of my thread/question I guess. Instrumenting as seen above in my screenshot does happen, but I'm one step before that: I'm not sure how to pipe the logs to Datadog in the first place. 
I hope @mcollina will have some pointers on how to proceed with regards to pino-datadog and pino-multi-stream ?

**Comment by Fdawgs** [comment]
@gkatsanos Did you manage to resolve this?

**Comment by gkatsanos** [comment]
We used simple console log and we did our own formatting.
