### ISSUE TITLE
level-change event fired when child is created

### ISSUE THREAD

**Issue by laSinteZ** [pinojs/pino#1006]
When I create a child instance of a logger, `level-change` event is fired. This, for example, causes 2 events per request in `pino-http` (can provide simple repro). I am not sure if it's desired behaviour, since it isn't described in the documentation and can be a bit confusing. If it is a desired behaviour, I can help expanding the documentation.

Example code:
```
const pino = require("pino");
const logger = pino();

logger.on("level-change", () => {
  console.log("level-change event had happened");
});

logger.info("Hello, world. No events.")
logger.child({});
logger.child({});
logger.child({});
logger.child({});
```

Output:
```
{"level":30,"time":1618034735938,"pid":16304,"hostname":"MacBook-Air.local","msg":"Hello, world. No events."}
level-change event had happened
level-change event had happened
level-change event had happened
level-change event had happened
```

**Comment by jsumners** [comment]
It happens because we need to set the level on the child instance: https://github.com/pinojs/pino/blob/84fa44b965e5b5bb2d51eb56583ef6b61e0244ef/lib/proto.js#L124

Which in turn invokes: https://github.com/pinojs/pino/blob/84fa44b965e5b5bb2d51eb56583ef6b61e0244ef/lib/levels.js#L84-L111

I _suppose_ an optional second parameter can be passed to signal omitting the event.

**Comment by mcollina** [comment]
I think this is a _bug_, as we should call reinitialize the EventEmitter state when creating a child. However, I'm not sure this is worth the overhead!

**Comment by laSinteZ** [comment]
Well, I guess at least it's worth to document it, since I was quite surprised to see those events polluting logs (even though I've solved it with simple if newVal !== prevVal in my handler)

**Comment by mcollina** [comment]
If you would like to try fixing it, I'd welcome a PR. The problem is caused by child loggers "inheriting" their parent event listeners.

**Comment by mcollina** [comment]
A PR updating the doc is also fine.

**Comment by laSinteZ** [comment]
@mcollina wouldn't it be effectively a breaking change if child loggers WON'T inherit event listeners though? I believe someone could rely on this functionality.

**Comment by mcollina** [comment]
> @mcollina wouldn't it be effectively a breaking change if child loggers WON'T inherit event listeners though? I believe someone could rely on this functionality.

version numbers are there to be bumped. We have the next branch that we accumulate all our breaking changes and then ship them.
