### ISSUE TITLE
Misleading error message on wrong options value

### ISSUE THREAD

**Issue by vladshcherbin** [pinojs/pino#1007]
Hey 👋 

When passing wrong option value (`ignore` as an array):

```js
pino({
  prettyPrint: {
    ignore: ['hostname']
  }
})
```

The error in console is:

```console
Error: Missing `pino-pretty` module: `pino-pretty` must be installed separately
```

I think it's quite misleading, would be nice to have an options error or smth.

pino - 6.11.2
pino-pretty - 4.7.1

Thanks

**Comment by jsumners** [comment]
What is misleading about it? If you configure pretty printing without `pino-pretty`, or other compatible module, installed then pretty printing is impossible.

**Comment by vladshcherbin** [comment]
@jsumners the misleading thing it that I have `pino-pretty` installed but the message says it's not. If I change option to correct value (`'hostname'` instead of `['hostname']`) error disappears.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
