### ISSUE TITLE
Feature: support rotating files

### ISSUE THREAD

**Issue by xmedeko** [pinojs/pino#1009]
Support file rotating transport for environments when logrotate is missing e.g. Electron.js apps. It could be implemented e.g. by [rogerc/file-stream-rotator](https://github.com/rogerc/file-stream-rotator) (used by [winstonjs/winston-daily-rotate-file](https://github.com/winstonjs/winston-daily-rotate-file) and many other projects). It could be a separate module.

**Comment by jsumners** [comment]
We believe this is outside of the scope of a logger.

**Comment by xmedeko** [comment]
It's pitty. I like pino's fast async file destination. But for Electron.js destkop app, wee need file rotation build in.

**Comment by jsumners** [comment]
You control the stream. You should be able to implement log rotation according the requirements of your application and the environment(s) it runs under.

**Comment by micalevisk** [comment]
@xmedeko they already covered it here: https://getpino.io/#/docs/help?id=rotate

I'm using [`@vrbo/pino-rotating-file`](https://github.com/ExpediaGroup/pino-rotating-file) with no worries ^^

**Comment by xmedeko** [comment]
@micalevisk cannot use logrotate as I have written. The [ExpediaGroup/pino-rotating-file](https://github.com/ExpediaGroup/pino-rotating-file) is what I was looking for, thanks.
IMO it would be great if this or a similar transport would be under @pinojs umbrella 😉

**Comment by davidmarkclements** [comment]
there's two things that can be done here depending on appetite

* add pino-rotating-file to the ecosystem -> community, section of the docs
* OR request (new issue) that the pino team review it and then add it to the pinojs org and make it part of core, with current maintainers continuing to maintain it. Given that it's under another company org, it's possible that the maintainers aren't interested in this option (which is totally fine of course)

**Comment by micalevisk** [comment]
@davidmarkclements `@vrbo/pino-rotating-file` is already in the docs _community_ section but with the old name `pino-rotating-file`. To me this is fine because they're maintaining it (I guess)

**Comment by xmedeko** [comment]
Unfortunately, @vrbo/pino-rotating-file is not async like SonicBoom, i.e. has not buffer and relies on the Node.js event queue only. Solution could be
1. implement rolling into SonicBoom.
2. or, do async with (formatted) log buffering in Pino and then allow to plug any stream into it - similarly to log4j `AsyncAppender`.
3. make a stream roller with pluggable any stream (e.g. a bit modified [streamroller](https://github.com/log4js-node/streamroller))

IMO the 2. is the best option, so as a users may have benefit with any other streams - TCP, HTTP, etc.

**Comment by jsumners** [comment]
Log rotation is a project unto itself. That is why https://github.com/logrotate/logrotate exists. It is not a trivial problem.

**Comment by xmedeko** [comment]
I agree logrotate is a good solution, but not for everyone. This issue is about solid build in log rotation.

The point 2. is not just about stream rotation, is about versatile async buffering for any stream. Then, any stream, even existing 3rd party rolling stream, may be plug into it. As I have mentioned, similar async buffers are in Java log4j, Python logging, C# NLog and others.

**Comment by jsumners** [comment]
> As I have mentioned, similar async buffers are in Java log4j, Python logging, C# NLog and others.

That may be, but they opted to add that maintenance burden and we have opted not to. If @mcollina and @davidmarkclements are willing to entertain PRs for the feature, then fine. But I do not think this belongs in the logger itself.

**Comment by mcollina** [comment]
@xmedeko all of your problems will be solved by the new transport system we are developing in https://github.com/pinojs/pino/pull/1003.

Note that you can develop something already using [`thread-stream`](http://npm.im/thread-stream), essentially running your async log rotation in a separate process while keeping the main stream logging synchronous.

**Comment by xmedeko** [comment]
@mcollina @vrbo/pino-rotating-file is async, but it lack a feature to throw away logs in case of massive logging (massive logging is a bug or other failure). E.g. SonicBoom has 16MB `MAX_WRITE` buffer. So my point is - pull that buffer from SonicBoom higher to some kind of `AsyncTransportWrapper` and then any async transport may be plugged into it and do not need to care about this protection. Other logging frameworks I have mentioned do it the same way.

Anyway, your solution looks great for both transports - sync and async, too. Even the existing rolling async stream have a bit of sync code, like rolling the file, unfortunately, Just do not forget to protect your buffers 😉

**Comment by weagle08** [comment]
check out bunyan... similar API, supports rotating log files out of the box
