### ISSUE TITLE
Syslog severity level

### ISSUE THREAD

**Issue by cojack** [pinojs/pino#1010]
Hi,
I would like to implement syslog severity level as follows:

```javascript
var pino = require("pino");
  
const customLevels = {
  emerg: 0,
  alert: 1,
  crit: 2,
  err: 3,
  warning: 4,
  notice: 5,
  info: 6,
  debug: 7
};

const logger = pino({ customLevels, useOnlyCustomLevels: true, level: 'debug' });

logger.alert('wooo');
```

But then this log is not presented, why?

**Comment by jsumners** [comment]
I would set some breakpoints in https://github.com/pinojs/pino/blob/0a56154fa0a24ac2b4015b597e6ae06468821699/lib/levels.js to determine the cause.

But I'd also ask if using https://github.com/pinojs/pino-syslog is not possible.

**Comment by cojack** [comment]
@jsumners pino-syslog convert to syslog format, I'm just curious how to override default pino severity levels with syslog one, but severity value is upside down.

**Comment by jsumners** [comment]
We established a log time ago that our algorithm is  `>=` instead of `<=`. https://github.com/pinojs/pino/issues/123

**Comment by cojack** [comment]
@jsumners any future plan to provide a callback to override this behaviour?

**Comment by Fdawgs** [comment]
@cojack Did you manage to resolve this?
