### ISSUE TITLE
limiting logs 

### ISSUE THREAD

**Issue by hibaAkroush** [pinojs/pino#1019]
hello 

is there a way to group logs in pino?

im trying to silence logger in case of huge number of duplicate logs in short period of time.

**Comment by mcollina** [comment]
It's not currently possible. You might be able to write a custom transport for this use case with #1003

**Comment by hibaAkroush** [comment]
@mcollina 
thanks Matteo, would a transport work without the usage of filesystem? in my case the logs are sent to the console in real time and another service listens to it im not writing the logs in a file

**Comment by mcollina** [comment]
That would be the target use case, yes.

**Comment by hibaAkroush** [comment]
solved it by using hooks 

`
messages = [];      
hooks:{
        logMethod (inputArgs, method, level) {
          if(!messages.includes(inputArgs[0].text)){
            messages.push(inputArgs[0].text)
            return method.apply(this, inputArgs)
          } else {
          // filter out duplicate logs 
            return;
          }
        }
      }
`
