### ISSUE TITLE
Suggestion: Write an easy console and file sample

### ISSUE THREAD

**Issue by sondreb** [pinojs/pino#1023]
I was looking into pino and started using it a bit on a new project, but I needed to log info level to disk and debug level to console, at least during development. I was unable to find any easy way to do this, and the very first example I found of a competing logging library did exactly this.

It might be just something I usually do, but I often need basic console and file logging, so I suggest some easy to find and use sample on how to log both to console (at different levels) and file.

**Comment by mcollina** [comment]
This will be part of https://github.com/pinojs/pino/pull/1003 and pino v7.

**Comment by mcollina** [comment]
This was done as part of https://github.com/pinojs/pino/pull/1003
