### ISSUE TITLE
Sets are not loggable

### ISSUE THREAD

**Issue by nate-anderson** [pinojs/pino#1025]
Using Pino v6.11.3, Sets cannot be logged.

Example:
```ts
const logger = require("pino")();
const s = new Set([1, 2, 3]);
logger.info(s, "hello set");
// {"level":30,"time":1620852114101,"pid":2319,"hostname":"Nathans-MacBook-Pro.local","msg":"hi"}

logger.info({ s }, "hello set property");
// {"level":30,"time":1620852114101,"pid":2319,"hostname":"Nathans-MacBook-Pro.local","s":{},"msg":"hi"}
```

The workaround I have found is coercing the set to an array, with `[...s]` or `Array.from(s)`. It would be nice to be able to log sets, though, as their notation is different from arrays.

I've confirmed the behavior in Node.js v10.23.1 w/ TypeScript v4.1.3, and Node.js v12.22.1 with and without Typescript v3.7.5

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/issues/627
