### ISSUE TITLE
tool to externalize serializers

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#103]
Proposal: A module that wraps a pino serializer (like [pino-noir](http://npm.im)) into a stream that can run as a second process

Naming for this could be hard:  "pino-exo"  ..?

**Comment by mcollina** [comment]
that would be awesome. We can in fact just reuse pino-noir. Maybe it can even be a global executable there `node server | noir`.

**Comment by davidmarkclements** [comment]
yes a `noir` executable could work but I'm thinking one of two options

1. a utility module that make this really easy for any serializer module

```js
#!/usr/bin/env node
require('pino-exo')(require('./'))
```

2. and/or possibly a executable that wraps a serializer
```sh
$ node server | pino-exo --serializer=pino-noir 
```

**Comment by mcollina** [comment]
So, I'm ok for `pino-exo`, but not as a CLI tool. `pino-noir`  still needs its config etc.

**Comment by jsumners** [comment]
My only opinion on this is that it shouldn't completely replace the current serializers feature. To do so would break the API compatibility with Bunyan. Thus, it would be more difficult for new adopters to replace Bunyan in their application with pino.

**Comment by davidmarkclements** [comment]
could not agree more - it's an option for someone who wants to make sure their event loop is free

some may even have a business constraint that doesn't allow them to serialize in a separate process (e.g. being paranoid about redaction for instance, don't want a chance it can leak if piped to the wrong place) 

Having this option could be useful extreme cases (for instance in the case of pino-noir, say very large objects are being logged, and with lots of deep nested redaction and wildcard usage)
