### ISSUE TITLE
Possible to remove a binding?

### ISSUE THREAD

**Issue by stowns** [pinojs/pino#1038]
I have been unable to determine the correct way to remove a binding from a logger instance. Is there a preferred (or possible way) to do this? It's quite easy to add bindings by creating a child logger. However, if I want to remove some context from a logger there doesn't appear to be an obvious way to do this. Can anyone help with this? thanks in advance for any insight

**Comment by mcollina** [comment]
That's not possible at the moment. You'd need to generate a new child logger.
