### ISSUE TITLE
Undefined interpolation value, strange log message

### ISSUE THREAD

**Issue by suhaig** [pinojs/pino#1054]
Hi,

just a minor thing. I have this very simple logging:

```
logger.debug("test: %o", anObject);
``` 
If `anObject` is `undefined` then the log message will be:

`"msg": "test: test: %o"`

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
I am facing the same problem and it is not only for `%o`. It happen for all placeholder expect `%s`.
My Repo Link: https://replit.com/@climba03003/pino-j-with-undefined
