### ISSUE TITLE
Issue with Pino and Webpack/Browserify

### ISSUE THREAD

**Issue by lagnat** [pinojs/pino#1063]
My goal is to use a particular node module in the browser.  That module is using Pino.  With both Browserify and Webpack the require for pino is returning null.

 ```
const pino_1 = require("pino");   // Returns null
```

I can see pino in the packaged file so I know it's there but not sure how to debug this.  Thanks for any suggestions.

**Comment by mcollina** [comment]
I have no clue.

**Comment by lagnat** [comment]
I was hoping you might.  I'll report back if I find anything specific to pino.  Closing.

**Comment by lagnat** [comment]
Following up with some likely explanation of what's going on.

The setup.  A node module that uses pino has some code like this:
```
const pino_1 = require("pino");
const logger = pino_1.pino({...});
```
This works as expected because pino.js exports the pino function like this:
```
module.exports.pino = pino
```
However when going through browserify or webpack, the browser-specific version of pino is used (browser.js, as specified in package.json) and that code exports the pino function like this:
```
module.exports = pino
```
The end result being that `pino_1.pino()` is undefined.

Exactly what I'm going to do about this, I'm not sure yet, but I hope this helps someone else.
