### ISSUE TITLE
My apps is not responding when too much logs happen

### ISSUE THREAD

**Issue by meotimdihia** [pinojs/pino#1064]
I posted this question to https://github.com/fastify/help/issues/482 . But It looks like I will not get the answer because this was related to pinots.  

Systemd command of my app: `/bin/bash -c '/usr/bin/node -r source-map-support/register /home/meotimdihia/sources/api/dist/src/index.js | tee >(/home/meotimdihia/sources/api/node_modules/.bin/pino-stackdriver --project api-xxxxxx --credentials /home/meotimdihia/logging-229904-xxxxxxxxx.json --logName api)'`

This error was happened when I used `pino-stackdriver` with logger level `info`. Currently, I have to limit the log level to `warn`.
```js
const server = fastify({
  logger:{ level: "warn" }
})
```

Do we have a way to solve this problem like Asynchronous Logging with transports? or other ways...

**Comment by mcollina** [comment]
The application is blocking because you are using synchronous logging (the default) and the pipe is full (cannot write more logs).

If you are producing logs in bursts, using an asynchronous destination will solve this at the expense of an increase memory usage.

There is also a small fix to do in pino-stackdriver: it currently waits a log line is uploaded and it does not perform batching but uploads one at a time.

Those two things combined should solve your problem or improve the situation.

**Comment by meotimdihia** [comment]
@mcollina thanks for the answer, but it seems asynchronous just push logs to file:
https://github.com/pinojs/pino/blob/master/docs/asynchronous.md

And I tried this but stuck at "how to push logs from file to stackdriver".

**Comment by mcollina** [comment]
This will do

```js
const pino = require('pino')
const logger = pino(pino.destination({
  sync: false // Asynchronous logging
}))
```

**Comment by meotimdihia** [comment]
@mcollina: Thanks for the answer. But I apologize I have forgotten why I tried the above code too then I reverted it to the current code: 
```
import fastify from "fastify"

const server = fastify({
  trustProxy: true,
  logger:
    process.env.NODE_ENV === "development"
      ? {
          prettyPrint: true
        }
      : { level: "warn" }
})
```

Could you help me to update how to use prettyPrint + level warn with your code in Fastify? 
```js
const pino = require('pino')
const logger = pino(pino.destination({
  sync: false // Asynchronous logging
}))

**Comment by meotimdihia** [comment]
I just have known how to create an instance pinojs with this. Sorry for waste your time.
```
const pino = require("pino")
const logger = pino(
  process.env.NODE_ENV === "development"
    ? {
        prettyPrint: true
      }
    : { level: "warn" },
  pino.destination({
    sync: false // Asynchronous logging
  })
)
```
Now, I have to wait for a fix from `pino-stackdriver`. Thanks for your responses.
