### ISSUE TITLE
Child log not overwriting parent property?

### ISSUE THREAD

**Issue by AviBueno** [pinojs/pino#1068]
Hi, the goal in the below example is to overwrite `reqId` in child logs. Instead, it is being chained.
I can't tell if this is a bug or a feature, but I would love to get some guidance on how to achieve the above goal.

```
import pino from 'pino';

let logger = pino();

logger = logger.child({ reqId: '1' });
logger.info('1');
logger = logger.child({ reqId: '1-2' });
logger.info('2');
logger = logger.child({ reqId: '1-2-3' });
logger.info('3');

// Output:
// {"level":30,"...","reqId":"1","msg":"1"}
// {"level":30,"...","reqId":"1","reqId":"1-2","msg":"2"}
// {"level":30,"...","reqId":"1","reqId":"1-2","reqId":"1-2-3","msg":"3"}
```

**Comment by jsumners** [comment]
https://getpino.io/#/docs/child-loggers?id=duplicate-keys-caveat

**Comment by AviBueno** [comment]
Thanks for the clarification @jsumners
For reference, this is not a theoretical case, we actually experience that in AWS CloudWatch logs
![image](https://user-images.githubusercontent.com/5699730/125463260-e23a5d96-e41c-4e4a-8bda-0d7913f47ae7.png)

**Comment by mcollina** [comment]
If you parse that JSON object, you'll get the correct value.
