### ISSUE TITLE
[Question] Per-level verbosity

### ISSUE THREAD

**Issue by c-simpson** [pinojs/pino#1088]
I'm using (and loving) Pino for logging on an API server. Is it possible to change the amount of information a particular logger invocation logs depending on the current log level? _e.g._,
For a particular logger.info() call at 'info', I just want X to show up in the logs.
But if the current log level is 'debug', I'd like that logger.info() call to include X _and_ Y.

As far as I can tell, the two options to achieve this would be

- A switch statement on the log level that executes _different_ calls depending on the current level
- Per-level redaction specifications where you could call logger.info() with everything you might want to log. Nothing gets redacted at 'trace', some gets redacted at 'debug', more gets redacted at 'info'.

Is there another option I've missed? The first seems very ugly; the second seems like a fair amount of work. Are there other reasons not to consider the second option? 

Thanks.

**Comment by jsumners** [comment]
Generally one would issue two logs: an `info` level log containing only the information important to be in recorded production logs and a `debug` level log that contains extra information important to debug issues.

**Comment by c-simpson** [comment]
Thanks, James.
