### ISSUE TITLE
Named Instances - Is it possible?

### ISSUE THREAD

**Issue by Zurdge** [pinojs/pino#1094]
Hi folks, 
I've tried finding the answers for this on the Pino and Pino-http github pages but have not really been able to find an answer.
I've got a seq service running as a named instance e.g. ```seq service install -n Server -l http://localhost:5341/server```

How can I configure pino to post to that endpoint?

Thanks :)

**Comment by mcollina** [comment]
It is definitely possible, however I have never used seq, so I do not know what config would be needed to implement this.

**Comment by marcbachmann** [comment]
https://www.npmjs.com/package/bunyan-seq might be a good start. That might only need a few adoptions 😉 
Or solve it on the instructure level itself: https://docs.datalust.co/docs/collecting-kubernetes-logs
