### ISSUE TITLE
next: worker-thread messages not log when pino used in both main-thread and worker-thread

### ISSUE THREAD

**Issue by climba03003** [pinojs/pino#1095]
When I use pino in both main-thread and worker-thread. Only the main-thread can log messages.

Repro Link: https://replit.com/@climba03003/pino-issue-1095

```js
// index.js
const { logger } = require('./logger.js')
const { Worker } = require('worker_threads')

const worker = new Worker('./pino.js')
setTimeout(function() {
  worker.terminate()
  process.exit(0)
}, 3000)

logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')

// logger.js
const pino = require('pino')

const logger = pino({ level: 'trace' }, pino.transport({
  targets: [
    { level: 'info', target: '#pino/file', options: {} }
  ]
}))

module.exports.logger = logger

// pino.js
const { logger } = require('./logger.js')

logger.info('worker - should show')
logger.info('worker - should show')
logger.info('worker - should show')
logger.info('worker - should show')
logger.info('worker - should show')
logger.info('worker - should show')
logger.info('worker - should show')

process.exit(0)
```

**Comment by mcollina** [comment]
Removing `process.exit(0)` from `pino.js` fixes it. The hooks that we use `beforeExit` and `exit` do not work the same in worker_threads so we cannot hook things correctly.

Maybe you could send a PR?

**Comment by climba03003** [comment]
I do not know if I can comes up a solution. I have tested a lot of method, it seems that when ever I called `process.exit` in the end of `worker_threads`, the worker is exit faster than `pino` can do anything (include register a process hook).

I would be better to use `process.emit('beforeExit')` to terminate the worker.

**Comment by JekRock** [comment]
From my understanding, the issue is that `process.on` doesn't deliver messages inside a worker thread.
From the [documentation](https://nodejs.org/docs/latest-v14.x/api/worker_threads.html#worker_threads_class_worker):
> Notable differences inside a Worker environment are:
> - Signals will not be delivered through process.on('...').

I don't see a way to attach a listener to the `exit` event from inside a worker thread when `process.exit(0)` is called  though.

**Comment by mcollina** [comment]
const { logger } = require('./b.js')

logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')
logger.info('main - show log')

process.exit(0)
```

The `process.exit(0)` will block the worker thread initialization. It's not possible to make it work :/.
