### ISSUE TITLE
child process/thread and interleaved stdout output

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#1098]
We just encountered a little weird output from one of our services. We use both worker threads and cluster in this service. All of the child processes/threads use pino with `sync: false` to output to stdout. What we've noticed is that sometimes the output of the different child process become interleaved which makes us think that the writes from pino are not atomic in the sense that the full string of serialized json is guaranteed to be transferred to the parent process stdout in one piece.

Are we doing something wrong here? Should we instead use pino-transport to "transport" all messages from child processes to the parent process and have only the parent process write to stdout?

Pino: @6.13.0

**Comment by ronag** [comment]
Seems related to cluster / child process + `sync: false`. We changed to `sync: true` on our http cluster workers.

**Comment by ronag** [comment]
I suspect this can have something to do with sonic boom `MAX_WRITE` which I think might cause messages to be split.

**Comment by jsumners** [comment]
A test case would be most helpful.

**Comment by mcollina** [comment]
I think the diagnosis is correct and #96 is the only solution.

**Comment by ronag** [comment]
> I think the diagnosis is correct and #96 is the only solution.

Do you mean https://github.com/pinojs/sonic-boom/issues/96?

**Comment by mcollina** [comment]
ah yes.

**Comment by zekth** [comment]
I can confirm i'm encountering something similar when logging a huge amount of data to stdout too.

**Comment by zekth** [comment]
6.13.2

**Comment by mcollina** [comment]
@zekth I would say try with pino@7. It should solve this.
