### ISSUE TITLE
pino tried to access pino-pretty, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound

### ISSUE THREAD

**Issue by Unbuttun** [pinojs/pino#1102]
While using pino and enabling the pretty print module, while installing or using the application through yarn 2/3 it starts complaining and refusing to start with error.

Example - 
```ts
  const app = await fastify({
    logger: {
      prettyPrint: true
    }
  });
```
  
Now when we start the app, yarn will give this error - 

```shell
pino tried to access pino-pretty, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Currently, we need to add this into `.yarnrc.yml`
```yml  
packageExtensions:
  pino@*:
    dependencies:
      pino-pretty: "*"
```
  
Stack trace 
```shell
Require stack:
- /1/app/server/.yarn/cache/pino-npm-6.13.1-69c64f98df-8124217b9f.zip/node_modules/pino/lib/tools.js
- /1/app/server/.yarn/cache/pino-npm-6.13.1-69c64f98df-8124217b9f.zip/node_modules/pino/lib/levels.js
- /1/app/server/.yarn/cache/pino-npm-6.13.1-69c64f98df-8124217b9f.zip/node_modules/pino/lib/proto.js
- /1/app/server/.yarn/cache/pino-npm-6.13.1-69c64f98df-8124217b9f.zip/node_modules/pino/pino.js
- /1/app/server/.yarn/cache/fastify-npm-3.20.2-2983538579-ae02705d72.zip/node_modules/fastify/lib/logger.js
- /1/app/server/.yarn/cache/fastify-npm-3.20.2-2983538579-ae02705d72.zip/node_modules/fastify/lib/reply.js
- /1/app/server/.yarn/cache/fastify-npm-3.20.2-2983538579-ae02705d72.zip/node_modules/fastify/fastify.js
- /1/app/server/apps/server/dist/main.js
    at /1/app/server/apps/server/dist/main.js:53:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mcollina** [comment]
The default package manager for Node.js is npm. It is your choice to use a package manager whose maintainers have decided to change the behavior of module resolution. Adding pino-pretty to dependencies or peerDependencies will cause a few additional modules to be installed for production usage.. and I am pretty sure that a lot of devs care about package size too.

There is a slightly more complicated way to load the dependency than what we are currently doing that should make yarn and/or pnpm happy and not complain. If you are interested, check out: https://github.com/fastify/fastify-plugin/blob/cc20d5fc63a804889df9c5bb8dc71bcf90b2506d/plugin.js#L81.

It has some downsides too, as it might not work for bundled applications (and in fact we reverted it in further releases of that module).

Given how many people complains about this option, I think our best path forward is deprecate it in v7 and point folks to use it directly from transport.

**Comment by mcollina** [comment]
Here is my solution to this: https://github.com/pinojs/pino/issues/1106.

**Comment by jsumners** [comment]
I am closing this in favor of #1106. @Unbuttun please follow along there.
