### ISSUE TITLE
Deprecate prettyPrint: true

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#1106]
We had too many folks complaining about how we load pino-pretty with yarn 2/3 and similar. I think we should either

1) require the user to pass in a reference to pino-pretty
2) make pino-pretty a full transport and let folks use it from there.

**Comment by jsumners** [comment]
I'd prefer to fully deprecate it from Pino. Let people pass in a transport or whatever that does it. I'd also like to keep `pino-pretty` narrowed to its current focus: parsing `stdin`. If necessary, and possible, I'd rather see us create `pino-pretty-transport` to provide the transport.

**Comment by leorossi** [comment]
Hi guys, I am willing to work on this.

Just to be clear, the intention of this is 
- remove `prettyPrint` option from constructor
- remove all tests that relies on this feature (i.e: checking the output has been "prettified" and things like this)
- remove all documentation related to that option, and redirect to `pino-pretty` 

is that correct?

Do we want to show a warning when passing `{ prettyPrint: true }` in the constructor?

**Comment by mcollina** [comment]
I have some code prepared for this, wait until I upload it (might take a few days).

**Comment by zhex900** [comment]
Hi,

I am using streams. What should I do to remove the deprecation message?

```

const loggerStream = () => {
  const logPath = path.resolve(
    process.platform === "win32"
      ? `${WIN_LOG_PATH}/${LOG_FILE}`
      : `${getAppDataPath()}/${LOG_FILE}`
  );
  return multistream(
    [
      {
        level: "error",
        stream: createStream(logPath, LOG_ROTATION_SETTINGS),
      },
      {
        level: "debug",
        stream: createStream(logPath, LOG_ROTATION_SETTINGS),
      },
      {
        stream: createStream(logPath, LOG_ROTATION_SETTINGS),
      },
    ],
    { dedupe: true }
  );
};

const logger = pino(
  {
    prettyPrint: {
      colorize: true,
      errorLikeObjectKeys: ["err", "error", "details"],
      levelFirst: true,
      translateTime: "SYS:hh:MM:ss TT dd-mm-yyyy",
      ignore: "pid,hostname,service",
      messageFormat: (log, messageKey) => {
        return applyServiceStyles(log, messageKey);
      },
    },
    level: process.env.LOG_LEVEL || "debug",
    serializers: {
      error: pino.stdSerializers.err,
    },
  },
  loggerStream()
);
````
