### ISSUE TITLE
Test pino.transport() with pnpm and yarn 2/3 pnp

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#1107]
As titled, we need to verify how we load 3-party transports in yarn 2/3 pnp and pnpm. Use pino-elasticsearch for testing if if all works fine.

**Comment by Eomm** [comment]
Working on it!

**Comment by Eomm** [comment]
> Use pino-elasticsearch for testing if all works fine.

Is it not updated to pino@7, or doesn't it need any change?

**Comment by mcollina** [comment]
it has been already updated.
