### ISSUE TITLE
Provide a default logger as part of the pino module

### ISSUE THREAD

**Issue by 0x2b3bfa0** [pinojs/pino#1108]
[Winston](https://github.com/winstonjs/winston) provides a default logger as part of the module and, to my mind, it's very convenient when there is no need to maintain a separate file for the common logging logic. Would it be advisable to have something similar in the `pino` module?

> _[The default logger is accessible through the `winston` module directly. Any method that you could call on an instance of a logger is available on the default logger.](https://github.com/winstonjs/winston#using-the-default-logger)_ (from the `winston` documentation)

```javascript
const logger = require('pino')()
logger.info('this is the current approach')
```

```javascript
const pino = require('pino')
pino.info('this is the suggested approach')
```

**Comment by mcollina** [comment]
I would recommend hardly against this. A logger is application specific: by making it global we would need to make it configurable.. and multiple modules might need different settings.

I do not store it as a global in my application either.

**Comment by 0x2b3bfa0** [comment]
Thanks for your feedback, @mcollina!

I was wondering what the best approach would be for a command-line application where logging is configured once and then used with the same settings across different files.

Keeping a separate file just for the logger and importing it from each source file doesn't seem especially convenient, and storing it as a global... Globals are Evil™ in most situations.

**Comment by mcollina** [comment]
Each node module is loaded only once, and it's attached to a global variable. Providing a default logger (or one within a module) is identical to use a global.

**Comment by 0x2b3bfa0** [comment]
> _Each node module is loaded only once, and it's attached to a global variable._
> _Providing a default logger (or one within a module) is identical to use a global._

The only difference would be that explicitly using a global makes it harder to determine the place where it came from, but having to import/require the logger from each file would, at least, give a clue about its origin.

Anyhow, is there a better practice to use a single logger from many files without having to reconfigure it over and over? Maybe I was trying to solve an [XY problem](https://xyproblem.info).

Thank you very much for your help!

**Comment by kibertoad** [comment]
@0x2b3bfa0 One of the better approaches is by using [dependency injection](https://github.com/jeffijoe/awilix) - if you use fastify, there is [plugin](https://github.com/fastify/fastify-awilix) for that as well.

**Comment by jsumners** [comment]
`const logger = require('./lib/logger')` is the regular Node way.

**Comment by 0x2b3bfa0** [comment]
Thank you very much for all your suggestions! [`yargs.parse`](https://yargs.js.org/docs/#api-reference-parseargs-context-parsecallback) can pass a context object where I can include the logger, so dependency injection would make a lof of sense.
