### ISSUE TITLE
Setting enabled to false still sends logs

### ISSUE THREAD

**Issue by patelnav** [pinojs/pino#1109]
Using pino-logflare's [VERCEL example](https://github.com/Logflare/pino-logflare/blob/master/docs/VERCEL.md), I have set enabled: false when creating the pino logger and logs are still being transmitted to logflare.

**Comment by mcollina** [comment]
Unfortunately that module is not part of this organization, I would recommend you to open an issue there.

**Comment by patelnav** [comment]
Thanks for responding @mcollina. I have created an issue on [their end](https://github.com/Logflare/pino-logflare/issues/31).
