### ISSUE TITLE
Hard to fully integrate with logging services like Rollbar

### ISSUE THREAD

**Issue by stalniy** [pinojs/pino#1119]
## The main issue

I'm integrating rollbar at stream level because I want to use all that reduction and serialization features from pino. 
But in order to get nice error stacktrace on rollbar issue page, I need to provide an instance of an `Error` to rollbar logger and I can't do this because my error has been already serialized by pino. 

So, currently I do this:

```ts
const logger = pino(
  {
    level: config.LOG_LEVEL,
    redact: ["req.headers.authorization"],
    serializers: DEFAULT_SERIALIZERS,
  },
  {
    write(chunk: string) {
      const { level, msg, err, ...data } = JSON.parse(chunk);

      process.stdout.write(chunk);

      if (level < PINO_LEVELS.warn) {
        return;
      }

      const log = LEVEL_TO_METHOD[level];

      if (err) {
        rollbarLogger[log](err, data, msg);
      } else {
        rollbarLogger[log](data, msg);
      }
    },
  }
);
```

But then my stacktrace is reported as a custom context parameter and not properly displayed in rollbar what makes debugging harder

## Desired behavior

I'd like to have an ability to intercept logged parameters before serialization and log them to rollbar, so I could do something like this:

```ts
logger.on("afterSerialization", (event) => {
  if (event.logArgs[0] instanceof Error) {
    const { err, ...data } = event.serialized;
    rollbar[event.level](event.logArgs[0], data);
  } else {
     rollbar[event.level](event.serialized);
  }
})
```

**Update**:
 I don't care about extending interface, it can be stream, hook, event, etc, I just need a way to log an error as it's otherwise rollbar will not display me a readable stack trace for that error

**Comment by mcollina** [comment]
Given how the rollbar JS SDK API is built, it's not compatible with pino. I would recommend you to create your wrapper that sends logs to both, or skip the rollbar SDK and build a pino transport that uploads to rollbar.

**Comment by stalniy** [comment]
How can I write that wrapper? Could you please provide suggestions?

I use pino v6, and streams to redirect pino output to rollbar but as I said I don’t have access to original arguments (i.e., error) at that stage. And at wrapper stage I don’t have access to redacted/serialized values 

I think there is the same issue with other logging solution like sentry. 

Re-implementing their SDK is a big problem for me because then I will need to support it, update on API changes and pay for their support. Doesn’t seem correct way for me

**Comment by stalniy** [comment]
In other words, it’s much easier to change logging library rather than re-implementing SDK, especially part related to source map re-mapping. 

But this means that pino despite being supper fast cannot be  fully used to solve real production issues

**Comment by stalniy** [comment]
I see 2 ways to solve this problem:
1. Implement `Logger` wrapper class and manually call serializers and redaction (would be good for pino to provide an api that consumes redacted values):
    ```ts
    class Logger {
        constructor() {
           this.rollbar = new Rollbar(...);
           this.pino = pino(...);
        }

       error(context, message) {
           if (context instanceof Error) {
              this.pino.error(context, message);
              this.rollbar.error(context, message);
              return;
           }

           const serialized = this.pino.serialize(context, message);
           if (context.err && context.err instanceof Error) {
              this.pino.logSerialized('error', serialized);
              this.rollbar.error(context.err, serialized);
              return;
           }

           this.pino.logSerialized('error', serialized);
           this.rollbar.error(serialized); 
       }
    }
    ```
2.  Through some pino hook/event/stream that accepts raw arguments what will allow me to get access to both serialized and original arguments

**Comment by stalniy** [comment]
Initially, I used wrapper class but then I realized that rollbar doesn't serialize  `FastifyRequest` correctly (actually it just walks through all properties and logs too much information)

I'd like to reopen this issue because currently it's impossible to integrate Rollbar with pino in a way that I get desired outcome in my dashboard
