### ISSUE TITLE
Create depth limit option for the log line

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#1121]
As titled.

Previous ones #990 #1120

**Comment by leorossi** [comment]
I am working on this, if I read it correctly this code
```js
const pino = require("pino")({ maxDepth: 3 });
const o = { a: { b: { c: { d: { e: { f: 'foobar' } } } } } }
pino.info(o)
```
would produce something like this: `{"a":{"b":{"c":"[...]"}}}`

I am currently testing with this code

```js
const pino = require("pino")();
const nested = {};
const MAX_DEPTH = 10 * 784;
let currentNestedObject = null;
for (let i = 0; i < MAX_DEPTH; i++) {
  const k = 'nest_' + i;
  if (!currentNestedObject) {
    currentNestedObject = nested;
  }
  currentNestedObject[k] = {};
  currentNestedObject = currentNestedObject[k];
}
pino.info(nested);
```

This is a very edge-case, a deeply nested object which is like this: `{ nest_0: { nest_1: { nest_2: {...} } } }`

We reach immediately this [line](https://github.com/pinojs/pino/blob/master/lib/tools.js#L490) which calls `JSON.stringify` which does not support a max-depth feature.

In fact with that big `MAX_DEPTH`, it raises a `RangeError: Maximum call stack size exceeded.` 

The same error is raised by the [next](https://github.com/pinojs/pino/blob/master/lib/tools.js#L493) `catch` block which tries `json-stringifys-safe`.

At this point the only way I see it is to parse the object and change it to removes all the keys at nesting level  `> MAX_DEPTH`, before passing to the write function. 

Is this the correct approach?

**Comment by mcollina** [comment]
> At this point the only way I see it is to parse the object and change it to removes all the keys at nesting level > MAX_DEPTH, before passing to the write function.

> Is this the correct approach?

Not really. Essentially we should embed json-stringify-safe and implement this feature there.

**Comment by runk** [comment]
I've had the same issue, however mostly around the size of the log and into how much money it translates. Been using https://github.com/runk/dtrim for quite some time - it covers all scenarios where you'd expect huge amounts of data to be logged: array, nested objects, buffers, big strings. Would be nice to see it used it in pino, or have similar functionality for truncating lengthy structures.

**Comment by Fdawgs** [comment]
@mcollina did #1169 resolve this?

**Comment by mcollina** [comment]
yes good catch!
