### ISSUE TITLE
Feedback on pino

### ISSUE THREAD

**Issue by kaihendry** [pinojs/pino#1128]
```
(ins)[hendry@t14s tw-test-logging]$ cat handler.js
"use strict";
const Logger = require("./logger");
const log = Logger("trace");

module.exports.hello = async (event) => {
  log.error("user login attempt failed", event);
  log.info(event, "a message")

  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: "Go Serverless v2.0! Your function executed successfully!",
        input: event,
      },
      null,
      2
    ),
  };
};
(ins)[hendry@t14s tw-test-logging]$ cat logger.js
const pino = require("pino");

module.exports = (level) => {
  return pino({
    level,
    formatters: {
      level: (label) => {
        return { level: label };
      },
    },
    name: process.env.FUNC_NAME,
  });
};
(ins)[hendry@t14s tw-test-logging]$ make
sls invoke local -f hello --path data.json
{"level":"error","time":1631519072197,"pid":1314081,"hostname":"t14s","msg":"user login attempt failed"}
{"level":"info","time":1631519072198,"pid":1314081,"hostname":"t14s","resource":"/","path":"/","httpMethod":"GET","msg":"a message"}
{
    "statusCode": 200,
    "body": "{\n  \"message\": \"Go Serverless v2.0! Your function executed successfully!\",\n  \"input\": {\n    \"resource\": \"/\",\n    \"path\": \"/\",\n    \"httpMethod\": \"GET\"\n  }\n}"
}
```
faq entry for [useLevelLabels](https://github.com/pinojs/pino/blob/master/docs/help.md#level-string) needs updating

With `log.error("user login attempt failed", event);`, how come "event" is not printed? silent failure is a bit worrying.

I'm a little surprised pid, hostname came in there without me asking for it.

Ideally i'd love to nest event under the "fields" key like https://play.golang.org/p/RWuIL1EvB-6

Do you have examples how to get time into a human readable timestamp like 2009-11-10T23:00:00Z? AWS Cloudwatch already attach a time stamp iiuc on log ingestion, so the important thing is to have readable date-times whilst looking through structured logs.

Sorry for abusing this for feedback. I didn't see another feedback channel.

Thank you!

**Comment by mcollina** [comment]
> faq entry for useLevelLabels needs updating

How? Would you like to send a PR?

> I'm a little surprised pid, hostname came in there without me asking for it.

I would be surprised if they were not there.

> Ideally i'd love to nest event under the "fields" key like https://play.golang.org/p/RWuIL1EvB-6

I do not understand this.

> Do you have examples how to get time into a human readable timestamp like 2009-11-10T23:00:00Z? AWS Cloudwatch already attach a time stamp iiuc on log ingestion, so the important thing is to have readable date-times whilst looking through structured logs.

This is well documented in: https://getpino.io/#/docs/api?id=opt-timestamp

**Comment by jsumners** [comment]
> With log.error("user login attempt failed", event);, how come "event" is not printed? silent failure is a bit worrying.

There isn't a failure. Please read the documentation for the logger methods.

**Comment by kaihendry** [comment]
PR would just point to https://github.com/pinojs/pino/issues/848#issuecomment-642768553 as that's how I worked around the warning.

RTFM... ok
