### ISSUE TITLE
GitHub Organization

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#115]
I think Pino should have its own GitHub Organization. This would provide a central place for "official" modules in the Pino ecosystem. Such modules would be things like `chops` and `pino-multi-stream` (since @mcollina is willing to help maintain it). Additionally, we would be able to give Pino a proper website via GitHub Pages. Given that we wouldn't want to put the website in the `pino` repository, I am proposing the organization name be `pinojs`.

What do you think, @mcollina @davidmarkclements ?

**Comment by davidmarkclements** [comment]
yes - @mcollina and I have discussed this and as far as I understand it, we're both in favour of it - but I'll let @mcollina confirm

**Comment by davidmarkclements** [comment]
Although I think anything we've helped people to build (e.g. with feedback) can be considered "official" (that is if third party auth's want to put it in etc.)

Also hapi-pino and the pino-http family

**Comment by davidmarkclements** [comment]
regarding org name - we can specify gh-pages comes from `/docs` branch in repo settings - wouldn't that mean can just put site on pino docs branch and have pino for org name?

**Comment by jsumners** [comment]
@davidmarkclements you can either have a `gh-pages` branch *or* a `/docs` within the master branch. See my https://github.com/jsumners/docs-test for the later (http://james.sumners.info/docs-test/). Personally, I don't like either option:

1. using the `gh-pages` branch method is a circus act that's easy to get wrong
2. using `/docs` we would end up with a lot of HTML in the main module; I wish it was a place for Markdown files to be auto-rendered, but that's not the case

Speaking of which, I created the `docs-test` repository specifically because I want to overhaul Pino's documentation. I think it is getting way too long for a single readme; if I make it to Austin, I had planned to discuss it with you two then.

**Comment by mcollina** [comment]
Created. Both of you are admins.

I moved pino, hapi-pino, express-pino-logger, pino-elasticsearch.

There are a bit of links to update: package.json, badges, travis, coveralls, etc. 

I'll leave this open till we move everything :)

**Comment by mcollina** [comment]
@jsumners feel free to setup up a new repo/website, we need it.

**Comment by mcollina** [comment]
I've updated this repo :).

**Comment by davidmarkclements** [comment]
Transfered:

* restify-pino-logger
* pino-http-print
* koa-pino-logger
* rill-pino-logger
* pino-http
* pino-noir

All have gh repos updated and pub'd to npm

I didn't transfer `pino-trace` because it's incomplete

**Comment by davidmarkclements** [comment]
exciting! :grin:

**Comment by mcollina** [comment]
I have the `pino.io` domain name, if anyone wants to give the website a shot.

**Comment by davidmarkclements** [comment]
hey @jsumners when (if) you transfer any of your pino modules, we're putting a 🌲 in front of each description so the org page looks like this

<img width="665" alt="screen shot 2016-10-25 at 09 41 45" src="https://cloud.githubusercontent.com/assets/1190716/19676979/83238aaa-9a97-11e6-9742-0307e5f04459.png">


cute right?

**Comment by davidmarkclements** [comment]
for the site - an automated (and searchable?) way to view "official" ecosystem pino modules would be so nice

**Comment by jsumners** [comment]
I can at least create a placeholder site using assets already available.

**Comment by jsumners** [comment]
I wonder if we qualify for a free npmjs.com organization. If not, shall we continue publishing modules under the lead maintainer's npmjs.com account?

**Comment by mcollina** [comment]
I'm ok with the current lead maintainer model. But if we get the npmjs.com org it would be awesome too.

We should probably all be able to publish, and avoid single point of failures (ah, humans).

**Comment by jsumners** [comment]
Then we should include such in a guidelines for contributing a pinojs project document.

**Comment by mcollina** [comment]
This should be sorted IMHO.
