### ISSUE TITLE
Rearranging log format

### ISSUE THREAD

**Issue by victorzw895** [pinojs/pino#1153]
Hi,

I noticed from some examples that the log format has been rearranged so that the message appears earlier in the line before pid and hostname.
<img width="1080" alt="Screen Shot 2021-10-12 at 5 23 45 pm" src="https://user-images.githubusercontent.com/51236363/136902921-33c1b176-f93e-4e28-aa0d-61ebb3fa3881.png">

I would like to get the message earlier just after logging level. I tried using merging object and message like above. But I always get the message right at the end. Is there any way to change this? 

Thanks
Victor

**Comment by mcollina** [comment]
Unfortunately it's not possible to control the order in which the properties are rendered in a performant way.
Anyway, to achieve this you would:

1. get the top level properties
2. sort the top level properties according to your criteria
3. generate a new objects, taking care of adding the properties in the same order of the previous step

I would recommend to do it in a transport, but potentially you could use the log formatter: https://getpino.io/#/docs/api?id=log.
