### ISSUE TITLE
template repo

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#116]
a repo that standardise file structure and readme layout (including badges etc) for anyone wanting to contribute a module to pinojs (or also for creating a third party module if desired)

we'd want to retrofit this template to all current modules for consistency

@mcollina @jsumners thoughts?

**Comment by jsumners** [comment]
What about a Yeoman generator instead? I already have one that I use for my own projects -- https://github.com/jsumners/generator-jsumners-node (definitely needs updating).

**Comment by mcollina** [comment]
I'm not fond of generators. I think a couple of good examples are much better.
More or less we have a single place with lots of good examples. It's basically a matter of copy-paste-change on what is currently here.

**Comment by jsumners** [comment]
Then a repo it is.

**Comment by jsumners** [comment]
Where are we at on this?

**Comment by mcollina** [comment]
@jsumners it seems I will never have the bandwidth to do it.
We might as well close.

**Comment by davidmarkclements** [comment]
let's just tag as help wanted?

**Comment by jsumners** [comment]
How about I just kickstart it? I created https://github.com/pinojs/pino-sapling . One immediate issue is that the benchmark is useless. Patches for making it otherwise would be welcome.

**Comment by davidmarkclements** [comment]
closing - since @jsumners you've essentially create a template repo - issues can go there
