### ISSUE TITLE
Runtime issue (packed by esbuild): Cannot find module 'pino-pretty'

### ISSUE THREAD

**Issue by Unga** [pinojs/pino#1164]
Hi,

I packed project with esbuild (output is one file index.js).
Configuration of Pino transport:
`
transport: {
     target: 'pino-pretty',
     options: {
       colorize: true,
       ignore: 'time,pid,hostname',
    },
},
`

On runtime I receive next error:
node:internal/modules/cjs/loader:930
  throw err;
  ^
Error: Cannot find module 'pino-pretty'
Require stack:
 /Users/d/test/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.resolve (node:internal/modules/cjs/helpers:99:19)
    at fixTarget (/Users/d/test/index.js:36543:34)
    at transport (/Users/d/test/index.js:36534:26)
    at normalizeArgs (/Users/d/test/index.js:41495:20)
    at Object.pino [as default] (/Users/d/test/index.js:42270:32)
    ...

Code (row 36543) from my packed index.js:
`
function fixTarget(origin) {
 
    if (isAbsolute(origin) || origin.indexOf("file://") === 0) {
      return origin;
    }
    
    switch (origin) {
      case "pino/file":
        return join4(__dirname, "..", "file.js");
      default:
        return callerRequire.resolve(origin);   // row 36543
    }
}`

Any ideas what to do? Thanks

**Comment by kibertoad** [comment]
Have you tried adding pino-pretty as a runtime dependency if you are usibg it?

**Comment by Unga** [comment]
> Have you tried adding pino-pretty as a runtime dependency if you are using it?

Yep. Installed "npm i pino pino-pretty"

**Comment by kibertoad** [comment]
wonder if bundler is not picking it up due to dynamic import. can you somehow force dependency bundling?

**Comment by Unga** [comment]
> wonder if bundler is not picking it up due to dynamic import. can you somehow force dependency bundling?

Yesterday I switched our project from Winston to Pino because Winston has same issue... I decided to try something new :) But when I added pino-pretty to config I got same issue. 
What do you mean "force dependency bundling"?
