### ISSUE TITLE
A "nestedKeyName: {}" is always added to the log and displayed by pretty even if there is nothing to nest

### ISSUE THREAD

**Issue by frzsombor** [pinojs/pino#1166]
If I set the `nestedKey: payload` option, the nested key is always added to the log and pino-pretty also displays it every time, even if I try to log a simple string (and if I can remember correctly, this was not the case with v6).

A simple `logger.info('info');` makes pino-pretty (with `base: undefined, timestamp: pino.stdTimeFunctions.isoTime` options) show the following:
```
[2021-10-17T17:52:12.208Z] INFO: info
    payload: {}
```

---

_My current workaround:
Right now I'm using the following hook method to achieve similar results as v6 (only wrap object if necessary):_

```javascript
hooks: {
    logMethod (inputArgs, method, level) {
        if (typeof inputArgs[0] !== 'string' && !(inputArgs[0] instanceof Error)) {
            return method.apply(this, [ { object: inputArgs[0] } ]);
        }
        return method.apply(this, inputArgs);
    }
},
```

**Comment by mcollina** [comment]
This looks like a bug. Would you like to send a PR to fix it?

**Comment by frzsombor** [comment]
I actually tried to fix this in the code too, but I could not decide if it is a problem in proto.js [here](https://github.com/pinojs/pino/blob/588b4858ebcc65f67ceac40c1c4a10452a84dc75/lib/proto.js#L166-L167) or I should simply add an additional check in tools.js [here](https://github.com/pinojs/pino/blob/588b4858ebcc65f67ceac40c1c4a10452a84dc75/lib/tools.js#L175). That's all I've found.

**Comment by mcollina** [comment]
probably in the line with mixin defined.

If that's the case this ha not been introduced in v7, what's the latesr version this was working for you?

**Comment by frzsombor** [comment]
I would be happy to help, but I think this task might require a deeper understanding of the codebase that I currently have in this project.

**Comment by simoneb** [comment]
A git bisect shows that this behavior was introduced in https://github.com/pinojs/pino/pull/885
