### ISSUE TITLE
Same level multistream logging is not working with "dedupe"

### ISSUE THREAD

**Issue by frzsombor** [pinojs/pino#1167]
If I set `dedupe` to true, the option works as stated in the docs, but it also _breaks_ the possibility to have multiple streams for the same level, as only the "first" stream of the given level will be used, not all the streams matching the level. I'm not sure if this is the intended way of working or this is something you might want to change. I understand that the way it currently works exactly means "deduping" but in my (and I think in most) use cases, we would expect dedupe to "send logs only to the stream with the higher level" but to **all** of them.

```javascript
var fs = require('fs')
var pino = require('pino')
var pretty = require('pino-pretty')
var streams = [
  { level: 'info', stream: pretty() },
  { level: 'info', stream: fs.createWriteStream(`./log-info.log`) },
  { level: 'error', stream: fs.createWriteStream(`./log-error.log`) },
]

var multistreamOpts = {
    dedupe: true,
};

var log = pino({
  level: 'info' // this MUST be set at the lowest level of the destinations
}, pino.multistream(streams, multistreamOpts))

log.info('this will be written ONLY to the console by pino-pretty and NOT in ./log-info.log')
log.fatal('this will be written ONLY to ./log-error.log')
```

---

I think changing the [current multistream write function](https://github.com/pinojs/pino/blob/588b4858ebcc65f67ceac40c1c4a10452a84dc75/lib/multistream.js#L45-L73) to the following would do the trick:

```javascript
function write (data) {
  //...
  for (let i = 0; i < streams.length; i++) {
    dest = streams[i]
    if (dest.level <= level) {
      //...
      if (!opts.dedupe || dest.level === level) { //change 'if' condition
        stream.write(data)
      }
    } else {
      break
    }
  }

  //TODO: remove
  //if (opts.dedupe && stream) {
  //  stream.write(data)
  //}
}
```

**Comment by mcollina** [comment]
The current implementation works as expected. If you would like to add a new feature, I'll be happy to review a PR.

**Comment by frzsombor** [comment]
All right, I understand if you don't want to change that and in this case, maybe I will try to create a PR for this some day.
Just let me add that, I don't think going with _"A"_ above would invalidate the _current_ meaning of dedupe or would go against the current docs, as first I even thought this is a bug, because I expected that dedupe is especially meant for "do not write logs to any stream with a level different from the specified" and not meant for "write logs _randomly_ to one of the streams matching the target level".

**Comment by mcollina** [comment]
ah, I might have missed the problem then. a PR with A) will be good.

**Comment by frzsombor** [comment]
Sounds great, then here is a PR for that:
