### ISSUE TITLE
community repo

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#117]
... maybe?

@mcollina @jsumners

**Comment by jsumners** [comment]
One that lists modules? Or one like https://github.com/hapijs/discuss ?

**Comment by mcollina** [comment]
What would that contain? A known list of compatible modules?

**Comment by jsumners** [comment]
💡 a badge for readme files that says "pino ecosystem" or something with an icon that has multiple trees (i.e. a forest). This would be usable by projects under the pinojs organization.

**Comment by mcollina** [comment]
I'm closing this, in favor of the issue tracker on https://github.com/pinojs/community.
