### ISSUE TITLE
Property 'flush' does not exist on type 'typeof P'

### ISSUE THREAD

**Issue by budarin** [pinojs/pino#1176]
Have upgraded to version 7.0.2 and got the error.

According to doc https://getpino.io/#/docs/asynchronous?id=prevent-log-loss-in-node-v12 I use flush method as 

```js
// asynchronously flush every 10 seconds to keep the buffer empty
// in periods of low activity
setInterval(function () {
  logger.flush()
}, 10000).unref()
```

**Comment by mcollina** [comment]
cc @kibertoad

**Comment by adibhanna** [comment]
You don't need to use `flush` if you're on Node 14+

**Comment by kibertoad** [comment]
Which type does `logger` have in your case?

**Comment by budarin** [comment]
> ```js
> logger.flush()
> ```

I tried not to make a logger.flash(), but then the record appears in the log only after the buffer is filled, which may not be filled quickly and logs are needed as soon as possible
