### ISSUE TITLE
pino not uninstalling

### ISSUE THREAD

**Issue by cybemachine** [pinojs/pino#1210]
the pino folder dosen't remove using yarn remove pino and gives a EPERM: operation not permitted, lstat 'path\\node_modules\\pino'

**Comment by cybemachine** [comment]
yarn-error.log

Yarn version: 
  1.22.17

Node version: 
  16.6.1

Platform: 
  win32 x64

Trace: 
  Error: EPERM: operation not permitted, lstat 'D:\main\important\coding\discord\node_modules\pino'

**Comment by cybemachine** [comment]
yarn-error.log

Yarn version: 
  1.22.17

Node version: 
  16.6.1

Platform: 
  win32 x64

Trace: 
  Error: EPERM: operation not permitted, lstat 'D:\main\important\coding\discord\node_modules\pino'

**Comment by mcollina** [comment]
How did you install pino? This has nothing to do with pino but what you did to install it.

**Comment by cybemachine** [comment]
ok i used yarn add pino
