### ISSUE TITLE
Ability to add mixins in child loggers

### ISSUE THREAD

**Issue by ford-prefect** [pinojs/pino#1211]
Just exploring the pino API for our usage here, and one early thing I see that might be useful is to have mixins in a child logger. Is this something that would be accepted upstream, or is this something that was explicitly omitted as a bad idea?

One problem I can imagine is that if the mixin needs to be an override, this might be surprising for users of the API (but this could have an explicit documentation caveat).

**Comment by mcollina** [comment]
I think this is a bad idea, but likely thhe change to implement it is minimal.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by ford-prefect** [comment]
Thanks @mcollina! Is it worth implementing if it is a bad idea? I can find alternatives for our use (reconstruct a child when context changes, which is not that often), if this would have performance or other impacts.

**Comment by mcollina** [comment]
I think your solution would be better if the context does not change often.

**Comment by ford-prefect** [comment]
Thank you for the feedback and the work on the library!
