### ISSUE TITLE
Cannot find module '/xxxxx/worker_threads'

### ISSUE THREAD

**Issue by fang-guang** [pinojs/pino#1214]
when i update version latest throw error of this
![image](https://user-images.githubusercontent.com/45454404/140872875-81d1f6fb-2d8a-4d18-8a36-ebc171652c0a.png)

when i lower version in 6 is fine

**Comment by mcollina** [comment]
worker_threads is part of Node.js.

Can you include a full example to reproduce your problem?

**Comment by jsumners** [comment]
The response remains the same. Provide a reproduction.

**Comment by aletome** [comment]
Use Node v10.1.0.
Install latest version of Pino.
Start the app and you get the error.
Switch back to Pino v6.14.0 and it works.

**Comment by jsumners** [comment]
We do not support Node v10 with `pino@7` https://getpino.io/#/docs/lts?id=schedule
