### ISSUE TITLE
Add mkdir option to pino/file transport

### ISSUE THREAD

**Issue by mojavelinux** [pinojs/pino#1221]
Like SonicBoom, it would be helpful if the pino/file transport provided a `mkdir` option to instruct the transport whether to ensure the directory of the destination file exists before attempting to open it for writing.

Consider the following script:

```js
const pino = require('pino')
const ospath = require('path')
const transport = pino.transport({
  target: 'pino/file',
  options: {
    destination: ospath.join(__dirname, 'logs/main.log'),
  },
})
const logger = pino(transport)
logger.error('something bad happened')
```

Assuming this is run in a fresh directory that does not contain a `logs` folder, this code results in the following exception:

```
Error: ENOENT: no such file or directory, open '/tmp/pino-lab/logs/main.log'
Emitted 'error' event on ThreadStream instance at:
    at destroy (/tmp/pino-lab/node_modules/thread-stream/index.js:341:12)
```

The proposed `mkdir` option, if set, would ensure that the `/tmp/pino-lab/logs` directory exists before trying to open the destination file for writing.

```js
const transport = pino.transport({
  target: 'pino/file',
  options: {
    destination: ospath.join(__dirname, 'logs/main.log'),
    mkdir: true,
  },
})
```

For more context and precedent, see https://github.com/pinojs/sonic-boom/issues/78.

**Comment by mojavelinux** [comment]
Implementing this option is a matter of forwarding it to pino.destination in file.js.

**Comment by davidmarkclements** [comment]
I think this is a good idea
