### ISSUE TITLE
Creating/using an in-memory pino logger instance

### ISSUE THREAD

**Issue by michael-melodyarc** [pinojs/pino#1227]
I'm not sure if in-memory is the most correct terminology, but hopefully a quick explanation will suffice.  I have a use case where we're essentially letting a user define a mini plugin, which our main app then calls a handler function from.  I'd like to pass a pino logger instance to the plugin, but I don't want the output to go to `process.stdout` or a file.  Instead, I'd just like to wait for the plugin to finish doing its thing, and then serialize the output from pino.  Ultimately, this use case is pretty simple, the following logic works, but I'm curious if this is actually the simplest/best way to do it, or if there's an easier or better recommendation.  Any help would be greatly appreciated :)

```js
import { PassThrough } from 'stream';
import pino from 'pino';

const pt = new PassThrough({ objectMode: true });
const logger = pino(pt);

// pass the logger instance to the plugin's handler function and let it log some stuff

pt.end();

const logs = [];

for await (const obj of pt) {
  logs.push(obj);
}

// save logs to database or print it out so I can hang it on my wall :P
```

Does this make sense or is there some gotcha with doing this?  I do know `pino-abstract-transport` exists, but I'm not sure if I'd actually get any benefit from using it versus the sample code above.  Thanks again.

**Comment by mcollina** [comment]
I would use a `split2` instance instead of a `Transform`... but that's the generic idea.
