### ISSUE TITLE
Log level numbers

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#123]
Given that the public interface is based on the standard established by Log4j, e.g. `info`, `warn`, etc., shouldn't the internal level numbers match the ones used by Log4j? They have:

level name  | level number
----------- | --------------
off | 0
fatal | 100
error | 200
warn | 300
info | 400
debug | 500
trace | 600
all | Number.MAX_VALUE

src: http://logging.apache.org/log4j/2.x/manual/customloglevels.html

Whereas we have:

level name  | level number
----------- | --------------
off | 100 ("silent")
fatal | 60
error | 50
warn | 40
info | 30
debug | 20
trace | 10
all | no equivalent

Of course, our numbers are matching Bunyan's.

**Comment by mcollina** [comment]
Currently, bunyan has 1million downloads per month. Log4js has 2millions. But we are targeting bunyan as compat.

It might make sense to change them, but they are legacy, and we do not want to go back and change all old log records.

**Comment by jsumners** [comment]
It would certainly be a breaking change and a log version bump. I was just working on something else and got curious if we were using the same numbers.
