### ISSUE TITLE
Clarify exit logging strategy in node 14+ if not using pino.final

### ISSUE THREAD

**Issue by humphd** [pinojs/pino#1232]
#1199 added a deprecation notice for `pino.final` in node 14+.  However, it's unclear (to me) what you should do instead, since the official docs still recommend it for [exit logging](https://getpino.io/#/docs/help?id=exit-logging).

Could the docs be clarified?

**Comment by jsumners** [comment]
Use Node v16 or greater is the intention.

**Comment by humphd** [comment]
@jsumners I'm confused, since 16 is also going to trigger this warning, is it not?

```
Welcome to Node.js v16.13.0.
>   const major = Number(process.versions.node.split('.')[0])
> major >= 14
true
```

If I'm using node 16+, are you saying that I should continue to use `pino.final` as written in the docs?

**Comment by jsumners** [comment]
Sorry. I misread. You should be switching to using `pino.destination`, I believe. And it looks like we need a doc update.

@mcollina can verify these guesses.

**Comment by mcollina** [comment]
`pino.final()` is not needed in node v14+ and it is deprecated. Internally we use https://github.com/mcollina/on-exit-leak-free to set up things automatically. Essentially it will automatically call `flushSync()` before your process exits.

I'll update that piece of doc.

**Comment by humphd** [comment]
Thanks for the clarification and doc update.  This is helpful.
