### ISSUE TITLE
`Warning: File descriptor 1 closed but not opened in unmanaged mode` when using default 'pino/file'

### ISSUE THREAD

**Issue by aduponchel** [pinojs/pino#1242]
* **OS**: WSL 2 through W10
* **Node**: v16.13.0
* **npm**: 8.1.0
* **pino**: 7.4.1

The warning `(node:24819) Warning: File descriptor 1 closed but not opened in unmanaged mode` is displayed when using Pino with default `pino/file` transport. I don't have this warning displayed while using pino with no transport.
UnfortunateIy need multiple transport, so I cannot use pino without transport parameter.
Btw this is not a critical error but maybe it is related to #1241.

Warning is displayed with or without pino-pretty. 

## Step to reproduce

```js
const pino = require('pino');
const main = pino(
    {
      transport: {
        target: 'pino/file',
      },
    },
);
main.info('Hello world');
main.error(new Error('Main Error'));
``` 

node demo.js | pino-pretty

```log
[1637948003517] INFO (24819 on ---): Hello world
(node:24819) Warning: File descriptor 1 closed but not opened in unmanaged mode
(Use `node --trace-warnings ...` to show where the warning was created)
[1637948003517] ERROR (24819 on ---): Main Error
    err: {
      "type": "Error",
      "message": "Main Error",
      "stack":
          Error: Main Error
              ---stack---
```

**Comment by mcollina** [comment]
I'm aware of this warning. I would say it's not a problem to worry about but I'd need to investigate this further.
