### ISSUE TITLE
Question: Transform entire log JSON format

### ISSUE THREAD

**Issue by dflor003** [pinojs/pino#1248]
Hi! We're trying to leverage pino logger at a large enterprise with a very specific logging JSON format that needs to be sent to STDOUT and STDERR in order to be scraped by our PaaS system and processed by the ELK stack.

Looking through the docs, I see that you can use formatters to transform individual pieces of the logs. However, in our case, this would not be sufficient. Is there anything in the library outside of a custom transport that will allow us to transform the entire log message at once?

Here's a rough example of how our log message format needs to look:

```json5
{
  "applog": { // <- Our logs need to be nested under a specific root key
    "log_level": ...,
    "context": "...",
    "http_request": {
      ...
    },
    ...
  }
}
```

Any help would be appreciated. Thanks!

**Comment by mcollina** [comment]
The best approach is to develop a custom transport that make it suit your needs, see https://getpino.io/#/docs/transports.
