### ISSUE TITLE
Adding attributes to the msg

### ISSUE THREAD

**Issue by igalarzab** [pinojs/pino#1263]
Hi 👋 ,

First of all, thanks for the library, I love it! 😄  

Is there any way to include the attributes of a message inside of the `msg` key, apart from including them as normal fields of the JSON output?

This:

```js
log.info({'f1': 'v1'}, 'Hello World');
```

would generate

```
{"f1": "v1", "msg": "Hello world f1=v1"}
```

And if there is no current way... would you accept a patch implementing the feature?

**Comment by mcollina** [comment]
See https://getpino.io/#/docs/api?id=interpolationvalues

**Comment by igalarzab** [comment]
Hey Matteo,

Thanks for the help! But I'm not sure how I could use the `interpolationValues` for the problem I have, without having to modify all the log lines of the project.

Basically all my loggers have an attribute called `module`, given when the logger is created (via the `child` method). I would like to have that specific attribute not only as part of the JSON object, but also at the end of the message field (concatenated to the message)

The closest thing I've seen that could help me would be a formatter, but the `log` formatter doesn't receive the `message` field, which makes it not useful for my case.

```ts
      formatters: {
        log (obj: any) {
          if ('module' in obj) {
            obj.message = obj.message += `module=${obj.module}`;  // message does not exist here
          }
          return obj;
        }
      }
```

**Comment by mcollina** [comment]
Oh now I understand what you want to achieve.
This case is covered by https://getpino.io/#/docs/api?id=logmethod.

**Comment by igalarzab** [comment]
Thanks for the quick answer! 🙇 

I've been playing a bit with the `logMethod` hook but I don't see how to access the object itself (to be able to get the properties that were set in the logger when it was created by the `child` method). Am I missing something?

**Comment by mcollina** [comment]
It should be `this`

**Comment by igalarzab** [comment]
Amazing, works wonderfully, thanks a lot for the help :) 

Copying here the result just in case it's useful for someone else:
```ts

const hooks = {
  logMethod(inputArgs: unknown[], method: PinoLogger.LogFn) {
    const { service } = (this as PinoLogger.Logger).bindings();
    let [ arg1, arg2, ...restArgs ] = inputArgs;

    if (service) {
      if (typeof arg1 === 'string') {
        arg1 = `[${service}] ${arg1}`;
      } else if (typeof arg2 === 'string') {
        arg2 = `[${service}] ${arg2}`;
      }
    }

    if (arg2 !== undefined) {
      restArgs.unshift(arg2);
    }

    return method.apply(this, [arg1 as string, ...restArgs]);
  }
}
```
