### ISSUE TITLE
The-cost-of-logging

### ISSUE THREAD

**Issue by galbeinx** [pinojs/pino#1266]
when implementing this tutorial: https://www.nearform.com/blog/the-cost-of-logging/
I'm getting that the Winston is Faster than the Pino with a number of requests, please, can you advise?

I'm using Pino version 7.5.1, Winston version 3.3.3

**Comment by mcollina** [comment]
That is a pretty old blog post. The new version of pino use synchronous logging by default to priotize safety and avoid memory issues. Therefore you could have lower performance if your destination/disk is slower (the terminal is very slow). You'd need to enable asynchronous logging to see all the performance benefit.
