### ISSUE TITLE
Add feature to lookup external LDAP classes

### ISSUE THREAD

**Issue by Aschen** [pinojs/pino#1272]
It could be interesting to be able to format some string using external LDAP serialized classes, what do you think?

**Comment by jsumners** [comment]
That would be an implementation detail for a custom transport. Adding such a feature to core is not going to happen because such operations are _extremely_ slow.

**Comment by marcbachmann** [comment]
I guess that was supposed to be a joke 😁 
Similar to https://twitter.com/brianloveswords/status/1469358777409454092?s=20

**Comment by jsumners** [comment]
Ah, I see. Locking this as off-topic because it is. @Aschen in the future, please only open actual issues. Triaging issues takes time, and triaging "jokes" is a waste of maintainers's time.
