### ISSUE TITLE
Type of pino logger

### ISSUE THREAD

**Issue by Balrrach** [pinojs/pino#1280]
I want to include a logger in a controller class as an atribute. Since I'm doing typescript I would like to know what type the pino logger is to declare the variable as such.
```ts
miClass(){
	private logger: any = pino(dest);
}
```

**Comment by mcollina** [comment]
cc @kibertoad

**Comment by robertsLando** [comment]
@Balrrach Should be `pino.Logger` 
https://github.com/pinojs/pino/blob/master/pino.d.ts#L210

**Comment by Balrrach** [comment]
Seems to be working correctly. Thanks a lot!
