### ISSUE TITLE
Multiple transports doesn't work: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by JaneJeon** [pinojs/pino#1285]
I have a very simple transport setup as follows:

```js
transport = pino.transport({
    targets: [
      { target: 'pino-pretty' },
      {
        target: 'pino/file',
        options: {
          destination: `logs/${dayjs().format('YYYY-MM-DDTHH:mm:ss')}.log`
        }
      }
    ]
  })
```

However, pino shits the bed, complaining of the following:
```
The "path" argument must be of type string. Received undefined
TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at fixTarget (/home/node/node_modules/pino/lib/transport.js:116:9)
    at transport (/home/node/node_modules/pino/lib/transport.js:111:22)
    at normalizeArgs (/home/node/node_modules/pino/lib/tools.js:410:10)
    at pino (/home/node/node_modules/pino/pino.js:85:28)
    at Object.<anonymous> (/home/node/lib/logger.js:32:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

Ultimately, I've tracked it down to the fact that despite the fact that I _specifically_ set `targets` property when initializing the transport, it's not there when the `ThreadStream` actually gets created (that's the transport "instance"). Here's the proof (I console.logged the actual transport instance that was being passed to the `function transport()` in `lib/transport.js`):
```
transport: ThreadStream {
    _events: [Object: null prototype] {
      ready: [Function: onReady],
      close: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    worker: Worker {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      performance: [Object],
      stream: [FakeWeakRef],
      [Symbol(kCapture)]: false,
      [Symbol(kHandle)]: [Worker],
      [Symbol(kPort)]: [MessagePort [EventTarget]],
      [Symbol(kParentSideStdio)]: [Object],
      [Symbol(kPublicPort)]: [MessagePort [EventTarget]],
      [Symbol(kNewListener)]: [Function (anonymous)],
      [Symbol(kRemoveListener)]: [Function (anonymous)],
      [Symbol(kLoopStartTime)]: -1,
      [Symbol(kIsOnline)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kImpl)]: {
      stateBuf: [SharedArrayBuffer],
      state: [Int32Array],
      dataBuf: [SharedArrayBuffer],
      data: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 4194254 more bytes>,
      sync: false,
      ending: false,
      ended: false,
      needDrain: false,
      destroyed: false,
      flushing: false,
      ready: false,
      finished: false,
      errored: null,
      closed: false,
      buf: ''
    }
  }
}
```

Clearly, a whole lot of symbols and a whole not of `targets`. This is why when you get to the `lib/transport.js` and do this, the `targets` is empty and thus causes the "Received undefined" error:
```js
function transport (fullOptions) {
  const { pipeline, targets, options = {}, worker = {}, caller = getCaller() } = fullOptions
...
```

I think this should be a straightforward fix?

Thanks

**Comment by mcollina** [comment]
That's really surprising because we cover that exact usecase in our tests. Maybe you can add a reproducible example we can run?

Given that's straightforward, I'd be happy to receive a PR from you that fixes it.

**Comment by climba03003** [comment]
The problem may relate to how he pass the `transport` to `pino`.
e.g. the following should throw the error
```js
const transport = pino.transport({
  targets: [
    { target: 'pino-pretty' },
    {
      target: 'pino/file',
      options: {
        destination: `logs/${dayjs().format('YYYY-MM-DDTHH:mm:ss')}.log`
      }
    }
  ]
})
pino({ transport })
```

**Comment by mcollina** [comment]
That's not correct. I think we might want to improve the error handling.

Either:

```js
const transport = pino.transport({
  targets: [
    { target: 'pino-pretty' },
    {
      target: 'pino/file',
      options: {
        destination: `logs/${dayjs().format('YYYY-MM-DDTHH:mm:ss')}.log`
      }
    }
  ]
})
pino(transport)
```

or

```js
pino({
  transport: {
 targets: [
    { target: 'pino-pretty' },
    {
      target: 'pino/file',
      options: {
        destination: `logs/${dayjs().format('YYYY-MM-DDTHH:mm:ss')}.log`
      }
    }
  ]}
})
```

**Comment by climba03003** [comment]
I know that the code I post is not correct, but it is the only possibility to cause error.
From the error stack
1. `normalizeArgs (/home/node/node_modules/pino/lib/tools.js:410:10)` - It is related to the option passed to pino
2. `transport (/home/node/node_modules/pino/lib/transport.js:111:22)` - It is creating a new instance of `ThreadStream`, which should not if you passing like `pino(transport)`

It is very clear that he pass the `ThreadStream` to `transport` option.

**Comment by mcollina** [comment]
@climba03003 do you think we should fix this and make it throw a more explicit error? I'm not convinced we should be accepting a stream as a `transport`.

**Comment by climba03003** [comment]
> @climba03003 do you think we should fix this and make it throw a more explicit error? I'm not convinced we should be accepting a stream for the `transport`.

I am fine with both detecting if user pass the wrong value to `transport` or accepting `stream` for `transport`.

**Comment by JaneJeon** [comment]
@climba03003 was absolutely right with his first guess, thank you!
