### ISSUE TITLE
[question] Truncating messages

### ISSUE THREAD

**Issue by R0st0s** [pinojs/pino#1289]
How should I go about limiting the length of fields logged with Pino? Let's say I have an object which has one nested field that's 100k characters long, and I want every field to be logged, but up until a specific length, for example 10k characters.
I looked into transports, but they didn't really look the perfect fit. I tried to substring the fields myself with
`logger.info({
    method: request.raw.method,
    route: request.raw.url,
    body: JSON.stringify(request.body, replacer),
});`
But then redaction doesn't work.

**Comment by mcollina** [comment]
Have you tried using the serializers: https://getpino.io/#/docs/browser?id=serialize-boolean-array?

**Comment by R0st0s** [comment]
Thanks for the suggestion, @mcollina! The only drawback is that the serializer are applied on the exactly matching properties, but I can work with that.
