### ISSUE TITLE
would pino support PM2 in future？ 

### ISSUE THREAD

**Issue by joebnb** [pinojs/pino#1290]
pino not work with pm2 cluster mode,could make a move to support it ?configuration or other ways

**Comment by mcollina** [comment]
how does pino not work with pm2?

**Comment by joebnb** [comment]
pino not work in pm2 cluster mode,  https://github.com/pinojs/pino/issues/491#issuecomment-414043388 i meet the same issue

**Comment by joebnb** [comment]
> pino not work in pm2 cluster mode, [#491 (comment)](https://github.com/pinojs/pino/issues/491#issuecomment-414043388) i meet the same issue

in ecosystem json add: exec_mode:'cluster'
```
{
  "apps": [{
    "name": "test",
    "watch": ["src"],
    "script": "src",
    "interpreter_args": "",
    "instances": 2,
    "exec_mode": "cluster"
  }]
}
```

**Comment by kibertoad** [comment]
@joebnb Did you read entire thread that you linked? If you have same issue, same fix should work for you.

**Comment by joebnb** [comment]
> @joebnb Did you read entire thread that you linked? If you have same issue, same fix should work for you.

thanks for mention
