### ISSUE TITLE
Should provide an OpenTelemetry transport

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#1292]
https://github.com/open-telemetry/opentelemetry-specification/blob/8e29f555b2282a3883b1b57009ad4eb11bfc5228/specification/logs/data-model.md

**Comment by marcbachmann** [comment]
Just a note. Currently I'm extracting the traceId in the `pino-http` `customProps` function: https://github.com/pinojs/pino-http/blob/0c778530cecac64ca80ae4e88624c55c942413b9/logger.js#L122

Having the traceId is enough in most cases, as that's the entrypoint of retrieving a trace in jaeger/loki.

Not sure this issue belongs into pino itself. Retrieving a trace might have too much overhead.

```js
module.exports = pinoHttp({
  // ...,
  reqCustomProps (req) {
    return {traceId: req.traceId}
  }
})
```

Together with 
```js
    registerInstrumentations({
      instrumentations: [
        new DnsInstrumentation(),
        new ExpressInstrumentation(),
        new GrpcInstrumentation(),
        new HttpInstrumentation({
          requestHook (span, req) {
            req.traceId = span?.spanContext().traceId
          }
        }),
        new IORedisInstrumentation(),
        new PgInstrumentation({enhancedDatabaseReporting: true})
      ],
      meterProvider: metrics.meterProvider,
      tracerProvider: tracing.tracerProvider
    })
```

**Comment by jsumners** [comment]
The idea would be to receive a standard Pino generated NDJSON line and mutate it to the format described in the linked OT documentation. Adding trace/span ids is out of scope.

**Comment by jhonrocha** [comment]
Hi! I will take a look on this!

**Comment by simoneb** [comment]
@jhonrocha any news?

**Comment by Vunovati** [comment]
I am working on this.

**Comment by Vunovati** [comment]
@jsumners could you please take a look if [my PR](https://github.com/Vunovati/pino-opentelemetry-transport/pull/1) solves the issue?

**Comment by jsumners** [comment]
@mcollina would you like to bring this into the org?

**Comment by Vunovati** [comment]
@jsumners The [PR](https://github.com/Vunovati/pino-opentelemetry-transport/pull/1) has been reviewed and the OpenTelemetry transport for Pino is now available on npm: https://www.npmjs.com/package/pino-opentelemetry-transport .

What else is needed to close this issue?

Should I submit a PR to add this transport to the [list of transports](https://github.com/pinojs/pino/blob/master/docs/transports.md#known-transports) in Pino docs?

**Comment by mcollina** [comment]
Sure, send a PR!
