### ISSUE TITLE
TypeScript types do not provide expected safety

### ISSUE THREAD

**Issue by pietrorea** [pinojs/pino#1293]
I recently migrated all my `console` logging statements to use a pino logger on a TypeScript backend codebase. Most of the changes worked out of the box with the matching default functions (e.g. `console.error(...)` mapping to `pino.error(...)`). 

The TS type checker let me happily move my `console.log(...)` statements to `pino.log(...)`, so I incorrectly assumed there was a default `log` method on the pino logger API. 

Obviously, there's no `log` function, so the service failed with error `TypeError: logger_1.logger.log is not a function`.

Totally my fault, but I expected the type system to help me here. Is there anything that can be done to get some help from TypeScript?

**Comment by pietrorea** [comment]
For now I've wrapped pino in my own logger API, but curious if I can use directly in a safer way.

**Comment by mcollina** [comment]
Could you include a full example to reproduce this? My understanding is that this should not be possible according to our types.

Note that TS does not provide any runtime safety - essentially this is true for any types you might want to use.

**Comment by kibertoad** [comment]
@mcollina Likely it is due to custom levels support, I think we are typing that part as a dictionary of <string, Logger>.

**Comment by pietrorea** [comment]
@mcollina I also thought the line @kibertoad was why. would you still like a full example? happy to provide, but wasn't sure if you were just looking for an entry point into the code.

i'm ok with no runtime safety. I'm just looking for the red squiggly as I type a method that's not defined, and for my build to fail, if that's the case

**Comment by mcollina** [comment]
Please do. `pino.log` should be flagged `pino().log` should pass through.

**Comment by pietrorea** [comment]
@mcollina here's the sample project: https://github.com/pietrorea/pino-types-example

```
npm i
npm run build  
node ./out-tsc/src/index.js 
```

The build step does not produce an error but it fails at runtime. I take it from your last comment that this is expected?

**Comment by mcollina** [comment]
Thanks for that. Just to confirm, using the log method without creating a pino instance is not possible, right?

**Comment by mcollina** [comment]
@kibertoad I think we might want to change this and remove that definition and document that people would have to add their definitions manually if using custom levels.

**Comment by pietrorea** [comment]
@mcollina yea, just doing `pino.log('...'`) is not possible:

<img width="393" alt="Screen Shot 2022-01-11 at 10 03 49 AM" src="https://user-images.githubusercontent.com/1264371/148967484-5b78152c-7d05-47e1-8508-bbe54a6be1bc.png">
