### ISSUE TITLE
Should we make "v" overridable?

### ISSUE THREAD

**Issue by stephanebruckert** [pinojs/pino#130]
Hello Pino team,

I would like to understand why "v" (LOG_VERSION) is compulsory and read-only. 
In our case we would like to override it to represent our service version instead.
If any backward-incompatible change had to happen inside Pino, we would update to the latest Pino and bump our service version, which still gives sense to "v".

Can we make it overridable? I've requested this on Bunyan also.

Thanks, Stephane

**Comment by mcollina** [comment]
Why do you want to override it?

**Comment by stephanebruckert** [comment]
Because the logs need to include our service version and the service version infers the Pino version.

**Comment by davidmarkclements** [comment]
Are you sure that's a desired coupling?

Perhaps if you just add a service version to a separate property, it may avoid unforeseen difficulties

**Comment by stephanebruckert** [comment]
I can, but having "v" and "version" is a bit confusing. Some might wonder what is what, and also wonder what is the use of "v". "v" is a short name which I would like to use. Basically that prevents me from outputting what I really need.

**Comment by jsumners** [comment]
My concern here is pino specific tooling. For example, the included prettifier checks for the `v` property to determine if the log line is appropriate to prettify. It doesn't yet check the version number, but it might become necessary to do so. Granted, this would be self inflicted breakage if you opted to change the meaning of that property, but it would mean we can't guarantee features and would always have to ask "did you change the `v` property?"

I don't think anyone is really asking themselves what `v` is for. It's clearly an indication of the log format version. However, it might be a good idea to state that explicitly in the documentation.

I present this as a possible solution:

```js
var pino = require('pino')
var log = pino(options).child({appname: require('package.json').version})
```

**Comment by davidmarkclements** [comment]
this is an unfortunate naming conflict across languages and paradigms, but we basically followed bunyans lead on this - I would be reticent to break away from that - I strongly doubt bunyan will make it overridable, and unless they do I don't think we should either

**Comment by stephanebruckert** [comment]
Ok, I understand. Thanks for the quick answers!

**Comment by stephanebruckert** [comment]
FYI there is an active issue on https://github.com/trentm/node-bunyan/issues/462

**Comment by jsumners** [comment]
@stephanebruckert they make the same argument as I did -- it would increase the difficulty of writing tools to work with raw Pino logs. I still think using a child logger with a property specific to your application, set to the application's version, is the appropriate solution.
