### ISSUE TITLE
Typescript declaration not found

### ISSUE THREAD

**Issue by adibhanna** [pinojs/pino#1308]
I'm using Pino in an Express+Typescript project.
I'm getting the following error with I do `import pino from 'pino';`

```
Could not find a declaration file for module 'pino'. '.../node_modules/pino/pino.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/pino` if it exists or add a new declaration (.d.ts) file containing `declare module 'pino';
```

How do I use Pino correctly with TS? I need to use its types as well.
Thank you

**Comment by mcollina** [comment]
From v7 types are shipped in the module, you don't need to install them separately

**Comment by Teyler7** [comment]
Hey, @adibhanna. 

Like @mcollina stated, **types are included in `pino` 7+**. My issue was that `@types/pino` (Which is not a direct dependency of `pino`) was causing type issues with the built in types for `pino` 7+. It's worth noting that `@types/pino` You will notice this change in the npm depreciation notice: https://www.npmjs.com/package/@types/pino

So if you are on Pino 7+, removing `@types/pino` should resolve the issue:
```shell
yarn remove @types/pino
```
