### ISSUE TITLE
Confusing "destination" docs

### ISSUE THREAD

**Issue by Ragnoroct** [pinojs/pino#1312]
The docs for destination are a bit confusing https://getpino.io/#/docs/api?id=destination 

It says it can accept an object with a `write` method or a Node.js stream but I found those did not work.

I dug into the code a bit and found that `destination` building a `SonicBoom` instance that is just looking for a string path or a file descriptor.

https://github.com/pinojs/pino/blob/54cd23b8ca1839fc38902f653327573585692ec0/pino.js#L186-L193
https://github.com/pinojs/pino/blob/54cd23b8ca1839fc38902f653327573585692ec0/lib/tools.js#L335-L336

**Comment by wbender-wurl** [comment]
Oh I see. the `destination` parameter can be any stream like object, fd, or path. The `destination` function only takes a `fd` or `path`. 

I still think that's confusing :thinking:

**Comment by mcollina** [comment]
We might want to change the name /behavior of some options if they are confusing.

**Comment by shayded-exe** [comment]
Just ran into this after scratching my head for an hour trying to pass a stream to `pino.destination()`.

The typings are incorrect.

https://github.com/pinojs/pino/blob/86c7b3ac924f7d0b4c8343f774ec3b8834e7db09/pino.d.ts#L756-L758

**Comment by mcollina** [comment]
cc @kibertoad
