### ISSUE TITLE
Pino does not produce JSON output, just text message within NextJS middleware function

### ISSUE THREAD

**Issue by pawelgalazka** [pinojs/pino#1315]
When using Pino within NextJS middleware function:

`pages/_middleware.ts`
```ts
import { NextFetchEvent, NextRequest, NextResponse } from "next/server"
import pino from "pino"

const logger = pino()

export function middleware(req: NextRequest, ev: NextFetchEvent) {
  logger.info("Pino log from middleware")
  return NextResponse.next()
}
```

and then I run `next dev`, request the page, Pino does not outputs message within JSON format:
```
Pino log from middleware
```

Weirdly when I use the same logging within any page component:

```tsx
const logger = pino()

const Home: NextPage = () => {
  logger.info("Pino log from page component")
  return (<div>Test</div>)
})

export default Home
```

Pino outputs log in JSON format:
```
{"level":30,"time":1643780601305,"pid":26203,"hostname":"xxxx.local","msg":"Pino log from page component"}
```

Not sure what's going. What can cause Pino dropping JSON format and falling back to plain text message?

**Comment by mcollina** [comment]
I think that's correct. The Vercel middleware is bundled as it would run on the frontend, picking the browser version of pino.
My understanding of the Vercel platform is that the middlewares do not run on Node, so this is needed. You might want to open an issue on Next.
