### ISSUE TITLE
Multiple redaction rules?

### ISSUE THREAD

**Issue by mziwisky** [pinojs/pino#1319]
Is it possible to use multiple redaction rules?  E.g. something like:
```js
pino({
  redact: [
    {
      paths: ['req.headers.authorization'],
    },
    {
      paths: ['req.id'],
      remove: true,
    },
  ],
})
```
I want the value at `req.headers.authorization` to be replaced by a censor (in this case, the default "[Redacted]") but i also want the key `req.id` to be completely removed.  The code above doesn't work, as `redact` can only be a single object or an array of strings (paths), but is there some recommended way to pull this off?

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/ef5e2e64164af01967b033c186910a6eb6f4cd7a/docs/api.md#serializers-object

**Comment by Fdawgs** [comment]
@mziwisky Did you manage to resolve this?

**Comment by mziwisky** [comment]
I did not resolve this, but I don't use pino anymore, so we're good.
