### ISSUE TITLE
Redact modifies the values being logged

### ISSUE THREAD

**Issue by Ruddickmg** [pinojs/pino#1320]
This is just an FYI, I'm sorry I can't provide a test case. While using the redact feature of pino, It modified the data being logged causing errors in the system. This happened when applying redact to an array element `*[*].data`. This seems like a very dangerous bug and is difficult to find with the assumption that logging should not modify the data being logged.

**Comment by mcollina** [comment]
In order to perform redaction with minimal overhead, it mutates all objects being logged and then restores those properties. Unfortunately that's the tradeoff. You could always resort to adding serializers.
