### ISSUE TITLE
Redact not properly restoring properties after modification

### ISSUE THREAD

**Issue by Ruddickmg** [pinojs/pino#1321]
Hi, I opened an [issue regarding redact modifying objects that were being logged](https://github.com/pinojs/pino/issues/1320) yesterday. I got a response [here](https://github.com/pinojs/pino/issues/1320#issuecomment-1028436897) which did not really address the issue which may be due to me not understanding the problem. To clarify, the errors that came about were due to `redact` not properly restoring the objects after modifying them.

The object logged before passing it in to the pino logger looked like this:

```ts
{
  action: {
    resource: "event",
    target: "some-target",
    data: { hello: "world" },
  },
  compensate: {
    resource: "event",
    target: "some-target",
    data: { goodbye: "world" },
  },
}
```

After logging with pino the object was modified to this:

```ts
{
  action: {
    resource: "event",
    target: "some-target",
    data: { goodbye: "world" },
  },
  compensate: {
    resource: "event",
    target: "some-target",
    data: { goodbye: "world" },
  },
}
```

The path definitions I had defined are as follows:

```ts
const pinoConfiguration = {
  redact: {
    paths: ['data', 'body', '*.data', '*.*.data', '*[*].*.data', '[*].data'],
    remove: true,
  },
  ...otherConfigDetails,
};
```

Based on this it seems like maybe if you have two properties in the same object that share an identically named field, the redact algorithm will replace them both of the identically named fields with one of them (in this case the last one it sees?) when "restoring" the object. If it helps the logged objects were in an array so most likely effected by the `[*].data` or `*[*].data` path definitions.

I'm pretty sure this is a bug, but if it cannot be addressed, please let me know what you mean by your comment "You could always resort to adding serializers". This behavior makes redact unusable to me and I may need to switch logging libraries if I can't sanitize sensitive data from the logs (Which it is my goal to avoid doing).

**Comment by jsumners** [comment]
Why have you opened another issue instead of following up in the original? Also, provide a minimal reproduction of the problem.

**Comment by Ruddickmg** [comment]
The original was closed, so I opened a new one. I'm not sure how to reproduce the bug as the code base is rather large and private. I'm just letting you know this bug exists in your application, do with that what you will.

**Comment by jsumners** [comment]
Without a minimal reproduction we are unable to help.
