### ISSUE TITLE
Using pino for assert errors

### ISSUE THREAD

**Issue by Kostanos** [pinojs/pino#1324]
For those who is interested on https://github.com/pinojs/pino/issues/1040

I found a small workaround, that may help

```
process.on('uncoughtException', err => {
  if (err.constructor.name === 'AssertionError') {
    pino({....});
  } else throw err;
}
```

This way, if you are using assert to validate function input, or other input parameters, you can have a nicely formatted response without putting assert into a `try/catch` block in every place.

**Comment by jsumners** [comment]
Thank you.
