### ISSUE TITLE
About the benchmarks result

### ISSUE THREAD

**Issue by dbacarel** [pinojs/pino#1325]
Hello 🌲ers,

I was playing a bit with the library and decided to run locally the `benchmarks/basic.bench.js`.
I found myself a bit puzzled when I compared the output with the results published in [Pino BASIC benchmark averages](https://getpino.io/#/docs/benchmarks?id=benchmarks) -  for some reason the results from the local run are much bigger (~2x) than those published in the page so I decided to take a look at the code.

In [benchmarks/basic.bench.js](https://github.com/pinojs/pino/blob/master/benchmarks/child-child.bench.js), each test consists of a ```for-loop``` that calls each logger ```max``` times, where ```max = 10```.  The benchmark terminates after ```10000``` iterations and prints out the averages.
The documentation page says: "_The following values show the time spent to call each function 100000 times_" so I decided to set ```max=1```  and set the number of iterations to ```10e4```, and viceversa:

#### max = 1 && iterations = 10e4
```
benchBunyan*100000: 1.320s
benchWinston*100000: 1.410s
benchBole*100000: 973.728ms
benchDebug*100000: 1.236s
benchLogLevel*100000: 1.168s
benchPino*100000: 2.225s
benchPinoAsync*100000: 1.810s
benchPinoNodeStream*100000: 1.244s
```
#### max = 10e4 && iterations = 1
```
benchBunyan*1: 346.062ms
benchWinston*1: 696.33ms
benchBole*1: 149.684ms
benchDebug*1: 198.902ms
benchLogLevel*1: 229.385ms
benchPino*1: 298.154ms
benchPinoAsync*1: 127.039ms
benchPinoNodeStream*1: 169.072ms
```
#### max = 10 && iterations = 10e3
```
benchBunyan*10000: 500.61ms
benchWinston*10000: 414.279ms
benchBole*10000: 219.685ms
benchDebug*10000: 300.176ms
benchLogLevel*10000: 307.505ms
benchPino*10000: 429.827ms
benchPinoAsync*10000: 228.316ms
benchPinoNodeStream*10000: 238.748ms
```

My thoughts are:
- Is there anything that I'm interpreting in the wrong way?
- Should I file a PR proposing Configuration#2?
- Configuration#1 output shows huge latencies, how come? Based on my understanding, I expected to see those values with Configuration#2.
  My interpretation is: call for ```max``` times, store execution time, repeat ```iterations``` times. Print out the average
- Should we consider dropping `fastbench` in favour of a more practical alternative (too naive?), like:

```javascript
const benchmark = (fns, iterations) => {
  const results = {}
  let timeAcc = 0
  const benchmark_ = function (fn) {
    timeAcc = 0
    for (let i = 0; i < iterations; i++) {
      const startTime = performance.now()
      fn()
      timeAcc += performance.now() - startTime
    }
    results[fn.name] = timeAcc
  }

  fns.forEach(benchmark_)
  fns.forEach(fn => {
    console.log(`${fn.name} average ${results[fn.name]}ms`)
  })
}

// Run benchmark
benchmark([
  function benchBunyan () {
    blog.info('hello world')
  },
  // ...
   function benchPino () {
    plogDest.info('hello world')
  }], 10e4);
```
#### iterations: 10e4
```
benchBunyan*100000 avg: 471.9955081343651ms
benchWinston*100000 avg: 791.2824565172195ms
benchBole*100000 avg: 165.09488606452942ms
benchDebug*100000 avg: 215.48404896259308ms
benchLogLevel*100000 avg: 229.3926374912262ms
benchPino*100000 avg: 251.84785568714142ms
benchPinoAsync*100000 avg: 188.01576679944992ms
benchPinoNodeStream*100000 avg: 280.7638087272644ms
```
- Purely based on ```basic.bench.js``` benchmark it seems that Bole logger is doing a great job compared to any flavour of Pino - if these numbers are validated by you then we should update the [Benchmarks section ](https://getpino.io/#/docs/benchmarks?id=benchmarks)

I apologise for the long post and, great job guys!

**Comment by mcollina** [comment]
I'm not sure why you closed this. It's a long report (as you said) and as such it's not easy to process in a busy week.

Thanks for checking it out, we'll do our due diligence and get back,

**Comment by dbacarel** [comment]
my bad, I closed it without leaving any note.
I only later on realised that there's a ```bench-basic``` task in place, while for my tests I just ran ```node test/benchmarks/basic.bench.js```. The reason for closing the issue was simply to put this on hold while verifying that anything relevant was involved in ```bench-basic``` task - next time I should just leave a comment.

Results from running that task are however in line with those listed in **#Configuration 3** so, I guess it's ok to keep this open for a validation.

Thanks for taking your time to review this, I appreciate it

**Comment by mcollina** [comment]
Which operating system are you testing them on? I can see quite a skew between Mac OS X and Linux - which I find very interesting.

The results on my dedicated Linux machine are:

```
$ node benchmarks/basic.bench.js
benchBunyan*10000: 414.807ms
benchWinston*10000: 286.033ms
benchBole*10000: 162.9ms
benchDebug*10000: 228.067ms
benchLogLevel*10000: 240.081ms
benchPino*10000: 152.771ms
benchPinoAsync*10000: 79.712ms
benchPinoNodeStream*10000: 169.184ms
benchBunyan*10000: 364.914ms
benchWinston*10000: 233.512ms
benchBole*10000: 150.972ms
benchDebug*10000: 219.359ms
benchLogLevel*10000: 238.837ms
benchPino*10000: 146.255ms
benchPinoAsync*10000: 74.246ms
benchPinoNodeStream*10000: 166.182ms
```

I've also tried a few other configurations and the result are all quite similar. Pino "sync" is as fast as bole, pino "async" is significantly faster, pino with a node stream is slightly slower (likely due to a bit more features we have).

I'm not exactly sure why the result on the Mac are so different - however it's not really a target production scenario.

**Comment by dbacarel** [comment]
Indeed, I ran it on a macOS Monterey - that's quite the difference!

Now I tested it on my Linux machine as well and I can confirm your results:
```
benchBunyan*10000: 589.614ms
benchWinston*10000: 576.806ms
benchBole*10000: 251.527ms
benchDebug*10000: 322.638ms
benchLogLevel*10000: 348.432ms
benchPino*10000: 195.499ms
benchPinoAsync*10000: 114.089ms
benchPinoNodeStream*10000: 271.667ms

benchBunyan*10000: 541.317ms
benchWinston*10000: 461.89ms
benchBole*10000: 241.261ms
benchDebug*10000: 326.996ms
benchLogLevel*10000: 365.495ms
benchPino*10000: 186.712ms
benchPinoAsync*10000: 112.197ms
benchPinoNodeStream*10000: 250.96ms
```

It's interesting how Pino seems to choke more when running on macOS, compared to others:
| Logger * 10000      | Linux (ms) | macOS (ms) | macOS / Linux |
|---------------------|------------|------------|---------------|
| benchBunyan         | 541,317    | 436,580    | 0,806514482   |
| benchWinston        | 461,890    | 406,524    | 0,880131633   |
| benchBole           | 241,261    | 231,663    | 0,960217358   |
| benchDebug          | 326,996    | 301,054    | 0,920665696   |
| benchLogLevel       | 365,495    | 303,889    | 0,831445027   |
| benchPino           | 186,712    | 408,337    | 2,186988517   |
| benchPinoAsync      | 112,197    | 220,830    | 1,968234445   |
| benchPinoNodeStream | 250,960    | 213,452    | 0,850541919   |

of course, this doesn't represent a valid statistical sample


> I'm not exactly sure why the result on the Mac are so different - however it's not really a target production scenario.

Agreed
