### ISSUE TITLE
How do you add custom stream to existing pino logger?

### ISSUE THREAD

**Issue by lxbc135** [pinojs/pino#1327]
How do you add custom stream to existing logger, like the older Probot's Bunyan logger `app.log.target.addStream(myStream)`?

Would like to upgrade to Probot v11+, which uses `pino` instead of `bunyan`.  So need pino equivalent of `addStream`.

Reference: [probot/issues/776](https://github.com/probot/probot/issues/776)

**Comment by dbacarel** [comment]
I think you need to create your custom ```transport``` - see https://getpino.io/#/docs/transports

**Comment by mcollina** [comment]
you will need to pass in a `pino.multistream()`, it has an `add` method that is not documented and it should be https://github.com/pinojs/pino/blob/ef5e2e64164af01967b033c186910a6eb6f4cd7a/lib/multistream.js#L124.

**Comment by dbacarel** [comment]
I guess that this issue can be closed now

**Comment by mcollina** [comment]
Thanks!
