### ISSUE TITLE
Feature: `pino.destination(string)` to interpolate env-vars

### ISSUE THREAD

**Issue by osher** [pinojs/pino#1332]
I think it would be useful that when `pino.destination(..)` is provided with a string - to interpolate env-vars if any.

e.g.:, consiuder
```
LOG_PATH=/builds/lksalEdq/0/my-org/my-repo/logs node node_modules/my-app/bin/svr
```
then, 
```
const d = pino.destination('${LOG_PATH}/my-app.log');

//resulting with  /builds/lksalEdq/0/my-org/my-repo/logs/my-app.log
```

## Use Case
The use-case is to be able to pass to applications that use pino (e.g. `verdaccio`) configuration that interpolates.
I do not develop `verdaccio` - I use it, and it in turn uses `pino` (see [here](https://github.com/verdaccio/verdaccio/blob/b78f35257e8a7284ccf30d948a73042da392f151/packages/logger/src/logger.ts#L144))

So mind that **_explicitly_** do **_not_** pass to `pino.destination(...)` a template-expression - but a string that should interpolate once, on load time.

 more info - [here](https://stackoverflow.com/questions/69668866/persisting-gitlab-ci-service-data-across-jobs-in-a-pipeline-or-how-to-seed-dat/70865469) my nick there is Radagast the Brown.

## implementation 
I think of something in the sort of:
```javascript
function normalizeDestFileDescriptor (destination, { env } = process) {
  const fd = Number(destination)
  if (typeof destination === 'string') {
    if (Number.isFinite(fd)) {
      return fd
    }

    destination = destination.replace(/$\{([a-z][a-z0-9_]}+)\}/gi, (expr, envVar) => envVar in env ? env[envVar] : expr);
  }

  return destination
}
```

would you embrace such a PR?
if yes, I'll add this change + tests.

**Comment by mcollina** [comment]
thanks for opening this issue, however I see quite a few ways this could become a potential security issue. I would recommend to ask to implement this feature to maintainers of Verdaccio.

**Comment by jsumners** [comment]
This is an application level feature. Pino accepts configuration and it is up to the developer to determine how that configuration is built.
