### ISSUE TITLE
Question: Merge all keys except certain ones under a single property

### ISSUE THREAD

**Issue by skrishnan22** [pinojs/pino#1340]
So, let's say I write` logger.info({description: 'Users fetched successfully',  path: '/users',  userData: {name: 'user'}, totalCount: 10}})`.
What is the best way to combine `userData` and `totalCount` under a single field like `metaData` while logging

Should I use hooks?

**Comment by jsumners** [comment]
The "best way" is to log what you intend:

`logger.info({ description: 'foo', metaData: { userData, totalCount } })`.

But if you don't care about performance of the logger, sure, use the `logMethod` hook.
