### ISSUE TITLE
How to ouput pino-pretty to console and file at the same time

### ISSUE THREAD

**Issue by FluffyDiscord** [pinojs/pino#1341]
As the `prettyPrint` option is deprecated, how can I output pretty printed log to two streams - console and file - at the same time ?

Currently I am using configuration bellow which works fine for me for now
```node
const pino = require('pino')
const logger = pino({
    prettyPrint: true
}, pino.multistream([
    { stream: process.stdout },
    { stream: fs.createWriteStream('/path/last.log') }
]))
```

**Comment by dbacarel** [comment]
According to https://github.com/pinojs/pino-pretty#programmatic-integration, the alternative is to use [pino-pretty transport](https://getpino.io/#/docs/transports?id=pino-pretty) 
which writes onto `stdout` by default.

So, you would need something like this:
```js
const pino = require('pino')
const transport = pino.transport({
  targets: [{
    level: 'info',
    target: 'pino-pretty' // must be installed separately
  }, {
    level: 'trace',
    target: 'pino/file',
    options: { destination: '/path/last.log' }
  }]
})
const logger = pino(transport)
```

**Comment by FluffyDiscord** [comment]
With this approach only console output is formatted, but the log file is still a raw json. I would like to have pretty formatted output in both

**Comment by dbacarel** [comment]
`pino-pretty` transport writes to `stdout` by default but "_the options.destination property may be set to log pretty logs to a file descriptor or file._"  see [pin-pretty transport](https://getpino.io/#/docs/transports?id=pino-pretty)

Like so:
```js
const pino = require('pino')
const transport = pino.transport({
  targets: [{
    level: 'info',
    target: 'pino-pretty'
  }, {
    level: 'info',
    target: 'pino-pretty',
    options: { destination: '/tmp/last.log' }
  }]
})
const logger = pino(transport)
```
