### ISSUE TITLE
Can you stop Pino from logging to the browser console?

### ISSUE THREAD

**Issue by moshie** [pinojs/pino#1347]
Hi,

Currently we are using a custom transport to handle logs we noticed that pino is also logging to the browser's console.  

Is there any way of turning this off in a production environment?

Sorry if this is already answered in the docs I couldn't find it anywhere.

**Comment by mcollina** [comment]
I don't think it's possible to disable right now, would you like to open up a PR?

**Comment by moshie** [comment]
Sure, how would you like the api to work?

**Comment by mcollina** [comment]
Maybe add a flag to disable it?

**Comment by ntedgi** [comment]
hi @moshie are you still working on it ? if not i would like to help here

**Comment by moshie** [comment]
Hey nope haven't started this yet feel free to pick it up 🙂

**Comment by dancastillo** [comment]
Would this solve the issue? Its not in docs but sets log level to `Infinity`
https://github.com/pinojs/pino/blob/master/browser.js#L56
