### ISSUE TITLE
pino is an empty module in the jest context

### ISSUE THREAD

**Issue by SalvadorJJ** [pinojs/pino#1358]
In my `logger.js` file I import pino in the following way
```javascript
const pino = require("pino");

// more code
```
Everything works fine.
just for test it if I do a console.log of pino.

```javascript
const pino = require("pino");
console.log(pino);  <---- the output is the module pino

// more code
```
the output is the expected. It's the module pino

but if I run pino since a jest unit test as the following way
```javascript
it(" ", () => {
   functionWherePinoIsCalled();
});

// more code
```

The output of the console log is `{}`

```javascript
const pino = require("pino");
console.log(pino);  <----- the output is {}

// more code
```

Therefore functions like `pino.destination`  can't be called because pino is undefined.

Why pino module is an empty object in the jest context?

**Comment by jsumners** [comment]
No idea. You should ask the Jest maintainers.

**Comment by mcollina** [comment]
Note that we test that pino is compatible with jest, so this is likely a problem in your setup.

**Comment by ntkoopman** [comment]
I have the same issue and it seems to be caused by pino being in a parent node_modules directory instead of the project one (we are using yarn workspaces)
