### ISSUE TITLE
employ an .npmignore file

### ISSUE THREAD

**Issue by osher** [pinojs/pino#136]
the published package is pacaked with all the sources in it, including tests, examples, demo.png and all.

published package should be slim and elegant.

proposed file:
`.npmignore`
```
benchmarks
test
example
CONTRIBUTING.md
*.png
*.yml
*.txt
```

**Comment by jsumners** [comment]
I agree. I just wish adding a npmignore file didn't cause npm to then ignore the gitignore file and make keeping them synced a problem.

**Comment by osher** [comment]
rich mans problem.

**Comment by osher** [comment]
mm. thats a nice idea for a CLI tool...
maybe I'll work on it later

**Comment by davidmarkclements** [comment]
@mcollina and I have some pretty strong views on keeping `test`, and to some extent example, folder in published module - possibly by extensions benchmarks too

*but* if we were to to do this, we might consider whitelisting instead via the `files` array in `package.json`

**Comment by jsumners** [comment]
For our code size, I'm really not concerned either way. I do like a production install only having what is absolutely necessary. But during development it can be useful to have these things delivered with the module so that you can easily peruse it if needed. So for me, ^shrug^.

**Comment by mcollina** [comment]
IMHO we should do this to remove the `*.png` files at a bare minimum. I really think we should retain the tests, examples and CONTRIBUTING.md. I actually prefer the `files` approach.

**Comment by osher** [comment]
I never thought this will become such a discussion.

https://github.com/pinojs/pino/pull/137

**Comment by osher** [comment]
@jsumners - when a package is installed as a dependency, there is no distinction between dependency on production and dependency on a developer machine.
The idea is that develoeprs that work on a package work with GIT and get everything from there.
All the rest - production, stage, QA, and developers that just use the package - get it from NPM.

To sum up:
- publish to NPM a slim package 
- keep in GIT all the dev-utils, docs, examples and design (excluded from published pacakges)

**Comment by jsumners** [comment]
I understand that there is no distinction. But I *do* navigate to modules within a project's `node_modules` to view the docs, code, and tests (since most people think they are documentation). So there is a reason to keep such things in the package. At the same time, I understand the desire to *not* have those things delivered when installing as a dependency for production. Hence my stance of accepting either solution.

**Comment by mcollina** [comment]
I think we are all in for a `files` section, and removing the not needed things: png, yml, benchmarks.

**Comment by jsumners** [comment]
@osher please update your PR to remove the `npmingore` file and add a `files` property to the `package.json` -- https://docs.npmjs.com/files/package.json#files

**Comment by osher** [comment]
@jsumners -
> But I do navigate to modules within a project's node_modules to view the docs, code, and tests
You're expectation is not correct.
In the `node_modules` you'll find `package.json` and from there you'll expect the homepage. 
This is where you should expect docs.
As for tests - you should expect them in the repository, also named in `package.json`.

**Comment by osher** [comment]
@mcollina  - will do

**Comment by osher** [comment]
Please double-check me, 
Is this a good result?
![image](https://cloud.githubusercontent.com/assets/803101/20887980/90997d96-bb05-11e6-896a-7d777eace475.png)

I mean - do I miss something or do I include something unecessary?

**Comment by mcollina** [comment]
Yes, you missed a lot. Read again https://github.com/pinojs/pino/issues/136#issuecomment-264023925.

I have a different expectation from
my modules. The assumption to go to a a doc website is not the goal of this project, as I would like to keep this project 100% consumable for a human being. 

More or less, the things you should remove are the png and the yml files, plus the benchmarks.

**Comment by osher** [comment]
Well, commit & pushed #137

**Comment by osher** [comment]
lets stop the ping pong, just let me know what's missing 😀

**Comment by osher** [comment]
Well, commit & pushed #137
