### ISSUE TITLE
Doesn't seem to work with ract-native

### ISSUE THREAD

**Issue by lolo-io** [pinojs/pino#1361]
Hi, I am using React Native and am trying to implement the Hello World from pino :

```
import pino from 'pino';

const logger = pino({});

logger.info('Hello World !');
console.info('Hello world !');

export default logger;
```

But both logger.info and console.info are giving me the same result in the react-native packager : 
```
 INFO  Hello World !
 INFO  Hello world !
```

**Comment by mcollina** [comment]
You are using the browser implementation of pino in react-native and that's the expected behavior.
