### ISSUE TITLE
does pino throttle output?

### ISSUE THREAD

**Issue by HUGEIT** [pinojs/pino#1369]
I was debugging something using pino and noticed that some functions are called with a noticeable delay. whilst I'm still not quite sure where the bottleneck in my code is I noticed that I'm seeing `console.log`s much earlier than the pino output.

pino seems to be instantaneous at first but as the process ages, the pino output seems to come in later and later.

I can see a few seconds' delay between a `console.log` and a `pino.trace` that are called at the same time.

I tried searching here for terms like "throttle" or "debounce" but I cannot find anything regarding that - should I? why are the output lines delayed sometimes?

(that is with a `{ level: 'trace' }` constructed object)

**Comment by mcollina** [comment]
Yes this is synchronous

**Comment by HUGEIT** [comment]
man I really don't know how to prove my point here. the statements are literally one after another and there is this delay.

I will check if I'm able to make a minimal example somehow

**Comment by HUGEIT** [comment]
ok here is an example output

code is:

```
date = new Date()
console.log(date.getMilliseconds(), "pre log")
logger.trace('log')
console.log(date.getMilliseconds(), "post log")
```

output is:

```
612 !!0 pre log
612 !!0 post log
{"level":10,"time":1647465394613,"pid":21554,"hostname":"me","msg":"log"}
```


after a few minutes this is worse:
```
908 pre log
908 post log
------14 seconds pass
{"level":10,"time":1647465595908,"pid":21554,"hostname":"me","msg":"log"}
```

and eventually it even goes cross-over:
```
622 pre log
622 post log
322 pre log
322 post log
{"level":10,"time":1647465595622,"pid":21554,"hostname":"me","msg":"log"}
{"level":10,"time":1647465595322,"pid":21554,"hostname":"me","msg":"log"}
```

like the console.log printed for iteration n AND for iteration n+1 which are at least 20 seconds apart before suddenly the logging catches up with the console.logs but not at all in an synchronous order with the console.logs


any idea?

**Comment by mcollina** [comment]
What OS is this code running? Could you upload a complete example to reproduce this problem: something I can run on my system.

**Comment by doums** [comment]
Hi, I'm not 100% sure, but maybe I'm currently facing the same weird problem with pino :

This is how I instantiate pino
```ts
    const loggerOptions: LoggerOptions = {
      level: LOG_LEVEL,
      formatters: {
        // in production print the label instead of the numeric value of the level
        level: (label) => ({ level: label }),
      },
    };

    this.log = pino(loggerOptions);
```
Then this same logger instance is used throughout our app (we use the same instance, we don't recreate new ones). We just do usual log like `log.debug`, `log.info` and `log.error`. This is the only interactions we have with the logger. Nothing special.

Our app is just a simple gRPC server, and for debugging, the only call made to it is each 5 seconds we emit a health check call. For one health check call, we output 2 log lines (we make to call to `log.info()`). The server respond well to this health check.
But from some point in time, pino starts to write the output after ~10min instead of the expected 5s freq, and write a big batch of log lines at once.

**Comment by doums** [comment]
@mcollina you mixed posts from @HUGEIT and mine @doums

**Comment by mcollina** [comment]
I would really like to have a way repro this

**Comment by HUGEIT** [comment]
I'm really sorry but I'm unable to make a minimal example.

we have this somewhat big project that showcases that behavior under specific circumstances but if I try to fetch the relevant bits and loop them 50k times, I cannot reproduce and pino works as expected. it's only with the big project that this issue comes up. 

what I thought to be too was that it happens once CPU usage sticks to 100 for a while and then even after cooling off however the tests I made today showed that as long as the CPU is not busy, the logs come in as normal.

so all in all this may actually be a case about "console.log is strictly sync, pino does some more processing and is less tight to when its data can write to the output stream".

I will let you know once I find more

**Comment by mcollina** [comment]
> "console.log is strictly sync, pino does some more processing and is less tight to when its data can write to the output stream".

That's not correct. The default configuration of pino uses `fs.writeSync()`. Or are you using any other configuration?

What version of pino are you using?

**Comment by jsumners** [comment]
Are all logs properly timestamped?

**Comment by CoderIvan** [comment]
I also encountered this problem.

After my observation, this delay increases over time

When I switched back to `console.log`, the problem no longer appeare

**Comment by mcollina** [comment]
Closing for now. If anybody could produce a reproduction script for this I would love to take a look.
