### ISSUE TITLE
Can not reuse Pino-pretty before sending message to any target

### ISSUE THREAD

**Issue by anton-hniadyi** [pinojs/pino#1411]
You are killing me!
Why I can't use Pino-pretty in a pipeline for formatting data before sending to any target?
It is very simple approach format it before sending to anywhere...
But instead this I should spend a lot of time to figure out how to format my data before sending to any target.
Why I can't use option "prettyPrint: true" for formatting before sending to anywhere?
Why I can't just reuse Pino-pretty for formatting?

**Comment by mcollina** [comment]
I'm closing this. Feel free to dig  deep and figure things out. Your tone in the message does not invite anyone of the maintainers in giving you an answer. They owe you nothing after all.
