### ISSUE TITLE
Special characters are messed up

### ISSUE THREAD

**Issue by vsnthdev** [pinojs/pino#1412]
### 🐛 What happens

When creating a custom prettifier function, special characters break in the output.

Using the following code to create a custom prettifier function 👇

```javascript
const logger = pino({
    prettifier: () => () => {
        return '•'
    },
    level: 10,
    prettyPrint: {
        colorize: false,
    },
})
```

The following is the output 👇

![Snip](https://user-images.githubusercontent.com/24322511/164748754-76e2226d-bed6-4179-92a6-d7dfef473860.jpg)

### ✅ What should happen

Special characters & emojis and colored text should be left intact 👇

![Snip](https://user-images.githubusercontent.com/24322511/164749114-73d05082-f005-479d-a718-df59c04e33e3.jpg)

### ♻️ Steps to reproduce

1. Create a new Node.js project
2. Install `pino` as dependency
3. Create `app.js` and put the following code 👇

```javascript
const pino = require('pino')

const logger = pino({
    prettifier: () => () => {
        return '•'
    },
    level: 10,
    prettyPrint: {
        colorize: false,
    },
})

logger.info('I am a info message')
```

----

#### ℹ️ Information
1. **Node.js:** v18.0.0
2. **npm:** v8.6.0
3. **pino:** v6.13.1

Happy to provide more information regarding this issue 😊

**Comment by mcollina** [comment]
Thanks for reporting. However we will be removing all of that prettifier implementation in the next release. You can now do all the post-processing of log lines in a separate thread, check out https://getpino.io/#/docs/transports.
