### ISSUE TITLE
Unknown file extension ".ts" when using pino.transport targets

### ISSUE THREAD

**Issue by HPieters** [pinojs/pino#1416]
I am migrating to pino 7 and decided to take advantage of the new transport functionality. However I keep running into an "issue" that I am unsure is due to my lack of understanding or bad doc reading. I am using typescript / ts-node which as far as I can tell should work as of PR [https://github.com/pinojs/pino/pull/1381](https://github.com/pinojs/pino/pull/1381).

The issue I am having is that my transport is working when just using pino.transport with target but is not working when using multiple targets, below I have a simpler example of the code I am using.

**transport.ts**
```typescript
import { once } from 'events';
import build from 'pino-abstract-transport';
import SonicBoom from 'sonic-boom';

export default async function () {
  const destination = new SonicBoom({
    dest: 1,
    sync: true,
  });
  await once(destination, 'ready');

  return build(
    async (source) => {
      for await (let obj of source) {
        const toDrain = !destination.write(JSON.stringify(obj) + '\n');

        // This block will handle backpressure
        if (toDrain) {
          await once(destination, 'drain');
        }
      }
    },
    {
      async close() {
        destination.end();
        await once(destination, 'close');
      },
    },
  );
}
```

**working-logger.ts**
```typescript
const transport = pino.transport({
      target: './transport.ts',
    })

const logger = pino(
  {
    name: 'example-logger',
    level: 'silly',
    customLevels: {
      silly: 1,
    },
  },
  transport,
);
```

**broken-logger.ts**
```typescript
const transport = pino.transport({
     targets: [
          {
            target: './transport.ts',
          } as any,
        ],
        levels: {
          silly: 1,
        },
    })

const logger = pino(
  {
    name: 'example-logger',
    level: 'silly',
    customLevels: {
      silly: 1,
    },
  },
  transport,
);
```

broken-logger.ts actually returns `"Error: the worker has exited"` but if I wrap it in an async function with a catch the error message becomes `Caught exception: TypeError: Unknown file extension \".ts\" for /<redacted>/transport.ts\n Exception origin: uncaughtException"`. If anyone could point me in the right direction that would be great.

**Comment by climba03003** [comment]
The last published version is `18 days ago` and the PR is merged `8 days ago`.
I think it is just pending to be release.

The reason why `target` works because `thread-stream` support `.ts` in released version. And `target` is processed by `thread-stream`.

**Comment by HPieters** [comment]
Thanks for the quick update and the release! Due to `- For "pure" TypeScript code, ES imports are still not supported (ES imports are supported once the code is transpiled)` I still cannot use my typescript code. However I realised I don't need my transport worker to be typescript, and by using .mjs rather than .ts it all works like a charm!

**Comment by HPieters** [comment]
Thanks for the quick update and the release! Due to `- For "pure" TypeScript code, ES imports are still not supported (ES imports are supported once the code is transpiled)` I still cannot use my typescript code. However I realised I don't need my transport worker to be typescript, and by using .mjs rather than .ts it all works like a charm!
