### ISSUE TITLE
Cannot find module 'thread-stream' from 'node_modules/pino/lib/transport.js'

### ISSUE THREAD

**Issue by akashishu777** [pinojs/pino#1422]
Fastify test is failing

<img width="778" alt="image" src="https://user-images.githubusercontent.com/19200161/165909617-6df7f2fb-3279-4306-9ec9-6a1fed0f3e07.png">

**Comment by mcollina** [comment]
For some reason your node_modules does not contain the needed dependencies. Remove it, remove your lock files, and install everything again.

**Comment by akashishu777** [comment]
@mcollina, After many tries I am getting a different error now, can you please have a look

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/19200161/165927607-2875f95b-4557-43c4-a7b0-2894e9c0830d.png">
