### ISSUE TITLE
Unclear how an error is received from worker transport

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#1437]
I'm trying to understand how a worker thread is passing an error back to the main Pino process through the worker message bus. In the code below there is a transport with an internal `EventEmitter` that emits an unhandled `error` event. Yet, somehow, we can attach an `.on('error')` listener to the transport and handle that emitted event. How does this work?

<details>
<summary>package.json</summary>

```json
{
  "dependencies": {
    "pino": "^7.11.0",
    "pino-abstract-transport": "^0.5.0"
  }
}
```

</details>

<details>
<summary>index.js</summary>

```js
'use strict'

const pino = require('pino')
const transport = pino.transport({
  target: './transport.js'
})

// Comment out this listener setup and the script will generate a process
// crash due to an unhandled error event.
transport.on('error', err => {
  console.error('error caught', err)
})

const log = pino(transport)
log.info('hello world')
```

</details>

<details>
<summary>transport.js</summary>

```js
'use strict'

const build = require('pino-abstract-transport')
const {Writable} = require('stream')
const {EventEmitter} = require('events')

module.exports = function (opts) {
  const emitter = new EventEmitter()

  const writeSteam = new Writable({
    objectMode: true
  , autoDestroy: true
  , write(chunk, _, cb) {

    console.log(chunk)
    emitter.emit('error', Error('boom'))

    cb(null)
  }
  })

  return build(function (source) {
    source.pipe(writeSteam),
    {
      close(err, cb) {
        writeSteam.once('close', cb.bind(null, err))
        writeSteam.end()
      }
    }
  })
}
```

</details>

**Comment by mcollina** [comment]
The error is catched in:

https://github.com/pinojs/thread-stream/blob/f19ac8dbd602837d2851e17fbc7dfc5bbc51083f/lib/worker.js#L59-L70

and 

https://github.com/pinojs/thread-stream/blob/f19ac8dbd602837d2851e17fbc7dfc5bbc51083f/lib/worker.js#L135-L149

Then, it's forwarded to the transport `'error'` event in https://github.com/pinojs/thread-stream/blob/f19ac8dbd602837d2851e17fbc7dfc5bbc51083f/index.js#L163-L164

I hope it's clearer.

**Comment by mcollina** [comment]
It will be good to document this.

**Comment by TommyDew42** [comment]
Hi it seems this is sth I can help with. Lemme take this one.

**Comment by TommyDew42** [comment]
This is a really fun issue to work with.

One thing I was really confused about was why an `error` message emitted by an _internal_ `EventEmitter` will be caught by the process.
It turns out the `error` event actually would be thrown as a normal error to the nodejs program, when we don't have a `error` listener on an `EventEmitter`. ([reference](https://nodejs.org/api/events.html#error-events))
