### ISSUE TITLE
[Testing] Capture log output for use in tests

### ISSUE THREAD

**Issue by budarin** [pinojs/pino#1438]
We are developing a microservice in which we use pino logger as a logger.

During testing of the microservice, it throws out standard errors for various reasons.
Analyzing only the response of the service with a standard error does not give an idea and confidence that the service responds correctly to the request and responds with an error to a specific situation.

The only option to make sure that the service responded correctly to the request can only be the contents of the logs.

Our logger configuration:

```js
export const logger = pino(
    pino.destination({
        dest: 1,
        sync: isNotProduction,
    }),
);
```
Tell me how I can intercept the logger output for its analysis in the test?

Pino: 7.11.0
Jest: 28.1.0

**Comment by jsumners** [comment]
This has been answered in https://github.com/fastify/help/issues/677. Please do not open duplicate issues.
