### ISSUE TITLE
Can't remove pid, hostname & version field from each log line

### ISSUE THREAD

**Issue by itsgaurav** [pinojs/pino#1442]
Want to remove the _hostname_, _v_, & _pid_ attribute. Sample log output
 _{"level":"info","time":1653552674618,"pid":5911,"hostname":"Gauravs-MacBook-Pro.local","msg":"an info log","v":1}_

**Comment by mcollina** [comment]
Take a look at https://getpino.io/#/docs/api?id=base-object.

**Comment by wong2** [comment]
```
pino({
  formatters: {
    base: undefined
  },
  ...
})
```

this doesn't work
