### ISSUE TITLE
Invalid JSON in raw output

### ISSUE THREAD

**Issue by stuft2** [pinojs/pino#1443]
The following example produces invalid json. 

Node v16.15.0
Pino v7.11.0

```js
const Logger = require('pino')
const logger = Logger({ name: 'foo' })
logger.error({ name: 'bar' })
// {"level":50,"time":1653600298444,"pid":8629,"hostname":"<redacted>","name":"foo","name":"bar"}
//                                                                                   ^ duplicate property
```

It should print only one "name" property.

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=name-string
https://getpino.io/#/docs/child-loggers?id=duplicate-keys-caveat

**Comment by stuft2** [comment]
The error does not occur in the following example, which seems super inconsistent with the first example above:

```js
const Logger = require('pino')
const logger = Logger({ name: 'foo' })
logger.error('Error occurred', { name: 'bar' })
// {"level":50,"time":1653601274525,"pid":8956,"hostname":"<redacted>","name":"foo","msg":"Error occurred"}
```
Why is the merge object in this example property deduplicating the keys but it's not in the first example?

**Comment by jsumners** [comment]
> Why is the merge object in this example properly deduplicating the keys but it's not in the first example?

This is a bug. Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by stuft2** [comment]
I will take a look

**Comment by stuft2** [comment]
The reason the error doesn't occur in the second example is because I have the merge object in the wrong position. It should be first, with the message following. Not a bug.
