### ISSUE TITLE
Using pino logger with ECS format does not log custom attributes

### ISSUE THREAD

**Issue by ibadb** [pinojs/pino#1447]
I'm using the following code to return a pino logger instance. I want to log a custom 'name' attribute but I don't seem to get it to work. No errors. It just does not log the 'name' attribute. Everything else is working as expected. Is this the correct way to create a logger instance?

```
return pino(
      ecs(),
      pino.destination({
          dest: dest, 
          mkdir: true,
          sync: false
      }),
      { name: 'My Project' } // it does not work
 );
```
But if I change the code and remove the ECS function, it starts working as expected:

```
return pino(
      { name: 'My Project' },
      pino.destination({
          dest: dest, 
          mkdir: true,
          sync: false
      })
 );
```
I need to get it working with the ECS format (https://www.npmjs.com/package/@elastic/ecs-pino-format).

**Comment by mcollina** [comment]
@delvedor is the best person to ask this question to. Or possibly open an issue in ecs-pino-format.
