### ISSUE TITLE
Passing multiple streams into pino

### ISSUE THREAD

**Issue by kinghadi** [pinojs/pino#145]
Hi,

Is it possible to pass multiple streams into `pino`? Something like what we do in `bunyan` lib?

```javascript
var bunyan = require('bunyan');
var log = bunyan.createLogger({
    name: <string>,                     // Required
    level: <level name or number>,      // Optional, see "Levels" section
    stream: <node.js stream>,           // Optional, see "Streams" section
    streams: [<bunyan streams>, ...],   // Optional, see "Streams" section
    serializers: <serializers mapping>, // Optional, see "Serializers" section
    src: <boolean>,                     // Optional, see "src" section

    // Any other fields are added to all log records as is.
    foo: 'bar',
    ...
});
```

**Comment by jsumners** [comment]
We have https://github.com/pinojs/pino-multi-stream to support the transition from Bunyan to Pino.

However, you *really shouldn't do this*. Performance with multiple destination streams is abysmal -- https://github.com/pinojs/pino-multi-stream#caveats

You should reconsider how you are handling your logs and move to non-multi-stream Pino as early as possible.

**Comment by mcollina** [comment]
@jsumners just created this https://github.com/pinojs/pino-tee to do _just that_, externally.

**Comment by jsumners** [comment]
@mcollina nice. But it looks like it isn't a utility, just an API?

**Comment by mcollina** [comment]
it will be an utility :). Feel free to contribute it you want.

**Comment by kinghadi** [comment]
Thank you guys for your solutions. I want to see my logs in my stdout instead of a file in the time of development. I can redirect the stdout into a file but I don't know about the performance.

**Comment by jsumners** [comment]
@kinghadi is your issue resolved?
