### ISSUE TITLE
Pino imports entire package.json into distribution instead only version from it

### ISSUE THREAD

**Issue by budarin** [pinojs/pino#1451]
In meta.js

```js
'use strict'

const { version } = require('../package.json')

module.exports = { version }
```
and as a result whole `package.json` is included into dist

**Comment by jsumners** [comment]
What is the problem?

**Comment by budarin** [comment]
extra code in the assembly that increases its size

**Comment by jsumners** [comment]
What is your suggestion?

**Comment by budarin** [comment]
do it with instruments in building process  
we do this creating the file which exports prevaled the const in building process :)

**Comment by jsumners** [comment]
Pino does not use a build process. This is working as expected.

**Comment by mcollina** [comment]
We could potentially use the same flow Fastify uses. It's not too complex
to implement.

**Comment by kibertoad** [comment]
@mcollina https://github.com/fastify/fastify/pull/3427/files -> is this the one you are talking about?

**Comment by mcollina** [comment]
yes exactly!

**Comment by kibertoad** [comment]
@budarin Could you create a PR, replicating https://github.com/fastify/fastify/pull/3427/files in pino?

**Comment by budarin** [comment]
> @budarin Could you create a PR, replicating https://github.com/fastify/fastify/pull/3427/files in pino?

I'll try

**Comment by budarin** [comment]
> @budarin Could you create a PR, replicating https://github.com/fastify/fastify/pull/3427/files in pino?

I've prepared PR, but unfortunately I have no permission to create a new branch :(

**Comment by kibertoad** [comment]
Can you create a fork and push it there?
