### ISSUE TITLE
TypeScript complains with `This expression is not callable.` using basic init

### ISSUE THREAD

**Issue by whoyawn** [pinojs/pino#1452]
```
const logger = require('pino')()

logger.info('hello world')
```

leads to VSCode saying 

```
This expression is not callable.
  Type 'typeof import("/Users/name/node_modules/pino/pino")' has no call signatures.ts(2349)
```

My tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es2016",     
    "moduleResolution": "node",  
    "allowJs": true,              
    "checkJs": true,          
    "strictNullChecks": true,      
  "exclude": ["node_modules", "**/node_modules/*"]
}
```

Do I have to install anything else to get the compiler to recognize my js file?

**Comment by mcollina** [comment]
@kibertoad ptal

**Comment by kibertoad** [comment]
@whoyawn which pino version are you using?

**Comment by whoyawn** [comment]
Here are my versions
```
    "pino": "^8.0.0",
    "typescript": "^4.6.4"
```

**Comment by sleroq** [comment]
@whoyawn try this:

```ts
import { pino } from 'pino'
const logger = pino()

logger.info('hello world')
```

**Comment by dcsan** [comment]
@sleroq that doesn't work 

![image](https://user-images.githubusercontent.com/514002/184551831-2aea1dec-ccef-49e2-a807-0968f037ba3a.png)

it's also odd there's no real mention of typescript on the pino docs apart from at the transport level

**Comment by maxxheth** [comment]
After wasting at least a couple of hours debugging this issue, I have a friendly word of warning to anyone using the `baseUrl` option in their tsconfig.json.

If you have it set to your root, it'll mess with TS's ability to properly resolve node_modules unless you also use the path option to point to the pino package like so:
`{`
`  "baseUrl": "./",`
`  "paths": {`
`    "pino": ["./node_modules/pino"]`
`  }`
`}`

The TS docs do spell out how this works, but they don't do a good enough job of forewarning users about pitfalls like this. Happy coding everyone!
