### ISSUE TITLE
Log crash if provided error message contains placeholders

### ISSUE THREAD

**Issue by jeandat** [pinojs/pino#1455]
node: 16.15.1
pino: 8.0.0
pino-http: 7.1.0
pino-pretty: 8.0.0

I format my error logs like this : 

```
logger.error(exception, '%s ⟡ 🛑 Responding with error', debugId);
```

pino shows me something like this:

```
err: {
      "type": "Error",
      "message": "format string \"sOfwuYpF ⟡ CSV report with id \"L1466588990b1c86e6f\" failed with error: Http failure response for https://localhost:8080/service/bazoocaster/request/csv/download?zoneOffset=%2B00%3A00&id=20220605-0801-2800-0641-ffffff0026e8: 404 Result id 20220605-0801-2800-0641-ffffff0026e8 not found\": conversion specifier \"%3A\" at character 5 has no matching argument (too few arguments passed)",
      "stack": ...
}
```

The exception message contains a URL which contains the characters %3A. It seems pino thinks this is a placeholder and try to convert it and crash cause it doesn't find any interpolation value for it.

It don't understand why pino act like this. The exception should not be interpolated IMO. Even so, %3A is not a valid placeholder according to documentation. 

Seems like a bug. Is there a way to workaround this?

**Comment by mcollina** [comment]
Can you provide steps to reproduce? We often need a reproducible example, e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by jeandat** [comment]
Indeed, I can't reproduce it outside of my project. Works perfectly in a minimal project. I'm working with puppeteer and at some point JSON.parse is invoked. Probably related in some way. Will investigate further down the rabbit hole but can't assume anymore this is a pino bug. Sorry for the inconvenience. Closing for now. Will reopen if I find clear evidence and can propose a reproducible example.
