### ISSUE TITLE
Using async mode inside a worker thread

### ISSUE THREAD

**Issue by maxpain** [pinojs/pino#1457]
Hello. I use pino in async mode and  want to use [bree](https://github.com/breejs/bree), which runs cron jobs inside worker threads.

Main:
```javascript
import { Worker } from 'worker_threads'
const worker = new Worker('./worker.js')
```

Worker:
```javascript
import pino from 'pino'

const logger = pino(pino.destination({
    minLength: 4096,
    sync: false,
}))

logger.info('test')
```

And getting this error from the worker:
```
Error: SonicBoom supports only file descriptors and files
    at new SonicBoom (/Users/maxpain/dev/test_worker_threads/node_modules/sonic-boom/index.js:120:11)
    at buildSafeSonicBoom (/Users/maxpain/dev/test_worker_threads/node_modules/pino/lib/tools.js:214:18)
    at module.exports.destination (/Users/maxpain/dev/test_worker_threads/node_modules/pino/pino.js:191:12)
    at file:///Users/maxpain/dev/test_worker_threads/worker.js:3:26
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

It is because `process.stdout.fd` is actually `undefined` according to Node.js documentation:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/5875582/172714039-cfb68dde-5ee2-4fbd-9744-3de3ed4c3d23.png">

Are there some ways to achieve this approach?

**Comment by mcollina** [comment]
Here it is:

```js
import pino from 'pino'

const logger = pino(pino.destination({
    minLength: 4096,
    sync: false,
    fd: 1
}))

logger.info('test')
```

**Comment by maxpain** [comment]
@mcollina I tried it. Without an explicit `logger.flush()` call my worker is exiting without any logs. How to fix it?

**Comment by mcollina** [comment]
remove `minLength`

**Comment by maxpain** [comment]
@mcollina I use pino with async mode enabled and `minLength: 4096` on production. When my application exit all the logs in the buffer flushes to stdout. But not in worker. Is it possible to do "auto flush" but without explicit `.flush()` call?

**Comment by mcollina** [comment]
That's expected. I don't think the thread_workers emits any events we can hook into to flush.

**Comment by maxpain** [comment]
@mcollina What about ['exit' worker event](https://nodejs.org/api/worker_threads.html#event-exit)?

**Comment by climba03003** [comment]
I use `bree` in my project and it turns out having the logger instance in main-thread and pass the log inside the `worker` to `main` is better option.

```js
// worker-logger.js
const workerLogger = {
  postMessage (level, args): void {
    if (parentPort === null) return
    parentPort.postMessage({ type: 'message', level, args })
  },
  trace: function (...args) {
    this.postMessage('trace', args)
  },
  debug: function (...args) {
    this.postMessage('debug', args)
  },
  info: function (...args) {
    this.postMessage('info', args)
  },
  warn: function (...args) {
    this.postMessage('warn', args)
  },
  error: function (...args) {
    this.postMessage('error', args)
  }
}
module.exports = workerLogger

// jobs/job.js
const workerLogger = require('./workerLogger')

workerLogger.info('something')

// main.js
const pino = require('pino')
const Bree = require('bree')

const logger = pino(pino.destination({
    minLength: 4096,
    sync: false,
}))

function handleBreeMessage (name: string, message: string): void {
  if (message === 'done') logger.debug(`Worker for job "${name}" signaled completion`)
  if (message === 'cancelled') logger.debug(`Gracefully cancelled worker for job "${name}"`)
}

const bree = new Bree({
  workerMessageHandler (data: WorkerData) {
    if (typeof data.message === 'string') return handleBreeMessage(data.name, data.message)
    if (typeof data.message !== 'object') return
    if (data.message.type === 'message') {
      const { level, args } = data.message
      const l = logger.child({ name: data.name })
      l[level as LogLevel].apply(l, args as any)
    }
  }
})

**Comment by maxpain** [comment]
@climba03003 Looks not too convenient, especially in my case when the same code can produce logs in both scenarios: from the main thread and from workers.

**Comment by maxpain** [comment]
By the way. Worker threads could communicate with each other using `MessageChannel`. Why not use it in pino? In this case, we can send logs to one pino worker thread from any other thread (including main). At the moment if we send logs from 100 threads using pino we create 100 additional threads of pino, isn't it? correct me if I'm wrong

**Comment by mcollina** [comment]
> @mcollina What about ['exit' worker event](https://nodejs.org/api/worker_threads.html#event-exit)?

That event is emitted on the "parent" not within the worker thread.

**Comment by maxpain** [comment]
Could you please reopen this issue to discuss inter-thread communication using `MessageChannel` as I suggested before?

**Comment by maxpain** [comment]
@mcollina
