### ISSUE TITLE
An error with Errors?

### ISSUE THREAD

**Issue by glyphCezilleSantillan** [pinojs/pino#146]
Very minor issue I came across, but it suddenly crashes node when it happens.

When I failed to wrap my Error object (which may be null) in an object, pino threw this message:

Code:

    logger.info(err, 'End of playback');

Error:

    C:\Users\<me>\Projects\<projectname>\node_modules\pino\pino.js:378
        pos = s.indexOf(i, pos);
               ^

    TypeError: Cannot read property 'indexOf' of null
        at countInterp (C:\Users\<me>\Projects\<projectname>\node_modules\pino\pino.js:378:12)
 
I tried doing this in the indicated function:

    pos = s ? s.indexOf(i, pos) : -1

And it revealed that I did not enclose my `err` in an object.

    { ... "msg":"null \"End of playback\"" ... }

However, I usually choose not to wrap `err`, because it results in the following log:

    logger.error({ error: err }, err.message);

    [2016-12-12T09:13:37.051Z] ERROR(appname/### on computer): <The contents of err.message -- this string has content>
       error: {}

The error is rendered as empty, but it does in fact have an message. The only way to get the full stack trace is to use `logger.error(err)`. This scenario works well with Promises (where err is guaranteed in the catch block); in this instance, `err` was a parameter in a callback. Thus, the above.

To wrap up:

1. It boils down to Errors being a special case, for some reason, and it is rendered as an empty object -- is this a bug?

2. Could the if-else above (`pos = s ? s.indexOf(i, s) : -1`) be incorporated into the `countInterp` function? It would at least prevent unexpected crashing.

**Comment by davidmarkclements** [comment]
hey @glyphCezilleSantillan good catch - this is definitely a bug 

the code causing this is relatively new, and this is totally my fault :bowtie: 

I'll take a look into it asap

**Comment by davidmarkclements** [comment]
@glyphCezilleSantillan strange I can't reproduce the crashing 

here's a test I added to `test/basic.test.js`

```js
test('correctly handles null', function (t) {
  t.plan(1)

  var instance = pino(sink(function (obj, enc, cb) {
    t.is(obj.msg, 'null "test"')
    t.end()
    cb()
  }))

  instance.info(null, 'test')
})
```

see https://github.com/pinojs/pino/blob/null-fix/test/basic.test.js#L344-L354

it's passing

could you please alter the test to demonstrate your crashing case?

**Comment by glyphCezilleSantillan** [comment]
Ahh I see, the problem seems to be the same as #139. It's not just `Error`s or `null`. I had just been using an older version, v3.0.1. When I added your test, it failed with the same `Can't read property 'indexOf' of null`. But when I tried it with v3.0.3, the test succeeded.

The second half of my problem isn't too much of a bug anymore, more a side-effect of how I debug errors; I usually do something like:

    ...
    function (err) {
        if (err) {
            logger.error({ error: err, variableA: variableA, variableB: variableB, ... }, "<Desperately trying to figure out what's wrong>");
        }
    }

I see now that pino actually handles `logger.<level>(<error instance>)` nicely, but when the error is embedded in another object, it results in 

    { err: {}, variableA: { ... }, variableB: { ... } }

Here's a (mostly-copied) test that demonstrates it:

    test('passing object with nested Error', function (t) {
      t.plan(1)
      var err = new Error('myerror')
      var instance = pino(sink(function (chunk, enc, cb) {
        delete chunk.time
        t.deepEqual(chunk, {
          pid: pid,
          hostname: hostname,
          level: 30,
          msg: '?',
          error: {
            type: 'Error',
            msg: err.message,
            stack: err.stack,
          },
          v: 1
        })
        cb()
      }))

      instance.info({ error: err }, '?')
    })

But again, probably just my usage. As a workaround, I can use `err.message` when I want to debug multiple things.

**Comment by jsumners** [comment]
As a suggestion, I usually log in the following manner:

```js
if (err) {
  log.error('could not do the thing that was to be done: %s', err.message)
  log.debug(err.stack)
}
```

**Comment by davidmarkclements** [comment]
hooray ok let's close when #134 lands - thanks @glyphCezilleSantillan
