### ISSUE TITLE
Pino integration with nextjs

### ISSUE THREAD

**Issue by PedroJBrito** [pinojs/pino#1461]
Hi,

I'm trying to use pino along with nextjs and I'm facing some problems that I'd like to clarify. We want a different behavior when we're running the app in production or in development. For development we want to log server side logs (from getServerSideProps, not from /api) to a local file and the client side logs to console. However, in production mode we want to send logs to exceptionless (for those who don't know it's a kind of sentry).  Is there any way to achieve this?

**Comment by kibertoad** [comment]
@PedroJBrito Can't you conditionally use different pino transports in app setup?
