### ISSUE TITLE
Custom transport absolute path

### ISSUE THREAD

**Issue by PedroJBrito** [pinojs/pino#1462]
Hi,

I've created a custom transport to send logs to an external log platform, however it is required that the target path for this custom transport is absolute. The problem is, if I set an absolute path, this path will need to be updated everywhere, depending on the machine where the project is being runned for tests or deployed for production. Is any way to solve this problem? 

Thank you for your help.

**Comment by mcollina** [comment]
Could you make the destination configurable?

**Comment by PedroJBrito** [comment]
Hi @mcollina ,

Well, if no other solution is available yes, but if there's a workaround that prevents have to change this path it would be better. Do you have any other alternative?

**Comment by PedroJBrito** [comment]
Hi @jsumners,

I tried that but after build the solution the file that contains my custom transport is inside of a chunk and no longer has the same name, so I couldn't solve the problem with this solution. Can you help me to get over this problem?

**Comment by mcollina** [comment]
Take a look at https://getpino.io/#/docs/bundling

**Comment by VladimirMikulic** [comment]
It turns out relative path works just fine as well.

**Comment by jsumners** [comment]
I'm closing this as we don't seem to have anything to take action on.
