### ISSUE TITLE
how to keep the default stdout steam but also adding transport?

### ISSUE THREAD

**Issue by tomery-metisdata** [pinojs/pino#1463]
i am using v7.
i am using pino-http, when i am init pino without any transport, i see json in stdout.
but when i am adding transport i dont see the json in stdout, how i can preserve the logging to stdout but also using transport?
looking at the code i see that pino is initializing stdout stream only in there is not transport

lib/tools.js

`
    stream = stream || process.stdout
    if (stream === process.stdout && stream.fd >= 0 && !hasBeenTampered(stream)) {
      stream = buildSafeSonicBoom({ fd: stream.fd })
    }
`

**Comment by nenadfspartans** [comment]
Use `pino-file` without options or `pino-pretty` as target. https://github.com/pinojs/pino/blob/master/docs/transports.md#pinofile
