### ISSUE TITLE
Remove npx from test command

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#1466]
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2958/nodes=win-vs2019/testReport/junit/(root)/citgm/pino_v8_0_0/

We need it to be fixed to be tested in Node.js CITGM smoker.

**Comment by mcollina** [comment]
@ShogunPanda could you take a look?

**Comment by ShogunPanda** [comment]
Yup, on my way!
