### ISSUE TITLE
Logging pitfalls

### ISSUE THREAD

**Issue by bacloud22** [pinojs/pino#1476]
Hi, Thank you for making and maintaining Pino 🥇 .

There is one big problem with Logging in general, besides performance which is already dealt with here, But I would like to raise the other big problem. I understand if this is let to the user, but it might be an addition to Pino.

We log messages, warnings and errors, and in many cases errors are the Errors objects we raise or other dependencies Errors. So we don't have full control over errors. An error in general is a stack plus an error message; Both could be very long ! Even more, logging could get stuck in a loop or repetitive executions (web requests...).

I know Errors are to be dealt with quickly, and maybe in many scenarios, it is better to not catch errors and let the app break, because otherwise the app would be inconsistent. But still, in many real world cases (like websites, ..) we log them and fulfil the requests.

It would be nice to have a support of logging JavaScript Error objects (all). Setting a limit of `err.message` and the depth of the stack of the error.
Second option is to have a timer and a counter, the exact same error thrown in the same time window would be substituted by a custom short user message.

Please let me know what do you think 👍🏻

**Comment by bacloud22** [comment]
I made a [generic solution](https://gist.github.com/bacloud22/0a2083f30d1ac80e998a0af8c990c1e4)

**Comment by mcollina** [comment]
I would prefer not to ship those opinionated behavior as defaults in pino, however you could implement your own [error serializer](https://getpino.io/#/docs/api?id=serializers-object) that does the same thing of your custom logic.

Thanks for discussion!
