### ISSUE TITLE
Help understanding the benchmarks doc

### ISSUE THREAD

**Issue by rluvaton** [pinojs/pino#1477]
Maybe it's just me but I really don't understand how logging a string takes more than 30x longer than a deep object, is this an error or am I missing something?

https://github.com/pinojs/pino/blob/456ada5f8486bab0bea0b99f37d01dbd2e22bcee/docs/benchmarks.md?plain=1#L4-L16

https://github.com/pinojs/pino/blob/456ada5f8486bab0bea0b99f37d01dbd2e22bcee/docs/benchmarks.md?plain=1#L35-L46

**Comment by mcollina** [comment]
The data between different are not supposed to be compared directly. In fact, the benchmarks for strings logs significantly more data.
