### ISSUE TITLE
Possible to Pretty Print on the Browser?

### ISSUE THREAD

**Issue by DoisKoh** [pinojs/pino#1479]
Is there a good way to pretty print Pino logs on the browser right now? I'm using Pino with Svelte and it requires the code to be isomorphic.

In nodejs, I just use pino-pretty, but it doesn't work in the browser, and now that the prettyPrint option has been deprecated, what's a good/best solution for printing on the browser console? (Just for development, in production it's turned off of course).

**Comment by mcollina** [comment]
Unfortunately, is no support for pretty logs in the browser. I'm not even sure how those could be implemented easily.
