### ISSUE TITLE
Add more information about the limitation of redaction

### ISSUE THREAD

**Issue by iamNoah1** [pinojs/pino#1509]
I stumbled across a limitation of the redaction feature, which took me a little bit to get behind. I am using pino in a Nest.js (Node+Typescrypt basically) application. 

I had the following logging command which should redact a key in its data: 

```
logger.debug(`connectionConfig: ${JSON.stringify(connectionConfig)}`);
```
While the _connectionConfig_ object contains a _passwd_ key and the pino config looked like this:

```
export const logger = pino({
  level: 'debug',
  redact: ['*.passwd'], // I also tried redact: ['passwd']
});
```

What happened was, that the _passwd_ was not redacted. I cannot exactly say why, but I guess I am not the only one that uses this kind of scenario (String plus Object). Anyways, I had to split my log commands: 

```
logger.debug(`connectionConfig: `);
logger.debug(JSON.stringify(connectionConfig));
```

I am not a Node and Typescript pro gamer, so maybe I was just too dumb to use it correctly :) If so, please tell me how to do it in the future. If not, I guess it would be nice to mention this "limitation" in the docs.

**Comment by mcollina** [comment]
Note that it's likely it won't be redacted anyway. Instead of including the object inside the message, you include it directly as JSON in the log line, like this:

```js
logger.debug({ connectionConfig }, 'connecting..');
```

As for docs, PRs are welcomed!

**Comment by iamNoah1** [comment]
Thanks, @mcollina. This worked for me: `logger.debug(redacted, 'connection');` While redacted is the following: 
```
  const redacted = {
    password: "blbablabla"
  }
```

I will see if I find the time to improve docs.
