### ISSUE TITLE
Getting `Error: Cannot find module './indexes'` when trying to run ncc bundle

### ISSUE THREAD

**Issue by boristian** [pinojs/pino#1510]
Hi, first of all, thanks for this great Module!

When i bundle an app using pino with [@vercel/ncc](https://github.com/vercel/ncc) and try to start the bundle i am always getting this error:

```sh
Error: Cannot find module './indexes'
Require stack:
- /<PROJECT_PATH>/dist/worker1.js
```
Start of `worker1.js`:

```js
'use strict'

const { realImport, realRequire } = require('real-require')
const { workerData, parentPort } = require('worker_threads')
const { WRITE_INDEX, READ_INDEX } = require('./indexes')
const { waitDiff } = require('./wait')
...
```

But there is no file `indexes` created in `dist`. Am i doing something wrong?

My code for creating the logger is:

```js
export const log = pino({
  level,
  name: 'MY_PINO_LOGGER',
  transport: {
    target: 'pino-pretty',
    options: {
      colorize: true,
      hideObject: !IS_DEV && process.env.DEBUG !== '1',
      translateTime: true
    }
  }
})
``` 

I don't know if this is the right place for the issue, but maybe somebody has an idea.

Thanks in advance!

**Comment by mcollina** [comment]
I have no clue on how to bundle this with ncc.
I don't think this is the right place either for asking :(.

**Comment by mcollina** [comment]
I'm sorry we couldn't be of help

**Comment by boristian** [comment]
Just for reference, this fixed it for me:

https://github.com/vercel/ncc/issues/794#issuecomment-1184908278
