### ISSUE TITLE
Log to terminal & write to the file

### ISSUE THREAD

**Issue by jan53n** [pinojs/pino#1523]
Hi, i want to re-configure pino in way that i can write the logs to a log file and also to the terminal

this is my conf:

```javascript
const pino = require('pino');

const transport = pino.transport({
    target: 'pino/file',
    options: { destination: './app.log' }
});

const logger = pino(transport);

function l(type, payload) {
    const t = logger.child({ type });
    t.info(payload);
}
```

**Comment by mcollina** [comment]
This example should get you what you want: https://github.com/pinojs/pino/blob/master/examples/transport.js.
