### ISSUE TITLE
logging request / response headers from fetch

### ISSUE THREAD

**Issue by RichardWright** [pinojs/pino#1524]
Hi!

When logging http request / responses, these are just empty objects. Am I missing something with pino on how to use the iteraties on this?

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.
