### ISSUE TITLE
is it possible to change log level according to the message ?

### ISSUE THREAD

**Issue by doricohen4** [pinojs/pino#1525]
im struggling to change the level according to the log message i would like. to change error level to warn level depend on the message , is it possible and how ?

tnx

**Comment by jsumners** [comment]
If the situation calls for a warning level message, issue `log.warn("a message")`.

**Comment by deanhaleem** [comment]
I think it makes sense for your code to be responsible for determining the log level based on the message. Then use the pino log function that fits your level (`warn`, `error`, etc).
