### ISSUE TITLE
Duplicate key issue in GCP Logging

### ISSUE THREAD

**Issue by KidkArolis** [pinojs/pino#1526]
We're using child loggers in our app to distinguish logs in various parts of the application. The top level logger has module: "app" and nested loggers override that, e.g. "webhook". From what I can tell, in GCP when it's parsing { module: "app", module: "webhook" } the module gets truncated to "web" - presumably because it saw "app" first which was 3 characters long and then saw the other value, but only took the 3 chars. This is a bit of a wild theory, but the only explanation I could come up with for why all module names in GCP logging appear truncated to 3 characters when our top level logger is "app".

Any suggestions of how to solve this issue and correctly override the module in each nested logger?

**Comment by KidkArolis** [comment]
I suppose the two options are:

1. Setup a transport and transform the values being logged somehow (an example would be great..), but at a cost of performance.
2. Modify the application to not need nested module naming. I.e. every logger with module key should be spawned from the root logger with no module key, and any further nested loggers should not override the module. No good way to enforce this though - and so this could always be an easily made mistake when introducing new loggers?

**Comment by KidkArolis** [comment]
But that will do!

**Comment by jsumners** [comment]
That was a bit of a rollercoaster. See https://getpino.io/#/docs/child-loggers?id=duplicate-keys-caveat
