### ISSUE TITLE
Logging to a JSON array and parsing it with pino-pretty, is this the correct approach?

### ISSUE THREAD

**Issue by maikeriva** [pinojs/pino#1528]
Hello!
I am using pino for the first time and despite spending quite some time studying the documentation, I am struggling to understand how to accomplish the following.

I have a serverless function which executes a long script whose internals are logged with pino. I want the resulting logs to be sent in the function's JSON response.

After reading the documentation, I wrote a basic Writable stream with which I could group all log entries into an array (I am not sure this is the correct approach, suggestions welcome):
```
  const logs = []
  const myTransportStream = new Writable({
    write: (chunk, enc, cb) => {
      logs.push(JSON.parse(chunk))
      cb()
    }
  })
  const logger = pino(myTransportStream)
  // Do stuff...
  return logs
```

Parsing the returned logs in a bash terminal with `cat ./serverlessFunctionOutput | pino-pretty` however doesn't seem to work. I guess that's probably because pino-pretty doesn't expect an array but rather a list of JSON objects separated by newlines?

My questions are:
- Is my approach for returning logs as a JSON array correct?
- How to parse that JSON array for easier visual debugging with pino-pretty?

Thanks for your help!

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.
