### ISSUE TITLE
Logging inside a transport

### ISSUE THREAD

**Issue by AceFire6** [pinojs/pino#1531]
We are currently testing pino as an alternative to a different logging library we are already using in production. Everything has gone smoothly so far.

However, we have strict redaction requirements on our logs. With the previous library we had a hook that ran the redaction over the log object before it reached any other transformation or transport code to Datadog for example.

In that code we passed the logger into the redaction formatter so we could log any warnings/issues we encountered during the redaction process.

This is the current setup we have with pino:
<details>
<summary>logger.ts</summary>

```ts
// logger.ts
const pinoLogger = pino({
        timestamp: stdTimeFunctions.isoTime,
        level,
        messageKey,
        errorKey: 'exception',
        transport: {
            pipeline: [
                {
                    target: './transports/redaction-transport',
                    options: {
                        enableRedaction: !isDevelopment || enableRedaction,
                        preventLoggerMessageRedaction,
                        shouldSaveRedactionSamples,
                        preventKeysRedaction
                    }
                },
                {
                    target: './transports/pretty-log-transport',
                    options: {
                        levelLabel,
                        messageKey
                    }
                }
            ]
        },
        formatters: {
            level: (label: string) => {
                return { [levelLabel]: label };
            }
        },
    });
```
</details>

<details>
<summary>./transports/redaction-transport.ts</summary>

```ts
// ./transports/redaction-transport.ts
export default async function (_options: RedactionOptions) {
    const redactionFormatter = createRedactionFormatter();

    return build(
        function (source) {
            const redactionStream = new Transform({
                autoDestroy: true,
                objectMode: true,
                transform(chunk, enc, cb) {
                    // modifies the payload somehow
                    const redactedChunk = redactionFormatter(chunk);

                    this.push(`${JSON.stringify(redactedChunk)}\n`);
                    cb();
                },
            });
            pipeline(source, redactionStream, () => {});
            return redactionStream;
        },
        {
            // This is needed to be able to pipeline transports.
            enablePipelining: true,
        }
    );
}
```

</details>

1. Is there some mechanism we could use to log out warnings/errors from inside a transport?
2. Does this use case suit transports? Or is there some better way to approach this problem?

Any assistance would be very much appreciated 😄

**Comment by mcollina** [comment]
What's the destination for those redaction logs?

You could:

1. run a pino instance within the transport, logging to stdout the redaction errors
2. include those logs as part of the stream
3. run a pino instance within the transport and feed those logs into the redactionStream itself.

I don't have any code around for implementing this.

you could also use postmessages to get those info back to the main process and then process them there: https://github.com/pinojs/thread-stream#emit-events.

**Comment by AceFire6** [comment]
@mcollina thanks for the quick response!

The logs all end up in the same place - stdout in kubernetes. We use the datadog agent to scrape the container logs and then those are shipped to Datadog.

I'd like to keep using the same pino instance/child logger that initiated the log to make sure we have consistent tagging across all of them.

I'll take a look at all of these suggestions and see which works best for us. Thanks 😄
