### ISSUE TITLE
Get access to children instances from parent

### ISSUE THREAD

**Issue by Diabl0269** [pinojs/pino#1534]
Hey,
I am using `pino` in a big project containing multiple children. I want to be able to change the log level on all loggers at once.
I saw there is another issue (https://github.com/pinojs/pino/issues/1330) about a similar scenario in which the answer was to create an array of loggers.
I would like to suggest to implement an array of children on a parent myself if you'd accept a PR regarding the subject.
The PR will:
1. Add `children` array to the `prototype` object [here](https://github.com/pinojs/pino/blob/master/lib/proto.js#L53).
2. Push the newly created child at the end of its creation function [here](https://github.com/pinojs/pino/blob/master/lib/proto.js#L144).

Please let me know your thoughts and in hope you agree I will create a PR :)

**Comment by mcollina** [comment]
We want the children to be lightweight and be able to create a new logger for each incoming and http request. Therefore tracking each children from the parent will be a memory leak.

What you'd like to achieve could be done in an external module. I _think_ https://github.com/pinojs/pino-arborsculpture does what you need.

**Comment by Diabl0269** [comment]
@mcollina Firstly, thanks for the quick response.
Secondly, what do you think about allowing a to pass a callback function on creation of an instance (which will be also passed to the children, same as the other properties).
Then the users of `pino` (e.g me), could pass such a callback in a single place to do a certain operation on the newly created instance.

About your point regarding memory leak, I understand the issue in implementing the original request as for some use cases it could actually be dangerous, but for my use case there is no risk of this. (All loggers are born and die on the service startup and shutdown).

**Comment by Diabl0269** [comment]
Issue accidentally closed. Please let me know what do you think of my last comment.

**Comment by mcollina** [comment]
yeah, I'll be ok with an `onChild` callback

**Comment by jonathansamines** [comment]
@mcollina Would it be feasible for pino to track all child instances internally using an iterable weakset implementation and transparently change the log level when the parent level is updated?

**Comment by mcollina** [comment]
That technique you are mentioning adds quite a bit of overhead in a hot path.

**Comment by Diabl0269** [comment]
@mcollina I have a PR I'm ready to push but missing access rights to push my branch, could you grant the needed permission?

**Comment by mcollina** [comment]
You should fork the repository (https://www.freecodecamp.org/news/how-to-fork-a-github-repository/)

**Comment by Diabl0269** [comment]
I am new to contributing to open source projects, so thank you for the explanation!
I am closing this issue in favor of the PR I opened. https://github.com/pinojs/pino/pull/1541
