### ISSUE TITLE
Support customising levels for multiple transports

### ISSUE THREAD

**Issue by fenos** [pinojs/pino#1538]
Hello, we all love pino!

However, i do not understand why i cannot have the `level` in my logs as a `label` when using multiple transports.
It seems a weird limitation

#ref https://github.com/pinojs/pino/blob/master/lib/tools.js#L284

Is there any workaround for now?

**Comment by jsumners** [comment]
Have you reviewed the issue that resulted in that code? https://github.com/pinojs/pino/issues/1353

**Comment by fenos** [comment]
Hello @jsumners 

Yes, i've had a look at the issue you linked, however even by using the `mixin` function i'm still unable to customise the `level` property.

I can only add an alternative key ex: `level-label`

My main problem is that i started using pino with a single transport then added a second one later on, since i'd like to keep my schema consistent and still retain the `level` key to be a string is there a way to achieve this?

**Comment by mcollina** [comment]
Not at this time, I think it's possible to drop the limitation but it requires some work on pink.  Would you like to send a PR?

**Comment by VladimirMikulic** [comment]
Hi @fenos - did you find some workaround?
