### ISSUE TITLE
Pino dynamic destination for transport

### ISSUE THREAD

**Issue by shawel** [pinojs/pino#1539]
Is there a possibility to update destinations dynamically... What i wanted is to change the file name with suffix dates so different files could be created daily.  Does this option exists ?

something like (pehraps by changing destination to a function?? or other similar method)
```
targets: [
      {
        target: 'pino/file',
        options: {
          destination: () =>  path.join(_path || LOG_PATH, `${namespace}.${ new Date().toISOString().split('T')[0]}.log`),
          sync: true,
          mkdir: true,
        },
      },
    ]
```

**Comment by mcollina** [comment]
It dones't, check out https://github.com/feugy/pino-roll
