### ISSUE TITLE
pino-pretty crashes

### ISSUE THREAD

**Issue by mzehrer** [pinojs/pino#154]
This happens while logging some random output from a shell command:

/usr/lib/node_modules/pino/pretty.js:50
  return line.hasOwnProperty('hostname') && line.hasOwnProperty('pid') && (line.hasOwnProperty('v') && line.v === 1)
             ^

TypeError: Cannot read property 'hasOwnProperty' of null
    at isPinoLine (/usr/lib/node_modules/pino/pretty.js:50:14)
    at DestroyableTransform.mapLine [as mapper] (/usr/lib/node_modules/pino/pretty.js:87:24)
    at DestroyableTransform.transform [as _transform] (/usr/lib/node_modules/pino/node_modules/split2/index.js:33:21)
    at DestroyableTransform.Transform._read (/usr/lib/node_modules/pino/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/usr/lib/node_modules/pino/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/lib/node_modules/pino/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/usr/lib/node_modules/pino/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/usr/lib/node_modules/pino/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)

**Comment by davidmarkclements** [comment]
hey @mzehrer can you add the output being logged?

**Comment by mzehrer** [comment]
Sorry, my fault, there was some direct console.log to stdout in one module. This is maybe the downside of the external transport idea?

**Comment by davidmarkclements** [comment]
Good time as any to discuss this

I would say, that if you're using a logger to stdout then a console.log would be stray,
so you that transport (or prettifier) to crash

Maybe a more helpful message in the prettifier? 

Maybe a recommendation in docs to noop console.log etc in production? 

```js
if (process.NODE_ENV === 'production') {
  console.log = console.error = console.warn = console.info = console.warn = console.trace = () => {}
}
```

@mcollina  @jsumners  thoughts?

**Comment by mzehrer** [comment]
If the pino prettifier crashes in dev environments I see no problem. But for production transports like pino-socket this would be horrible and in a large team there is no guarantee that no one uses console.log

**Comment by jsumners** [comment]
The point of https://github.com/pinojs/pino/blob/23e331cac8fe262fe044eee2cb2c4301dcab43a2/pretty.js#L87 is to catch exactly this scenario and silently ignore it; your downstream processor has to deal with it in its own way.

So what I'm wondering is how https://github.com/pinojs/pino/blob/23e331cac8fe262fe044eee2cb2c4301dcab43a2/pretty.js#L84 even succeeded in parsing the line (i.e. didn't generate a `parsed.err`). What is the input that caused the line to parse as JSON but not be an object that would have the `hasOwnProperty` method? Was it a serialization of an array?

**Comment by jsumners** [comment]
@mzehrer re: `pino-socket`, you're right, I need to update it to validate the input is parseable JSON.

**Comment by mzehrer** [comment]
Here is the stdout: https://gist.github.com/mzehrer/a8bc5c3386e9b305577625d546d72672

**Comment by davidmarkclements** [comment]
A crazy solution would be add an option that caches the write function of the stream passed to pino, and overwrite the original write function with a noop func. That way any writes to stdout will be discarded, other then what's logged via pino

Could call the option "lockdown" or something

**Comment by jsumners** [comment]
It's that first line: `null`.

**Comment by davidmarkclements** [comment]
ahahahaha

**Comment by davidmarkclements** [comment]
Still I think a "lockdown" option might be a good idea for production, 
since we're essentially "taking over" the STDOUT stream 

@mcollina what do you think

**Comment by mcollina** [comment]
@davidmarkclements I'm really against any lockdown. If we want lockdown, it's another module with global scope. There is already too much global stuff happening for extreme mode.

**Comment by davidmarkclements** [comment]
yep fair enough - in that case catering to stray `console.log` (or any other stdout writes) 
is out of our scope
