### ISSUE TITLE
Pino made tests with jest fail

### ISSUE THREAD

**Issue by ktfth** [pinojs/pino#1540]
Without made any change on a project who I'm working, pino pop up with a Reference error on FinalizationRegistry and this made me confused, someone know why this happen? I can come with more information soon.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by ktfth** [comment]
Sorry, I have changed the version of my node and all worked fine. Previously used 14.0.0 because some internal motives on the company. But now running everything well with 16.17.0
