### ISSUE TITLE
mismatch between shasum used at publish time and GitHub tag for 8.6.0 (breaking CITGM)

### ISSUE THREAD

**Issue by MylesBorins** [pinojs/pino#1567]
The head of the repo when the package was publish was f1aa631cc68fe20b7570360da9490da171913c34, which doesn't match the ref of the tag which is https://github.com/pinojs/pino/commit/2858099139be54428b7167db25b87790b55453c4

This seems to have been the case for both 8.6.0, 8.5.0, 8.3.1, and potentially more releases.

**Comment by MylesBorins** [comment]
skipped in CITGM in this PR https://github.com/nodejs/citgm/pull/929

**Comment by targos** [comment]
@mcollina

**Comment by mcollina** [comment]
Released v8.6.1 with matching everything.

(I'd love to have a better flow for 2FA and automated publishes, as the currently manual approach can fail sometimes).
