### ISSUE TITLE
multiple pino instances in same nodejs process... supported?

### ISSUE THREAD

**Issue by pcafstockf** [pinojs/pino#1571]
A quick scan for `global` and `globalThis` as well as the `pino` constructor would indicate that we can have multiple instances of pino (with very different configurations and transports) within the same nodejs process.

This would seem to be an unusual use case, so I wanted to ask if this is a **supported** scenario, or just the current state of the project?
I do understand that some transport implementations could have their own global limitations.  My question is just regarding pino and its dependencies.

**Comment by mcollina** [comment]
There is no problem with having mulitple pino instances within a process. You might incur some race condition issues if they try to write to the same file: if you want to do that, you might consider having a single `pino.destination()` for all the instances writing to the same file.
