### ISSUE TITLE
Redact mutates the original object

### ISSUE THREAD

**Issue by AlexRex** [pinojs/pino#1575]
We noticed that redact is mutating the original object, and not bringing back its properties.

Snippet to reproduce:

```ts
import pino from 'pino'

const config: pino.LoggerOptions = {
  level: 'debug',
  redact: [ // Eliminate these fields from the logs!
    'context.password',
    'password',
    'context.*.password',
    'context[*].password'
  ]
}

const logger = pino(config)

const test = {
  whatever: { password: '1234' }
}

logger.info({ context: test }, 'info')

console.log(test) //  { whatever: { password: '[Redacted]' } }

```

Versions used:
```json
"pino": "7.11.0",
"pino-pretty": "7.6.1"
```

**Comment by mcollina** [comment]
This is due to the fact that you have multiple patterns covering the same object. There is likely one more bug. Would you like to send a PR?

**Comment by stefanwaldhauser** [comment]
Just encountered this bug in a project. Seems to still exist in the newest version

**Comment by matthiasg** [comment]
Just fell into that. Our forwarded requests internally lost authentication cookies.

**Comment by srzainab** [comment]
Just ran into this as well on our production servers. Causing all sorts of issues. Any ideas on a fix?

**Comment by emmyakin** [comment]
FWIW, I tested this in the latest version `v9.1.0`, and can no longer reproduce
