### ISSUE TITLE
Request: removeLevel function

### ISSUE THREAD

**Issue by simone-sanfratello** [pinojs/pino#158]
Hi,
first of all: thank you for this great module!

I would like to ask for the function .removeLevel; I had write by myself in fork but I'm not sure I miss some details about stream flow.

Thank you

**Comment by davidmarkclements** [comment]
hi @simone-sanfratello - can you elaborate a little? 

Is there an equivalent `removeLevel` function on another logger? 

There always has to be a level.. perhaps your idea for `removeLevel` is for child loggers, to reset them to the level of the parent? If so, what's the use case for doing that? 

Or indeed, what's the use case in general?

**Comment by simone-sanfratello** [comment]
Hi @davidmarkclements 

I'll explain better: I'd like to have a function to remove a previously added level. It should work either con parent and children logger

Example

````js
var pino = require('pino')
var log = pino()
log.addLevel('myLevel', 35)
// ...
log.removeLevel('myLevel')
````

I suppose can be complicated remove a "core" level (trace, info, error etc)

My case is: I'd like to add a level, collect something, then remove it when I don't need anymore, keeping the currente ````levelVal````

**Comment by mcollina** [comment]
This will be hard to do, because the parent-child relationship is not maintained at runtime. The child gets the data from the parent, but we do not maintain a link between the two.
The correct way to do this is to create a child logger, add your level, log stuff, and the dispose the logger. Creating child logger is really fast.

**Comment by simone-sanfratello** [comment]
@mcollina thanks for support, I'll do in that way

Thanks!

**Comment by davidmarkclements** [comment]
ok cool - closing :bowtie:
