### ISSUE TITLE
Browser side usage: "browserify" and/or browser.js ?

### ISSUE THREAD

**Issue by jpduvet** [pinojs/pino#1585]
For browser side usage, the doc advises to use browserify. There is also a browser.js file aside the pino.js file.
Which file should we import?

**Comment by jsumners** [comment]
I don't know anything about bundlers, but this supposedly does something:

https://github.com/pinojs/pino/blob/121c71dfea6fa1cb545e3409c3d96f7f11d7d938/package.json#L8

**Comment by mcollina** [comment]
cc @ShogunPanda

**Comment by ShogunPanda** [comment]
My advice would be to import `browser.js` and see if it works.
