### ISSUE TITLE
How to make a custom handler for uncaughtException?

### ISSUE THREAD

**Issue by dnl4** [pinojs/pino#1589]
I'm using a package that uses Pino in its core, and due this I can't make custom handler for uncaughtException.

This doesn't works:
```
process.on("uncaughtException", e => {
    console.error(e);
});
```

How can I make this work while using Pino?

**Comment by mcollina** [comment]
Thanks for reporting!

Why it doesn’t work? Pino does not tinker with `uncaughtException`.


Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by dnl4** [comment]
When creating a reproducible example, I could see that the problem is created by pm2, not by "pino". Thanks for your help.

test.js
`
process.on("uncaughtException", e => {
    console.log("============================ CUSTOM HANDLER EXECUTED ============================");
});

(async () => {
    throw new Error("Test Error");
})();`

This command works as expected (the custom handler is executed).
`node test.js`

This doesn't:
`pm2 start test.js --attach`

**Comment by jsumners** [comment]
We recommend using a native process manager and avoiding pm2. PM2, as you have discovered, modifies Node's core internal objects.
