### ISSUE TITLE
Facing Issue with maxAge option

### ISSUE THREAD

**Issue by Harsh246** [pinojs/pino#1594]
Hi,
I am using rotate-logs transport but not able to figure how to set the maxAge of the gunzip log files? How to configure .rotate.js to remove all compressed logs older than one month?
Here is my .rotate.js file:
`module.exports = {
  filter(data) {
    return !!data.req
  },
  output: {
    path: 'combined.log', // name of file
    options: {
      path: './src/logs/', // path to write files to
      size: '1M', // max file size
      interval: '1d', // rotate daily
      compress: 'gzip' // compress rotated files
    }
  }
}
`

Can you please provide some inputs or help me with it.

Thanks in advance.

**Comment by mcollina** [comment]
Thanks for reporting! As you can see, the rotate-logs transport is not part or this organization. Please open your issue on that repository instead.
