### ISSUE TITLE
Can't use custom levels in multistream with TypeScript

### ISSUE THREAD

**Issue by frzsombor** [pinojs/pino#1595]
The following code worked totally fine in JS, but I'm currently in the process of converting my NodeJS app to typescript.
I would like to use custom levels in multistream with TypeScript, but the definitions are not allowing me to do so.
I have this file, where I prepare and configure pino to use it in different parts of my application:

```ts
import * as fs from 'fs';
import pino, { StreamEntry } from 'pino';
import pretty from 'pino-pretty';

const customLevels = {
    debug   : 1,
    info    : 2,
    network : 3, // <- my custom level
    error   : 4,
};

const pinoOpts = {
    //...
    useOnlyCustomLevels: true,
    customLevels: customLevels,
    //...
};

const multistreamOpts = {
    dedupe: true, //send logs only to the stream with the higher level
    levels: customLevels,
};

const streams: StreamEntry[] = [
    { level : 'debug',   stream : fs.createWriteStream(`./log/log-debug.log`,   { flags: 'a' }) },
    { level : 'info',    stream : pretty() },
    { level : 'info',    stream : fs.createWriteStream(`./log/log-info.log`,    { flags: 'a' }) },
    { level : 'network', stream : fs.createWriteStream(`./log/log-network.log`, { flags: 'a' }) },
/*             ^^^^^^^
                  └ - ❗ TypeScript error ❗
*/
    { level : 'error',   stream : pretty() },
    { level : 'error',   stream : fs.createWriteStream(`./log/log-error.log`,   { flags: 'a' }) },
];

export default pino(pinoOpts, pino.multistream(streams, multistreamOpts));
```

However, I get the following error where I define `streams`:
`Type '"network"' is not assignable to type 'Level | undefined'.ts(2322)`

The reason is that in pino.d.ts, [Level is explicitly defined](https://github.com/pinojs/pino/blob/v8.7.0/pino.d.ts#L220) to be `"fatal" | "error" | "warn" | "info" | "debug" | "trace"` and no matter how many times and different approaches I tried to override/extend the definition, none of my attempts worked.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by frzsombor** [comment]
@mcollina I'm quite new to TS, and not sure what would be the best practice, to fix this issue.
However if you, or someone could help me with an idea, I can try to implement it in a PR.

**Comment by aalzubidy** [comment]
I'm having the same problem even with the default log levels.

`const streams: StreamEntry[] = [
  { stream: process.stdout, level: logConsoleLevel },
  { stream: fs.createWriteStream(logFilePath, { flags: 'a' }), level: logFileLevel, streamOpt: { sync: false } },
];`

Error:
Type 'string' is not assignable to type 'Level | undefined'.ts(2322)
pino.d.ts(289, 9): The expected type comes from property 'level' which is declared here on type 'StreamEntry'

**Comment by aalzubidy** [comment]
I can submit a PR, is it removing the type checking for that one so users can add custom levels or map the custom levels values to the type?

**Comment by frzsombor** [comment]
@mcollina I think this issue still exists, I can still only get around this problem by using `@ts-ignore` on the line above the custom level.

**Comment by ramiel** [comment]
I see the very same error

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
cc @kibertoad

**Comment by simoneb** [comment]
This was actually closed by https://github.com/pinojs/pino/pull/1778. @mcollina can you close this issue?

**Comment by mcollina** [comment]
thx @simoneb
