### ISSUE TITLE
Maintaining an up to date 2.x branch with Node.js 0.10 support

### ISSUE THREAD

**Issue by watson** [pinojs/pino#160]
I've been experimenting with what it would take to get the 2.x branch up to date with `master` and still retain Node.js v0.10 support (see reason below).

It's mainly `Object.assign` and a single use of template strings that is the issue.

I've forked this repo and made a `2.x` branch on my own repo with a few commits to make this happen here:
https://github.com/watson/pino/commits/2.x

There's currently a single test still failing that I'm having some issues with. So I was hoping that (if this was in the interest of the pino community) someone could help me figure out how to fix that test.

Also I've never maintained an old branch like this, so I don't know what the optimal approach is to keeping it in sync with `master`. If someone have experience, I'd like to chat.

## Reason for keeping Node.js v0.10 support

Though Node.js v0.10 and v0.12 is no longer maintained and everyone is encouraged to move to version 4 or newer, my company still have a lot of customers running old projects on Node.js v0.10. And there's no indication that this is going away any time soon.

If you look at the world-wide usage stats, Node.js v0.10 is still responsible for over 10% of installations out there as far as I remember (sorry, can't find the source right now).

**Comment by watson** [comment]
Also, I'd like some pointer as to which things in 3.x are considered breaking and hence shouldn't be back-ported :)

**Comment by mcollina** [comment]
We've removed support for 0.10 and 0.12 to simplify maintenance. I would be very happy if you want to maintain the v2.x.x line and backport what is backportable. We'll need to adjust our release process, and figure it out.

I've created https://github.com/pinojs/pino/tree/v2.x.x for that purpose.

What is the test that is failing?

As for landing commits, I think you can either use cherry-pick, or the same process of node:

```js
curl -L https://github.com/nodejs/node/pull/xxx.patch | git am --whitespace=fix
```

**Comment by watson** [comment]
@mcollina I started out trying to cherry-pick but had issues cherry-picking PR merge commits. But maybe the command you listed here will help me do that 😃

**Comment by watson** [comment]
@mcollina I've been trying to figure out which [commits in the v3.0.0 release](https://github.com/pinojs/pino/compare/v2.15.0...v3.0.0) that was considered breaking and that I therefore shouldn't cherry-pick to the `v2.x.x` branch.

So far I've found the following two commits. Please let me know if you think there's more of if I'm wrong:

- [Replace non-native Object.assign with native](https://github.com/pinojs/pino/commit/038e2ca339efc09ff38913379432bf1ba3da7b7e)
- [Move addLevel to an instance method](https://github.com/pinojs/pino/commit/50adaf59d73cfc5b2d5c66ddbf04e8721f487289)

**Comment by mcollina** [comment]
I think that's all.

**Comment by jsumners** [comment]
I think this issue is resolved, yes?

**Comment by davidmarkclements** [comment]
I think it's save to close
