### ISSUE TITLE
Documentation: Help > Exit logging dead link

### ISSUE THREAD

**Issue by francarranza** [pinojs/pino#1600]
There is a dead link to "Exit Logging" that shouldn't be there. It doesn't take you anywhere.

How to reproduce it:

1. Go to Help docs page: https://getpino.io/#/docs/help
2. Click on Exit Logging sub menu option
3. Nothings happens, even it's not in the main `Help` index page

<img width="266" alt="Screenshot 2022-12-07 at 16 20 37" src="https://user-images.githubusercontent.com/8448996/206218614-a3085e33-a81c-4227-a1e9-80515b8f83ee.png">

<img width="716" alt="Screenshot 2022-12-07 at 16 21 12" src="https://user-images.githubusercontent.com/8448996/206218774-05274a37-3ffc-4efc-bc9c-a9322139bb75.png">

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? We removed that section, there is nothing specific to be done anymore.

**Comment by francarranza** [comment]
@mcollina Will do! Assign this ticket to me
