### ISSUE TITLE
What is the recommended way for library authors to use pino?

### ISSUE THREAD

**Issue by aishwar** [pinojs/pino#1603]
For an application I am working on, we use pino as the logger for the application. We have some code broken into libraries. Today, this code just initializes a new instance of pino. This seems to work for us because we use the default setting for the pino logger. What is the recommended way for library authors to get access to the same logger instance as the main application?

For e.g. Log4j provides 2 packages - one with the implementation, one with just the interface. Library authors can just take a dependency on the interface package and all the logging calls from the library can be directed to the application's logger instance.

How do we achieve the same effect with pino?

**Comment by jsumners** [comment]
Utilize https://www.npmjs.com/package/abstract-logging which is meant for this exact purpose.

**Comment by aishwar** [comment]
Thank you @jsumners. With Log4j, I believe the interface package scans the environment for a configuration to figure out what implementation to use. However, with `abstract-logging` it looks like you need to pass in the logger implementation to the library and `abstract-logging` just provides the interface. Is this correct?

Or is there some kind of auto-discovery mechanism that'll avoid having to manually pass in loggers wherever I need to use it.

**Comment by jsumners** [comment]
> Is there some kind of auto-discovery mechanism that'll avoid having to manually pass in loggers wherever I need to use it.

No. JavaBeans is not a thing in Node.js development. You are responsible for your own dependency injection.
