### ISSUE TITLE
Sonic boom not ready

### ISSUE THREAD

**Issue by abacaj** [pinojs/pino#1605]
Getting error:
```Error: sonic boom is not ready yet```

Not sure why, this is happening locally.
Pino version: **8.7.0**

![image](https://user-images.githubusercontent.com/7272343/207702028-65cc1f32-d089-4b72-907d-5884f3c5dfd4.png)

**Comment by jsumners** [comment]
Please provide a minimal reproduction.

**Comment by abacaj** [comment]
Ok I see the issue, not sure why I got this error instead seems like a false positive - I had a compile error in my typescript file.
Fixing the compile error, removes the sonic boom error 🤷
