### ISSUE TITLE
Strings with % in them don't work right with interpolation

### ISSUE THREAD

**Issue by Okobiti** [pinojs/pino#1606]
Strings with % in them don't work right with interpolation it seem the output respects the % that doesn't match interpolation, however the actual value passed in is "consumed" anyway. 

*Pino* - version 8.7.0

## Test Case 1
Run 
const name = 'testing value';
logger.info('I have a % for some reason, and interpolated text is %s',  name);

*Expected Behavior*
{...,"msg":"I have a % for some reason, and interpolated text is testing value"}

*Actual Behavior*
The following is logged:

{...,"msg":"I have a % for some reason, and interpolated text is %s"}

## Test Case 2

Run
const param = 'one';
const paramTwo = 'two';
logger.info('I have a % for some reason, and interpolated text is %s',  param, paramTwo);

*Expected Behavior*
{...,"msg":"I have a % for some reason, and interpolated text is one"}

*Actual Behavior*
The following is logged:

{...,"msg":"I have a % for some reason, and interpolated text is two"}

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jsumners** [comment]
This seems like correct behavior for any "printf style placeholders" system (https://getpino.io/#/docs/api?id=interpolationvalues). Which is to say, it is undefined what will happen if you do not provide a full interpolation sequence. 

If you need to log a literal `%` character, you must escape it like so:

```js
const log = require('pino')()
log.info('foo %% %s', 'bar') // "foo % bar"
```
