### ISSUE TITLE
log format different on dev and on prod

### ISSUE THREAD

**Issue by gzhhong** [pinojs/pino#1607]
Hello, 

I run my application locally for development environment (not docker image); and run the application on production environment managed by k8s (docker based). For the same code:
```
    const moduleLogger = logger.child({component: "middleware"});
    moduleLogger.info(`>> request ${req.url}, pathname = ${reqUrl.pathname}`);
```

The issue is: on local dev environment the log format looks like:
```
{"level":30,"time":1671434168115,"pid":11642,"hostname":"Zhihongs-MacBook-Pro.local","name":"console","component":"middleware","msg":">> request http://localhost:8080/img/buzz.png, pathname = /img/buzz.png"}
``` 
but on prod the log format looks like:
```
{ component: 'middleware' } >> request http://localhost:8080/api/health, pathname = /api/health
```
what's wrong with my configuration? 

Thanks a lot for the support,

James

**Comment by jsumners** [comment]
> what's wrong with my configuration?

You haven't shown any configuration.

**Comment by gzhhong** [comment]
Hello James, this is the way I use:
Logger.js
```
const logger = require('pino')()

export default logger;
```
then use it as
```
    const moduleLogger = logger.child({component: "middleware"});
    moduleLogger.info(`>> request ${req.url}, pathname = ${reqUrl.pathname}`);
```

I add pino in the package.json like:
```
    "pino": "^8.8.0",
```
Then no other special config.

Thanks,

James

**Comment by mcollina** [comment]
There is definitely something else that is messing with your logs.

**Comment by gzhhong** [comment]
Hello @mcollina , could you give me more information about what missed in the config?

**Comment by mcollina** [comment]
Nothing. It should work the same. You have something else modifying your logging setup.
