### ISSUE TITLE
Logging an Error along with both an object and a string

### ISSUE THREAD

**Issue by watson** [pinojs/pino#161]
I'd like to be able to log an error along with a string and an object without pino merging the object and the string together. Is this possible without using the child feature?

My first attempt at doing this was:

```js
pino.info(new Error('foo'), {bar:42}, 'baz')
```

The result unfortunately is that `msg` becomes `{\"bar\":42} \"baz\"`:

```json
{"pid": 83039,
 "hostname": "...",
 "level": 30,
 "time": 1483531681798,
 "msg": "{\"bar\":42} \"baz\"",
 "type": "Error",
 "stack": "...",
 "v": 1}
```

It looks a little nicer if I reverse the string and the object:

```js
pino.info(new Error('foo'), 'baz', {bar:42})
```

Then `msg` becomes `baz {\"bar\":42}`:

```json
{"pid": 83039,
 "hostname": "...",
 "level": 30,
 "time": 1483531743505,
 "msg": "baz {\"bar\":42}",
 "type": "Error",
 "stack": "...",
 "v": 1}
```

But what I really want is the the same output as if I did:

```js
var child = pino.child({bar:42})
child.info(new Error('foo'), 'baz')
```

This produces the expected result with `bar` as a separate property:

```json
{"pid": 83039,
 "hostname": "...",
 "level": 30,
 "time": 1483531573985,
 "msg": "baz",
 "type": "Error",
 "stack": "...",
 "bar": 42,
 "v": 1}
```

**Comment by mcollina** [comment]
Unfortunately merging all object would probably slow things down, but if you can send us a PR that does not slow things down in the other cases, I'll be very happy to review and merge.

You can do:

```js
logger.info({ err: new Error('foo'), bar: 42 })
```

Would that work for you?

**Comment by watson** [comment]
So with a string it would be like this?

```js
```
```js
pino.info(new Error('foo'), {bar:42, msg:'baz'})
```

**Comment by watson** [comment]
I could try and do that.

So with a string it would be like this right?

```js
logger.info({err:new Error('foo'), bar:42}, 'baz')
```

Alternatively I was also thinking I could do this:

```js
pino.info(new Error('foo'), {bar:42, msg:'baz'})
```

That currently just sets `msg` to `[object Object]`?! But would it be an issue supporting that format?

**Comment by mcollina** [comment]
```js
logger.info({err:new Error('foo'), bar:42}, 'baz')
```

is right.

> That currently just sets msg to [object Object]?! But would it be an issue supporting that format?

Having types that are changing usually cause issues with optimizations. We use that knowledge to cut down on function size, avoid some for loops, and make the function inlineable.

**Comment by watson** [comment]
Cool, I'll try and make a PR to make the format you suggest work. I guess you want me to detect if the object contains an property called `err` that contain an Error object to then trigger this functionality?

**Comment by mcollina** [comment]
That should already work. You just need to add an err serializer

**Comment by watson** [comment]
Ah cool, yes that works. Didn't know about the serializer feature. Thanks 😃

**Comment by peterpod-c1** [comment]
So to understand, if I pass an object into pino's logger it will not stringify the data for me?
Or to put it another way `msg` will be of type `Object`.

Ex:
`logger.info({'event': payload})`

Our team has a use-case where our ELK stack parses the messageKey and expects it to be a string so we not receive the logs.

**Comment by mcollina** [comment]
Your example will be correctly stringified.

**Comment by peterpod-c1** [comment]
Hmm.. Is there a neat way to pass an object into pino logger and have the object stringified, but not the message? Without explicitly JSON.stringifying the object you concatenate?

Ex:
`logger.info('Message', {'event': payload})`
`// {"level":"info","message":"This is a fatal message", "event": {\"payload\":\"true\"}" }`

**Comment by mcollina** [comment]
```js
logger.info({'event': payload}, 'Message')
``` 

Works as expected.

**Comment by peterpod-c1** [comment]
I think I have sort of an edge case requirement.
Your code above works as expected and prints.
```
{"level":"fatal","time":1553794234128,"text":"Message","pid":12259,"hostname":"dca90498bed4","name":"myapp","event":{"payload":{ .. }},"v":1}
```

But I need the `event` attribute to be stringified since Logstash is unable to parse the subobject as a string.

```{"level":"fatal","time":1553794234128,"text":"Message","pid":12259,"hostname":"dca90498bed4","name":"myapp","event":{\"payload\":\"true\"}","v":1}```

**Comment by jsumners** [comment]
Supply a serializer for your specific properties that need extra serialization.

**Comment by davidmarkclements** [comment]
http://getpino.io/#/docs/api?id=serializers-object

**Comment by peterpod-c1** [comment]
Okay, I will definitely try this out. If you guys have any examples handy of serializing custom model objects, that would be super useful. Otherwise, no worries.

**Comment by davidmarkclements** [comment]
Look at pino-std-serializers

**Comment by omidkrad** [comment]
> You can do:
> 
> ```js
> logger.info({ err: new Error('foo'), bar: 42 })
> ```

This syntax is definitely not working with [pino-seq](https://github.com/simihartstein/pino-seq).

```javascript
import pino from 'pino';
import pinoToSeq from 'pino-seq';
const seqStream = pinoToSeq.createStream({
  serverUrl: 'http://localhost:5341',
});

const log = pino({ level: 'info'}, seqStream);
const err = new Error('Some error occurred.');
log.error(err); // works OK
log.error({ err }); // does not log error

// The only way I found to log error with additional meta data is this:
log.error({ stack: err.stack, type: err.name, meta: 'aaa' }, err.message);
```
