### ISSUE TITLE
Log nested objects to stdout?

### ISSUE THREAD

**Issue by vivekprm** [pinojs/pino#1616]
I was trying to log some objects using:

`logger.debug("data is %o", dataObj);`

I see object is getting logged in stringified form. 
What is the right way to log nested objects in stdout. I don't want to log stringified objects.

Here is my logger config:
```js
const pino = require('pino')

let config = {
    level: process.env.LOG_LEVEL || 'debug',
    formatters: {
        level: (label) => {
            return { level: label };
        },
    },
}
module.exports = pino(config)
```

**Comment by jsumners** [comment]
Pino is an NDJSON logger. What are you expecting?

**Comment by vivekprm** [comment]
Ok..here is a dummy sample code:

```js
const pino = require('pino');
const logger = pino({
    name: 'test',
    level: 'debug',
    nestedKey: 'obj'
});

let obj = {
    "name": "xyz",
    "age": 19,
    "nestedObj" : {
        "xyz": "123",
        "pqr": 1
    }
}

logger.debug(obj)
```

It logs the object properly like below:
`"obj":{"name":"xyz","age":19,"nestedObj":{"xyz":"123","pqr":1}}`

But when i changed it to:
```js
logger.debug("Obj is: ", obj)
```

It prints below log:
`"msg":"Obj is: "`

%o prints in stringified form as below:
`"msg":"Obj is: {\"name\":\"xyz\",\"age\":19,\"nestedObj\":{\"xyz\":\"123\",\"pqr\":1}}"`

Is there a way to print it like this (i know it's possible using multiple log statements)
`"msg":"Obj is: {"name":"xyz","age":19,"nestedObj":{"xyz":"123","pqr":1}}"`

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=logger

**Comment by vivekprm** [comment]
Thanks for the details..Got it working!
