### ISSUE TITLE
Can prettifier option still be used?

### ISSUE THREAD

**Issue by borjapazr** [pinojs/pino#1619]
Hi!

Can the `prettifier` option still be used? As far as I can see, this property is defined in pine types ([pino.d.ts](https://github.com/pinojs/pino/blob/27d2ab8b58e64547fd24864c2f21ac898f4752c4/pino.d.ts#L408)) but then it doesn't seem to work. Checking the source code I don't see any reference to it or that it is being used.

If it really is no longer used, it would be interesting to update the documentation to adapt it to the new way of configuring a prettifier, for example, `pino-pretty`.

The `Pretty Printing` section should reflect the new way to set up a prettifier, for example:

```js
const pino = require('pino')
const logger = pino({
  transport: {
    target: 'pino-pretty'
  },
})

logger.info('hi')
```

Thanks in advance.

Regards.

**Comment by mcollina** [comment]
The `prettifier` is no longer used and it has been removed. Would you like to send a PR to update the docs and the types?

**Comment by borjapazr** [comment]
Hi, @mcollina 👋

Thanks for the reply. Yes, of course. I will be happy to send a PR updating the documentation and types. When I create it I will associate it with this issue and as soon as it is merged I will close it.

Best regards.
