### ISSUE TITLE
Is there any way to print any output to a logfile?

### ISSUE THREAD

**Issue by dunklesToast** [pinojs/pino#162]
Hey,

idk if I am to dumb to find it but is there anyway to print pinos output globally to a log file?

- dunklesToast

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/master/docs/howtos.md#rotate

**Comment by dunklesToast** [comment]
Ok, when I add `node foo > log.txt` then it will print anything to my file but I have no console output anymore :(

**Comment by jsumners** [comment]
This question is really covered in the discussion on how we deal with transports -- https://github.com/pinojs/pino/blob/master/docs/transports.md

Basically, Pino is a logger and only a logger. It does not handle the output in anyway. So you need to use pipes to handle the output in whatever way you wish.

With `node foo > log.txt` you can simply `tail -f log.txt` to view the output. Or you can use `pino-tee` to write to a file while retaining the output on `stdout` -- https://github.com/pinojs/pino/blob/master/docs/howtos.md#multiple
