### ISSUE TITLE
Pino redact doesn't work with hyphens

### ISSUE THREAD

**Issue by polRk** [pinojs/pino#1623]
Error: pino – redact paths array contains an invalid path (res.headers.set-cookie)

```js
{
  redact: [
    `["${HTTP_REQUEST_HEADER_PREFIX}cookie"]`,
    `["${HTTP_REQUEST_HEADER_PREFIX}authorization"]`,
    `["${HTTP_RESPONSE_HEADER_PREFIX}set-cookie"]`,
    `["${HTTP_RESPONSE_HEADER_PREFIX}authorization"]`,
    "req.headers.cookie",
    "req.headers.authorization",
    "res.headers.set-cookie",
    "res.headers.authorization",
  ],
}
```

**Comment by polRk** [comment]
But with format is work.
```js

`["res.headers.set-cookie"]`,

```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

This likely should go into the [fast-redact](https://www.npmjs.com/package/fast-redact) module.

**Comment by ValentinH** [comment]
This is actually documented here: https://getpino.io/#/docs/redaction

![Screenshot_2023-03-25-06-16-15-53_e4424258c8b8649f6e67d283a50a2cbc~2.jpg](https://user-images.githubusercontent.com/2678610/227697867-95bed4a5-0d85-4307-a088-d88781a486ab.jpg)
