### ISSUE TITLE
Resolved/invalid issues to close

### ISSUE THREAD

**Issue by VladimirMikulic** [pinojs/pino#1626]
While exploring issues list, I noticed a lot of issues don't apply anymore or have been resolved but not closed so I thought I'd compile this list so you can close them:
- #1600 (resolved)
- #1485 (resolved) 
- #1383 (third party package issue)
- #1258 (question answered by maintainers) 
- #1248 (question answered by a maintainer)
- #1052 (question answered by a maintainer) 
- #1043 (prettyPrint option no longer exists)
- #835 (prettyPrint option no longer exists)
- #805 (resolved)
- #651 (resolved)
- #510 (prettyPrint option no longer exists)
- #850 (PR closed)

**Comment by mcollina** [comment]
Thanks, all closed now!

**Comment by VladimirMikulic** [comment]
Recently, I had some more time to triage those old/invalid issues.
Here's the new batch for you @mcollina 

- #1603 (question answered by a maintainer)
- #1585 (question answered by a maintainer)
- #1552 (original issue resolved)
- #1528 (can be closed with link to https://getpino.io/#/docs/transports?id=writing-a-transport)
- #1524 (very vague description, no further details)
- #1595 (duplicate of #1538)
- #1504 (question answered by a maintainer)
- #1330 (resolved in #1541)
- #1271 (resolved in #1640)
- #1213 (question answered by a maintainer)
- #1100 (question answered by a maintainer)
- #1041 (resolved/not relevant anymore)
- #1022 (question answered by a maintainer)
- #1011 (question answered by a maintainer)
- #991 (vague description, no further reproduction)
- #648 (resolved / issue reported settled on a solution)

**Comment by mcollina** [comment]
thx!
