### ISSUE TITLE
How to define a property and override it in child logger

### ISSUE THREAD

**Issue by bguerout** [pinojs/pino#1632]
Hello,

I would like to be able to create child loggers with a specific `module` property and configure the parent logger with a default value so that the `module` property has always a value

```js
const log = parentLogger.child({module: 'foo'})
```

I have tried to configure this default property with mixin and formatters.log options but both solutions seems to override the value provided to the child.

The only solution I found is to create a child and use it as the main logger

```js
const parentLogger = pino(...).child({module: 'main'})
const log = parentLogger.child({module: 'foo'})
```

**Comment by mcollina** [comment]
That's how I would do it!

**Comment by bguerout** [comment]
OK thanks
