### ISSUE TITLE
How to define a property without a child logger

### ISSUE THREAD

**Issue by mbrevda** [pinojs/pino#1633]
When logger is created on startup and `export`ed (esm) - there doesn't seem to be a way to replace/append metadata at runtime. One option would be to make logger creation async, but that would incur a startup performance penalty. How can data be appended to every log **without** using a child logger?

**Comment by jsumners** [comment]
I don't know what sync vs async has to do with this, but the solution is:


***logger.mjs***
```js
import pino from 'pino'

const logger = pino().child({ meta: 'data' })

export default logger
```


***index.mjs***
```js
import logger from './logger.mjs'

logger.info('hello world')
```

**Comment by mbrevda** [comment]
Apologies if that was unclear. The use case is updating the logging instance after it was exported. It seems like calls to `child()` create a new logger, which wouldn't affect the exported one

**Comment by jsumners** [comment]
> It seems like calls to `child()` create a new logger, which wouldn't affect the exported one

That is correct.

**Comment by mbrevda** [comment]
So the question is how to update an existing log instance with data that only becomes available later on (hence the async reference)?

**Comment by jsumners** [comment]
```js
const someData = { foo: 'foo', answer: 42 }
log.info({ someData }, 'a log')
```

**Comment by mbrevda** [comment]
My question isn't how to log, it's how to add to logger so that when `log.info` is called, it also includes that data (for example metadata)
