### ISSUE TITLE
Logger.debug and logger.trace not display in browser (Google or Firefox)

### ISSUE THREAD

**Issue by InfiniteLearner** [pinojs/pino#1641]
Hello,

I might be missing a configuration but the debug and trace level does not seem to appear in browser (Google and Firefox) when using pino with next.js.

```
async function greeting(){
    logger.debug("Start of greeting");
    
    logger.fatal('fatal');
    logger.error('error');
    logger.warn('warn');
    logger.info('info');
    logger.debug('debug');
    logger.trace('trace');

    console.log("Hello");
    console.log("Goodbye");

    logger.debug("End of greeting");
  }
```

Full version of the code : https://github.com/InfiniteLearner/debug_error_next_reproduction

Also does any know why the log doesn't get output in the terminal with _nexdev_ ?
![2023-02-08_20h58_18](https://user-images.githubusercontent.com/29714758/217637984-23158dff-7973-4fe7-a5cc-454324b92f4c.png)
![2023-02-08_20h59_47](https://user-images.githubusercontent.com/29714758/217638286-c5ed523b-a4ec-4b83-b856-2d3805be3847.png)

**Comment by mcollina** [comment]
the default level pino logs is "info", anything under it is silenced.
