### ISSUE TITLE
Error instance is logged as empty object when nested

### ISSUE THREAD

**Issue by kpedrozag** [pinojs/pino#1652]
Hi. I'm logging an object with an Error instance and it's logging the error prop as an empty object. Can someone please help me to understand why?

I'm running this code:
```js
try {
  throw new Error("ERROR boom");
} catch (error) {
  pino.error({ data: { a: 1, b: 2, c: 3 }, error });
}
```

And getting:

```log
{"level":50,"time":1676929039261,"pid":21850,"hostname":"my_pc","data":{"a":1,"b":2,"c":3},"error":{}}
```

Notice that the `error` property is inside the object I'm logging. Thanks for the help.

**Comment by mcollina** [comment]
`Error` objects are "special" objects that needs extra handling. You are missing the serializer for the `error` property. By default, that's configured on `err`. This should work:

```js
try {
  throw new Error("ERROR boom");
} catch (err) {
  pino.error({ data: { a: 1, b: 2, c: 3 }, err });
}
```
