### ISSUE TITLE
global serializer

### ISSUE THREAD

**Issue by siddisking** [pinojs/pino#1653]
I have a requirement in which I need to run validator on the class object before logging it to avoid disclosure of sensitive information. 

The field (password) is being excluded from response through class validator's exclude decorator but need to run classToPlain on the whole object before logging.

tried something like this but no success

```
            serializers: {
              [Symbol.for('*')]: (object: any) => {
                return classToPlain(object);
              },
            },

```

the alternative would be extend Logger class and all functions but this seems like a cleaner solution.

I was not able to spot the global serializer in the doc and picked this code in some resolved issues but its not working.

Any help on this would be appreciated

Thanks

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by siddisking** [comment]
> Thanks for reporting!
> 
> Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

Sure.

But before that can you share a working example of global serializer ?

Maybe I doing this incorrectly.

I am using nestjs-pino

Here the my code:

```
LoggerModule.forRootAsync({
  inject: [
    getConfigToken(Configs.AppConfig),
    getConfigToken(Configs.LoggerConfig),
  ],
  useFactory: async (
    appConfig: Configs.AppConfig,
    loggerConfig: Configs.LoggerConfig,
  ) => {
    const options: Params = {
      pinoHttp: {
        logger: pino({
          base: undefined,
        }),
        transport:
          appConfig.env === Env.LOCAL
            ? { target: 'pino-pretty' }
            : undefined,
        level: 'debug',
        autoLogging: loggerConfig.suppressStdout
          ? false
          : ({
              ignorePaths: [
                '/liveness',
                '/readiness',
              ],
              getPath: (req: Request) => req.originalUrl,
            } as any),
        serializers: {
          [Symbol.for('*')]: (obj: any) => {
            return classToPlain(obj);
          },
          req(req: Request) {
            return {
              id: req.id,
              method: req.method,
              url: req.url,
            };
          },
          res(res: any) {
            return {
              statusCode: res.statusCode,
            };
          },
        },
      },
    };

    return options;
  },
}),
```

**Comment by mcollina** [comment]
Unfortunately I don't have time to assemble an example just for you.

**Comment by siddisking** [comment]
> Unfortunately I don't have time to assemble an example just for you.

There is no need to assemble one, since this feature is already merged just point me toward the doc.

I was able to find a PR regarding this which you merged long back.

https://github.com/pinojs/pino/pull/365/files

**Comment by BenMaGit** [comment]
I think this feature is removed from the codebase, I cannot find it in master branch, is there another way to accomplish this ?

**Comment by Fabioni** [comment]
this would be very helpful to just serialize all objects with a specific type no matter which name they have. Please let us know where this feature went or how we can do this.

**Comment by Fabioni** [comment]
Okay, then let me answer with what I think what happened: the feature 'global serializer' was removed in https://github.com/pinojs/pino/pull/775 without any further discussion and change documentation.

A replacement for that is using formatters with the log() function as documented in https://github.com/pinojs/pino/blob/master/docs/api.md#log, which gives you the global object you can operate on and replace individual objects with its serialised version.

**Comment by jsumners** [comment]
So this issue is resolved?

**Comment by Fabioni** [comment]
I think so. the thing @siddisking wants to implement can be done with my suggestion.

**Comment by jsumners** [comment]
Thank you.
