### ISSUE TITLE
mutate before logging

### ISSUE THREAD

**Issue by IainMcHugh** [pinojs/pino#1656]
Hello, thank you for the library!

I am using pino in a custom server with NextJS, and I want to log a specific cookie on `req.headers.cookie`, but nothing else on `req.headers`. I am using redact to manually remove all headers accept the one I need, wondering if it would be feasible to expose a `mutate` function as part of the options to give custom control before log is logged, so something like:

```ts
const logger = pino({
  level: 'warn',
  redact: {
    paths: REDACTED,
    remove: true,
  },
  mutate(logObject) => {
    // can manipulate here
    return logObject;
  } 
});
```

**Comment by jsumners** [comment]
You can provide your own request serializer. https://getpino.io/#/docs/api?id=serializers-object

**Comment by IainMcHugh** [comment]
Ah will try that, thanks 👍
