### ISSUE TITLE
Logs are written twice to file though it's only called once

### ISSUE THREAD

**Issue by mayeaux** [pinojs/pino#1658]
```
var pino = require('pino')
var multistream = pino.multistream

const streams = [
  { stream: pino.destination({ dest: process.cwd() + '/logs/error.log' }), level: 'error' },
  { stream: process.stderr, level: 'error' },
  { stream: process.stdout, level: 'info' },
  { stream: pino.destination({ dest: process.cwd() + '/logs/info.log' }), level: 'info' },
];


var opts = {
  levels: {
    silent: Infinity,
    fatal: 60,
    error: 50,
    warn: 50,
    info: 30,
    debug: 20,
    trace: 10
  },
  dedupe: true,
}

var log = pino({
  level: 'trace' // this MUST be set at the lowest level of the
  // destinations
}, multistream(streams, opts))

// log.debug('this will be written ONLY to process.stdout')
// log.info('this will be written ONLY to process.stdout')
// log.error('this will be written ONLY to process.stderr')
// log.fatal('this will be written ONLY to process.stderr')

const error = new Error('Example error')
log.error(new Error('Example error'));

module.exports = log
```

Why with this setup are the logs written to logs/error twice?

**Comment by couragecowardlydog** [comment]
> ```
> var pino = require('pino')
> var multistream = pino.multistream
> 
> const streams = [
>   { stream: pino.destination({ dest: process.cwd() + '/logs/error.log' }), level: 'error' },
>   { stream: process.stderr, level: 'error' },
>   { stream: process.stdout, level: 'info' },
>   { stream: pino.destination({ dest: process.cwd() + '/logs/info.log' }), level: 'info' },
> ];
> 
> 
> var opts = {
>   levels: {
>     silent: Infinity,
>     fatal: 60,
>     error: 50,
>     warn: 50,
>     info: 30,
>     debug: 20,
>     trace: 10
>   },
>   dedupe: true,
> }
> 
> var log = pino({
>   level: 'trace' // this MUST be set at the lowest level of the
>   // destinations
> }, multistream(streams, opts))
> 
> // log.debug('this will be written ONLY to process.stdout')
> // log.info('this will be written ONLY to process.stdout')
> // log.error('this will be written ONLY to process.stderr')
> // log.fatal('this will be written ONLY to process.stderr')
> 
> const error = new Error('Example error')
> log.error(new Error('Example error'));
> 
> module.exports = log
> ```
> 
> Why with this setup are the logs written to logs/error twice?

@mayeaux  You might have run the script twice and it appended to the same file
