### ISSUE TITLE
Pino in NextJS Middleware does not work

### ISSUE THREAD

**Issue by vsaw** [pinojs/pino#1667]
I'm using Pino in my NextJS 13 App to log server API calls etc.

While Pino works in "regular" API code, is throws a weird error when used in NextJS Middleware

```
error - src/utils/Logger.ts (5:0) @ <unknown>
error - (0 , pino__WEBPACK_IMPORTED_MODULE_0__.pino) is not a function
> 5 | const Logger = pino(options);
  6 | Logger.info({context: 'Logger Ready'});
```

The options itself are pretty basic as far as I can tell

```ts
export const options: LoggerOptions = {
    redact: ['auth.token']
}
if(process.env.NODE_ENV !== 'production') {
    options.level = 'debug'
    options.transport = {
        target: 'pino-pretty',
        options: {
            colorize: true
        }
    }
}
```

I've recently read about some [limitations of Middleware](https://www.smashingmagazine.com/2022/04/next-js-middleware-feature/), but I don't know Pino well enough to understand if it's running into any of them.

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](https://discord.gg/NestJS) channel (support) for such questions.

**Comment by vsaw** [comment]
@mcollina ah sorry I'm running [NextJS](https://nextjs.org/), not Nest.

Don't know if this changes anything, I just wanted to tell you since there was a mistake in my original post. Sorry for the confusion

**Comment by mcollina** [comment]
Ah my bad, I might have been actually too quick (I was doing mass triaging).

Essentially middlewares runs the "browser" build of Next.js. So, you are 100% hitting the limitations of Next.js middlewares.

**Comment by vsaw** [comment]
@mcollina The "browser" mode did the trick. Here's my work around for now. It's not pretty but it allows for consistent logging in development and production.

```ts
// LoggerOptions.ts
// Important to keep options in extra file, otherwise middleware might accidentally
// try to create non-browser pino and break the build
import { LoggerOptions } from "pino";

export const options: LoggerOptions = {
    redact: ['auth.token']
}
if(process.env.NODE_ENV !== 'production') {
    options.level = 'debug'
    options.transport = {
        target: 'pino-pretty',
        options: {
            colorize: true
        }
    }
}
```

```ts
// MiddlewareLogger.ts
import pino from 'pino';

// Import shared options from 'non-browser' pino
import { options } from "@/utils/LoggerOptions";

const logLevels: any = {
    10: { name: 'TRACE', color: '\x1b[34m' },
    20: { name: 'DEBUG', color: '\x1b[34m' },
    30: { name: 'INFO', color: '\x1b[32m' },
    40: { name: 'WARN', color: '\x1b[33m' },
    50: { name: 'ERROR', color: '\x1b[31m' },
    60: { name: 'FATAL', color: '\x1b[91m' },
}

function writeJson(o: any) {
    console.log(JSON.stringify(o));
}

function writePretty(o: any) {
    const d = new Date(o.time);
    const timeString = d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: '2-digit', fractionalSecondDigits: 3, hour12: false });

    const pidString = process.pid !== undefined ? `(${ process.pid })` : '';

    console.log(`[${ timeString }] ${logLevels[o.level].color}${ logLevels[o.level].name }\x1b[0m ${ pidString }: \x1b[36m${o.msg}\x1b[0m`);

    const ctx = {...o};
    delete ctx.time;
    delete ctx.level;
    delete ctx.msg;
    const lines = JSON.stringify(ctx, null, 4).split('\n').filter((value) => !(value === '{' || value === '}')).join('\n');
    console.log(lines);
}

export const MiddlewareLogger = pino({
    ...options,
    browser: {
        write: (o: any) => {
            if(options?.transport && (options?.transport as any).target && (options?.transport as any).target === 'pino-pretty') {
                writePretty(o);
            } else {
                writeJson(o);
            }
        }
    }
});
```

I'm posting this here hoping it may be useful to someone.

**Comment by jsumners** [comment]
> Not sure if you know this but the official [NextJS docs](https://nextjs.org/docs/going-to-production#logging) recommend using Pino for logging. I hope that makes this issue important enough to take a look at.

I'd say it's still an issue for NextJS. They are the ones making the recommendation without showing how to make it work in their system. At a minimum, their docs need to make it clear what caveats need to be considered.
