### ISSUE TITLE
Support for error.cause

### ISSUE THREAD

**Issue by Yuval-Peled** [pinojs/pino#1669]
Hi maintainers! 
Thanks for creating this library, it's fantastic.

error.cause is now supported in all browsers + node.js.
When I pass an Error object that has a `cause`, I expect pino to print the "cause" fully, including any fields on the Error.
This would make debugging issues much much easier.

**Reproducible example: (pino@8.11.0, latest version at the time of this writing)**
```javascript
const pino = require('pino');

class ErrorWithMetadata extends Error {
    constructor(message, errorOptions, data) {
        super(message, errorOptions);
        this.data = data;
    }
}

const innerError = new ErrorWithMetadata('inner error', {}, { type: 'inner' });
const outerError = new ErrorWithMetadata('outer error', {cause: innerError}, { type: 'outer' });

pino().info({ err: outerError }, 'print outer');
```

The resulting print:
```json
{
  "level": 30,
  "time": 1678632974123,
  "pid": 9540,
  "hostname": "Yuvals-MacBook-Pro-2.local",
  "err": {
    "type": "ErrorWithMetadata",
    "message": "outer error: inner error",
    "stack": "<omitted for brevity>",
    "data": {
      "type": "outer"
    }
  },
  "msg": "print outer"
}
```

**Expected behavior**
pino should treat the inner error the same way it does the outer error, and print all of its fields, something like the following:
```json
{
  "level": 30,
  "time": 1678632974123,
  "pid": 9540,
  "hostname": "Yuvals-MacBook-Pro-2.local",
  "err": {
    "type": "ErrorWithMetadata",
    "message": "outer error: inner error",
    "stack": "<omitted for brevity>",
    "data": {
      "type": "outer"
    },
    "cause": {
        "type": "ErrorWithMetadata",
        "message": "inner error",
        "stack": "<omitted for brevity>",
        "data": {
          "type": "inner"
        },
    }
  },
  "msg": "print outer"
}
```

As an example of where this behavior would help me very much:
TypeORM throws errors that contain fields like what the original query was. Currently if I want to put the TypeORM error in a "cause" field, I lose that extremely valuable information which would make debugging much harder.

**Remediation**
I'm happy to work on a PR that fixes this (with slight nudges to the correct solution as I'm very unfamiliar with pino's codebase).
Alternatively - if I'm doing something wrong here, I'd love to know what.

Thank you!

**Comment by kibertoad** [comment]
have you tried using stdSerializer for errors?

**Comment by Yuval-Peled** [comment]
> have you tried using stdSerializer for errors?

According [to the documentation](https://github.com/pinojs/pino/blob/master/docs/api.md#serializers-object), this is already the default: 

> Default: `{err: pino.stdSerializers.err}`

I tried it anyway, with the following code:
```js
const pino = require('pino');
const { err } = require('pino-std-serializers');

class ErrorWithMetadata extends Error {
    constructor(message, errorOptions, data) {
        super(message, errorOptions);
        this.data = data;
    }
}

const innerError = new ErrorWithMetadata('inner error', {}, { type: 'inner' });
const outerError = new ErrorWithMetadata('outer error', {cause: innerError}, { type: 'outer' });

pino({ serializers: { err } }).info({ err: outerError }, 'print outer');
```

And got the same result

**Comment by Yuval-Peled** [comment]
I just found the root cause for this behavior [in the `pino-std-serializers` repo](https://github.com/pinojs/pino-std-serializers/blob/e388fb51f7679939c4c48632a6e28afa6dd344fb/lib/err.js#L64):
```js
  for (const key in err) {
    if (_err[key] === undefined) {
      const val = err[key]
      if (isErrorLike(val)) {
        // We append cause messages and stacks to _err, therefore skipping causes here
        if (key !== 'cause' && !Object.prototype.hasOwnProperty.call(val, seen)) {
          _err[key] = errSerializer(val)
        }
      } else {
        _err[key] = val
      }
    }
  }
```

The `for (const key in err)` loop does not iterate over the `cause` param since it is non enumerable.

I'm happy to put in a PR that changes this behavior, but I'm not sure that the pino maintainers are ok with this change, or whether I should open a new issue in the `pino-std-serializers` repo. 

Please let me know!
Thanks!

**Comment by jsumners** [comment]
https://github.com/pinojs/pino-std-serializers/pull/123

**Comment by Yuval-Peled** [comment]
> [pinojs/pino-std-serializers#123](https://github.com/pinojs/pino-std-serializers/pull/123)

Thanks. I wasn't able to find past issues in my searched. I'm closing this issue.
