### ISSUE TITLE
Lowering the overhead - let's remove unit tests from npm package

### ISSUE THREAD

**Issue by koresar** [pinojs/pino#1672]
Hello

I was quite surprised to see that this package deliberately decided to publish unit tests to npm registry. See here: https://www.npmjs.com/package/pino?activeTab=code

I've never seen this before (except accidental publish). But in this project the `test` folder is included to the `files` of the `package.json`: https://github.com/pinojs/pino/blob/49a29bb9d7895e791e7166fadfd7fd379f8db504/package.json#L17

This mistake is dragging from the first most version of pino.
Would you agree to make this module tiny by removing a hundred of files, and shrink down the size of npm tarball by half?

I urge removing this `test` folder from being published to NPM. I'm ready to submit a PR if needed. It's literally a 1 line change (need to remove "test" from the `package.json/files` array).

**Comment by koresar** [comment]
Looks like I need to go rethink my DX experience when I publish my npm modules.

Thanks @jsumners for taking your time explaining.

**Comment by jsumners** [comment]
> Looks like I need to go rethink my DX experience when I publish my npm modules.

If you like. We don't pretend that everyone agrees with our philosophy. We suggest doing what you think is right for your own projects.

**Comment by koresar** [comment]
I typically do what is right for the npm package users (their DX). My DX goes right after theirs though.
