### ISSUE TITLE
[Help] Having trouble to format output

### ISSUE THREAD

**Issue by rafaell-lycan** [pinojs/pino#1678]
Hi y'all,

I'm having a bad moment trying to archive a standard format we use in the company as we are trying to move from Express/Winston to Fastify/Pino.

By reading the docs I've found that I can use `bindings` to format my output on `formatters` but I'm still getting some bits of the original log format such as `level`, `timestamp`, etc.

Essentially the output format we already use is composed of 2 properties: `log` and `request`.
```json
{
	"request": {
		"path": "/webhooks/abcdef/submit",
		"route": "/webhooks/:form/submit",
		"method": "POST",
		"response_code": 200,
		"duration_ms": 523,
		"request_id": "7d34ca10-8ddc-491a-93ed-5b1d7a5f6240"
	},
	"log": {
		"message": "Submission processed",
		"level": "info",
		"timestamp": "2023-03-28T10:55:44.000Z"
	}
}
```

Other properties such as `workspace` and `form` can be also included on the final payload as additional metadata, and that is already covered.

**Comment by jsumners** [comment]
We do not have any feature that will make such a reformatting of output possible. Were I to add such a feature, I'd start by investigating adding a new hook at https://github.com/pinojs/pino/blob/2d5c522398731c1063a453295ed0f906b5ae54ff/lib/proto.js#L214-L215

Roughly:

```js
if (stream[needsMetadataGsym] === true) {
    stream.lastLevel = num
    stream.lastObj = obj
    stream.lastMsg = msg
    stream.lastTime = t.slice(this[timeSliceIndexSym])
    stream.lastLogger = this // for child loggers
  }

  if (this[hooksSym].preWrite) {
    s = this[hooksSym].preWrite.call(this, s)
  }

  stream.write(s)
```

See https://github.com/pinojs/pino/pull/808.

**Comment by mcollina** [comment]
An option would be to create a transport to do this reformatting.

**Comment by rafaell-lycan** [comment]
@mcollina currently we use Winston by formatting the whole thing to our standard. It would be nice if _Pino_ could provide a flexible way for that.

**Comment by jsumners** [comment]
> @mcollina currently we use Winston by formatting the whole thing to our standard. It would be nice if _Pino_ could provide a flexible way for that.

You have received a couple of suggestions. One of which requires no changes to Pino.
