### ISSUE TITLE
`crlf` missing from LoggerOptions TS interface

### ISSUE THREAD

**Issue by pushred** [pinojs/pino#1679]
The included type definitions for the [LoggerOptions](https://github.com/pinojs/pino/blob/2d5c522398731c1063a453295ed0f906b5ae54ff/pino.d.ts#L321) interface do not include the `crlf` property that is [accepted for options](https://github.com/pinojs/pino/blob/2d5c522398731c1063a453295ed0f906b5ae54ff/pino.js#L90) and otherwise [documented](https://github.com/pinojs/pino/blob/2d5c522398731c1063a453295ed0f906b5ae54ff/docs/api.md#crlf-boolean).

Curious if this is intentional? Happy to submit a PR if not!

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by pushred** [comment]
Resolved by https://github.com/pinojs/pino/pull/1696
