### ISSUE TITLE
Type definitions indicate they are for an older version (7.0)

### ISSUE THREAD

**Issue by pushred** [pinojs/pino#1680]
The [lead comment](https://github.com/pinojs/pino/blob/2d5c522398731c1063a453295ed0f906b5ae54ff/pino.d.ts#LL1) in the TS definitions file currently indicates they are for v7.0. While inspecting the types in my project this prompted some sanity checking to verify my version.

Not sure if the comment is worth retaining if it's not being maintained with version updates?

**Comment by mcollina** [comment]
We forgot to remove that line. Would you like to send a PR?
