### ISSUE TITLE
Strange formatting when writing pretty-pino output to .log files

### ISSUE THREAD

**Issue by vitoff34** [pinojs/pino#1683]
Hello,
I am trying to log errors using pretty-pino not only to the console but also to files. This is my code for the logger: 
`const pino = require('pino');
const transport = pino.transport({
    targets: [{
        level: 'error',
        target: 'pino-pretty' // must be installed separately
    }, {
        level: 'trace',
        target: 'pino-pretty',
        colorize: true,
        options: { destination: 'logs/error.log' }
    }]
})
const logger = pino(transport)`

However when the error is added to the error.log there is some strange formatting like this: 
[31mERROR[39m (55774): [36muser is not defined[39m
Additionally in front of every "[" there is something like and ESC emoji. 
How can I remove this formatting? 
Thank you

**Comment by jsumners** [comment]
Don't colorize the output.

**Comment by vitoff34** [comment]
I removed the colorize but I still get the strange formatting.

**Comment by jsumners** [comment]
The characters provided in the issue are terminal color escape sequences.

**Comment by jsumners** [comment]
You are welcome to write whatever you like to a log file. It's a matter of tooling to interpret them in the way you want.

**Comment by vitoff34** [comment]
So I can format in one way in console and another in .log files for pino pretty? Can you show me some code how to achieve this if it is not too much trouble? Thank you

**Comment by jsumners** [comment]
We have significant documentation around multiple streams. Please open an issue if you find problems with that documentation.
