### ISSUE TITLE
undefined (reading 'Symbol(pino.msgPrefix)') crash

### ISSUE THREAD

**Issue by jstaro** [pinojs/pino#1687]
We have a service that is occasionally throwing this (uncaught) error, bringing down the service.

```
/app/node_modules/pino/lib/tools.js:59
if (typeof this[msgPrefixSym] === 'string' && msg !== undefined && msg !== null) {
TypeError: Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')
  at LOG (/app/node_modules/pino/lib/tools.js:59:22)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Looking at the Pino source code I don't really understand how this could happen, but I do see that the `msgPrefix` feature is a very recent one. One we are not using.

It doesn't make sense to me that it would only happen once in a blue moon.

```json
    "pino": "^8.11.0",
```

**Comment by jstaro** [comment]
I think this might be because of `this` being torn off somewhere. On second thought I could see it happening if we do `.catch(logger.error)` somewhere, but we don't. So I suppose I'll have to hunt around in (apparently rarely used) code for some missing closure captures.

**Comment by gnoyixiang** [comment]
Experiencing the same issue on my end.

**Comment by gnoyixiang** [comment]
Found that this code caused the error, but not sure why.
```
const errLog =
  !axiosErr?.status || axiosErr.status < HttpStatusCode.InternalServerError
    ? serverLogger().warn
    : serverLogger().error;
errLog({ error }, 'Request data error');
```

I updated the code to this and the error is gone.
```
if (
  !axiosErr?.status ||
  axiosErr.status < HttpStatusCode.InternalServerError
) {
  serverLogger().warn({ error }, 'Request data error');
} else {
  serverLogger().error({ error }, 'Request data error');
}
```

**Comment by jsumners** [comment]
I don't understand the code you have posted, but it looks like you are passing the logger's method, e.g. `error`, to a function that then attempts to invoke the logger method without providing the proper `this` context. The simplest solution is:

```js
someFuncNeedingToLog(yourLoggerInstance.error.bind(yourLoggerInstance))
```
