### ISSUE TITLE
Logs are not sent to Sentry using the transport

### ISSUE THREAD

**Issue by slim-hmidi** [pinojs/pino#1694]
I tried to send the error logs to Sentry using the `transport` but I'm not able to achieve that:
```ts
import pino from 'pino';
const logger = pino(
    {
      level: 'error',
      formatters: {
        level: label => {
          return { level: label };
        },
      },
      transport: {
        target: 'pino-sentry-transport',
        options: {
          sentry: {
            dsn: 'xxxxx',
          },
        },
      },
      timestamp: () => `,"timestamp":"${new Date(Date.now()).toISOString()}"`,
    }
  );
  ```
 I checked the Sentry connection and it works well but the error logs not sent with transport.
I use `pino-sentry-transport` **v1.0.4** and pino **v8.11.0**.

**Comment by jsumners** [comment]
Please file an issue with the maintainer of the `pino-sentry-transport` module.
