### ISSUE TITLE
msg not always a string?

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#170]
```{"pid":1,"hostname":"03c629b527e3","name":"storage-fs","level":50,"time":1484571351146,"msg":-1,"v":1}```

This breaks bunyan CLI.

**Comment by jsumners** [comment]
I'm just curios, is there a reason to pass Pino's output through Bunyan's CLI instead of Pino's own?

**Comment by ronag** [comment]
@jsumners: Didn't know pino had its own.

**Comment by jsumners** [comment]
@ronag it does. It works just the same as the Bunyan one. Install Pino globally and pipe the logs through it. See https://github.com/pinojs/pino/blob/master/docs/cli.md
