### ISSUE TITLE
`bindings` formatter not called when creating child logger bug

### ISSUE THREAD

**Issue by nadhifikbarw** [pinojs/pino#1700]
According to [docs](https://github.com/pinojs/pino/blob/master/docs/api.md#bindings)

> Changes the shape of the bindings. The default shape is { pid, hostname }. The function takes a single argument, the bindings object. **It will be called every time a child logger is created.**

But with this simple reproduction, it doesn't seem to be the case
```js
"use strict";
const pino = require('pino');
const log = pino({
  formatters: {
    bindings(b) {
      console.log('will be called every time a child logger is created')
      return { pid: b.pid }
    }
  }
})
log.info('Test Main Logger');
const child = log.child({ bindprop: 42 });
child.info('Test Child Logger');
const child2 = log.child({ bindprop2: 101 });
child2.info('Test Child Logger 2');
```

Result
```
will be called every time a child logger is created
{"level":30,"time":1682657223899,"pid":12868,"msg":"Test Main Logger"}
{"level":30,"time":1682657223900,"pid":12868,"bindprop":42,"msg":"Test Child Logger"}
{"level":30,"time":1682657223900,"pid":12868,"bindprop2":101,"msg":"Test Child Logger 2"}
```

Would love to help, but i was bit puzzled on where to start when reading the source code 😢

**Comment by mcollina** [comment]
The docs is incorrect.

As you can see in https://github.com/pinojs/pino/pull/775/files#diff-78c851c106059931b9042837eb4d521a7650b32535f306d9cb85bbddef22f877R108, the bindings configuration is reset when child is created. Can you send a PR to update the docs?

**Comment by mcollina** [comment]
Thx!
