### ISSUE TITLE
Disable log for certain context

### ISSUE THREAD

**Issue by rubiin** [pinojs/pino#1732]
I have  context such as BootStrap as well as RouterExplorer . Is there a way i could tell pino to ignore these context. Using log level is not an option in this case

**Comment by jsumners** [comment]
I am unable to follow this question. Please provide an example.

**Comment by rubiin** [comment]
```
{"level":30,"time":1686581134251,"pid":6020,"hostname":"alex","context":"hello"}
{"level":30,"time":1686581134252,"pid":6020,"hostname":"alex","context":"world"}
{"level":30,"time":1686581134252,"pid":6020,"hostname":"alex","context":"hello"}
{"level":30,"time":1686581134252,"pid":6020,"hostname":"alex","context":"world"}

```
I want to disable the logs for contexts `world`.

**Comment by mcollina** [comment]
Use child loggers and set a high log level for them.

Alternative, write a transport that filters the logs.
