### ISSUE TITLE
Integration with restify-errors

### ISSUE THREAD

**Issue by nodo** [pinojs/pino#175]
Hi all,

I have an issue in using `pino` and `restify-errors` (https://github.com/restify/errors).

I assumed that when pino see an error object with a stack, it automatically log the stack.

For instance:
```
> var pino = require('pino');
> var log = pino();
> log.info(new Error());
{"pid":70521,"hostname":"mll1p05607.local","level":30,"time":1484658304444,"msg":"","type":"Error","stack":"Error\n    at repl:1:10\n    at sigintHandlersWrap (vm.js:22:35)\n    at sigintHandlersWrap (vm.js:96:12)\n    at ContextifyScript.Script.runInThisContext (vm.js:21:12)\n    at REPLServer.defaultEval (repl.js:313:29)\n    at bound (domain.js:280:14)\n    at REPLServer.runBound [as eval] (domain.js:293:12)\n    at REPLServer.<anonymous> (repl.js:513:10)\n    at emitOne (events.js:101:20)\n    at REPLServer.emit (events.js:188:7)","v":1}
```

However, when using `restify-errors` the stacktrace is ignored.
```
> var e = require('restify-errors');
> log.info(new e.InternalServerError())
{"pid":70521,"hostname":"mll1p05607.local","level":30,"time":1484658353255,"res":{"statusCode":500},"v":1}
```

Note that both errors have a stacktrace:
```
> new Error().stack
'Error\n    at repl:1:1\n    at sigintHandlersWrap (vm.js:22:35)\n    at sigintHandlersWrap (vm.js:96:12)\n    at ContextifyScript.Script.runInThisContext (vm.js:21:12)\n    at REPLServer.defaultEval (repl.js:313:29)\n    at bound (domain.js:280:14)\n    at REPLServer.runBound [as eval] (domain.js:293:12)\n    at REPLServer.<anonymous> (repl.js:513:10)\n    at emitOne (events.js:101:20)\n    at REPLServer.emit (events.js:188:7)'
> new e.InternalServerError().stack
'InternalServerError\n    at repl:1:1\n    at sigintHandlersWrap (vm.js:22:35)\n    at sigintHandlersWrap (vm.js:96:12)\n    at ContextifyScript.Script.runInThisContext (vm.js:21:12)\n    at REPLServer.defaultEval (repl.js:313:29)\n    at bound (domain.js:280:14)\n    at REPLServer.runBound [as eval] (domain.js:293:12)\n    at REPLServer.<anonymous> (repl.js:513:10)\n    at emitOne (events.js:101:20)\n    at REPLServer.emit (events.js:188:7)'
```

System specs:
```
pino 3.1.1
restify-errors 4.3.0
node 6.9.2
```

Am I doing something wrong?

Andrea

**Comment by jsumners** [comment]
The issue is that `restify-errors` isn't returning a direct descendent of `Error` -- https://github.com/restify/errors#checking-error-types

You'll have to supply an error serializer that takes this into account.

**Comment by nodo** [comment]
Thanks @jsumners , please can you point me the part of `pino` where this is checked?

As far as I understood the problem is here: https://github.com/pinojs/pino/blob/master/pino.js#L406

Since `new e.InternalServerError().statusCode` is true, `mapHttpResponse` is called and the stacktrace is filtered. I would suggest to change this logic, if possible.

**Comment by nodo** [comment]
Also, this seems related https://github.com/pinojs/express-pino-logger/issues/7

**Comment by jsumners** [comment]
Hmm, maybe I'm wrong and that Pino _should_ be serializing these errors without any extra work -- https://github.com/restify/errors#bunyan-support

**Comment by mcollina** [comment]
> Since new e.InternalServerError().statusCode is true, mapHttpResponse is called and the stacktrace is filtered. Do you know the reason for this? I would suggest to change this logic, if possible as it removes potentially useful data.

Go ahead and refactor https://github.com/pinojs/pino/blob/master/pino.js#L405. Add a unit test. A good way to check is checking if out is an `OutgoingMessage` via `instanceof`. However, `instanceof` is not fast, hence we should check the benchmarks. How about we check for `setHeader` instead?

> Hmm, maybe I'm wrong and that Pino should be serializing these errors without any extra work -- https://github.com/restify/errors#bunyan-support

@jsumners I do not think so. `restify-errors` is not restify.

**Comment by nodo** [comment]
Thanks @mcollina, I'd be happy to do it. Surely, the most readable would be to check with `instanceof`, but also `setHeader` seems reasonable for me. I will keep you updated.
