### ISSUE TITLE
redact mutates input

### ISSUE THREAD

**Issue by morriq** [pinojs/pino#1752]
Hello, 

I prepared https://stackblitz.com/edit/stackblitz-starters-or5hfr?file=index.js

with two routes
/mutable
/nomutable

/mutable catch error from got, use pino to log and the same error is returned to client. You can see `authorization":"[Redacted]"` there.

/nomutable uses simple object, use pino and after return this object to the client. no mutation appeared.

is it bug or the feature? can somebody explain why pino mutates got error?

**Comment by jsumners** [comment]
#1745
