### ISSUE TITLE
Pino handles the "error" object strangely. I can't access error.type.

### ISSUE THREAD

**Issue by GeorgiiGalechyan** [pinojs/pino#1758]
Hello. Faced a small problem while writing a backend on fastify + postgres. I have a user registration function on a website that under the hood contributes data to Postgres. I am now optimizing error handling and ran into a problem. I want to get data from object "err".

I tried to solve the problem on [stackoverflow](https://stackoverflow.com/questions/76793261/strange-behavior-of-js-object-cant-get-a-value-from-a-key?noredirect=1#comment135382378_76793261), they wrote there that the problem is most likely in Pino or Fastify. I don't want to duplicate the question completely, I will describe the problem briefly. The full problem can be viewed on stackoverflow.

The point is that the error object, among other things, contains a key-value pair "type": 'DatabaseError". Then i use

```javascript
try {
  // any logic
} catch (err){
  app.log.error(error)
}
```
then I get an err object with all the fields at the output.

When I try to access the fields individually, Pino ignores the `type` field as if it doesn't exist.
```
try {

  // database transaction logic

} catch (err) {
  app.log.error({
    msg: `Error adding user '${login}' to table 'users'`,
    'Error code': err.code,
    'Error type': err.type,
    'Message': err.message,
    'Detail': err.detail,
    'DB table': err.table,
    'DB constraint': err.constraint,
    'Stack': err.stack,
  })
}
```

Screenshots of the err object ignoring the type field can be viewed on stackoverflow.

**Comment by GeorgiiGalechyan** [comment]
app.log.error({msg: `${err.type}`}) outputs to the terminal [undefined](https://prnt.sc/G2UMFiFHNZhb)

**Comment by GeorgiiGalechyan** [comment]
That's not all. If we call the following commands, we get an interesting result.

```
try {

  // database transaction logic

} catch (err) {
  app.log.error(err) // will output an 'err' object with a 'type' field
  app.log.error({ err: err }) // will output an 'err' object with a 'type' field
  app.log.error({ error: err }) // prints the 'err' object without the fields 'type ', 'message' and 'stack'
}
```

Screenshots: [app.log.error(err)](https://prnt.sc/RoSwFBWsQftw), [app.log.error({ err: err })](https://prnt.sc/2kJvGxPKzpSb), [app.log.error({ error: err })](https://prnt.sc/5Rm-ai7WiJHd).

**Comment by GeorgiiGalechyan** [comment]
https://github.com/fastify/fastify/issues/4937 - There was a more correct code example here.

**Comment by climba03003** [comment]
> app.log.error(err) // will output an 'err' object with a 'type' field

When `Error` is passed directly, it check by 
https://github.com/pinojs/pino-std-serializers/blob/632babcc82c3afec0187920977d9960492ab5314/lib/err.js#L12-L14
The `Error`, then parsed without modification.

> app.log.error({ err: err }) // will output an 'err' object with a 'type' field

When `Error` is passed with `err` attribute, it check by
https://github.com/pinojs/pino/blob/6eac50dcece59cb11ef5ff555542eba2064e4e1a/lib/tools.js
The `Error`, then parsed without modification.

Note that the default `errorKey` is defined in 
https://github.com/pinojs/pino/blob/6eac50dcece59cb11ef5ff555542eba2064e4e1a/pino.js#L54

> app.log.error({ error: err }) // prints the 'err' object without the fields 'type ', 'message' and 'stack'

When `Error` is passed with other attributes, it just slap through.
So, it no longer handle by the error serializer.
We all knows that all the default property from `Error` is not enumerable that is why the default property will never shown.

**Comment by GeorgiiGalechyan** [comment]
Hello, thanks for the clarification. I'm still wondering how to write code to get the value from the 'type' field of the 'err' object?

Let's experiment.
Let's disable logging and take Pino out of the equation. Let's also change `app.log.error()` to `console.log()`.

```javascript
try {

  // Postgres transact logic

} catch (err) {

  console.log(err)
  console.log(err.type)

}
```

In the terminal we get:

```
// console.log(err)
error: duplicate key value violates unique constraint "users_login_key"
    at C:\Users\galec\dev\lottery\backend-lottery\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/galec/dev/lottery/backend-lottery/src/routes/register.js:46:13 {
  length: 196,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (login)=(test) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'users',
  column: undefined,
  dataType: undefined,
  constraint: 'users_login_key',
  file: 'nbtinsert.c',
  line: '649',
  routine: '_bt_check_unique'
}

undefined // console.log(err.type)
```

So we conclude that the `err: { "type": "DatabaseError" }` field comes from Pino. Or could it be that Pino sees that the error is caused by @fastify/postgres and assigns `"type": "DatabaseError"}` to the error?

The main question is how to access `"type": "DatabaseError"`?
Or please advise me on a more correct approach to customizing logging errors. I am self-taught, so I don't understand many concepts. Please be understanding.

**Comment by Eomm** [comment]
it comes from pino

https://stackoverflow.com/a/76797207/3309466

**Comment by GeorgiiGalechyan** [comment]
Thank you all. It's nice when the community helps newbies understand the technology. I think I can take it from here.
