### ISSUE TITLE
asJson() method doesn't return a valid JSON if mergingObject key contains a double quote

### ISSUE THREAD

**Issue by OlenaHryshko** [pinojs/pino#1767]
In case key(s) of the mergingObject contains `"` symbol, it is not getting shielded. So, logged object is not a valid JSON string.

See code example:
```
const pino = require('pino');
const logger = pino();

logger.info({'some"prop': {'details': true}});
```
This will result in the log below:
`{"level":30,"time":1690897379299,"pid":41644,"hostname":"your-hostname","some"prop":{"details":true}}`

I'm using newrelic to collect logs and it relies on asJson() method. Due to an invalid JSON is returned, JSON.parse throws an error.
Please see details here https://github.com/newrelic/node-newrelic/issues/1744.

Please confirm whether this is an expected log format or it should be fixed. 
From methods name `asJson()` I'd expect it to return a valid JSON string.

**Comment by mcollina** [comment]
Looks like a bug that needs fixing! Good spot!

**Comment by OlenaHryshko** [comment]
Hi @mcollina 
Thanks for the confirmation. What are further actions on this issue? Will it be fixed by pino team?

**Comment by jsumners** [comment]
Given that none of the maintainers have ever encountered this issue, it's unlikely to be on our priority list. We would be eager to review any PR that solves it, though.

**Comment by tzviki** [comment]
I create [this](https://github.com/pinojs/pino/pull/1779) pull request.
I fully understand if this should be changed as a feature, or option with override stringifier for keys. Happy to discuss further!

**Comment by tzviki** [comment]
I added the issue now (updated my comment on pr) since I relized this issue can probably be closed. Sorry didn't initially include it
