### ISSUE TITLE
bundling question

### ISSUE THREAD

**Issue by wcaneira** [pinojs/pino#1770]
Thank you for maintaining `pino`.

Newbie question for you please: I bundled `pino` into a backend project with `esbuild` and forgot to include the additional files suggested [in the documentation](https://github.com/pinojs/pino/blob/master/docs/bundling.md).  In past projects I've done this with `esbuild-plugin-pino`.

To my surprise, `pino` seems to be "working" (logging as expected) without the additional file support.

Can you clarify for me what this means?  In my case, does `pino` "work" in a degraded mode NOT using worker threads?  

I'm happy to add `esbuild-plugin-pino` into my project if necessary, I'm just surprised by the result, and curious what functionality suffers without these files.

**Comment by mcollina** [comment]
Are you using any transports?

**Comment by wcaneira** [comment]
No, not using any transports.  Just using the default behavior to log to console/STDOUT

**Comment by mcollina** [comment]
Then it's not using any worker_threads.
