### ISSUE TITLE
When having single transport in pipelining the worker exit in the middle

### ISSUE THREAD

**Issue by rluvaton** [pinojs/pino#1774]
I know pipelining is intended to have multiple transports but in our tests, we sometimes don't have transport and only have our transformer as a transport.

## Reproduction:

Given this code:
```js
const pino = require("pino");
const { setTimeout } = require("timers/promises");

const log = pino({
  level: "info",
  transport: {
    pipeline: [
      {
        target: "./empty",
      },
    ],
  },
});

async function run() {
  while (true) {
    log.info("Hello World!");
    await setTimeout(1);
  }
}

run();
```

and this transport :
```js
// empty.js
const build = require("pino-abstract-transport");

module.exports = {
    default: async () =>
        build(async function* (source) {
                for await (const logEntry of source) {
                    yield ''
                }
            },
            {
                // This is needed to be able to pipeline transports.
                enablePipelining: false,
            }),
};
```

I get:
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: the worker has exited
    at ThreadStream.write (~/dev/tmp/pino-bug/node_modules/thread-stream/index.js:229:19)
    at Pino.write (~/dev/tmp/pino-bug/node_modules/pino/lib/proto.js:217:10)
    at Pino.LOG [as info] (~/dev/tmp/pino-bug/node_modules/pino/lib/tools.js:71:21)
    at run (~/dev/tmp/pino-bug/index.js:20:9)
Emitted 'error' event on ThreadStream instance at:
    at Immediate.<anonymous> (~/dev/tmp/pino-bug/node_modules/thread-stream/index.js:360:12)
    at process.processImmediate (node:internal/timers:476:21)

Node.js v18.16.0
```

The workaround is to add another proxy transport...

**Comment by mcollina** [comment]
Why are you using a transport in tests to do nothing? You can just set the log level extremely high and nothing will be logged.

**Comment by rluvaton** [comment]
I think it should either warn about this or drop the data, Why does it work with 2 targets that are the same?

**Comment by rluvaton** [comment]
Even when we don't `yield` anything this has the same result...

**Comment by mcollina** [comment]
I think a better error message for this. Using pipelining must require at least 2 streams. Take a look at this https://github.com/pinojs/pino/blob/1aacfd25646923902b556a73182c82e8aa68d7db/lib/worker-pipeline.js#L28: the `pipeline` function would be called with only one stream, erroring.

Would you like to send a PR?

**Comment by rluvaton** [comment]
Should it log/throw error if the only stream is writable (or don't emit data to the next)?

**Comment by mcollina** [comment]
Yes it should throw an error in this case

**Comment by rluvaton** [comment]
wouldn't this be a breaking change?

**Comment by mcollina** [comment]
It does not seem the code is working at all right now, what will it break?
What we need is a better error message for this situation.

**Comment by rluvaton** [comment]
I'll create a PR now

**Comment by rluvaton** [comment]
I just checked and this **will** be a breaking change when the transport consumes the data:

Example:
```js
const pino = require('pino');
const fs = require('fs');
fs.writeFileSync('./to-file-transport.js', `
'use strict'

const fs = require('fs')
const { once } = require('events')

async function run (opts) {
  if (!opts.destination) throw new Error('kaboom')
  const stream = fs.createWriteStream(opts.destination)
  await once(stream, 'open')
  return stream
}

module.exports = run
`);

let outputPath = './file-output.js'
fs.writeFileSync(ouputPath, '')

const transport = pino.transport({
  pipeline: [{
    target: './to-file-transport.js',
    options: { destination: outputPath }
  }]
})
const instance = pino(transport)

setInterval(() => {
  const output = (fs.readFileSync(outputPath)).toString();
  console.log(output)
}, 1000);

async function run() {
  while(true) {
    instance.info({ hello: 'world' }, 'hello')
    await new Promise(resolve => setTimeout(resolve, 1))
  }
}
run();
```

**Comment by mcollina** [comment]
Sure, but this transport results in a `Writable`, not in a `Duplex` https://github.com/pinojs/pino-abstract-transport/blob/b6d7973a80b115b9bad3098efb669279ff9667c9/index.js#L69-L7. If the last stream is a readable, the pipeline will not flow, likely causing a crash somewhere. I think just intercepting that the last stream is a Readable and throwing a nice-to-understand error is fine. 

The question is finding out exactly why the worker is crashing and then intercepting this condition early.

**Comment by rluvaton** [comment]
and it will break `pino-pretty` as it returns a Transform:

(use this with the PR and see it's failing)
```js
const pino = require("pino");
const { setTimeout } = require("timers/promises");

const log = pino({
  level: "info",
  transport: {
    pipeline: [
      {
        target: "pino-pretty",
        options: { destination: 1 } // use 2 for stderr
      },
    ],
  },
});

async function run() {
  let i = 0;
  while (true) {
    log.info(`Hello World! ${i++}`);
    await setTimeout(1);
  }
}

run();
```

**Comment by mcollina** [comment]
I don't understand then why your example at the top fails while pino-pretty does not have this problem.

**Comment by rluvaton** [comment]
that's the question, yesterday I debugged it for hours and maybe it's related to the fact the `needDrain` is true

and `drain` is never called (I checked by adding an interval to keep the process alive and it never called)

**Comment by rluvaton** [comment]
Fixed by emitting a warning in thread-stream
