### ISSUE TITLE
Issue with Nullish Coalescing Operator (??) on Chrome 79 and below

### ISSUE THREAD

**Issue by hchangjae** [pinojs/pino#1775]
Hello `pino` maintainers,

I've come across an issue while using the `pino` library in an environment running Chrome version 79 and below [[can i use]](https://caniuse.com/mdn-javascript_operators_nullish_coalescing) It appears that the Nullish Coalescing Operator (`??`) used in the library isn't recognized by these older versions of Chrome, leading to a `SyntaxError: Unexpected token '?'`.

Given the widespread usage of Chrome and potential for projects to require support for older versions, it might be worth considering either:
- A transpilation step for backwards compatibility
- Adding a note in the documentation regarding the minimum supported browser versions.

### Steps to reproduce:
1. Use `pino` library in a project with browser options. `pino({ browser: { ... } })`
2. Run the project in Chrome 79 or an older version.
3. Observe the `SyntaxError`.
  
I also tested this on Android Chrome version 78.0.3904 and observed the same issue.
  
Thank you for your work on this library, and I appreciate your attention to this matter.

<img width="1012" alt="image" src="https://github.com/pinojs/pino/assets/52942171/7ccc0c4f-a02b-4359-91bd-90dcff6a131e">

**Comment by mcollina** [comment]
I don't think we have the bandwidth to do either. I think the only solution for your problem is to remove `??`.. and a PR would be highly appreciated.

**Comment by jsumners** [comment]
Chrome 79 was released in 2019 (https://cloud.google.com/blog/products/chrome-enterprise/admin-insider-whats-new-in-chrome-enterprise-release-79). Chrome's LTS version is at 96 at the time of this post (https://chromereleases.googleblog.com/2022/02/long-term-support-channel-update.html?m=1). I do not see any reason we should try and support such an old release as 79.

**Comment by hchangjae** [comment]
Next.js supports Chrome 64+. Given that pino is recommended by Next.js, it would be beneficial for pino to also support this version. This ensures a consistent experience for developers using both tools.
