### ISSUE TITLE
TypeScript interface LogFn bugged (e.g. logger.info, logger.debug, etc.)

### ISSUE THREAD

**Issue by Zamiell** [pinojs/pino#1782]
The normal usage for Pino is to use one argument, like this:

```ts
logger.info("foo"); // "foo" is logged.
```

If you try to use 2 arguments, Pino will use the second argument as a string interpolation argument. However, Pino will silently drop the second argument it if you don't have any `%` signs in your first argument:

```ts
logger.info("foo", "bar"); // "foo" is logged, but "bar" is dropped.
```

[The TypeScript definitions for Pino](https://github.com/pinojs/pino/blob/master/pino.d.ts) are therefore bugged, as the TypeScript compiler does not throw an error when you supply a second argument.

In order to fix this problem, I believe that the type definitions for the function need to be more specific.

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=logger

**Comment by Zamiell** [comment]
Ok, I spent a few hours on this and I think I have a pretty good fix for the bug:

https://www.typescriptlang.org/play?#code/PTAEBUAsEsGdTqALpApqAbgQwHbQDb5agAK0OA9qAAYAyFA5gGI7WgAmqAZudEtBRwAuAFDAAVCPJJUAJy5YAxunrMcoAN4jQO0AB5woVAA8ZOdvAoAjAFapFSAHwAKazaEQANKAC2sBgD8HrBIsuQM3gB00ViyDLAeuACeANoAugCUHhgU0OwA3Nq6rrYeAK44ANaUAO443n6BwaHhUTFxCaDJ6VmYuQVFOs6NzWE4EaDRkbHxiTipmdn9hQC+IuLAImJgUIiIPkkIPgAOshQYqOyk5FSqLBzcvPyCotJyCsqgd+pauvoAsv4jKZUOZ4CExgwXCNQICJlMIeEAJI4GSyY4UIjPHAAQQ6HgAoqZZEokHj4no4Y5ejk8oU-gZgWYLKA3PYkN44UzQSzEeMXG4POAGv4PHC2pE+QwUWiMViBLj8aAiaFSeTYJT-NSlnTBvpDCZmfAcGUfFY5KAAD6gKwUTGoXBW0CwJJmzEuGZCmnLERrMTiSSgcQQNCYLD4PLOlrjBCouRyrDY0DHIjKSCYziyeCxdDsCiKU2gmRXNCyVCiIOgSBIJDHBIgBioWs3SICYAAYmAecUsGAWGO0ACeQAvPhGI3ZNoNlI4-IlOgAMrR6WzhPY2hNtHgCjgJLHdC-XSdKX03TsDwms1yU86CgeNkOG+gADy99s7Kf7lZ78fvq2SD3dAVRJBx1UZQ0eXBZdHFAYcIG5MEaAAEg0KUVgAUhQ8guAtAAlFZqD1AJQFwhCWWoLCcBw2RQBxFZKOo0AACECL1P5iJxMj4EqVAkgoLhQCXSEZXjTFEwVDcazkbdd33Ni-l0YiUiE5FVzE9dN2kndAJSHE0glYC1Q6PQmMcNJ5IU0BCWJIyKVMiyrOVGzQOM3DHD1Dx0n-QDQAAOQoJAVPGZ9ZGfH8kAMGC4INEFEKlUBiJwVALhooUuO-OwHAS0AkpSxzwEKbZQAAWlKsryoqyqquqmrarq+qGsapqtk4RQiDLUBFEEEJYy4O8vkYFhCpAErmpGgBGWi4kLVEIFQEJYCKpriq2EaAHUKFkSpYEiGc+ucAAicB5v4GNiCsLBYGgRQo0hUAxwYXx5tgLBG0iA6MkKbCKGccaACYAGZPr2n7QjKVBge+5wF1dW18EOvqKA+4GlrGsA-qmhgZqQOaFtRxrVrADatsWqGDv+Z7XvQGo+EgLp1DedF1IVMN8HBjx0NgA7vAOxGPq+qifvJynG1AGmUHp2NZWZwRWfZ0B0PYbnQH+oGBf24XYBe0Xxbpx1GbXFnsDZ8sFaR7wNBWFGRqYLACHgc1FCwMpYHQFA5HQOAcAAchx2AymODFXauJAqHNLpnXsQQrhmbHdrJimtapsXaZyqgDZl9RjfB96eb562wFt+2bXsZ3XbF9A+riALkFDV2uvMLppp8IsjFRaAy3wJJ48Fw7E+16nU-1tT5Vl7PTc5-mQb7kXB4l4fpdHrPw3lxWp4T2eU-nhmR-EseV4npGC9AIv8Ad0uXep9BjjKHH3bFs4YwA-cunge-6+jpusZb1Ee41-vk660lhnJecsJ5c28KrSGvdNYDy3nrHei897LxNhzJWec7TrxgQAnWQ9EGiVAePDm5tQC80wcfZaRUAaY2xrjJAi0RqUKKsTba09YGANTkgGo6dd5JnHp0TmCsIGkL5jzC6sgsH-03kArhPCkF8IPgIq4a9IGA28AAFgAKwADZoFSKTrgiWsipYEOQWAgRVB0IkMthbK2w1C52zPiXJ2l8K6gCrgwGu98UAdxjs3VuRYO6oC7n-IWOC5502MSAsx-CObwEnhgo+6swnSM4dwkxTNCGKLQQrdBKtAZ6JSQYiJyB0nRIUSbCxZtlaW2Piw0m2DUlGLKbwo2ijWQCXYNALg1FW7P3mnE3JysyEkKgckmexT4GlLkaYip4NLCdO6b02a-SlHVNUQDWxx9T7nxceXGo19b612po-R6-TX7HNrr4r+cc2HhKmVE1p+9KkdI4Esj2KzAICPiXkkZwzxGSKKXAmRLT5FtJefxN5PSPl3y+TkqxytVYaJ0cDIAA

Thanks to -n- and Burrito in the TypeScript Discord for helping me create this.

**Comment by Zamiell** [comment]
I just updated the playground to account for functions being passed, which should be disallowed now.

I can submit a PR if needed.

**Comment by mcollina** [comment]
Send it over, thanks!
