### ISSUE TITLE
Using a transport to transform logs and then write to a custom stream

### ISSUE THREAD

**Issue by justindeocampodd** [pinojs/pino#1786]
Hello,

I am currently trying to change Pino's base logging structure using a custom [transport pipeline](https://github.com/pinojs/pino/blob/master/docs/transports.md#creating-a-transport-pipeline) but I am having some trouble piping the log data to a custom stream if one is provided when I initialize the logger. 

Here is what my transport pipeline looks like:

```
const exampleTransformer = async (options: any): Promise<Transform> => {
  return build(
    function (source: any) {
      const transportStream = new Transform({
        autoDestroy: true,
        objectMode: true,
        transform(chunk: any, enc: BufferEncoding, cb: TransformCallback) {
          const logObj = transformLogObject(chunk) // this is just a function that removes some properties of the logs
          this.push(`${JSON.stringify(logObj)}\n`)
          cb()
        }
      })
      console.log(options)

     // THIS IS WHERE IM CONFUSED
      if (options && options.customStream) {
        pipeline(source, transportStream, options.customStream, () => {});
      } else {
        console.log("DEFAULT STREAM")
        pipeline(source, transportStream, () => {});
      }
      return transportStream
    },
    {
      // This is needed to be able to pipeline transports.
      enablePipelining: true
    }
  )
}
export = exampleTransformer
```

When I initialize my logger I am using this as my transport pipeline

```
transport: {
        pipeline: [
          {
            target: './example-transformer.js',
            options: {
              customStream: stream // this is the custom stream that I am trying to pass into my transport pipeline
            }
          },
          {
            target: 'pino/file'
          }]
      },
```

The problem is the transport pipeline is only seeing the custom stream that I am passing in as `undefined`. I believe that the issue is that Pino uses a worker thread to asynchronously do the transport work which means that the custom stream I am passing in when initializing the logger isn't guaranteed to exist when getting passed into it. 

My questions are:
1. Is it possible to use transport pipelines to write to a custom stream that I pass in when initializing the logger?
2. Is it possible to unit test the output of what happens after a transport pipeline? I'm finding it difficult because of the inability to write to a custom stream and the asynchronous nature of transport pipelines
3. What is the best practice for reshaping the Pino logs with full customization (e.g. removing the 'msg' variable and being able to nest it inside of some other property in the logger). I feel like transports gave me full customization over how I want the log to look, but it gives severe limitations in where I can write the output to, making it difficult to test

Thanks for the help!

**Comment by justindeocampodd** [comment]
> Write a unit test for your transport directly. There are a few examples on how to deal with this inside this repo, however this is mostly not needed: any bug in that logic should be done here.

Ahh ok this makes sense. I couldn't find the examples but I know what you mean.

> Use transports. Note that you can code your transform so that it is just a node stream, (see pino-pretty), so that `pino(buildYourTransport())` is possible, allowing for your testing.

Do you think you could explain this a bit more? Not sure I'm understanding what is meant by `pino(buildYourTransport())`. Not seeing how this gets around the issue of being able to write to a stream that is passed in on initialization. I know you said in the first answer that bc transports are run in a worker thread its not possible, but this seems like a huge limitation of transports doesn't it? Essentially what you're saying is if I use a transport I have to write to std.out?
```
const opts: pino.LoggerOptions = {
   transport: {
        pipeline: [
          {
            target: './unified-transformer.js'
          },
          {
            target: 'pino/file'
          }
        ]
      },
}

```
This is currently what my transport pipeline looks like. From the docs it seems `pino/file` writes to std.out by default, and you can pass in a destination as an option, but the destination is just a path to a file and not a custom stream like I'd like to do.

**Comment by mcollina** [comment]
> This is currently what my transport pipeline looks like. From the docs it seems pino/file writes to std.out by default, and you can pass in a destination as an option, but the destination is just a path to a file and not a custom stream like I'd like to do.

Due to JavaScript limitations, you cannot pass a custom stream: functions cannot pass through threads, only serializable objects. I already said this in https://github.com/pinojs/pino/issues/1786#issuecomment-1680874642.

You'll have to construct your custom stream as a transform itself:

```tws
const opts: pino.LoggerOptions = {
   transport: {
        pipeline: [
          {
            target: './example-transformer.js'
          },
          {
            target: './example-destination.js',
            options: { ... }
          }
        ]
      },
}
```

> Essentially what you're saying is if I use a transport I have to write to std.out?

No, you can write wherever you want or need, there are plenty of transports available.

> Do you think you could explain this a bit more? Not sure I'm understanding what is meant by pino(buildYourTransport()).

You want to have implement this same API https://github.com/pinojs/pino-pretty/blob/fa386a964cce7d7c5cbeb4ce5bb8d28785001acd/test/basic.test.js#L1013-L1038, which you do by using the pino-abstract-transport (which you already seem to be using).
Take a look at https://github.com/pinojs/pino-pretty/blob/fa386a964cce7d7c5cbeb4ce5bb8d28785001acd/index.js#L212-L246 as well.

**Comment by justindeocampodd** [comment]
> Due to JavaScript limitations, you cannot pass a custom stream: functions cannot pass through threads, only serializable objects. I already said this in [#1786 (comment)](https://github.com/pinojs/pino/issues/1786#issuecomment-1680874642).
> 
> You'll have to construct your custom stream as a transform itself:
> 
> ```
> const opts: pino.LoggerOptions = {
>    transport: {
>         pipeline: [
>           {
>             target: './example-transformer.js'
>           },
>           {
>             target: './example-destination.js',
>             options: { ... }
>           }
>         ]
>       },
> }
> ```

How does adding another transport fix the issue of passing in the custom stream to the pipeline? Not sure what we should be passing in as an option to the example-destination.js if it only takes serializable objects

**Comment by mcollina** [comment]
I'm currently on vacation for the next two weeks. Responding to your question would require me to write an example and publish it. I don't have more textual explanation to give compared to what I have already written. The answer and examples already shows most of it, it's just a matter of putting things together.

**Comment by justindeocampodd** [comment]
Ah okay, feel free to respond to this when you're back.  I believe I finally understood what you meant. So I just pass in a serialized object to the destination pipeline and then reconstruct that stream from within the transport. 
```
transport: {
        pipeline: [
          ...
          {
            target: './destination-transport.js',
            options: {
              destination: {write: customstream?.write}
            }
          }
        ]
      },
```
```
const destinationTransport = async (opts: DestinationTransportOpts = {}): Promise<Transform> => {
  return build(
    function (source: Transform) {
      const transportStream = new Transform({
        autoDestroy: true,
        objectMode: true,
        transform(chunk: any, enc: BufferEncoding, cb: TransformCallback) {
          this.push(JSON.stringify(chunk) + '\n')
          cb()
        }
      })

      let destination: Writable
      // If the transport receives a destination opt (which must be serialized as an object),
      // we want to wrap it in a Writable stream and use that in our pipeline, otherwise pipe to stdout
      if (typeof opts.destination === 'object' && typeof opts.destination.write === 'function') {
        destination = new Writable({
          autoDestroy: true,
          objectMode: true,
          write(chunk: any, enc: BufferEncoding, callback: TransformCallback) {
            opts.destination!.write(chunk.toString())
            callback()
          }
        })
      } else {
        destination = process.stdout
      }

      pipeline(source, transportStream, destination, (err: Error | null): void => {
        if (err) {
          console.error('Destination Pipeline Error:', err)
        }
      })
      return transportStream
    },
    {
      // This is needed to be able to pipeline transports.
      enablePipelining: true
    }
  )
}
```
So I basically take the custom stream from when the logger is initialized, and then wrap it in a `Writable` stream to be passed to the pipeline?

**Comment by mcollina** [comment]
Let's go throught it one more time: 

> The transport are run in a separate thread, and functions cannot be transferred.

So, doing

```js
transport: {
        pipeline: [
          ...
          {
            target: './destination-transport.js',
            options: {
              destination: {write: customstream?.write}
            }
          }
        ]
      },
```

is fundamentally incorrect and can lead to all sort of problems.

Do this instead:

```js


const destinationTransport = async (opts: DestinationTransportOpts = {}): Promise<Transform> => {
  function write () {
    // this implements write...
  }

  return build(
    function (source: Transform) {
      const transportStream = new Transform({
        autoDestroy: true,
        objectMode: true,
        transform(chunk: any, enc: BufferEncoding, cb: TransformCallback) {
          this.push(JSON.stringify(chunk) + '\n')
          cb()
        }
      })

      let destination: Writable

        destination = new Writable({
          autoDestroy: true,
          objectMode: true,
          write(chunk: any, enc: BufferEncoding, callback: TransformCallback) {
            write(chunk.toString())
            callback()
          }
      } else {
        destination = process.stdout
      }

      pipeline(source, transportStream, destination, (err: Error | null): void => {
        if (err) {
          console.error('Destination Pipeline Error:', err)
        }
      })
      return transportStream
    },
    {
      // This is needed to be able to pipeline transports.
      enablePipelining: true
    }
  )
}
```

**Comment by justindeocampodd** [comment]
Oh, that seems to be what I put above, minus the 'if' statement? Not sure if you intended to replace that with something else or if I had it correctly

**Comment by mcollina** [comment]
The difference is that it implements the `write` function inside the worker thread and not in the main thread, because

> The transport are run in a separate thread, and functions cannot be transferred.

**Comment by justindeocampodd** [comment]
So is anything getting passed in as opts to the transport? If we are implementing the 'write' inside the transport itself then how do we ensure that we are writing to the stream that is getting initialized as an option in the logger? It seems like your code removed the 'if' statement I had that dealt with that case

**Comment by justindeocampodd** [comment]
Thank you for writing it out, but I don't believe that really solves what I was asking for. How can we implement the "write" function inside the worker thread if the worker thread has no idea what to write to?

https://github.com/pinojs/pino-pretty/blob/fa386a964cce7d7c5cbeb4ce5bb8d28785001acd/index.js#L212-L246

I'm currently looking at this code from pino-pretty where they either take in a destination or it will write to standard out (essentially what I'm trying to do). But how does line 226 work? It is essentially saying you can pass in an object that looks like 
`destination = { write: some_custom_function} ` and it pipe the data to that destination. But you are saying otherwise, that we cannot transfer the write function to the worker thread. A little bit of confusion there

**Comment by mcollina** [comment]
> Thank you for writing it out, but I don't believe that really solves what I was asking for. How can we implement the "write" function inside the worker thread if the worker thread has no idea what to write to?

You pass the path you want to write to as an option. 

> I'm currently looking at this code from pino-pretty where they either take in a destination or it will write to standard out (essentially what I'm trying to do). But how does line 226 work?

That option only works if passed programmatically and not via the transport system, e.g. if you want to build your own transport that uses pino-pretty.

**Comment by justindeocampodd** [comment]
Oh, so we can really only write to stdout or to a file at a given path? How would we write to a pino.destinationStream is what I'm trying to figure out I suppose

**Comment by mcollina** [comment]
> Oh, so we can really only write to stdout or to a file at a given path? 

You can log to elasticsearch, loki, syslog or just write your own transport. However, you need to initialize those objects/functions within the transport, and not pass functions from outside.

**Comment by justindeocampodd** [comment]
Okay so it seems like based off the example I gave it is not possible to do what I am trying to achieve? 

Assume my logging library is called @logging-library and is built on top of pino.

Basically library A would do something like this
```
import { Logger } from @logging-library

let SOME_CUSTOM_STREAM = xyz

let logger = new Logger.init({some_opts_here}, SOME_CUSTOM_STREAM)
```

In my @logging-library I am receiving the custom stream as a parameter:
```
public init(opts?: LoggingLibraryOpts, stream?: pino.DestinationStream): pino.Logger {
    const mergedOpts: pino.LoggerOptions = {
      transport: {
        pipeline: [
          {
            target: './unified-transformer.js'
          },
          {
            target: './destination-transport.js',
            options: {
              destination: stream ? { write: stream.write } : undefined // <- I know this doesn't work since we can't pass functions to worker threads, but what can we do?? This logger doesn't know where to write to until library A initializes the custom stream
            }
          }
        ]
      },
    this._pino = stream ? pino(mergedOpts, stream) : pino(mergedOpts)

    return this._pino
  }
```
I am trying to have my logging library write to the custom stream but it only knows about what is being passed in from Library A. I hope this clears up my question

**Comment by mcollina** [comment]
As said multiple times above, What you want to achieve is not possible. You cannot move a function across threads.
