### ISSUE TITLE
Type for mixinFn doesn't match docs - mixin doesn't actually get `logger` parameter

### ISSUE THREAD

**Issue by jason-curtis** [pinojs/pino#1787]
The docs for the `mixin` option state that it has 3 arguments: https://getpino.io/#/docs/api?id=mixin-function
```The first parameter is the value mergeObject or an empty object. The second parameter is the log level number. The third parameter is the logger or child logger itself```

However, the type declaration only has two arguments:
https://github.com/pinojs/pino/blob/91a3505cfaef323f565e3cfe93f5d5077320faff/pino.d.ts#L31

Which of these versions of reality is correct?

Here's a screenshot of the resultant type error in VS code:
![image](https://github.com/pinojs/pino/assets/3341011/060f1d1e-3e21-49ea-ae89-3db093cbc00c)

Pino version: 8.15.0

**Comment by mcollina** [comment]
I think the test are the best form of documentation:

https://github.com/pinojs/pino/blob/309cdfbff7ccf4d97b6969b95daec7b6ff9455cf/test/mixin.test.js#L164-L178

Could you check the behavior and make sure docs and types are correct?

**Comment by jason-curtis** [comment]
Just as a heads up, my team has worked around this issue for now and I don't expect to have time to check and update the docs.

**Comment by andreiwow2** [comment]
I encountered the same problem.

```
Type '(obj: any, num: any, logger: any) => { tags: any; }' is not assignable to type 'MixinFn'.
  Target signature provides too few arguments. Expected 3 or more, but got 2.
  ```

**Comment by Downster** [comment]
When can we expect this fix to be released? What would be the best workaround for now?
