### ISSUE TITLE
Release new version to include fast-redact fixes?

### ISSUE THREAD

**Issue by lsanwick** [pinojs/pino#1793]
Based on this [closed issue](https://github.com/pinojs/pino/issues/1708), `fast-redact` 3.2 has fixes to multiple wildcard usage, but the dependency in `pino` has not been updated.  Can you release an updated version pulling that fixed version in?

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/91a3505cfaef323f565e3cfe93f5d5077320faff/package.json#L105

^ that covers it. Reinstall your dependencies.
