### ISSUE TITLE
Is `disabled: true` working as intended? (browser)

### ISSUE THREAD

**Issue by MuktadirHassan** [pinojs/pino#1795]
Hi there! 👋
I was looking through the documentation to implement logging for a react client, and found the `disabled: true` property for disabling logging to console. I assume that, it is supposed to suppress all the default logging that is done via pino internally when logger.info("message") or something like that is called. Please correct me if I am wrong. 

This is the code I am referring to: 
```typescript
const logger = pino({
  browser: {
    disabled: true,
    asObject: true,
  },
});

logger.info("message"); // no output in the console
```

However, when using with `transmit`, it doesn't seems to work and it prints to the console.
```typescript
const logger = pino({
  browser: {
    disabled: true,
    asObject: true,
    transmit: {
      send: (level, logEvent) => {
        // send to logging service
      },
      level: "debug",
    },
  },
});

logger.info("message"); 
/** 
{
    "time": 1693736563301,
    "level": 30,
    "msg": "message"
} 
as output
*/
```
So, I am confused if it's a feature intended or a bug? 

Here is a workaround though, we just need to pass a empty callback function to `write` if we want to disable console.log and also use `transmit`
```typescript
const logger = pino({
  browser: {
    disabled: true,
    asObject: true,
    write: () => {},
    transmit: {
      send: (level, logEvent) => {
        // send log to logging service
      },
      level: "debug",
    },
  },
});
```

Thanks. 🙏

**Comment by mcollina** [comment]
This works as intended.
