### ISSUE TITLE
Regression in Pino browser 8.14.1 > 8.14.2

### ISSUE THREAD

**Issue by koenoe** [pinojs/pino#1816]
When updating from 8.14.1 to 8.14.2 I get the following error when bundling with Webpack + Babel:
![Screenshot 2023-09-28 at 08 43 23](https://github.com/pinojs/pino/assets/35213/a0e5f7f9-e073-4d70-b243-36fa8b891f9d)

Same issue occurs in latest Pino.

Can't see anything in this changelog that could be causing it: https://github.com/pinojs/pino/compare/v8.14.1...v8.14.2
Maybe one of the dependency bumps?

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by koenoe** [comment]
Will do
