### ISSUE TITLE
Pino reliability

### ISSUE THREAD

**Issue by npdev453** [pinojs/pino#1820]
As stated here I can catch any exceptions from the transport (and `ThreadStream.write` as I can see)
https://github.com/pinojs/pino/blob/master/docs/transports.md#error-messages

However, there is no option provided for handling these errors later (```Error: the worker has exited``` for example):
1) Recreate the transport and replace the failed one with it.
2) Completely to re-init pino.

Currently, impossible to reactivate logs without restarting the application (which can be hard in production) or using Proxy object (that can hit performance).

--- 
I would also like to have an option to format gated errors to JSON without sending them to any transport, something like:
```ts
const bar = logger.error.dry({ err: transportError, tag: 'logger:failed' });
// ~ bar = {  ..base, ...defaults, ...mixins,  ...log};
```
This would be useful when pino is broken, for example, for `stderr.wirte` .

**Comment by jsumners** [comment]
> easily runnable without any changes or extra code.

Please follow the instructions in the request. You have provided two independent snippets.

**Comment by mcollina** [comment]
I'm aware of the problem this issue depicts. Essentially we need the main logger to "watch" for the worker thread close event and restart if it fails.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by emmyakin** [comment]
I tried reproducing this using the latest version 9.1.0, and looks like this is fixed.
