### ISSUE TITLE
Memory Leak Pino, Pino Http, & Pino Pretty

### ISSUE THREAD

**Issue by masb0ymas** [pinojs/pino#1823]
I'm getting memory leak issues when running pino target `pino-pretty`, but when I run pino-pretty via command it's fine, with command like this : 
```sh
node ./dist/main.js | pino-pretty
```

(node:33295) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

```js
export const logger = pino({
  level: env.NODE_ENV === 'production' ? 'info' : 'debug',
  // BUG Memory Leak
  transport: { target: 'pino-pretty', options: { colorize: true } },
})
```

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by masb0ymas** [comment]
The case is like this: I have `3 libraries` that use `pino` (with the transport target `pino-pretty`), then the boilerplate I created imports those libraries and the boilerplate also sets the pino configuration (with the transport target `pino-pretty`) this is where the problem lies.

so now my library code is fixed, just import pino without (transport `pino-pretty`), pino-pretty is only used in boilerplate (to `reduce memory leaks`)

**Comment by mcollina** [comment]
Can you create a repository that shows this behavior. None of us has been able to reproduce, there is something that you do in your boilerplate that is causing this.

**Comment by masb0ymas** [comment]
List repository :
- library ( https://github.com/masb0ymas/expresso/commit/4c3cf84f26f369725161f851bb366ce87cff736d )
- boilerplate ( https://github.com/masb0ymas/expresso-typeorm/commit/a4a148ad7c9781cb1405358729057d0ccab205da )

how to improve my code to avoid memory leaks ?
Thanks.

**Comment by mcollina** [comment]
What are the steps to reproduce the problem with the above?

**Comment by masb0ymas** [comment]
The problem occur when i used transform configuration and not use the level configuration like : 

```js
export const logger = pino(
  {
    level: env.NODE_ENV === 'production' ? 'info' : 'debug',
    transport: {
      target: 'pino-pretty',
      options: {
        colorize: true,
      },
    },
  },
  pino.destination(`./logs/pino-${formatDate(new Date())}.log`)
)
```

it's work when : 

```js
export const logger = pino({
  level: env.NODE_ENV === 'production' ? 'info' : 'debug',
  // transport: { target: 'pino-pretty', options: { colorize: true } },
})
```

to pretty console with CLI: 
```sh
node ./dist/main.js | pino-pretty
```

**Comment by mcollina** [comment]
I'm dumb and I don't have much time to figure out your project setup, could you please list it up for me?

1. do x
2. do y
3. kaboom

Thanks

**Comment by masb0ymas** [comment]
1. git clone https://github.com/masb0ymas/expresso-sequelize my-backend
2. cd my-backend
3. pnpm install
4. copy `.env.example` to `.env`
5. adjust .env
```sh
SEQUELIZE_CONNECTION=postgres
SEQUELIZE_HOST=127.0.0.1
SEQUELIZE_PORT=5432
SEQUELIZE_DATABASE=dev_expresso
SEQUELIZE_USERNAME=postgres
SEQUELIZE_PASSWORD=postgres
SEQUELIZE_SYNC=false
SEQUELIZE_LOGGING=true
SEQUELIZE_TIMEZONE=Asia/Jakarta
```
```sh
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=
```

6. yarn build
7. yarn db:reset
8. yarn start


You will see the CLI message
```sh
(node:79345) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```
