### ISSUE TITLE
Cloudwatch expects microseconds

### ISSUE THREAD

**Issue by stephanebruckert** [pinojs/pino#183]
Hi,

As you can see [here](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html) (#`datetime_format`), Cloudwatch [doesn't accept milliseconds](https://forums.aws.amazon.com/thread.jspa?messageID=676107), but only microseconds.

My problem now is that PinoJS generates milliseconds but the API doesn't allow to specify a custom time format. What do you think could be a quick and nice way to add microseconds to the ISO time stamps in PinoJS?

Thanks!

**Comment by mcollina** [comment]
there is the `slowtime` option that will let pino emit data using ISO timestamps https://github.com/pinojs/pino/blob/master/docs/API.md#parameters.

However, I recommend writing a https://github.com/pinojs/pino/blob/master/docs/transports.md that sends things straight to cloudwatch, without passing through the Agent, see #33.

**Comment by stephanebruckert** [comment]
Yes I'm already using `slowtime: true`. Going to have a look at the transports. Thanks

**Comment by jsumners** [comment]
JavaScript doesn't have such a high resolution timer. The finest resolution you can achieve, natively, is milliseconds. It looks like there is a module that will use the system API `gettimeofday` to achieve microsecond resolution. I'm against including any node-gyp dependencies in the core library. So I'd rather see it used on a downstream transport.

**Comment by davidmarkclements** [comment]
we don't need a node-gyp dep - `process.hrtime` gives [seconds, nanoseconds] tuple 

from what I recall we used it in the first place and converted to milliseconds, it's slightly slower the `Date.now()` so we switched. We could add a `hirestime` option...

**Comment by jsumners** [comment]
I was unaware that exists. That being the case, I don't see why another `getTime` function couldn't be added.

**Comment by davidmarkclements** [comment]
Such as:

```js
function getMicrosecondTime() {
   var hrTime = process.hrtime()
   return "time":' + Math.round(hrTime[0] * 1000000 + hrTime[1] / 1000) + '\n'
}
```

However, this would def be slower.. perhaps we should just have an hrtime option

```js
function getHrTime () {
  var hr =  process.hrtime() 
  return ',"time": [' + hr[0] + ',' hr[1] + ']\n'
}
```

and then the cloudwatch transport converts that to microseconds,
and the transport readme says, use the `hrtime` option

**Comment by davidmarkclements** [comment]
ok let's do this: 

1. allow for another option, "hrtime"
2. if hrtime is true use the `getHrTime` function (above)
3. on instantiation, throw if both slowtime and hrtime are true (can't be both)
4. add unit tests for 1-3
5. add benchmarks for hrtime option
6. use benchmarks to determine the performance cost between default time and hrtime - document this in the same way as it's documented for slowtime

@stephanebruckert would you be interesting in making a PR? 

this would then allow us to complete issue #33 using hrtime to determine microseconds

**Comment by stephanebruckert** [comment]
@davidmarkclements I will make a PR yes. I should come back to you by the end of the week

**Comment by stephanebruckert** [comment]
> WARNING: This option carries a 25% performance drop

@davidmarkclements It doesn't look like you currently have anything that benchmarks `slowtime`? Where does the 25% come from?

**Comment by davidmarkclements** [comment]
very early local benching - must not have made it into the benchmarks, we should def. add benchmarks for slowtime, would you be interested in making this part of the PR?

**Comment by davidmarkclements** [comment]
@stephanebruckert see http://npm.im/fast-date for the difference between Date.now() and (new Date).toUTCString())

**Comment by stephanebruckert** [comment]
Thanks for that. Yep the time benchmarks will be part of the PR.

**Comment by davidmarkclements** [comment]
discussion in #202 highly relevant this this - before you put effort into PR we should get a cohesive idea of the bigger pic

**Comment by jsumners** [comment]
@stephanebruckert I have solved #202 and released it as v4.5.0. If you'd like to supply a PR to add this as a standard function, please do.

**Comment by jsumners** [comment]
ping: @stephanebruckert

**Comment by stephanebruckert** [comment]
Ok, this weekend!

**Comment by stephanebruckert** [comment]
I just realised that `hrtime` [gives an arbitrary time](https://stackoverflow.com/a/25027080/1515819) that's not related to the time of day. It seems to me as it won't help achieving what we want. What do you suggest?

**Comment by jsumners** [comment]
@stephanebruckert the docs say:

> The process.hrtime() method returns the current high-resolution real time in a [seconds, nanoseconds] tuple Array....

**Comment by jsumners** [comment]
> These times are relative to an arbitrary time in the past, and not related to the time of day and therefore not subject to clock drift. The primary use is for measuring performance between intervals.

That seems way too narrow of a usage situation to be in core if you ask me.

cc: @jasnell

**Comment by davidmarkclements** [comment]
It seems to me that you have to get hr time at same time as current date, and then calculate the microsecond difference from there

take a look at https://github.com/davidmarkclements/fast-date/blob/master/fallback.js

Notice how we cache the date for each second in the clock by setting a timeout, minus the millisecond difference from that second (already used processing time). 

I'm not necessarily saying use a cache mechanism over every second (it depends on the accuracy needed) but to get an accurate microsecond calculation you're going to have subtract the processing time it took to get the date or/and hr time

**Comment by mcollina** [comment]
You change whatever gets added for time by passing a `timestamp`  option: https://getpino.io/#/docs/api?id=timestamp-boolean-function.

**Comment by willdurand** [comment]
@mcollina ah oops, sorry I missed this option, thanks! 😞

**Comment by davidmarkclements** [comment]
I think this can be closed - we have an option for changing the timestamp format
