### ISSUE TITLE
pino-datadog-transport  return deprecated warning

### ISSUE THREAD

**Issue by insafzakariya** [pinojs/pino#1830]
This is my Code :
`const transports = pino.transport({
    targets: [
      {
        level: logLevel,
        target: 'pino-pretty',
        options: {
          base: {
            loggerName: name
          }
        }
      },
      {
        level: logLevel,
        target: 'pino-datadog-transport',
        options: {
          base: {
            loggerName: name
          },
          ddClientConf: {
            authMethods: {
              apiKeyAuth: process.env.DATADOG_API_KEY
            }
          },
          ddServerConf: {
            site: process.env.DATADOG_SITE
          },
          ddsource: 'nodejs'
        }
      }
    ]
  });
  return pino(options, transports);`

This is response in console:
`setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
setServerVariables is deprecated, please use Configuration.setServerVariables instead.`

**Comment by mcollina** [comment]
The pino-datadog-transport is an independent module and not part of this org. report it there.
