### ISSUE TITLE
Missing msg property

### ISSUE THREAD

**Issue by merojosa** [pinojs/pino#1833]
Hello, Pino team! Thanks for this project, it's pretty awesome.

I had a pretty small problem while I was checking some logs. See the following line of code:

```
logger.info('Info message', 'This a message');
```

My common sense told me that this would have logged both messages somehow. However, when I was debugging an unrelated error, I realized that "This is a message" is skipped. My guess is that it thinks it's an arg:

![2023-10-21 17_36_53 logger.ts - Visual Studio Code](https://github.com/pinojs/pino/assets/38768936/36964067-5375-48dd-a4b0-b9dd8c530081)

It isn't a big deal, but I think it'd be nice if both messages can be printed somehow or if TypeScript tells me that the second argument as string is invalid. Not sure what you think about it.

To be honest, I'm not sure if the second option it's possible, but I'm willing to try and contribute if you agree it's worth it. Let me know what you think, thanks!

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=logger
