### ISSUE TITLE
How to use this with React.JS/Next.JS, preferable with Node HTTP2 server?

### ISSUE THREAD

**Issue by khteh** [pinojs/pino#1836]
Recommended in https://nextjs.org/docs/pages/building-your-application/deploying/production-checklist#logging but I don't see how to use this with React.JS / Next.JS, preferably using Node HTTP2 server?

**Comment by jsumners** [comment]
I believe you should be contacting the writers of the documentation you linked. If you have an issue with our documentation showing how to use this library with Node.js, please ask that question.

**Comment by khteh** [comment]
Isn't that asked?

**Comment by mcollina** [comment]
You can find a not up to date example of pino+next.js at https://github.com/pinojs/pino-nextjs-example.
This does not include http/2, ask the Vercel team.
