### ISSUE TITLE
Log formatting, file stream, request parameter logging

### ISSUE THREAD

**Issue by khteh** [pinojs/pino#1837]
Does this log to file stream, `/var/log/myapp/log-*`, for instance?
Does this capture various request parameters like the user, geo info, etc?
How to do that?

**Comment by jsumners** [comment]
Please review the documentation https://getpino.io

**Comment by khteh** [comment]
I found `pino.destination` but not following:

- remote user
- remote IP address
- request method
- request path
- response status code
- request agent
- response time

**Comment by jsumners** [comment]
Your question is far too vague. We don't know anything about your application, how it presents such information, and how it would hand off that information to the logger.  I suggest reviewing the documentation again, in particular the sections on serializers and ecosystem modules.

**Comment by khteh** [comment]
How to automatically extract these information from HTTP request and log them?

**Comment by jsumners** [comment]
Again, your question is extremely generic. My previous answer continues to address it. If you continue to have issues:

Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).
