### ISSUE TITLE
passing logger methods to a function (2)

### ISSUE THREAD

**Issue by OnkelTem** [pinojs/pino#1839]
I cannot come up with a solution to extract pino's logging methods.
I found a few issues here, discussing this one, but I cannot successfully bind `this`.

**Example 1**: using a single method:

```js
const logger = pino();
const info = logger.info
logger.info.bind(logger)
info('test')
```
Error:
```
/home/runner/PinoBind/node_modules/pino/lib/tools.js:68
      if (typeof this[msgPrefixSym] === 'string' && msg !== undefined && msg !== null) {
                     ^
TypeError: Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')
    at LOG (/home/runner/PinoBind/node_modules/pino/lib/tools.js:68:22)
```
Sandbox: https://replit.com/@OnkelTem/PinoBind#index.js

**Example 2**: using  an object with methods:

```js
const logger = pino();
const methods = {
  info: logger.info
}
logger.info.bind(logger)
methods.info('test')
```
Error:
```
/home/runner/PinoBind/node_modules/pino/lib/tools.js:71
      this[writeSym](null, format(msg, n, this[formatOptsSym]), level)
                    ^

TypeError: this[writeSym] is not a function
    at Object.LOG [as info] (/home/runner/PinoBind/node_modules/pino/lib/tools.js:71:21)
```
Sandbox: https://replit.com/@OnkelTem/PinoBind#index2.js

**Comment by jsumners** [comment]
```js
const logger = pino();
const info = logger.info
logger.info.bind(logger)
info('test')
```

You have assigned the bound function to nothing and then used the unbound function to log the string `'test'`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

**Comment by OnkelTem** [comment]
Answering to myself.
`bind()` isn't mutating, it returns a new thing.

So the correct variants are:

```js
const logger = pino();
const info = logger.info
logger.info.bind(logger)
info('test')
```

```js
const logger = pino();
const methods = {
  info: logger.info.bind(logger)
}
methods.info('test')
```

Sandbox: https://replit.com/@OnkelTem/PinoBind2

Surprisingly, this was overlooked in previous answers.

**Comment by OnkelTem** [comment]
@jsumners Ah, I was answering to myself at the same time.

Thanks!
