### ISSUE TITLE
Bun support?

### ISSUE THREAD

**Issue by lundjrl** [pinojs/pino#1842]
Hey all, 

I don't see a discussions section for this repo but I'm curious if there's any traction to support Bun in the project.

If there is, any ways I can help?

Coming from [here](https://github.com/directus/directus/discussions/19643#discussioncomment-6980271)

**Comment by jsumners** [comment]
Thank you for the report. This project targets the [Node.js](https://nodejs.org) runtime. If you are encountering issues using Bun, please file issues there as [requested by them](https://twitter.com/jarredsumner/status/1700497869160268155).
