### ISSUE TITLE
log message along with object

### ISSUE THREAD

**Issue by thewh1teagle** [pinojs/pino#1850]
Hello! 
I would like to log messages along with objects, similar to how `console.log` works.
for instance
```ts
import pino from 'pino'

const logger = pino({
  name: 'app',
  level: 'debug',
  transport: {
    target: "pino-pretty",
    options: {
      colorize: true,
    },
  },
});

logger.info('New message', {content: 'hello world'})
```

Expected output:
```log
New Message {content: 'hello world'}
```

Actual output:
```log
New Message
```

**Comment by bngarren** [comment]
In this case, try passing the object as the first param and the message string second. This is the way pino's log methods are overloaded. If a string is first param, you cannot pass a mergingObject next.

**Comment by jsumners** [comment]
https://getpino.io/#/docs/api?id=logging-method-parameters

https://getpino.io/#/docs/api?id=logmethod
