### ISSUE TITLE
Unable to determine transport target for "pino-pretty" w/ T3 Env

### ISSUE THREAD

**Issue by claudiorivera** [pinojs/pino#1853]
Hello!

I've got a `logger.ts` with:
```ts
export const logger = pino({
  transport: {
    target: "pino-pretty",
  },
});
```
and I'm calling `logger.info("hello world")` from a Next.js page component and it's working as expected 👍🏼 

However, I'm trying to use [T3 Env](https://env.t3.gg/docs/nextjs) to validate some env vars in this file, but as soon as I attempt to access `env` inside `logger.ts` (even a simple `console.log({ env })`), `pino` throws:

```
 ⨯ Error: unable to determine transport target for "pino-pretty"
    at fixTarget (/Users/me/Developer/pino-pretty-transport-issue/node_modules/pino/lib/transport.js:144:13)
    at transport (/Users/me/Developer/pino-pretty-transport-issue/node_modules/pino/lib/transport.js:114:22)
    at normalizeArgs (/Users/me/Developer/pino-pretty-transport-issue/node_modules/pino/lib/tools.js:316:16)
    at pino (/Users/me/Developer/pino-pretty-transport-issue/node_modules/pino/pino.js:87:28)
    at eval (webpack-internal:///./src/lib/logger.ts:17:59) {
  page: '/'
}
```

For what it's worth, I noticed that without the `console.log`, `getCallers()` inside of `transport.js` returns:
```
[
  undefined,
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/pages/index.js",
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/webpack-runtime.js",
  undefined,
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/pages/index.js",
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/webpack-runtime.js",
  undefined,
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/pages/index.js",
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/webpack-runtime.js",
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/pages/index.js",
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/pages/index.js",
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/webpack-runtime.js",
  "/Users/me/Developer/pino-pretty-transport-issue/.next/server/pages/index.js",
]
```
However, with the `console.log`, it returns `[undefined]`, which means `callers` ends up being `[undefined]`, which means we never give a value to `fixTarget` in the `for (const filePath of callers)` loop, which ends up causing `transport.js` to throw:
```ts
if (!fixTarget) {
  throw new Error(`unable to determine transport target for "${origin}"`)
}
```

Any idea what I might be doing wrong? I'm happy to take this to T3 Env, but wanted to make sure it wasn't an issue with `pino` first.

Minimal reproduction here: https://github.com/claudiorivera/pino-pretty-transport-issue

Thanks!

**Comment by mcollina** [comment]
Take a look at https://github.com/pinojs/pino-nextjs-example. It's likely out of date.

(also better docs on this might be necessary)
