### ISSUE TITLE
Any plan for connector to nitro?

### ISSUE THREAD

**Issue by maicss** [pinojs/pino#1855]
Repo: https://github.com/unjs/nitro

Currently used by [Nuxt](https://nuxt.com/)

**Comment by jsumners** [comment]
What exactly are you asking for?

**Comment by maicss** [comment]
List in https://github.com/pinojs/pino#usage
```
For using Pino with a web framework see:

 - Pino with Fastify
 - Pino with Express
 - ...
 - Pino with nitro (this is what I ask for)
```

**Comment by jsumners** [comment]
Would you like to submit a PR to resolve this?

**Comment by maicss** [comment]
I may not have the ability to do this 😅

**Comment by mcollina** [comment]
You mean https://github.com/unjs/nitro? I think this is best asked to the nitro maintainers. Plugging in `pino-http` should be simple enough for a basic integration, but I have no better idea than you on how to grab the Node.js http server.
