### ISSUE TITLE
Pino 8.17.0 breaks logging from catch in TypeScript

### ISSUE THREAD

**Issue by castdin** [pinojs/pino#1865]
#1783  seems to have re-introduced #1115 as `LogFn` no longer accepts an object of type `unknown`, which is what TypeScript emits for caught errors.

<img width="861" alt="image" src="https://github.com/pinojs/pino/assets/7321311/fde14354-7d76-4d17-a5ba-7a737748ff8f">

**Comment by castdin** [comment]
Ah - I see now from the discussion in that PR that this is intentional. This is unfortunate as it constitutes a breaking change for those who previously logged this way. 

From a DX perspective it's also somewhat surprising that Pino won't accept the error object as-is.

**Comment by mcollina** [comment]
Thanks, will revert asap.

https://github.com/pinojs/pino/pull/1866
