### ISSUE TITLE
Typescript/Intellisense not accurate after using logMethod hook 

### ISSUE THREAD

**Issue by logonv** [pinojs/pino#1878]
Hi,

I used this [logMethod hook](https://github.com/pinojs/pino/blob/master/docs/api.md#logmethod) to change the function signature for the logger functions. 

However, typescript expects the default pino function signature. 

![image](https://github.com/pinojs/pino/assets/15173199/6782e634-2472-48be-b898-4481e8867d90)

Do you have any advice on how to fix this? (Using the new log method, the default pino function signature would not work and typescript/intellisense should reflect this)

Thanks!

**Comment by mcollina** [comment]
I have no clue on how to fix this is in TS. Likely you'd have to define your own types.

**Comment by logonv** [comment]
@mcollina yep, that was it. Thanks.

for any others who may want to do this in the future, we did it like this:

```
type LogLevel = 'fatal' | 'error' | 'warn' | 'info' | 'debug' | 'trace' | 'silent'

type ServerlessLogger = Omit<Logger, LogLevel> & {
  [K in LogLevel]: CustomLogFn
}
```

where `CustomLogFn` was a modified version of https://github.com/pinojs/pino/blob/af002c71a1198330010b6bbe015f0c5ec0230253/pino.d.ts#L315
