### ISSUE TITLE
Allow custom levels comparison

### ISSUE THREAD

**Issue by obrus-corcentric** [pinojs/pino#1880]
I need levels to be compatible with `syslog`.

So override values for example, like this, doesn't work:

```ts
Pino({
  level: 'info',
  customLevels: {
    fatal: 2, // crit
    error: 3, // err
    warn: 4, // warn
    info: 6, // information
    debug: 7, // debug
    trace: 8 // trace
  },
})
```

The main problem here, that in `syslog` lower number shows more critical level, but in `pino` it works in opposite order.

So using `syslog` levels determine `fatal` as lower than `debug` and set up `level` to `debug`, will show only `debug` and `trace` logs.

It would be nice to have ability setup order to compare level values or at least custom comparison function to be able filter logs correct

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jsumners** [comment]
https://github.com/pinojs/pino-syslog

**Comment by obrus-corcentric** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

#1883

**Comment by homersimpsons** [comment]
I think this can be closed with both
> https://github.com/pinojs/pino-syslog

and

> https://github.com/pinojs/pino/pull/1883
