### ISSUE TITLE
Pino streams do not honor logger level debug

### ISSUE THREAD

**Issue by SGudbrandsson** [pinojs/pino#1884]
I'm attempting to use multiple streams in pino, however, I'm unable to get debug messages to be printed in stdout.

Here's an example code, along with the accompanying screenshot
```typescript
import pino from "pino";
import pretty from "pino-pretty";
import { createWriteStream } from "pino-sentry";

const stream = createWriteStream({
  dsn: process.env.SENTRY_DSN,
  environment: process.env.NODE_ENV || "development",
  level: "error",
});

const streams = [stream];
if (process.env.NODE_ENV !== "production") {
  const pp = pretty({
    colorize: true,
    ignore: "pid,hostname",
    minimumLevel: "debug",
  });

  streams.push(pp);
}

export const logger = pino({ level: "debug" }, pino.multistream(streams));
console.log(logger.isLevelEnabled("debug"));
logger.debug("Logger initialized");
console.log("Logger finished");

```
![image](https://github.com/pinojs/pino/assets/1608474/c2effa05-a91d-472d-aeb1-d562a33ca0d1)

If I remove streams and use only the `pino({ level: "debug" });` then I get debug logs.

Do you have any idea what might be wrong?

**Comment by mcollina** [comment]
I think this should work:

```js
import pino from "pino";
import pretty from "pino-pretty";
import { createWriteStream } from "pino-sentry";

const stream = createWriteStream({
  dsn: process.env.SENTRY_DSN,
  environment: process.env.NODE_ENV || "development",
  level: "error",
});

const streams = [stream];
if (process.env.NODE_ENV !== "production") {
  const pp = pretty({
    colorize: true,
    ignore: "pid,hostname",
    minimumLevel: "debug",
  });

  streams.push({ level: 'debug', stream: pp });
}

export const logger = pino({ level: "debug" }, pino.multistream(streams));
console.log(logger.isLevelEnabled("debug"));
logger.debug("Logger initialized");
console.log("Logger finished");
```

I know this is verbose, a PR to improve things would be highly welcomed.

**Comment by SGudbrandsson** [comment]
This worked, thanks!!!

I'll see what I can do with a PR real quick.
The biggest win would be a documentation update, so I'll add that at least.
Since the initialization flow is the way it is, the only thing I can think of is to have some config builder that would prepare a standard object for initializing streams, transports, etc.

I don't have a clear idea of how to execute that cleanly without a sizeable refactor.
I'll add the documenation bit in a PR though.

**Comment by SGudbrandsson** [comment]
No, looks like this is documented here https://github.com/pinojs/pino/blob/89fc326c7a118032ad1c0df355f72e49e90c5bed/docs/help.md#log-to-different-streams

I just didn't see it

**Comment by SGudbrandsson** [comment]
I'll see if I can make a PR that simplifies this a bit later.
