### ISSUE TITLE
It will be cool to configure level per context, it's available in other languages and libraries 

### ISSUE THREAD

**Issue by vsamofal** [pinojs/pino#1886]
So usually libraries have their own log management system, and their own configuration, it will be nice to have a standard at least in pino, so we can control the level for context. Context usually it's a class name, so pino can consume configuration like: 

contextLevels: 
  MyClassName: info
  AnotherClassName: off 

that way we will be able to granularly disable annoying logs 
https://stackoverflow.com/questions/4972954/how-to-disable-loggers-of-a-class-or-of-whole-package here is an example how it's done in java 

we can't make it exactly like this, because there is no "packages" in js/ts, but even changing level by context will be super helpful in  cases where we do use a library and want to listen less from it

**Comment by mcollina** [comment]
This is already possible with child loggers. What's missing?

**Comment by vsamofal** [comment]
@mcollina can't find how to change the minimal level per child logger. 

So the idea is to say that this child logger should show trace up to trace, for investigating the issue, even if root level is info. 

can you please point me to the docs? 

https://getpino.io/#/docs/child-loggers nothing like that here, or I'm blind

**Comment by mcollina** [comment]
https://getpino.io/#/docs/api?id=child

**Comment by vsamofal** [comment]
will give it a try, thanks
