### ISSUE TITLE
Logs errors as empty object

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#190]
```js 
require('pino')().info({ err: new Error("test") }) // {"pid":65037,"hostname":"Roberts-MacBook-Pro-2.local","level":30,"time":1487085324551,"err":{},"v":1}
```

**Comment by mcollina** [comment]
What is the bug? You need to install a serializer for errors if you want that.
You can get a pre made one in https://github.com/pinojs/pino/blob/master/docs/API.md#errSerializer.

**Comment by ronag** [comment]
@mcollina: How does that work? e.g. if I wanted the example above to be serialized properly?

**Comment by mcollina** [comment]
Check this out: https://github.com/pinojs/pino/blob/master/test/error.test.js#L84-L86

**Comment by xinshangshangxin** [comment]
hi,  I want to use like

`logger.warn('some message',   new Error('at second location'))`;

it not work.

@mcollina

**Comment by mcollina** [comment]
@xinshangshangxin no it does not, and at the moment there is no plan to support it. The error comes in the first place. Check out the discussion in #221, we might work something out in the future.

**Comment by xinshangshangxin** [comment]
@mcollina thanks
