### ISSUE TITLE
ESLint: Unsafe call of an `any` typed value.(@typescript-eslint/no-unsafe-call)

### ISSUE THREAD

**Issue by andy-gpt** [pinojs/pino#1923]
```
import { default as Pino }  from 'pino'

const logger = Pino(  {
  level: 'info'
});

export default logger;

```

I'm getting `ESLint: Unsafe call of an `any` typed value.(@typescript-eslint/no-unsafe-call)` with this simple initialization.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

In this case, please include both your eslint & ts config.
