### ISSUE TITLE
Verifying logs from unit tests (again!)

### ISSUE THREAD

**Issue by cressie176** [pinojs/pino#1926]
Hello,

I've been trying to verify log records in unit tests, and thought I would share my solution. I realise this has been discussed before (https://github.com/pinojs/pino/issues/1274), however the proposed solution was incomplete, and I suspect will no longer work due to serialisation issues inherent with worker threads (https://github.com/pinojs/pino/issues/1786).

Instead, the approach I've taken is to transmit data from the worker to the parent via [postMessage](https://nodejs.org/api/worker_threads.html#workerpostmessagevalue-transferlist) as described in https://github.com/pinojs/pino/issues/1343. This works because the transport is an instance of [ThreadStream](https://www.npmjs.com/package/thread-stream) and providing the postMessage data is in the [correct format](https://www.npmjs.com/package/thread-stream#emit-events), it will be re-emitted as a regular [node event](https://nodejs.org/api/events.html#class-eventemitter).

Here's the code...

```js
// logger.js
const { join, resolve } = require('node:path');
const pino = require('pino');

const targets = [{
  target: 'pino/file',
  options: { destination: 1 }
}, {
  target: resolve('post-message-transport')
}];

const transport = pino.transport({
  targets
});

const logger = pino({
  base: null, // Exclude pid and hostname
}, transport);

// Forward 'message' events from the transport to the logger
transport.on('message', (...args) => {
  logger.emit('message', ...args);
})

module.exports = logger;
```

```js
// post-message-transport.js
const { parentPort } = require("node:worker_threads");
const build = require('pino-abstract-transport');

module.exports = function() {
  return build(function(source) {
    source.on('data', function(record) {
      // code: 'EVENT' is required by ThreadStream
      // name: 'message' determines the event name
      parentPort.postMessage({ code: 'EVENT', name: 'message', args: [record]});
    })
  })
}
```

```js
// my.test.js
const { strictEqual: eq, deepStrictEqual: deq } = require('node:assert');
const { describe, it } = require('zunit');
const logger = require('../logger');

it('should verify logs', (t, done) => {
  logger.once('message', (record) => {
    eq(record.msg, 'Some message')
    eq(record.foo, 'bar')
    done();
  });
  logger.info({ foo: 'bar' }, 'Some message');
})
```

**Comment by mcollina** [comment]
nice! I think it might be a good addition to the new https://www.npmjs.com/package/pino-test

**Comment by cressie176** [comment]
Thanks. I wasn't aware of [pino-test](https://www.npmjs.com/package/pino-test). I'll take and see if I can work out where it fits in. Guessing from a brief look, the idea would be to add the post-message-transport.js, update the README and add some tests?

**Comment by mcollina** [comment]
yes exactly

**Comment by cressie176** [comment]
Sorry closed prematurely. 

Looking at pino-test, I'm not sure how I would make the post-message-transport accessible in a way it could be resolved by pino.

If I understand correctly, pino either requires an absolute path, or the module name for the target. Assuming I'm right, wouldn't it be simpler if I publish the post-message-transport as its own module? Or maybe there's something I'm missing?

**Comment by mcollina** [comment]
yes that would also be ok.
