### ISSUE TITLE
Pino logs string literals without quotes.

### ISSUE THREAD

**Issue by rvypandey** [pinojs/pino#193]
Hi guys,

A big thanks for developing a beautiful and free to use logger. :)

Issue:
I have a logger.js (wraps Pino):
```
var _logger = require("pino")();

info: function (msg, dataObj) {
	dataObj = dataObj || {};
	dataObj.log_level_name = "info";
	_logger.info(dataObj, msg);
}
```

Now, we use this logger in our application:
`logger.info("Some message", someData);`
and the messages this prints is:
`{"pid":49622,"hostname":"host","level":30,"time":1487295290475,"msg":"Some message","log_level_name":info,"v":1}`

If you see closely, the value of "log_level_name" is info (without quotes), not "info" (with quotes). When I try to JSON.stringify this, it fails with the message: `ReferenceError: info is not defined.`

Is there a workaround to this?

**Comment by jsumners** [comment]
Pino works with strings, not objects. Hence, `JSON.stringify` isn't going to help you. You need to set the value as it would be written in a JSON string: `dataObj.log_level_name = '"info"';`

**Comment by rvypandey** [comment]
Thanks, that fixed it. Really appreciate the quick response!
