### ISSUE TITLE
Docs: Pino Logging with Grafana Promtail/Loki

### ISSUE THREAD

**Issue by janpaepke** [pinojs/pino#1932]
I recently spent way to much time to get Promtail and Loki to consume our pino logs in a way that I found satisfactory.
Since logs, which aren't processed or read by anything are basically useless, this should be fairly common challenge.

Information about setting this up properly is surprisingly hard to find, which is why, when I finally made it work, I decided to write an article about it.

I humbly present it here, A for feedback and B so it might be helpful to other pino users.
https://medium.com/@janpaepke/structured-logging-in-the-grafana-monitoring-stack-8aff0a5af2f5

If the maintainers agree this may be useful information, we could also consider linking it in the package docs somewhere.

**Comment by mcollina** [comment]
Would you like to add a link to that page in our help section?

I've used pino-loki with great satisfaction as well.
