### ISSUE TITLE
Release, Tag and Changelog Entry needed for v9 Release

### ISSUE THREAD

**Issue by joshuabremerdexcom** [pinojs/pino#1951]
Hi, we just an upgrade for v9.0 and there wasn't a Changelog entry or Github Release for it. I figured it out and saw it was just a Node compatibility change, but I still wanted to let you know to reduce any confusion for your users. 

Thank you!

**Comment by mcollina** [comment]
I’ve published it.
No major change, only dropping of old Node.js versions
