### ISSUE TITLE
v9 release doesn't list breaking changes

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [pinojs/pino#1952]
https://github.com/pinojs/pino/releases/tag/v9.0.0

Can you update the release notes to include the breaking changes so folx don't have to hunt for it?

*************

### ⚠ BREAKING CHANGES

- Dropped support for Node.js 14, 16, & 19

**Comment by mcollina** [comment]
done

**Comment by 10xLaCroixDrinker** [comment]
Thank you!
