### ISSUE TITLE
`browser.formatters.level` does not inline attributes into message anymore

### ISSUE THREAD

**Issue by timtrense-leadec** [pinojs/pino#1966]
after trying out the sample code of [PR#1898](https://github.com/pinojs/pino/pull/1898) with `v9.0.0` I sadly must report that the level formatter for browser does not inline the contained attributes anymore, but blindly puts a `level` object in the resulting log entry.

Expected:
```json
{
  time: 1707198967745,
  label: 'info',
  level: 30,
  msg: 'I am logging a message from the middleware'
}
```

Actual:
```json
{
  time: 1707198967745,
  level: {label: 'info', level: 30},
  msg: 'I am logging a message from the middleware'
}
```

**Comment by timtrense-leadec** [comment]
This seems to be a degradation after `v.8.19.0` in https://github.com/pinojs/pino/commit/7f33a0ee3f094e0c050119b59f024273b8878662

In deleted line 339 there used to be an `Object.assign`, whereas now in added line 338 is a simple assignment of `o.level = levelFormatter(...)`.

**Comment by emmyakin** [comment]
This changes causing this bug has been reverted in #1971, and thus fixed
