### ISSUE TITLE
Console colors.

### ISSUE THREAD

**Issue by ro70** [pinojs/pino#197]
Aren't ANSI-colors working with .info()?
```
var pino = require('pino')()
var colors = require('colors')

var info = function(msg) {
  pino.info({
    'info': msg,
    // ...
    'test': '\u001b[34m\u001b[1mTEST\u001b[22m\u001b[39m' // Not working.
  }, 'INFO'.bold.cyan) // Not working.

  console.log('\u001b[34m\u001b[1mTEST\u001b[22m\u001b[39m') // Working.
  console.log('TEST2'.bold.cyan) // Working.
}
```
Console output is something like:
```
{"pid":83541,"hostname":"...","level":30,"time":1488351215653,"msg":"\u001b[36m\u001b[1mINFO\u001b[22m\u001b[39m","info":"...","test":"\u001b[34m\u001b[1mTEST\u001b[22m\u001b[39m","v":1}
TEST
TEST2
```
This is pino 4.0.1 and node 6.2.2.

**Comment by jsumners** [comment]
I'm not sure what you're expecting to happen. Pino log lines are JSON strings. Thus any such escape sequences will be escaped in the output.

**Comment by ro70** [comment]
@jsumners Thanks for your answer. Well, I'm sure when I used this code a few weeks ago the 'INFO'.bold.cyan was printed in cyan to my console (iTerm2).

**Comment by jsumners** [comment]
Then would you be up for tracking down the problem? Git bisect should help -- http://webchick.net/node/99

**Comment by davidmarkclements** [comment]
I think the correct behaviour is to escape - prettification is external - what you could do is create a prettifier that unescapes the control codes (we could even have this an option for the pino cli, say `node app.js | pino -u`

**Comment by davidmarkclements** [comment]
closing for now - @ro70 feel free to continue discussion :)

**Comment by ro70** [comment]
@davidmarkclements Thanks for the hint. This one solved the issue:
```
var pretty = pino.pretty({
  formatter: function(json) {
    var s = JSON.stringify(json)
    var r = /\\u([\d\w]{4})/gi
    s = s.replace(r, function(match, grp) {
      return String.fromCharCode(parseInt(grp, 16))
    })
    return s
  }
})
```
Found [here](http://stackoverflow.com/questions/7885096/how-do-i-decode-a-string-with-escaped-unicode).

**Comment by davidmarkclements** [comment]
nicely done :) to state the obvious, avoid using that in-process in production

**Comment by ro70** [comment]
> avoid using that in-process in production

I'm new to the node world. What do you mean exactly with this?

**Comment by avetisk** [comment]
@ro70 I think he meant to say that it's not very good to use such formatter in production env, considering performance, etc.
