### ISSUE TITLE
How to delete log file

### ISSUE THREAD

**Issue by davidbonan** [pinojs/pino#1981]
In the context of a batch process that identifies tasks to do and then stops directly when it finds none, I need to delete the log file generated by Pino. Is there a simple way to do this? Currently, I have to do a sonicBoom.end() followed by an fsExtra.removeSync(), but I'm not familiar with the asynchronous aspects of SonicBoom.

**Comment by mcollina** [comment]
You should wait for a `close` event emitted by `sonicBoom`.
