### ISSUE TITLE
How to add context data using the same pino instance

### ISSUE THREAD

**Issue by nelsonprsousa** [pinojs/pino#1994]
Hi community,

**Goal**: Set contextual data (e.g. `url.pathname`, `url.method,` `headers.referrer`, ...) per scoped request, with the same pino instance, to be used across the same request.

**Findings**: `pino().child()` could be the answer, but it returns a new pino instance, so we can't access it on middleware and then on util classes.

**Problem**: On a web api, using fastify or express, add contextual data regarding the request to all logging on the scoped request. New requests should not share the same contextual data.

**Pseudocode**:

```typescript
// Middleware (entry.express.ts)
export const onGet: RequestHandler = async ({
  pathname,
  method,
  request,
}) => {
  // Instead of returning a new instance, set some scoped context?
  LoggerFactory.getLogger().child({
    pathname,
    httpMethod: method,
    referrer: request.referrer,
  });
};
```

```typescript
// Util function called in the scoped flow (utils/languages.ts)
export const getLanguagesFromDb = async (): Promise<Language[] | null> => {
  try {
    return await db.query.languages.findMany();
  } catch (e) {
    // Ideally the log should contain contextual data of the current request
    LoggerFactory.getLogger().error(e);
    return null;
  }
};
```

**Possible workaround**: Instantiate a new pino instance per request.

**Possible workaround 2 (not tested)**: Use https://github.com/aigoncharov/cls-proxify lib?

Am I missing something?
Thank you for your help and guidance,
Happy to contribute with PRs / docs / wtv once we get into a conclusion.

**Comment by mcollina** [comment]
If you want to use something like that, you would need to use some integration of `AsyncLocalStorage`.

As an example: https://github.com/mcollina/fastify-asyncforge will give the request logger from  fastify with already all the settings.

Alternatively, you can use the `mixin` option of `pino` and use that function to fetch the request data from an AsyncLocalStorage that you manage.

**Comment by nelsonprsousa** [comment]
If I am understanding correctly, that means that, if using fastify, I can add `fastify-asyncforge` dependency and deal with it, right?

Looks exactly what it is necessary, this seems pretty convenient for most apps.

**Comment by mcollina** [comment]
Yes exactly.

**Comment by nelsonprsousa** [comment]
I am going to close this issue 👍

**Comment by nelsonprsousa** [comment]
Just leaving some feedback that I'd see adding context data to logging as a cool feature for this library as well.

I am a backend developer coming from .NET/C# so I am used to it, maybe I am biased tho.
