### ISSUE TITLE
Forbid using default log levels when `useOnlyCustomLevels: true`

### ISSUE THREAD

**Issue by chernodub** [pinojs/pino#1998]
Currently, pino's TS declaration allows using default log levels when `useOnlyCustomLevels` is `true`. This following code will result in a runtime error:

```ts
import { pino } from 'pino';

const logger = pino({
  customLevels: { customInfo: 10 },
  useOnlyCustomLevels: true,
});

logger.info('123'); // TS should warn here ?
logger.customInfo('123'); // should work fine
```

Expected behavior:

```ts
import { pino } from 'pino';

const logger = pino({
  customLevels: { customInfo: 10 },
  useOnlyCustomLevels: true,
});

logger.info('123'); // TS errors here
logger.customInfo('123'); // works fine
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests. We use `tsd` for the types.

**Comment by chernodub** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests. We use `tsd` for the types.

Yep, already submitted the PR https://github.com/pinojs/pino/pull/1999 :)
