### ISSUE TITLE
pino transport - is it worth using a transport in another process for writing to stdout?

### ISSUE THREAD

**Issue by RichardWright** [pinojs/pino#2000]
To stop our thread being blocked, is it possible to get a worker thread eg a transport to handle logging to stdout? Does this transport used shared memory to get around serialisation costs?

Thanks!

**Comment by mcollina** [comment]
> To stop our thread being blocked, is it possible to get a worker thread eg a transport to handle logging to stdout? 

It's supported, but not something I would recommend unless you have some specific needs to fix.

> Does this transport used shared memory to get around serialisation costs?

It uses some shared memory but there will be some serialisation costs involved.

**Comment by RichardWright** [comment]
> It's supported, but not something I would recommend unless you have some specific needs to fix.
We have long running stateful processes which can get less reactive as gc picks up. Anything we can offload is therefore good for us

> It uses some shared memory but there will be some serialisation costs involved.

If the objects stay in memory, what are the serialisation costs?

> It uses some shared memory but there will be some serialisation costs involved.

_**

**Comment by mcollina** [comment]
You can't move object references across threads in Node.js/V8. Everything must be serialized down to binary and deserialized.

In our case, we are serializing it to JSON directly.
