### ISSUE TITLE
Typescript: turn Level typings into an enum

### ISSUE THREAD

**Issue by binarykitchen** [pinojs/pino#2020]
In the pino namespace, we have this definition:
```ts
type Level = "fatal" | "error" | "warn" | "info" | "debug" | "trace";
```

It would be good to turn this into an enum, something like:
```ts
enum Level {
  FATAL = "fatal",
  ERROR = "error",
  WARN = "warn",
  INFO = "info",
  DEBUG = "debug",
  TRACE = "trace",
}
```

Why?

Instantiating a pino logger the current way with a hard-coded string is fragile:
```ts
const logger = pino({
  level: isProd() ? "warning" : "debug",
```

See? "warning" is a wrong level. This could be prevented with the enum usage like:

```ts
const logger = pino({
  level: isProd() ? Level.WARN : Level.DEBUG
```

LMK if you like that idea before I do a PR ...

**Comment by mcollina** [comment]
I'm of the school of thought that pure-TS constructs should be avoided at all costs. This includes enum.

Also, the level names are 100% flexible, so doing it in a pluggable way would be hard.
