### ISSUE TITLE
Accept log level env var as UPPER or LOWER case

### ISSUE THREAD

**Issue by filipeandre** [pinojs/pino#2022]
Currently it won't accept UPPER case log levels.
But why "DEBUG" is invalid?

"DEBUG" should be as valid as "debug".

When setting level, please convert the input to lower case :)

**Comment by balaji-atoa** [comment]
`formatters: {
          level: (label) => {return { level: label.toUpperCase() }; },
        },`
        
 The above snippet can help u transform log levels to uppercase.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by balaji-atoa** [comment]
@jsumners i can take it up.

**Comment by balaji-atoa** [comment]
@jsumners raised a PR. can u please check https://github.com/pinojs/pino/pull/2034 :)

**Comment by elevatedbuttonpusher** [comment]
> formatters: { level: (label) => {return { level: label.toUpperCase() }; }, },

any idea why this doesn't actually work? this is my config I'm passing to pino 

`pino({
      formatters: { level(label) { return { level: label.toUpperCase() }; } },
      level: 'debug',
      browser: {
        asObject: true
      },
    });`

output looks like 
![image](https://github.com/user-attachments/assets/a41d6ee4-6224-49ad-b4a1-b876d37099c8)

**Comment by jsumners** [comment]
If you are using `pino@9.4.0` or later, please open a new issue.
