### ISSUE TITLE
pino crashes the server when logging an error from request-promise

### ISSUE THREAD

**Issue by nodo** [pinojs/pino#203]
Hi,

When logging an error from `request-promise`, `pino` does not handle it correctly and causes the server to crash.

### Create a server which returns an error
```javascript
var restify = require('restify');

var server = restify.createServer();

server.get('/boom', (req, res, next) => {
  console.log('GET /boom');
  res.send(500, 'yay! 500');
  return next(false);
});

server.listen(1337, function() {
  console.log('Listening at localhost:1337');
});
```

### Create a server which calls the previously created server
```javascript
var restify = require('restify');
var rp = require('request-promise');
var pino = require('pino');
var log = pino();

var server = restify.createServer();

server.get('/oops', (req, res, next) => {
  rp({
    url: 'http://localhost:1337/boom',
    simple: true
  })
  .then(() => {
    log.info('SUCCESS');
    res.send(200);
  })
  .catch((err) => {
    log.error(err);
    res.send(500);
  });
});

server.listen(1338, function() {
  console.log('Listening at localhost:1338');
});
```

## Send a request
```
 curl -i localhost:1338/oops
```
The curl request just hand and hitting `Ctrl-C` cause the server to crash.

## Environment

I am using `node v6.9.2`. You can find my package.json below:

```
{
  "name": "bug",
  "version": "0.0.1",
  "dependencies": {
    "pino": "^4.0.2",
    "request": "^2.80.0",
    "request-promise": "^4.1.1",
    "restify": "^4.3.0"
  }
}
```

## Root Cause

The root cause seems to be at this line: https://github.com/pinojs/pino/blob/master/pino.js#L189 where `fast-safe-stringify` is called. It looks like in the error object there is a `response` object with some non-serializable properties (e.g. socket, connection, etc...). A possibility might be that `fast-safe-stringify` is not handling this properly. There is a related closed issue here: https://github.com/davidmarkclements/fast-safe-stringify/issues/4 .

Even if this error seems related to `fast-safe-stringify`, I have open the issue here for two reasons:
1. visibility to pino users.
2. I think pino should not try to serialise *all* the fields of an error object, as the risk to hit these kind of problems are quite high.

Apologies if I missed something, I would be happy to help you out fixing this.

**Comment by davidmarkclements** [comment]
@nodo thanks for a sterling detailed issue - can you add one thing - what's the output on crash?

**Comment by nodo** [comment]
The output is not that useful unfortunately.

`pino` logs the message as follows:
```
{"pid":14846,"hostname":"MLL1P05607","level":50,"time":1489001780459,"msg":"500 - \"\\\"yay! 500\\\"\"","type":"Error","stack":"StatusCodeError: 500 - \"\\\"yay! 500\\\"\"\n    at new StatusCodeError (/Users/anodari/other_projects/pino-bug/issue/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/Users/anodari/other_projects/pino-bug/issue/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/Users/anodari/other_projects/pino-bug/issue/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/Users/anodari/other_projects/pino-bug/issue/node_modules/request/request.js:187:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/Users/anodari/other_projects/pino-bug/issue/node_modules/request/request.js:1126:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/Users/anodari/other_projects/pino-bug/issue/node_modules/request/request.js:1046:12)\n    at IncomingMessage.g (events.js:291:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)\nFrom previous event:\n    at Request.plumbing.init (/Users/anodari/other_projects/pino-bug/issue/node_modules/request-promise-core/lib/plumbing.js:36:28)\n    at Request.RP$initInterceptor [as init] (/Users/anodari/other_projects/pino-bug/issue/node_modules/request-promise-core/configure/request2.js:41:27)\n    at new Request (/Users/anodari/other_projects/pino-bug/issue/node_modules/request/request.js:129:8)\n    at request (/Users/anodari/other_projects/pino-bug/issue/node_modules/request/index.js:54:10)\n    at Server.server.get (/Users/anodari/other_projects/pino-bug/issue/server_2.js:9:3)\n    at Domain.next (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:912:30)\n    at Domain.f (/Users/anodari/other_projects/pino-bug/issue/node_modules/once/once.js:25:25)\n    at Domain.run (domain.js:221:14)\n    at Server._run (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:971:7)\n    at /Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:718:18\n    at onRoute (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:770:17)\n    at Router.find (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/router.js:525:9)\n    at Server._route (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:753:21)\n    at routeAndRun (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:711:14)\n    at Server._handle (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:731:9)\n    at Server.onRequest (/Users/anodari/other_projects/pino-bug/issue/node_modules/restify/lib/server.js:332:14)\n    at emitTwo (events.js:106:13)\n    at Server.emit (events.js:191:7)\n    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)","name":"StatusCodeError","statusCode":500,"message":"500 - \"\\\"yay! 500\\\"\"","error":"\"yay! 500\"","options":{"url":"http://localhost:1337/boom","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":500,"body":"\"yay! 500\"","headers":{"content-type":"application/json","content-length":"10","date":"Wed, 08 Mar 2017 19:36:20 GMT","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:1337","port":"1337","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/boom","path":"/boom","href":"http://localhost:1337/boom"},"method":"GET","headers":{}}},"v":1}
```
But the client is hanging. After hitting `Ctrl-C` (on the client side) the server crashes with the following error:
```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: handle != self._handle
    at TCP.onread (net.js:533:3)
```

**Comment by davidmarkclements** [comment]
I've tried to replicate the same on fast-safe-stringify master with 

```
 http.get('http://google.com', (res) => { console.log(require('./')({res: res})) })
```

and there's no crash

currently pino is using 1.1.3
could you try upgrading `fast-safe-stringify` in `pino` to `1.1.6` and see if that solves it?

**Comment by davidmarkclements** [comment]
just to be clear - when you remove the log.error(err) line the server behaves correctly? 

it's strange that an error is actually being logger *before* crashing

promises do make these things so much harder to debug

**Comment by nodo** [comment]
I confirm that:
1. the server behaves correctly without logs
2. `fast-safe-stringify@1.1.6` does not fix the problem.

I might be wrong but it looks to me that `fast-safe-stringify` corrupts the connection object (which is inside the error object).

**Comment by davidmarkclements** [comment]
can you find an isolate the object it's choking on, e.g. one piece of (zero dependency) code 
that we can turn into a test for `fast-safe-stringify`?

**Comment by davidmarkclements** [comment]
what version of Node are you using?

Even with this I can't replicate:

```js
// check.js
var rp = require('request-promise')
var pino = require('pino')
var log = pino()
var http = require('http')

http.createServer((req, res) => {
  rp({
    url: 'http://localhost:1337/boom',
    simple: true
  })
  .then(() => {
    log.info('SUCCESS');
    res.on('yay')
  })
  .catch((err) => {
    log.error(err);
    res.end('oh no')
  })
}).listen(8080)
```

```sh
$ node check.js
```

Server completes request:

```sh
$ curl http://localhost:8080
oh no
```

**Comment by davidmarkclements** [comment]
above also works on 4.8.0

**Comment by davidmarkclements** [comment]
also what's you your OS - this is working for me on macOS 10.12.1 (16B2657)

**Comment by davidmarkclements** [comment]
very strange - taking you're whole piece with restify - and then I can replicate

**Comment by nodo** [comment]
OS: `10.11.6 (15G31)`
Node: `6.9.2`

Yes, I confirm that your piece of code works for me.

**Comment by davidmarkclements** [comment]
Ok
 
Looks like `fast-safe-stringify` is causing an infinite loop

**Comment by davidmarkclements** [comment]
but only in this very precise scenario, needs some digging

**Comment by davidmarkclements** [comment]
sorry no - spoke too soon, it's not an infinite loop - I think I need sleep - go back to what @jsumners is saying

**Comment by davidmarkclements** [comment]
it's very weird because if you use `http.get` instead of request-promise and you just put the `res` object into the logger (inside a `restify` context) it also works fine. It's only this exact combination

**Comment by davidmarkclements** [comment]
I'm out of time atm but I've isolated it to the `request` prop of the `reponse` prop of the `err` object

```js
var restify = require('restify');
var rp = require('request-promise');
var pino = require('pino');
var log = pino(require('fs').createWriteStream('/dev/null'));

var server = restify.createServer();

server.get('/oops', (req, res, next) => {
  rp({
    url: 'http://localhost:1337/boom',
    simple: true
  })
  .then(() => {
    log.info('SUCCESS');
    res.send(200);
  })
  .catch((err) => {
    delete err.response.request
    delete err.response.toJSON
    log.error(err.response)
    res.send(500)
  });
});

server.listen(1338, function() {
  console.log('Listening at localhost:1338');
});
```

**Comment by davidmarkclements** [comment]
*but* it logs by itself just fine e.g. `log.error(err.response.request)`

I think it might be  related to the toJSON function using the err.response.request object

**Comment by davidmarkclements** [comment]
hypothesis even more likely since this fails in the same way:

```
var restify = require('restify');
var rp = require('request-promise');
var pino = require('pino');
var log = pino(require('fs').createWriteStream('/dev/null'));

var server = restify.createServer();

server.get('/oops', (req, res, next) => {
  rp({
    url: 'http://localhost:1337/boom',
    simple: true
  })
  .then(() => {
    log.info('SUCCESS');
    res.send(200);
  })
  .catch((err) => {
    res.send(500)
    err.response.request = {}
    log.error(err)
  });
});

server.listen(1338, function() {
  console.log('Listening at localhost:1338');
});
```

**Comment by davidmarkclements** [comment]
ok got it (see #204)

fix to fast-safe-stringify here https://github.com/davidmarkclements/fast-safe-stringify/blob/master/index.js#L4-L7

and here https://github.com/davidmarkclements/fast-safe-stringify/blob/master/index.js#L37

performance of fast-safe-stringify is unaffected by changes which is great

thanks @nodo for bringing this up!

**Comment by nodo** [comment]
Great @davidmarkclements ! 👍 I had this in mind, but I am not sure if relying on "external" `toJSON` function would make `fast-safe-stringify` not so safe anymore. WDYT?

Also, please would you mind to explain how your change fix the with the error above?

**Comment by davidmarkclements** [comment]
so - I made a slight change (bumped up to 1.1.11) 
so that if toJSON returns a circ ref it's handled

so yeah, it's just as safe - calling manually vs `JSON.stringify` calling natively makes no difference to safety

It was some weirdness to do with the interaction between the objects returned from toJSON functions objects in the tree - it may have lead to a leaking reference (of a response or more likely a request object), which meant that a socket couldn't be destroyed effectively by the internal net module. That's my guess, but I found that we can sidestep the whole thing by calling toJSON up front.

**Comment by nodo** [comment]
Sorry, I was meaning the change in `fast-safe-stringify`. There are some questions I don't really understand the answer. 

- Why the problem appears only with restify?
- How could a reference be leaked? Shouldn't  the `net` module have its own reference?

If possible, I would like to precisely identify the root cause. It would also be great to add a unit test, even if probably it's quite hard to do.

**Comment by nodo** [comment]
@davidmarkclements Should we keep this open for root-cause-analysis?

**Comment by davidmarkclements** [comment]
no - the issue is solved as far as pino is concerned

regarding your questions though, as I say, I'm just guessing - it's a weird one - 

But I can give you my theory which you can consider in your investigation, 
I think there's some interplay with the way restify ultimately uses sockets, 
and the way those sockets (which were on the response and response.request objects) 
are returned from toJSON,

Combined with the fact that we're modifying the object during the serialization processes, as triggered by calls to toJSON from the C layer (the internal implementation of JSON.stringify), state is shifting around inside the object as it's being serialized (this is why we use the counter in the Circle.prototype.toJSON function)

I think both request-promise and restify modify the objects in some way, and the objects *returned* from toJSON bypass the way we manage state inside the object as it's being serialized, which could (at the C level) lead to a leak. 

I may or may not be correct, but beyond I can't say more, without spending significant time researching - (which unfortunately I don't have)

Whether or not this is the case, the simplest way around it is to call `toJSON` up front, which means the objects safely become part of fast-safe-stringify sleight of hand state management during serialization

If you get to the root cause, do drop a note here! :bowtie: 

thanks for the help @nodo

**Comment by nodo** [comment]
Sure thing! thanks for the quick response @davidmarkclements.

**Comment by darylsew** [comment]
Hey, I was running into this yesterday on ubuntu with a Node/React stack - it happens nondeterministically:
```
INFO  [1587790359862] (32324 on ubuntu-s-1vcpu-1gb-sfo2-01): Request that caused error:
INFO  [1587790359865] (32324 on ubuntu-s-1vcpu-1gb-sfo2-01): request errored
    res: {
      "statusCode": 500,
      "headers": {
        "x-powered-by": "Express",
        "access-control-allow-origin": "*",
        "content-type": "application/json; charset=utf-8",
        "content-length": "45",
        "etag": "W/\"2d-ypylZ7o4mwqEYtLSYY3+vQ6pkFM\""
      }
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/home/dev/taste/server/node_modules/pino-http/logger.js:67:38)
              at emitNone (events.js:111:20)
              at ServerResponse.emit (events.js:208:7)
              at onFinish (_http_outgoing.js:720:10)
              at _combinedTickCallback (internal/process/next_tick.js:132:7)
              at process._tickCallback (internal/process/next_tick.js:181:9)
    }
    responseTime: 14
    req: {
      "id": 2,
      "method": "POST",
      "url": "/submit",
      "headers": {
        "connection": "upgrade",
        "host": "fitvise.ai",
        "content-length": "52",
        "accept": "application/json, text/plain, */*",
        "dnt": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/8
1.0.4044.122 Safari/537.36",
        "content-type": "application/json;charset=UTF-8",
        "origin": "https://fitvise.ai",
        "sec-fetch-site": "same-origin",
        "sec-fetch-mode": "cors",
        "sec-fetch-dest": "empty",
        "referer": "https://fitvise.ai/app/",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.9,es;q=0.8",
        "cookie": "_ga=GA1.2.1400904315.1582426818; intercom-id-s79b21ti=d0a6a664-3e56-4c75-82d7-54324db4771b; __strip
e_mid=04dde533-b5af-405e-8daa-cfd479fc90df; __stripe_sid=93a03831-1498-4e73-9f24-195a7f75b49f"
      },                                                                                            
      "remoteAddress": "::ffff:127.0.0.1",
      "remotePort": 51836                                                                           
    }
INFO  [1587790359865] (32324 on ubuntu-s-1vcpu-1gb-sfo2-01): request errored                        
    res: {                                                                                          
      "statusCode": 500,                                                                            
      "headers": {                                                                                  
        "x-powered-by": "Express",                                                                  
        "access-control-allow-origin": "*",                                                         
        "content-type": "application/json; charset=utf-8",                                          
        "content-length": "45",
        "etag": "W/\"2d-ypylZ7o4mwqEYtLSYY3+vQ6pkFM\""                                              
      }                                                                                             
    } 
```

**Comment by mcollina** [comment]
I'm very sure _this one_ was fixed. If you have a crash with some specific input plase open one more with a specific example
