### ISSUE TITLE
General Linux question: best command to view pino logs?

### ISSUE THREAD

**Issue by binarykitchen** [pinojs/pino#2036]
On a production Linux server, when you want to check the pino-generated logs, what command do you use and recommend?

Before I switched to pino, using a different format, this command worked:
```zsh
tail -f out.log | jq
```

But now, not anymore, due to this error:
```
parse error: Unmatched '}' at line 1, column 5
```

Because a JSON was printed:
```
[19:43:16.703] ERROR (26178 on videomail.io): connect ECONNREFUSED 127.0.0.1:25
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED 127.0.0.1:25",
      "stack":
          Error: connect ECONNREFUSED 127.0.0.1:25
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      "errno": -111,
      "code": "ESOCKET",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 25,
      "command": "CONN"
    }
```

So, wondering what command you guys use for that? Thanks for any advice. Cheers :)

**Comment by jsumners** [comment]
It looks like you are using `pino-pretty` to format the written logs. Don't do that.

**Comment by binarykitchen** [comment]
@jsumners 

Right, done:

```js
  const forHumans = isLocal();
  
  ....
  
  if (forHumans) {
    transportTargets.push(pinoPretty);
  }
  ```
:shrug:

**Comment by jsumners** [comment]
What should I understand from that?

Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).
