### ISSUE TITLE
Recipe on how to downgrade error level for common errors?

### ISSUE THREAD

**Issue by binarykitchen** [pinojs/pino#2038]
Hello again, :)

How do you downgrade log levels for some common errors?

Like 404 HTTP errors, in the code they are logged as errors, yet, I do not want to be alerted every time about 404 errors.

For example, HTTP 404 errors on the server side, like when a video can't be found, `throw new Error("Your video does not exist blahblah")`, which results in a 500 HTTP error using the last middleware.

Spammer or crawlers, it's common.

I've read the documentation 4 times and checked all the existing issues on GitHub, still don't have a solution.

Thanks for any advice - M.

**Comment by jsumners** [comment]
Pino is a logging library. You have described an application concern. You application should log errors at the level you would like to see them recorded.

**Comment by binarykitchen** [comment]
Well, in Node.js, as you already know, you can throw an Error, anytime, anywhere and it’s always at the error level.And in errors you can’t distinguish them with warnings. Agree, it’s an application concern, yet I feel it’s mixed.Just don’t want to wake up in the middle of the night because of some 404 if you get the message?On 2 Sep 2024, at 23:38, James Sumners ***@***.***> wrote:﻿
Pino is a logging library. You have described an application concern. You application should log errors at the level you would like to see them recorded.
