### ISSUE TITLE
Add pino.destination to an existing instance

### ISSUE THREAD

**Issue by bozzelliandrea** [pinojs/pino#2058]
Hi everyone 👋, is there a way to add a **destination** to an existing pino instance without creating a new one?

something similar to transports that can be modified inside `pino.LoggerOptions`.

My use case: I need to edit the fastify pino logger instance, without creating a new one.

**Comment by jsumners** [comment]
It is not possible. Options are parsed and solidified at creation time.

**Comment by bozzelliandrea** [comment]
Hi @jsumners, thanks for the reply, btw could this be a possible new feature?
