### ISSUE TITLE
Jest detects open handle

### ISSUE THREAD

**Issue by wi1s0n** [pinojs/pino#2085]
Hello! 
Would like to have your input on my issue!

I have been playing around with Pino the last 2 weeks. With the intention to replace Winston.

I'm struggling with two issues, and they might be the same issue, I don't know. 

My tech stack is like Mac (14.6.1), vscode (1.95.1).
yarn 1.22.22
pino 9.5.0
pino-pretty 13.0.0
jest 29.7.0
ESM.

I don't find any issue when running the logger itself, but when trying to add tests by using jest to verify my configuration, it doesn't work well. Now I just created a very basic project, doing nothing really, and added one test and it passes. But it doesn't shut down gracefully. So I would like to have your professional input and see if I do something wrong or I should do it in a different way.

package.json
```javascript
"test": "NODE_OPTIONS='--experimental-vm-modules --no-warnings=ExperimentalWarning ' jest --forceExit --detectOpenHandles"
```

![image](https://github.com/user-attachments/assets/8b4ab2cd-c65f-4b3e-a37e-7caf3a1910b3)

The thing is as well, it doesn't happen every time. Like if I run it 5 times, this error appears 4 times.

![image](https://github.com/user-attachments/assets/30d565a2-7b90-4472-bd96-c21e4ad0eb79)

I have cleaned my cache.
I have added jest openHandlesTimeout set to everything between 2000 - 10000.
I have added --forceExit. 

The other error is this, which appears in another service. In that repo I'm running both yarn locally and in docker file. But the error still appears.
![image](https://github.com/user-attachments/assets/9d205551-bed8-4f30-bd0e-04321864bce0)

index.jest.js
```javascript
import createPinoLogger from '../pinologger.js';
import { jest } from '@jest/globals';

describe('Test pino lib', () => {
    beforeEach(() => {
      jest.clearAllMocks();
    });

    it('should create a ThreadStream pino logger when NODE_ENV is "local"', () => {
      process.env.NODE_ENV = 'local';
      const logger = createPinoLogger();
  
      expect(true).toBe(true);
    });
});
```
pinologger.js
```javascript
import pino from 'pino';

function createPinoLogger() {
  return pino({
    level: process.env.LOG_LEVEL || 'info',
    msgPrefix: '[dummy] ',
    transport: {
      target: 'pino-pretty',
    },
  });
}

export default createPinoLogger;
```

If I remove the `--detectOpenHandles` it doesn't get prompted of course.

Any ideas/input? 😅

**Comment by jsumners** [comment]
Duplicate https://github.com/pinojs/pino/issues/1268
