### ISSUE TITLE
[bug?] Symbol inspection

### ISSUE THREAD

**Issue by wi1s0n** [pinojs/pino#2089]
Hey
I was looking into defined and running logger I have configured, and was interested to extract some config data to verify I have got a correct logger based on my configuration.

I ran a inspect
`console.log('logger', util.inspect(logger, { showHidden: true, depth: null, colors: true }));`

and I happen to notice the `Symbol(pino.lsCache)` object in the end, and my question is if there isn't a `}` -sign missing on every row in that object?

![image](https://github.com/user-attachments/assets/8146f629-edd4-4a69-a259-a1296fd1601b)

Have a nice day.

**Comment by mcollina** [comment]
That's expected, it's a partial JSON that is used.
