### ISSUE TITLE
Ecosystem lists should be alphabetized

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#2093]
As with #2061, the lists in https://github.com/pinojs/pino/blob/3505a688dcc7c87a618e1114d5ef47fa6ab69071/docs/ecosystem.md should be alphabetized.

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this!

**Comment by jsumners** [comment]
Feel free to jump in and work on this task!

We've decided not to assign the issue to avoid any ["cookie licking"](https://www.redhat.com/en/blog/dont-lick-cookie), so please remember these simple guidelines:

- First, check if there are any existing Pull Requests (PRs) related to this issue. Just check the notifications on this page.

- If you create a PR or draft PR, make sure to link it to this issue using the [GitHub keyword method](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). It helps keep things organized, and you'll see a nice message here.

Don't worry about whether this issue is assigned to your GitHub handle or not—just dive right in. We're all about collaboration here!
