### ISSUE TITLE
How to test pino's log output when pino is wrapped into a custom logger?

### ISSUE THREAD

**Issue by dimklose** [pinojs/pino#2096]
I have a custom logger written in TypeScript which is using pino.

Is there a way to access the log output? Actually I would like to do sth like this (which can be done with console):

`const mockInfoConsole = jest.spyOn(console, 'info').mockImplementationOnce(() => {})`
`...`
`expect(mockInfoConsole).toHaveBeenCalledTimes(1)`

**Comment by jsumners** [comment]
If you need to verify the final NDJSON of individual logs, you should supply a stream that collects the logs and then inspect that collection. See https://github.com/pinojs/pino/issues/1274#issuecomment-997971329.

**Comment by dimklose** [comment]
I found a solution by myself. I enabled my logger to redirect to a different output stream. In my test I use `sink()` from pino-test.
