### ISSUE TITLE
I would like to inline my transport, is this possible?

### ISSUE THREAD

**Issue by crskycode** [pinojs/pino#2107]
My code

```Javascript
import myTransport from './daily-transport.js?raw'

// Here "myTransport" is a string containing the transport source code.

const blobUrl = URL.createObjectURL(new Blob([myTransport], {
  type: 'text/javascript'
}))

const transport = pino.transport({
  target: blobUrl,
    options: {
      filename: 'app'
  }
})
```

I get this error

```
unable to determine transport target for "blob:nodedata:2f77800b-b2d6-49df-806b-46e1543c4af9"
```

My question: is it possible to load transport in this method?

**Comment by mcollina** [comment]
```
import myTransport from './daily-transport.js?raw'
```

I'm not sure what this does, but I've never seen it.

---

No, it's not possible atm. PRs are welcome.

**Comment by crskycode** [comment]
> ```
> import myTransport from './daily-transport.js?raw'
> ```
> 
> I'm not sure what this does, but I've never seen it.
> 
> No, it's not possible atm. PRs are welcome.

This `import` keyword is processed by vite. I'm using electron-builder to pack my electron app.

I know this method works in the browser. See https://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string

I'm not sure if node has the ability to load a worker from a blob url

Thanks for your reply
