### ISSUE TITLE
unbound pino crashes against expectation

### ISSUE THREAD

**Issue by cdaringe** [pinojs/pino#2109]
# Problem

`foo().then(proceed, logger.error)`, where `logger` is a `pino` instance, yields

```
/project/node_modules/.pnpm/pino@9.5.0/node_modules/pino/lib/tools.js:59
      if (typeof this[msgPrefixSym] === 'string' && msg !== undefined && msg !== null) {
                     ^
```

It's a bit rare these days that we hit _this_ binding errors.

# Discussion

Can `pino` either a) pre-bind its references, or b) detect and give more user friendly binding assumptions up front?

**Comment by mcollina** [comment]
The problem is that binding all functions has a performance overhead, specifically when using child loggers. Thanks for your feedback, but I don't see this changing in the future.
