### ISSUE TITLE
pino.child , context object plus the new 4.2.0 browser.asObject API

### ISSUE THREAD

**Issue by temsa** [pinojs/pino#220]
When logging using a one level `child`, a context object during the logging and a string message, using the new `browser` `asObject` API:
- the `msg` is filled with the `child` context object ( https://github.com/pinojs/pino/blob/master/browser.js#L70 )
- `args[args.length -1]` contains the actual `msg` content, not args[0]

The result  either having a context object, and/or childs, is not having the actual `msg` content in the `msg` property

**Comment by temsa** [comment]
I'm preparing a PR to fix this, just switching to `args[args.length -1]` does not seem to solve everything, still investigating :)

**Comment by davidmarkclements** [comment]
thanks for repoting @temsa - got a fix for it in #223
