### ISSUE TITLE
message / object merging bug

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#221]
```
const pino = require('./')()

pino.info({a: 1}) 
// => {"pid":5630,"hostname":"x","level":30,"time":1490212859240,"a":1,"v":1}

pino.info({a: 1}, {b: 2})

// => {"pid":5630,"hostname":"x","level":30,"time":1490212859243,"msg":"[object Object]","a":1,"v":1}

pino.info({a: 1}, {b: 2}, {c: 3})

// => {"pid":5630,"hostname":"xl","level":30,"time":1490212859249,"msg":"{\"b\":2} {\"c\":3}","a":1,"v":1}
```

I would suggest that if there's no string, just copy properties across. 

However, if we have two objects with same key, one will overwrite the other - however putting them in the `msg` string means they'll both appear and it's valid JSON. 

So, I think we just have to fix `[object Object]` output

**Comment by davidmarkclements** [comment]
On the other hand - we already have this caveat with child loggers (keys may overwrite) 

so... maybe it's better to merge all objects? 

but then you have to think about if, say, the 5th param is a string, what do you do then?

I think it has to be a string...

**Comment by marcbachmann** [comment]
Yes, I think merging them is the expected behavior.
Regarding the string, maybe we can append the string separated by newline to the `msg` property.
So we would have to keep the msg context until all arguments are stringified.

```js
pino.info({a: 1}, 'b', 'c')

// => {"pid":5630,"hostname":"xl","level":30,"time":1490212859249,"msg":"b\nc","a":1,"v":1}
```

**Comment by davidmarkclements** [comment]
when you say merge - do you mean - merge them into the top level object, or do you mean merge them into the string

because I'm saying - I would *like* that merging them into top level object is the right thing

but I don't think it is the right thing - because it's ok to overwrite when dealing with child loggers (because that's an interface, you have to think about it) but not if you throwing several objects into a logger - in that case you want to make sure you see every key, which means it has to go into the msg string 

also this `pino.info({a: 1}, {b: 2}, 'hi', {c: 3})` gives `{"pid":7776,"hostname":"Davids-MacBook-Pro.local","level":30,"time":1490215091751,"msg":"{\"b\":2} \"hi\" {\"c\":3}","a":1,"v":1}`

But if you merge into object, what then? merge everything before the string param, then run everything after through format? 

I don't think the newline is necessary? currently we already delimit with spaces (pino.info('a', '

**Comment by marcbachmann** [comment]
> when you say merge - do you mean - merge them into the top level object, or do you mean merge them into the string

Yes, I'd merge them into the root object.

> but I don't think it is the right thing - because it's ok to overwrite when dealing with child loggers (because that's an interface, you have to think about it) but not if you throwing several objects into a logger - in that case you want to make sure you see every key, which means it has to go into the msg string

I chose to use pino because it generates json and thereby it is filterable on platforms like loggly, not only because it's the fastest.

I'd really overwrite all existing values. If somebody wants to prevent a property from getting overwritten, they should create a new object. e.g. `child.info({childmsg: {msg}})`.
But then, we can do that also automatically, for example automatically create a `child0` property for the first child, `child1` for the second and so on.

**Comment by marcbachmann** [comment]
I wouldn't support formatted strings unless it's at the first position.

**Comment by jsumners** [comment]
Is there a use case for logging multiple objects that I'm not aware of?

**Comment by davidmarkclements** [comment]
good points there @marcbachmann 

so we just ignore strings not in the first position?

@jsumners you mean, why do it in the first place? space saving?

**Comment by davidmarkclements** [comment]
also - just to note - if we change this at all we'll have to update browser now pino too (since the introduction of write hooks and asObject mode)

**Comment by jsumners** [comment]
I mean, what is the use case for `log.info({obj: 1}, {obj: 2})`? I think if you're doing this, you should probably be explicit in your desire and `log.info('Original: %j, Mutated: %j', {obj: 1}, {obj: 2})`.

**Comment by davidmarkclements** [comment]
agree on that

@mcollina - fancy a new major release?

**Comment by mcollina** [comment]
We never supported `pino.info({a: 1}, {b: 2})`. This is a highly costly operation, and I avoided it since the very early beginning, because otherwise we would lose a lot of throughput. I'm happy if anyone can implement that _without losing throughput_.

> Is there a use case for logging multiple objects that I'm not aware of?

@jsumners I do not see any, but it seems @marcbachmann and @davidmarkclements see a case for this. Can you articulate this further?

> I mean, what is the use case for log.info({obj: 1}, {obj: 2})? I think if you're doing this, you should probably be explicit in your desire and log.info('Original: %j, Mutated: %j', {obj: 1}, {obj: 2}).

This is how I would do that.

> fancy a new major release?

For what?

**Comment by jsumners** [comment]
ping: @davidmarkclements

**Comment by davidmarkclements** [comment]
happy to close this I think
