### ISSUE TITLE
create an npm org

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#225]
https://www.npmjs.com/features

what do you folk think?

**Comment by davidmarkclements** [comment]
yes - totes - when did they become free?

**Comment by mcollina** [comment]
today
Il giorno gio 23 mar 2017 alle 15:39 David Mark Clements <
notifications@github.com> ha scritto:

**Comment by jsumners** [comment]
I am in full support of this awesomeness.

**Comment by mcollina** [comment]
that's done :)

**Comment by davidmarkclements** [comment]
can I open this again? it's true we've create the org but we've not moved any packages across 

I'm going to move the packages that I can across now, there will prob be some left over (like pino-arborsculpture for instance)

**Comment by davidmarkclements** [comment]
wait a sec - wont this mean installing with scope instead - e.g. `@pino/pino` and `@pino/http` etc? 

is that what we want? what's the purpose of the org?

**Comment by davidmarkclements** [comment]
ok no it's fine it doesn't enforce scoping - but we could use the `@pinojs` namespace for incubating experiments? 

I'll move what I can over

**Comment by davidmarkclements** [comment]
https://www.npmjs.com/package/pino-debug
https://www.npmjs.com/package/pino-http-print
https://www.npmjs.com/package/pino-http
https://www.npmjs.com/package/koa-pino-logger
https://www.npmjs.com/package/pino-trace
https://www.npmjs.com/package/restify-pino-logger
https://www.npmjs.com/package/pino-noir
https://www.npmjs.com/package/rill-pino-logger

added to org

**Comment by davidmarkclements** [comment]
I think permissions to move are based on last person to publish - for instance I can't move express-pino-logger because @mcollina was the last person to publish

**Comment by jsumners** [comment]
I'll move my things soon.

**Comment by mcollina** [comment]
How do I move a module?

**Comment by mcollina** [comment]
I moved my things.

**Comment by jsumners** [comment]
I moved mine.

**Comment by davidmarkclements** [comment]
sweet - closing
