### ISSUE TITLE
Pump in devDependencies

### ISSUE THREAD

**Issue by justechn** [pinojs/pino#227]
You have the pump package in both dependencies and devDependencies in the package.json. I believe this makes it so that npm prune --production will remove the pump library, which breaks pino.

https://docs.npmjs.com/cli/prune

> If the --production flag is specified or the NODE_ENV environment variable is set to production, this command will remove the packages specified in your devDependencies. Setting --production=false will negate NODE_ENV being set to production.

you should probably remove pump from devDependencies

**Comment by mcollina** [comment]
Fixed in v4.2.3
