### ISSUE TITLE
Log Object should not be able to change default keys

### ISSUE THREAD

**Issue by MechanicalHuman** [pinojs/pino#230]
Currently if an object has a key named after a default key it will override it. Is this by design?  
Generally it shouldn't be a problem as sending a custom object is the appropriate way but the err-serializer doesn't follow that convention.  
Ex: _Monngose Errors include the key `name` so the serializer changes the logger name_

**Comment by jsumners** [comment]
Generally, yes -- https://github.com/pinojs/pino#duplicate-keys

But maybe the error serializer should serialize to a scoped object? cc: @davidmarkclements @mcollina 

https://github.com/pinojs/pino/blob/master/docs/API.md#err

Instead of the above, maybe:

```
{
  "pid": 40510,
  "hostname": "MBP-di-Matteo",
  "level": 50,
  "msg": "an error",
  "time": 1459433282301,
  "v": 1,
  "obj": {
    "message": "an error",
    "type":  "Error",
    "stack": "Error: an error\n    at Object.<anonymous> (/Users/matteo/Repositories/pino/example.js:16:7)\n    at Module._compile (module.js:435:26)\n    at Object.Module._extensions..js (module.js:442:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:313:12)\n    at Function.Module.runMain (module.js:467:10)\n    at startup (node.js:136:18)\n    at node.js:963:3"
  }
}
```

**Comment by MechanicalHuman** [comment]
Probably better to do: 

````JSON
{
  "pid": 40510,
  "hostname": "MBP-di-Matteo",
  "level": 50,
  "msg": "an error",
  "time": 1459433282301,
  "v": 1,
  "err": {
    "message": "an error",
    "type":  "Error",
    "stack": "Error: an error\n    at Object.<anonymous> (/Users/matteo/Repositories/pino/example.js:16:7)\n    at Module._compile (module.js:435:26)\n    at Object.Module._extensions..js (module.js:442:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:313:12)\n    at Function.Module.runMain (module.js:467:10)\n    at startup (node.js:136:18)\n    at node.js:963:3"
  }
}
````

**Comment by mcollina** [comment]
@MechanicalHuman if that's your issue, you can easily achieve that by:

```js
logger.error({ err }, 'something bad happened')
```

I'm 👎  on changing the current behavior.

**Comment by jsumners** [comment]
@mcollina isn't that the only way to use the serializer, to pass in an object with the 'err' property?

**Comment by mcollina** [comment]
if an `Error` object is passed in, it's treated in a special way: https://github.com/pinojs/pino/blob/master/pino.js#L131-L133.

Anyway, I think the only way to avoid the conflicting property is to wrap it into another object.

**Comment by jsumners** [comment]
I see. I thought we were talking about the standard error serializer since @MechanicalHuman referenced it in his original post.

**Comment by jsumners** [comment]
@MechanicalHuman before I close this, can you provide a snippet of sample code showing what originally led to the report?

**Comment by MechanicalHuman** [comment]
@mcollina yeah that's definitely the source of the issue. Wrapping it in an object will do for now, if I think on something clever I'll do a PR
