### ISSUE TITLE
configurable `msg` property name?

### ISSUE THREAD

**Issue by mmcgahan** [pinojs/pino#231]
This looks like a great tool, and I'm eager to use it on an app that I'm using with Stackdriver on Google Cloud.

Stackdriver plays nicely with JSON logs, but will automatically use a `message` property in the JSON object to label the log output, while Pino favors a hard-coded `msg` prop for similar functionality - would there be interest in making `msg` configurable or should I just manually assign `message` in the object I pass to the logger?

The downside of the latter option is that I wouldn't get the highlighted `msg` string in the pretty-printed logs in dev.

**Comment by mcollina** [comment]
I'm open to a PR on this if it does not slow things down.
Would you like to assemble a PR?

**Comment by mmcgahan** [comment]
I can put together a PR, but probably not right away - as long as there aren't any major blockers on on your end, I'll put that on my todo list, thanks
