### ISSUE TITLE
Finishing pino-mongodb

### ISSUE THREAD

**Issue by Kuroljov** [pinojs/pino#236]
Hello again. I have time to finish this module and it would be great if we will include it to the `pino` group. Could you explain me what type of benchmarks are required? `pino-elasticsearch` do not have any. `pino-noir` is basically another type of module and because it interacts with `pino` interface we can benchmark it. `pino-mongodb` even do not have `pino` interface so how do I benchmark it?

**Comment by jsumners** [comment]
Duplicate #109 .
