### ISSUE TITLE
How to use Serializers?

### ISSUE THREAD

**Issue by jbcpollak** [pinojs/pino#238]
I'd like to experiment with migrating from bunyan to pino, but one of the things we need is serializers. 

I searched the issues and I see some references to them, but I don't see them in the documentation. 

Are they still available? If so, could something be added to the readme about how to use them?

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/master/docs/API.md#parameters

Also, see the tests -- https://github.com/pinojs/pino/blob/master/test/serializers.test.js

**Comment by jsumners** [comment]
@jbcpollak has your question been answered?

**Comment by jbcpollak** [comment]
Yes, thanks. 

I didn't see the link to API on the main Readme.md and didn't know there was a docs directory. I guess that could be a bit more obvious, but thanks! 👍
