### ISSUE TITLE
Add a custom output format for shell utility

### ISSUE THREAD

**Issue by serge1peshcoff** [pinojs/pino#242]
It would be cool to have the possibility to specify the custom output format when piping logs to `pino`.

For example, my logs outputs this format (not counting the default fields):

```
{ "category": 'some_category", "message": "some_message" }
```

And I want to have the output in such format:

```
${timestamp} [${category}] ${message}
```

So my message would look like:

```
2017-05-05T19:43:46.874Z [some_category] some_message
```

I know I can specify the messagey key, but not the category key, and anyway it would be cool and useful (at least for me).

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/master/docs/API.md#pretty

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/eda4f9ba659ddbf860fa407f03b851062eede737/test/pretty.test.js#L67-L79

**Comment by davidmarkclements** [comment]
http://npm.im/pino-toke will make specifying your format easy (also takes a function for custom keys). For best performance, run the formatting as a separate process (see pino-toke readme)

**Comment by jsumners** [comment]
Do these links solve your issue @serge1peshcoff ?

**Comment by serge1peshcoff** [comment]
I think they do, thanks for linking.

**Comment by jsumners** [comment]
Excellent. If you can think of a way to improve the documentation to make this clearer/more obvious, don't hesitate to send in a PR.
