### ISSUE TITLE
Invalid time value with prettyPrint and timestamp:false

### ISSUE THREAD

**Issue by PatrickHeneise** [pinojs/pino#243]
> node app.js | pino

```
/myp/node_modules/pino/pretty.js:130
    return new Date(time).toISOString()

RangeError: Invalid time value
```

This happens when you set `prettyPrint` true (or pipe the output to pino without timestamps)

**Comment by mcollina** [comment]
Good job in finding this!

**Comment by PatrickHeneise** [comment]
Right, I couldn't find pino-colada .. maybe a 'Reporters' section would be good in the Readme
