### ISSUE TITLE
Pino always show custom levels if they were added after the logging level is set

### ISSUE THREAD

**Issue by bbonagura9** [pinojs/pino#246]
**Here's a test code**

```javascript
const pino = require('pino')({
  level: 'info'
})
pino.addLevel('verbose', 25)
pino.addLevel('silly', 5)

pino.fatal('fatal')
pino.error('error')
pino.warn('warn')
pino.info('info')
pino.verbose('verbose')
pino.debug('debug')
pino.trace('trace')
pino.silly('silly')
```

**Output**
```
{"pid":5484,"hostname":"bruno-All-Series","level":60,"time":1495832557805,"msg":"fatal","v":1}
{"pid":5484,"hostname":"bruno-All-Series","level":50,"time":1495832557806,"msg":"error","v":1}
{"pid":5484,"hostname":"bruno-All-Series","level":40,"time":1495832557807,"msg":"warn","v":1}
{"pid":5484,"hostname":"bruno-All-Series","level":30,"time":1495832557807,"msg":"info","v":1}
{"pid":5484,"hostname":"bruno-All-Series","level":25,"time":1495832557807,"msg":"verbose","v":1}
{"pid":5484,"hostname":"bruno-All-Series","level":5,"time":1495832557807,"msg":"silly","v":1}
```

**Ther last two lines shouldn't be printed.**

The workaround we found is to set the logging level after the addLevel calls:

```javascript
const pino = require('pino')()
pino.addLevel('verbose', 25)
pino.addLevel('silly', 5)
pino.level = 'info'

pino.fatal('fatal')
pino.error('error')
pino.warn('warn')
pino.info('info')
pino.verbose('verbose')
pino.debug('debug')
pino.trace('trace')
pino.silly('silly')
```

I'm not sure whether it is an undocumented requirement or a bug. Either way it would be nice do document or fix it. I wasted a few hours trying to fix it.

**Comment by jsumners** [comment]
[Documentation](https://github.com/pinojs/pino/blob/e3bbb2496fdf376021c35330693088d20c09aaee/docs/API.md#discussion-11):

> When using this method, the current level of the logger instance does not change. You must adjust the level with the level property after adding your custom level.

Therefore, bug.

**Comment by bbonagura9** [comment]
Maybe it's [this line](https://github.com/pinojs/pino/blob/master/pino.js#L236) that set the custom level log function regardless of the current levelVal setup. It should be `noop` if the custom level value is smaller than the levelVal.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by bbonagura9** [comment]
Yes. I need write permissions to do so, right?
I've already branched and fixed it locally.

**Comment by jsumners** [comment]
Excellent. I wasn't sure when I would get to it.

1. Fork the project
2. Clone your fork
3. Put your fix on a feature branch
4. Push your branch to your fork on GitHub
5. Use GitHub to create a Pull Request
