### ISSUE TITLE
How to pretty print logs after it was logged into a file as JSON?

### ISSUE THREAD

**Issue by kinghadi** [pinojs/pino#250]
Hi :)

Is there any way to pretty print logs after they are saved into a file as JSON format? I mean, suppose we have the following log saved into file:

```
{"pid":2640,"hostname":"hdhd-srv","level":30,"time":1496236280290,"msg":"API endpoints are configured (NODE_ENV= PROD)","app":"api-server","tags":"dev","t":1496236280289,"ip":"localhost","port":"8085","v":1}
{"pid":2640,"hostname":"hdhd-srv","level":30,"time":1496236280838,"msg":"nothing to be cached","app":"api-server","tags":"dev","t":1496236280838,"v":1}
{"pid":2640,"hostname":"hdhd-srv","level":30,"time":1496236280838,"msg":"api server is running :)","app":"api-server","tags":"dev","t":1496236280838,"v":1}
```

Then we can do something like the following:
```
cat logs | ./node_modules/pino/pretty.js 
```
and it will print in the way pretty prints?

**Comment by jsumners** [comment]
`cat logs | pino`

**Comment by mcollina** [comment]
You will need to install pino globally for that. You can also use
pino-colada.
Il giorno mer 31 mag 2017 alle 15:44 James Sumners <notifications@github.com>
ha scritto:

**Comment by kinghadi** [comment]
Thank you @jsumners @mcollina :+1: 
I tested the following and it worked. I think I don't need to install it globally:

```
cat logs | ./node_modules/pino/bin.js
```
