### ISSUE TITLE
Poll: should we continue striving for Bunyan API compatibility?

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#256]
As the title says, should we continue comparing our API, and new features, to that of Bunyan's? That is, are we okay with being our own thing now and not worrying about being a drop-in replacement going forward?

Community: please feel welcome to cast your vote.

Vote with a thumbs up or thumbs down. Comment with concerns/support.

👍  = move forward with Pino's own API
👎  = continue trying to remain faithful to Bunyan's API as much as possible

2017-06-29: To clarify, this is solely about the configuration options passed to the constructor. The resulting log line API is set and not expected to change.

Also, I will close this poll on or after July 31. That should be plenty of time for this poll.

2017-08-01: I am closing this poll. It has 10 up votes and 5 down votes at the time of closure. Therefore, if we come up with a feature that should be added, and it cannot easily be incorporated in such a fashion as to maintain _constructor_ API compatibility with Bunyan, we will go our own route.

![2017-08-01 17-27-43 poll should we continue striving for bunyan api compatibility issue 256 pinojs pino](https://user-images.githubusercontent.com/321201/28847963-1dbcb888-76df-11e7-8b7c-d0fbfdb6910e.png)

**Comment by yunong** [comment]
Supporting the same schema for logging output would be nice. Bunyan ships with a very nice CLI, and if we can keep the output of Pino the same as Bunyan, it means we don't have to do additional work to migrate the features from the Bunyan CLI over to Pino, and folks can continue to use Pino with the Bunyan CLI.

**Comment by jsumners** [comment]
@yunong let me clarify: this is only in regard to configuration of the logger. The output format is set and unlikely to ever change.

**Comment by davidmarkclements** [comment]
I think *feature parity* will always remain a must but API differences I'm okay with as long as there's a performance reason. Providing transitional API integration (for bunyan and other loggers) via pino ecosystem modules at a speed trade-off is the best approach, imo.

**Comment by mcollina** [comment]
Here are the things I think should stay the same:

a. log-level methods will keep having the current signature, those are locked.
b. the log-line schema is versioned, but it would likely stay the same for the future

The question is _only_ about the configuration options. Is this correct @jsumners?

@yunong are you ok if we change/offer different configuration option compared to Bunyan, if the rest stays the same?

**Comment by jsumners** [comment]
@mcollina that is correct. I should have been clearer.

**Comment by yunong** [comment]
@mcollina it'd be nice to keep the APIs the same. As a maintainer of restify -- I'd like to continue telling my customers they can use either bunyan or pino, that will offer them flexibility. Tho I suspect we could do some introspection in restify to figure out if a logger they've passed in is a pino logger or a bunyan logger.

**Comment by mcollina** [comment]
@yunong yes! That will never change. We are talking just about the options in the constructor of `pino()`.

**Comment by jsumners** [comment]
I have updated the original post to clarify my intention with the question. I have also given the poll a lifetime until the end of July.

**Comment by cncolder** [comment]
Forget bunyan. It waste me two day to try integrate with webpack. Finally I GIVE UP.

I love pino browser write. Easily send log to cloud service.

**Comment by jsumners** [comment]
This poll is now concluded with 10 up votes and 5 down votes. As a result, if necessary our constructor API may diverge from Bunyan compatibility.
