### ISSUE TITLE
Question: Flush on exit with extreme mode off

### ISSUE THREAD

**Issue by ccs018** [pinojs/pino#257]
I've read through the docs and issue #92 (and referenced issues), but have the following question:

If extreme mode is **off**, is there an issue with writing a log event to a file immediately prior to exiting?  For example:

logger.fatal('bad thing happened');
process.exit(1);

Using Bunyan, that last fatal event is not flushed to the log file.  We've implemented a work-around which works well.  We are considering swapping out Bunyan for Pino, but we'd like to know if this handled natively by Pino.

I like the added performance of extreme mode, but not sure the risk of losing events under extreme failures will be acceptable.

Our environment is Node v6.10.3 and Debian 8.7 (jessie).

**Comment by jsumners** [comment]
It's easy to test:

```
[jsumners@sumners-osx] /tmp/07
% cat baz.js    
'use strict'

const log = require('pino')()
log.fatal('bad thing happened')
process.exit(1)
[jsumners@sumners-osx] /tmp/07
% node baz.js                     
{"pid":11705,"hostname":"sumners-osx.int.clayton.edu","level":60,"time":1496858415837,"msg":"bad thing happened","v":1}
```

Basically, as long as Node itself finishes processing the stream, then the messages will be written. The caveat with extreme mode is that we buffer messages before writing them in that mode. In the normal mode, we write messages directly to the stream as fast as we can.

**Comment by ccs018** [comment]
Thanks.  I guess I should have tried that test code myself.  But it doesn't sound like that there is anything explicitly done to ensure that the stream was flushed to disk.  That's what we did to work around this issue using Bunyan.  We created a new method which calls logger.fatal(), gets the logger's fd, sets a handler for the finish event, and end()'s the stream.  The handler for the finish event then calls process.exit.

**Comment by jsumners** [comment]
@ccs018 well, in extreme mode we do flush synchronously when a `process.exit` event gets fired -- https://github.com/pinojs/pino/blob/36f416761629997b99f8e62e54dec27598e955cc/pino.js#L302-L311

Short of the OS killing the process prior to Node finishing its work, this is as good as we can do.

If you think there is a better way to handle this sort of scenario outside of extreme mode, please submit a PR. We'd be happy to review it.

**Comment by ccs018** [comment]
When we get around to swapping out Bunyan, I'll be sure to check if this is an issue in our environment.  While I haven't looked at your code, just based on the discussion in issue #92, it would appear that the scenario isn't too different - just a much shorter window for data loss in normal mode.  If we experience the same issue as with Bunyan, it could be that the solution you've implemented for issue #92 could be extended to include normal mode.

**Comment by mcollina** [comment]
@ccs108 that solution works only is there is data to be flushed out in pino. In normal mode, data is being queued up in libuv.

**Comment by jsumners** [comment]
@ccs018 the problem with that, is that we are a logger. We shouldn't be interfering with process management. By registering an event handler with `process.on('exit')`, Node will no longer handle everything; it is then up to the application. We compromise in extreme mode by making it clear in the documentation that we change how process exit is handled because we need to try our best to clear the buffer _internal to Pino_. In normal mode, the standard streams API is taking care of its own buffer.

**Comment by davidmarkclements** [comment]
I'm guessing Bunyan must do it's own buffering outside of libuv

In normal mode we write each log message directly to the stream, if this stream is a I/O stream (or pipes to an I/O stream) then as @mcollina says, it's going straight to libuv.

If there is any queued data in libuv not being flushed on exit/crash then this is a Node issue

If we can prove a scenario where data isn't flushed, we should open an issue on node core, 
and possibly document a temporary work around

**Comment by ccs018** [comment]
@jsumners I hear what you're saying.  In our work around, we aren't interfering with process management by registering an event handler with `process.on('exit')`.  Rather the application is explicitly calling a new method which logs a fatal event and exits.  This `fatalExit()` method simply delays the call to process.exit() until the stream has been flushed & closed.

@davidmarkclements It's possible that Bunyan is doing some other buffering or there's an issue in Node.  I can only report what I observed where the last log event immediately before an exit is not appearing in the log file.  We are writing to both stdout and a log file (which we probably shouldn't be doing in the first place) and I see the event while using journalctl, but not in the log file (as it wasn't being scrapped by tdagent).  Others had raised this in the Bunyan repo some time ago and no one suggested this was an issue in Node, rather the discussion was around changing Bunyan (which never happened).  The belief was that the file write is asynchronous and so the `process.exit()` was taking place before the file write could be complete.

As I said, I'll be sure to check this when we swap Bunyan for Pino and let you know what we find.  Worse case, we simply continue to use our `fatalExit()` method with Pino.

**Comment by mcollina** [comment]
I think this have been fully discussed, but feel free to reopen if you think otherwise.
