### ISSUE TITLE
Question: is there a pino-request or pino-api

### ISSUE THREAD

**Issue by doron2402** [pinojs/pino#261]
I've checked and couldn't find any info about it. 
I'm looking for a Pino "plugin" to post logs to an external API, is it exist?
If not would be more than happy to create one

**Comment by mcollina** [comment]
As far as I know there isn't! Feel free to do one, let us know how you get on, we can help!

**Comment by doron2402** [comment]
Cool thanks for the quick response

**Comment by davidmarkclements** [comment]
wait...

when you say "post logs to an external API" 

do you mean something like [`pino-socket`](http://npm.im/pino-socket) but that's an HTTP client instead of a TCP client?

**Comment by doron2402** [comment]
@davidmarkclements  yeah over HTTP (with the option to have authorization header) I know it's not ideal or fast

**Comment by marcbachmann** [comment]
That would be interesting especially when pino is used in the browser.

Maybe a pull-stream based api would be good there to ensure that values are saved properly.
```js
const stream = pullStreamToStream(pull(cacheInLocalStorage(), postToServer()))
pino(stream)
```

**Comment by doron2402** [comment]
I thought about adding a buffer same as `good`  that you can define the number of logs before posting it to the remote end-point.

for ex' every 10 logs (object) post it. so you don't make a request every time you log.

**Comment by max-l** [comment]
Has this been implemented ?

**Comment by max-l** [comment]
https://github.com/sventschui/pino-transmit-http
