### ISSUE TITLE
Question: extra info for all messages

### ISSUE THREAD

**Issue by itavy** [pinojs/pino#271]
Hi,

i need to add same metadata for all messages, because they are needed on a logstash collector;
i wonder if this could be set when i instantiate the logger and then it will be appended for all messages?

Thank you,

**Comment by davidmarkclements** [comment]
hey @itavy hows things?

Absolutely this is what child loggers are for, see https://github.com/pinojs/pino/blob/master/docs/API.md#child

**Comment by itavy** [comment]
hi,

that was my problem; in child loggers i have those info and in parent logger i don't have them;
i think i can use this setup with child loggers only and main logger won't be used.

Thank you,

**Comment by itavy** [comment]
Hi,

after i try this setup i run in another problem; each module i am using has its own name and creating a hierarchy of loggers it will append module name on each child, but on parsing message the name of the module is unpredictable because of https://github.com/pinojs/pino#duplicate-keys

**Comment by davidmarkclements** [comment]
hi @itavy - yes the usual recommendation is create a single child logger as your main logger for all static meta data - and spawn child loggers off that as needed 

Parsing an object (with `JSON.parse` that is) with duplicate keys will always result in the *last* key being used - so it's is deterministic in that sense - where it be unreliable or flaky is if you're using other parsers in different languages - you could overcome that using a transport that simply parses and reserializes to normalize the data.

e.g. say we have a file `normalize.js`:

```js
'use strict'
var ndjson = require('ndjson')
var pump = require('pump')

pump(process.stdin, ndjson.parse(), ndjson.serialize(), process.stdout)
```

Now I can test this like so:

```sh
echo '{"module": "a", "module": "b"}' | node normalize.js
```
It will output

```sh
{"module":"b"}
```

So if, say your application is called `app.js` and your using pino defaults (that is logs are going to stdout): 

```sh
node app.js | node normalize.js
```

**Comment by itavy** [comment]
hi,

that will solve my problem with parsing (the parser in logstash is written in ruby); i will try this setup and it seems that it will solve the requirement for my application :)

Thank you for support

**Comment by davidmarkclements** [comment]
a pleasure! closing for now

**Comment by jsumners** [comment]
FYI: I find https://www.npmjs.com/package/@sematext/logagent to be a fantastic way to ship logs to a remote Elastic Search instance (or whatever else).

And on the receiving side, I don't even bother with Logstash (or whatever it is) as a receiver. I simply have: `socat -T 0.5 -u tcp4-listen:8888,fork,reuseaddr,su=nobody tcp4:127.0.0.1:9200`.

As a systemd unit:

```toml
[Unit]
Description=Pass logs into ElasticSearch
After=network.target

[Service]
Restart=always
RestartSec=10
ExecStart=/bin/socat -T 0.5 -u tcp4-listen:8888,fork,reuseaddr,su=nobody tcp4:127.0.0.1:9200

[Install]
WantedBy=multi-user.target
```
