### ISSUE TITLE
Ecosystem doc page

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#272]
@davidmarkclements have a nice diagram of our ecosystem, and I think we should provide a list of all the modules around pino.

**Comment by jsumners** [comment]
I think that is an impossible list to maintain. Even https://www.npmjs.com/search?q=keywords:pino&page=1&ranking=optimal won't show them all because not every module is tagged with "pino" (e.g. the `pino-http` module).

**Comment by mcollina** [comment]
Usually a community curated page solve all those. People that do pino modules can (and should) contribute there.

**Comment by jsumners** [comment]
I'm not opposed. I just think it'll be a lot of maintenance.
