### ISSUE TITLE
Bind pino to namespace, so I'm able to track transactionId

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [pinojs/pino#273]
Hey there,
I'm trying to implement `continuation-local-storage` so I'm able to create a child log with a transactionId, which is quite handy when you want to track all logs of a particular request.

https://github.com/othiym23/node-continuation-local-storage

https://stackoverflow.com/questions/25880816/nodejs-transactionid-with-continuation-local-storage

I think I have to bind pino to the namespace somehow. Do you guys have any idea how to do this? :)

**Comment by mcollina** [comment]
We tried something similar with https://www.npmjs.com/package/pino-trace.
However we did not update it in a very long time, and it was not working very well.
Maybe a new approach on top of Node 8 async hooks would be nice.

 cc @davidmarkclements

**Comment by GuilhermeMedeiros** [comment]
Sounds good @mcollina. Although`continuation-local-storage` seems like an easy solution and it doesn't depend on Node 8.

**Comment by mcollina** [comment]
@GuilhermeMedeiros I would recommend using Node 8 and async-hooks if you want to code something using this style. There are plenty of edge cases where the async-hooks approach would perform better, and it would be more reliable in the long run.

**Comment by GuilhermeMedeiros** [comment]
@davidmarkclements any ideas? :)

**Comment by deividasjackus** [comment]
+1

**Comment by mcollina** [comment]
So, why don't you:

```js
var getNamespace = require('continuation-local-storage').getNamespace;
var session = getNamespace('my session');

// in your route
session.set('log', pino.child({ transactioId: id }))

// to log
session.get('log').info('hello world')
```

**Comment by GuilhermeMedeiros** [comment]
yes, I was able to do something like that:

```js
// log.js file 
const appName = 'myApp'
const session = require('{..}/session')
const environment = process.env.ENVIRONMENT
const pino = require('pino')({
    level: 'trace', 
}).child({
    appname: appName,
    environment: environment,
})

const wrap = key => (...args) => (session.get('log') || pino)[key](...args)

module.exports = {
    // set the log to the session (hopefully with transactionId)
    setSession: (...args) => session.set('log', pino.child(...args)),

    // wrap pino functions
    info: wrap('info'),
    error: wrap('error'),
    warn: wrap('warn'),
    child: wrap('child'),
    debug: wrap('debug'),
    trace: wrap('trace'),
}
```

```js
//middleware.js

const log = require('{...}/log')
const session = require('{...}/session')

module.exports = function (req, res, next) {
    const transactionId = req.headers.transactionId || uuidV4()

    session.run(() => {
        log.setSession({
            transactionId: transactionId,
        })

        next()
    })
}
```


and then finally on any function that was triggered by a request:
```js
// myService.js
const log = require('{..}/log')

module.exports = function() {
    log.info('yeyy I have transactionId!!!')
}

```
