### ISSUE TITLE
How to return log object, to store it in a variable.

### ISSUE THREAD

**Issue by snaerth** [pinojs/pino#275]
Hi all,

Thank you for this blazing fast library. I am wondering how can I return pino log object and store it in a variable. I need to for example store the object in db or to save the object in a error-log with fs.appendFile

For example I was trying to store the the log in a variable
```
import pino from 'pino';
import ErrorLog from '../models/log';

/**
 * Logs error messages to db
 * @param {Any} message
 * @returns {Promise}
 */
export default function logError(message) {
  return new Promise((resolve, reject) => {
    try {
      const errorLog = new ErrorLog(pino().info(message));
      errorLog.save((error) => {
        if (error) {
          return reject(error);
        }

        return resolve();
      });
    } catch (error) {
      throw new Error(error);
    }
  });
}
```

#help wanted

Thank you

**Comment by jsumners** [comment]
Our normal response for this is https://github.com/pinojs/pino/blob/master/docs/transports.md

For an introduction as to why, and for a potential method for solving your direct desire, see https://github.com/pinojs/pino#transports

**Comment by davidmarkclements** [comment]
you'll also need to know about streams if you don't already

https://nodejs.org/dist/latest-v8.x/docs/api/stream.html
https://github.com/substack/stream-handbook
https://github.com/workshopper/stream-adventure

**Comment by jsumners** [comment]
I am closing this because I think it has been sufficiently answered. Please re-open if you have further questions.
