### ISSUE TITLE
Not inspecting surplus arguments

### ISSUE THREAD

**Issue by asafh** [pinojs/pino#281]
While the API doc for the logging methods describes
> ... If more args follows msg, these will be used to format msg using util.format.  

The actual behaviour is different when sending more arguments than interpolation placeholders. While console.log, util.format and the npm module 'debug' all behave similarly (concatenating with space these extras after running them through util.inspect), pino simply truncates these extra arguments - tools.js:94:
`        n.length = l + countInterp(a, '%d') + countInterp(a, '%s') + 1
`  
Doesn't necessarily feel like a speed optimization since it just blocks this use case (to avoid these objects being inspected, don't send them in the first place - same result).  
If this makes sense to you too, would the correct logic to apply in genLog be: if no %j and countInterp(%j,%d,%s) <= n.length we can call quick escape, otherwise pass all of n into util.format.

What do you think?

**Comment by mcollina** [comment]
Can you make an example with how pino behaves now, and how you would like it to behave?

**Comment by asafh** [comment]
For this code:
```
const util = require("util");
const pino = require('pino')({});
const additionalObject = new Error("ErrName");
const value = "fromInteropt";
pino.info("pino %s", value, additionalObject);
console.log("console interopt=%s", value, additionalObject);

const debug = require("debug")("debug-tag");
debug("debug interopt=%s", value, additionalObject);
```
You can see both console and debug print the error message and stack, while pino only prints an empty object (though earlier I thought even that doesn't happen, I should investigate further).
```
$ DEBUG=* node test.js
{"pid":14342,"hostname":"asafh-mac.local","level":30,"time":1502110326544,"msg":"pino fromInteropt {}","v":1}
console interopt=fromInteropt Error: ErrName
    at Object.<anonymous> (/Users/asafh/test/test.js:4:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
  debug-tag debug interopt=fromInteropt Error: ErrName
    at Object.<anonymous> (/Users/asafh/test/test.js:4:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3 +0ms
```

**Comment by jsumners** [comment]
The others are inspecting the object prototype and handling errors as a special case. Pino does not do so unless specifically instructed to do so via a configured serializer. Pino ships with an error serializer that you can use. See the docs and unit tests.

**Comment by asafh** [comment]
Correct me if I'm wrong, serializers only work on the log event properties, but not on the values formatted into the message property. Regardless at even looking at the object prototype, surplus message format values don't get appended in some cases, and in some cases they do (which is like the documentation).  
```
const pino = require('pino');
const logger = pino({});
const additionalObject = {"a":"b"};//new Error("ErrName");
const value = "fromInteropt";
logger.info("pino interpolating in=%s extra:", value, additionalObject); //gets appended
logger.info("pino interpolating in=%j extra:", value, additionalObject); //doesn't get appended
```
Outputs:
```
{"pid":19636,"hostname":"asafh-mac.local","level":30,"time":1502895146644,"msg":"pino interpolating in=fromInteropt extra: {\"a\":\"b\"}","v":1}
{"pid":19636,"hostname":"asafh-mac.local","level":30,"time":1502895146646,"msg":"pino interpolating in=\"fromInteropt\" extra:","v":1}
```

That is due to when we have %j interopts, we use utils.format but trim to only the count of %j, %s, %d interopts, ditching any remaining objects.

**Comment by mcollina** [comment]
@asafh would you like to send a PR for this?

**Comment by asafh** [comment]
Sure, I'll make sure to run the tests before and after and I'll mention this issue in the PR.

Thanks.

**Comment by jsumners** [comment]
Associated PR: #285.

**Comment by jsumners** [comment]
I have done some digging and found the commit where this behavior was introduced https://github.com/pinojs/pino/commit/a5b532fcc42b906f43e4b6c74be86b186ccd34a8

This was a commit from @davidmarkclements in PR #129 to speed up large object interpolation. Specifically, he has this to say about this very issue:

> We have to count interpolators because of a nasty perf regression in util.format where if the args exceed interpolators speed drops drastically (which quick-format handles, but util.format is much faster at deep obj interpolation)

Therefore, I think the real fix here is to update the readme to document the correct behavior. Do you agree @davidmarkclements and @mcollina ?

**Comment by mcollina** [comment]
Agreed!

**Comment by ishan123456789** [comment]
https://gist.github.com/ishan123456789/8758409f605c95bc6afa1b2b65fca6b9
Created a simple wrapper to allow multiple arguments. Might help someone like me so posting in this thread.

**Comment by mcollina** [comment]
FYI: that type of wrapper will slow down logging significantly.

**Comment by ishan123456789** [comment]
Ohh, any fast fix as in all our apps we're passing multiple arguments and I created this to replace all of them in one go

**Comment by mcollina** [comment]
it’s even documented: http://getpino.io/#/docs/api?id=logmethod

**Comment by ishan123456789** [comment]
Can you please try in TS version I've tried adding it but it says hooks/hook is not a valid key

**Comment by mcollina** [comment]
There are no official type definitions, we do not maintain those.

**Comment by ishan123456789** [comment]
Ohh, so the "@types/pino": "^6.0.0", isn't the official one? Then I'll have to fork and modify it.

**Comment by ishan123456789** [comment]
Here's the faster implementation as per @mcollina suggestion with modified use of options
https://gist.github.com/ishan123456789/8758409f605c95bc6afa1b2b65fca6b9#file-fastermodifiedpinnologger-ts

**Comment by mcollina** [comment]
Yes, that's ok. Pino does not have official types.
