### ISSUE TITLE
Configuring baseLog

### ISSUE THREAD

**Issue by deividasjackus** [pinojs/pino#283]
Would it make sense to give control over `pino._baseLog` using a constructor option?

More specifically allowing to:
1. Pick whether or not `hostname` or `pid` are included in every log line.
2. Allowing additional values to be stringified and present in every log line.

#### Explanation
We decided to use the following properties for our services using `pino`:
- `host`, which might actually be the network address and not the hostname
- `node`, which might be a generated value and not the process ID.

This effectively made `hostname` and `pid` redundant while still present in every single log line.

**Comment by jsumners** [comment]
This looks like a duplicate of #282.

**Comment by deividasjackus** [comment]
My bad, you are correct.
