### ISSUE TITLE
Remove process ID and lowercase level labels

### ISSUE THREAD

**Issue by Aurelsicoko** [pinojs/pino#286]
First of all, thanks for creating Pino! It's an amazing logger. So faaast! I succeeded to configure it as I want but I still got two issues.

- Remove the process ID from the log. I can't find a way of doing that.
- Lowercase the level labels. INFO => Info or DEBUG => Debug

Thanks!

**Comment by jsumners** [comment]
+ Pid: #282 
+ Case: where is this a problem? When using the prettifier?

**Comment by Aurelsicoko** [comment]
@jsumners Thanks for your quick response! Okay, so I will wait for the merge of the PR #282. And this happens when I set the `prettyPrint` option to `true`. I suppose it's due to these lines https://github.com/pinojs/pino/blob/master/pretty.js#L7

**Comment by jsumners** [comment]
The current styling is typical of log level labels in Log4j type loggers.

**Comment by Aurelsicoko** [comment]
So there is no way to lowercase these labels (I'm talking about all of them not only INFO or DEBUG)?

**Comment by mcollina** [comment]
@Aurelsicoko you will need to write your own prettifier.

**Comment by davidmarkclements** [comment]
@Aurelsicoko to be clear, are you prettifying in process? 

for production we recommend that you pipe JSON log output into a second process that you use for prettifying see https://github.com/pinojs/pino#transports (consider transforms like prettifiers to be a subclass of a transport)

**Comment by davidmarkclements** [comment]
I think we're good to close here, but @Aurelsicoko feel free to continue conversation :)

**Comment by Aurelsicoko** [comment]
@davidmarkclements Thanks for your answer! I will try to implement your solution with the transport feature.
