### ISSUE TITLE
How to dynamically change stdTimeFunctions

### ISSUE THREAD

**Issue by rvypandey** [pinojs/pino#289]
After going through the docs and some of the open/closed issues, I was not able to find how could I change the stdTimeFunctions from `epoch` to `slowTime` **dynamically**, or any other formats.

I tried the code thinking that it will be similar to [.level](https://github.com/pinojs/pino/blob/master/docs/API.md#level), something like 	`logger.timestamp = "slowTime";`
 
Can you please provide an example to make this change on runtime?

Thanks.

**Comment by rvypandey** [comment]
Ok, I went and tried few more things. This works for me:

```
let logger = require("pino");
let _logger = new logger();

module.exports = {
	setOptions: function (options) {
		_logger.time = logger.stdTimeFunctions.slowTime;
		...
	}
};
```

I was half expecting to make it work by passing `keys` for using time functions, like "slow" for slowTime, "epoch/default" for epochTime, and so on.

Anyways this works. Thanks again!

**Comment by davidmarkclements** [comment]
1. I really love issues that start "after going through the docs and some of the open/closed issues" highly appreciate that @rvypandey - thank you 
2. would you be interested in a submitting a doc PR for this case?
