### ISSUE TITLE
Support for arbitrary fields

### ISSUE THREAD

**Issue by DonutEspresso** [pinojs/pino#290]
Hey folks, I've noticed that even with the bunyan flag set to true, arbitrary fields are supported only in child loggers:

```
const parent = require('pino')({
    bunyan: true,
    name: 'pino',
    a: 1,
    b: 2
});

const child = parent.child({
    a: 1,
    b: 2
});

parent.info('hello world');
child.info('hello world');
```

```sh
{"pid":78592,"hostname":"foobar","name":"pino","level":30,"time":1504134604651,"msg":"hello world","v":1}
{"pid":78592,"hostname":"foobar","name":"pino","level":30,"time":1504134604653,"msg":"hello world","a":1,"b":2,"v":1}
```

Is this intentional? If so, feel free to close. At the least, I think this might be worth calling out in the docs.

**Comment by marcbachmann** [comment]
AFAIK there's no `bunyan` property at all. So that won't have any effect.

Luckily there's already an open pull-request for exactly what you're asking for:
https://github.com/pinojs/pino/pull/282

**Comment by DonutEspresso** [comment]
Apologies - I confused [pino-multi-stream[(https://github.com/pinojs/pino-multi-stream)'s options with pino core. Thanks for the link to the PR, not sure how I missed it. Looking forward to it!
