### ISSUE TITLE
Upload logs to Stackdriver

### ISSUE THREAD

**Issue by dgonzalez** [pinojs/pino#293]
Currently there is no support for Stackdriver on Pino. I'd say the solution is 99% the same as https://github.com/pinojs/pino/issues/33 (Cloudwatch).

Once we have this working we can request to add a how-to in this page: https://cloud.google.com/logging/docs/setup/nodejs

**Comment by jsumners** [comment]
Would you like to create a module and submit a PR to add it to the transports list?

**Comment by benjsicam** [comment]
+1. Would be great to have an official transport for Google Stackdriver Logging.

**Comment by Istar-Eldritch** [comment]
Is there any progress on this line? If not shall I give it a try?

**Comment by davidmarkclements** [comment]
Go for it, I'd recommend using an existing repo as a template - pino-elasticsearch may be a good starting point

**Comment by jsumners** [comment]
Looks like someone has attempted this:
+ https://www.npmjs.com/package/pino-google-cloud-logging
+ https://github.com/seangenabe/pino-google-cloud-logging

cc: @seangenabe

**Comment by vincentlaucy** [comment]
facing the same issue, a follow up question:
- Given no control in GCP Cloud functions environment, how could we deal with the transport? spawn a new process within the process?
Now I'm trying to workaround by overriding pino logger with fallback to calls to `@google-cloud/logging`

**Comment by ovhemert** [comment]
While I was finishing up my own version of the module, I just found out this thread exists.
Please see if this already is what you are looking for. Could be added to the transport list if you like.

- https://www.npmjs.com/package/pino-stackdriver
- https://github.com/ovhemert/pino-stackdriver

cc: @dgonzalez @davidmarkclements

**Comment by davidmarkclements** [comment]
@ovhemert awesome - only just getting to this - so many badges

at the very least do a PR for https://getpino.io/#/docs/transports?id=known-transports to add your transport - with regards to making it an official transport, with you as the maintaining author can you please open a fresh issue re making it an official transport, for the core team to review? 

closing now, since we have an answer to this issue thanks to @ovhemert
