### ISSUE TITLE
The IRC channel advertised in the README.md has a password

### ISSUE THREAD

**Issue by gajus** [pinojs/pino#299]

**Comment by jsumners** [comment]
The channel should be `#pinojs`. Are you willing to submit a PR to fix it?

**Comment by gajus** [comment]
I am sure it is going to faster if you just change it.

**Comment by marcbachmann** [comment]
no, not really. Everything goes through pull requests and so do docs changes.
The github ui offers everything to do pull request of such simple changes.
Most times it's easier to directly create a pr for small changes instead of opening issues.
