### ISSUE TITLE
Make options configurable using environment variables

### ISSUE THREAD

**Issue by gajus** [pinojs/pino#301]
http://getpino.io/#/docs/API?id=constructor

It should be possible to set all of these values using environment variables, e.g. `PINO_LEVEL=trace`

**Comment by jsumners** [comment]
I completely disagree. That's for the application to deal with.

**Comment by mcollina** [comment]
We talked about this extensively. If you want to do that, it's straightforward to wrap pino yourself.

**Comment by mdornseif** [comment]
Example:

    pino({
      // Default Level: Info
      level: process.env.PINO_LEVEL || process.env.LOG_LEVEL || 'info',
      prettyPrint: (process.env.NODE_ENV || 'development') === 'development',
    })
