### ISSUE TITLE
Add a global way to append a property

### ISSUE THREAD

**Issue by gajus** [pinojs/pino#304]
This would be similar to `.child()`, e.g.

```js
const pino = require('pino')();

pino.set({
  taskId: 1
});

pino.info('test');

// => {taskId: 1, msg: 'test'}

```

This is handy when logs need to be associated with a certain parameter for a duration of the program execution (e.g. while executing a specific task) and there is no way to pass an instance of a logger to the dependent components.

e.g.

```js
import {
  foo
} from './utilities';

const taskIds = [1, 2, 3];

for (const taskId of taskIds) {
  // `foo` utility utilises pino logger.
  // I need a way to append parameters to those logs in order
  // to get a comprehensive log of events associated with a particular task.
  foo(taskId);
}

```

**Comment by jsumners** [comment]
So why doesn't `foo(taskId)` have a line like `log.info('(task: %s) some information', taskId)`?

**Comment by gajus** [comment]
That would require injecting logger instance to every utility function/ dependency in the library.

This sort of tight coupling is asking for a problem.

**Comment by gajus** [comment]
Anyway, I am closing this as I have decided to work on a fork/ logger of my own.

Pino is great. But I have strong opinions about how logger should be structured and these do not align with Pino at the moment.

**Comment by jsumners** [comment]
I was just trying to get an understanding of the problem.

**Comment by marcbachmann** [comment]
I'd advise against such an api cause it will result in  a mutable object. Then modules could modify your log parameters and mess up your log instance.

**Comment by gajus** [comment]
> I'd advise against such an api cause it will result in a mutable instance. Then modules could modify your log parameters and mess up your log instance.

Yup, I agree. It is not something I'd recommend 99% of the time.
