### ISSUE TITLE
Only log message in output

### ISSUE THREAD

**Issue by robinvdvleuten** [pinojs/pino#306]
Hi there!

I really like using the Pino logger on my Heroku app, but I find the output quite noisy. Is it possible to log only the actual message and the loglevel in the output? I currently am running the logger with `node ./lib/server | pino`. Thanks in advance for any help!

**Comment by jsumners** [comment]
Please see https://github.com/pinojs/pino/blob/master/docs/transports.md

**Comment by jsumners** [comment]
I think this has been answered. If you still have questions, please re-open.
