### ISSUE TITLE
Best way to get current level for a logger

### ISSUE THREAD

**Issue by Epitrochoid** [pinojs/pino#308]
Forgive me if I missed something in `pino/API.md`, but I don't see an obvious way to figure out the current level a logger is set at. Bunyan handles this by using an empty call, e.g. `logger.debug()` returns true if the logger is at or above debug level; it looks like Pino just creates an empty log when called without any parameters. I see that there is a field `_levelVal` on the Pino logger and I could use that along with `logger.levels.values`, but I would prefer a way that doesn't require accessing a private field. Is there another way to accomplish this?

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/master/docs/API.md#levelVal

**Comment by Epitrochoid** [comment]
So `logger.levelVal` and the map in `logger.levels.value` would be the correct way to do this?

I'll probably write a util for myself along the lines of `logger.isLevelEnabled('debug')` to make this easier. Would be that useful to add in a PR, or is this not something people are doing enough to warrant it?

Thanks

**Comment by jsumners** [comment]
Correct, that is how you would determine the current level name. The API is geared toward development, e.g. `if (logger.levelVal > 30) doSomething`, not to be read by a human.

We will most certainly consider a PR. It would help if you submit a use case in your PR description, though.
