### ISSUE TITLE
hasOwnProperty is not a function

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#313]
`"err":{"type":"TypeError","message":"bindings.hasOwnProperty is not a function","stack":"TypeError: bindings.hasOwnProperty is not a function\n    at asChindings (/usr/src/app/node_modules/pino/pino.js:171:62)\n    at EventEmitter.child (/usr/src/app/node_modules/pino/pino.js:181:16)\n `

Maybe `child` should make sure that bindings is valid? It doesn't support `Object.create(null)`?

**Comment by jsumners** [comment]
Do I understand correctly that you did something like?:

```
var bindings = Object.create(null)
bindings.name = 'foo'
log.child(bindings)
```

**Comment by davidmarkclements** [comment]
this is already supposed to be fixed: 

https://github.com/pinojs/pino/issues/180
https://github.com/pinojs/pino/commit/2a9c8269bef4b07ce87ef5a47be5b8f1b7d7f0e5

@ronag are you able to show us the exact code?

**Comment by ronag** [comment]
@jsumners example should have the behaviour. You are missing a `a.hasOwnProperty` check in https://github.com/pinojs/pino/blob/master/pino.js#L184

**Comment by jsumners** [comment]
Stupid `Object.create(null)`.

**Comment by mcollina** [comment]
@ronag that is on purpose. Unfortunately that is on the _slowest path of pino_ when creating a child for every http request. BTW, the same problem is in https://github.com/pinojs/pino/blob/master/pino.js#L171.

What is exactly your use case for passing in an object created with `Object.create(null)`?

**Comment by ronag** [comment]
@mcollina I'm passing in an object from another library (deepstream, firebase) which creates it's objects using `Object.create(null)`.

**Comment by mcollina** [comment]
I would recommend _not_ to pass those objects through. They are probably internal things, create a new one with the property that you need.

**Comment by ronag** [comment]
@mcollina: the problem is that we don't always know how the object was created... having to worry about this everywhere is not very ergonomic. What's wrong with just adding a check in pino?

**Comment by mcollina** [comment]
@ronag you should do that anyway, as an object can be pretty polluted with a lot of things. With the new escape analysis in V8, creating the object will be optimized away, so there is no performance penalty in doing so.

The checks will slow req/s in pino-http by 10% at least.

**Comment by jsumners** [comment]
Simple solution: `log.child(Object.assign({}, stupidNullNonObject)`.

**Comment by jsumners** [comment]
Closing because I believe the issue has been addressed with valid solutions. Please re-open if you have further questions.
