### ISSUE TITLE
Pretty dev formatter

### ISSUE THREAD

**Issue by adam-26** [pinojs/pino#316]
Hi,

Pino is great for production logging, but during development you don't always want to see so much information.

I tried using [pino-toke](https://github.com/pinojs/pino-toke), but it prevents log output from dependencies that don't use pino. [pino-http-print](https://github.com/pinojs/pino-http-print) adds some basic functionality around the `formatter`, but it's not possible to make modifications - for example do something simple like display an error stack trace if the log entry includes an error.

It would be nice if the `pretty.js` [formatter()](https://github.com/pinojs/pino/blob/master/pretty.js#L103) function was easier to work with.. currently you need to write a lot of code to customize log output.

It would be beneficial if access to existing data/functions were provided in the formatter, one possibility may be:

```js
// already exists in pretty.js
line = (levelFirst)
        ? asColoredLevel(value) + ' ' + formatTime(value)
        : formatTime(value, ' ') + asColoredLevel(value)

// relocate this after the line prefix is created
if (formatter) {
  return formatter(parsed.value, { 
    prefix: line, 
    chalk: ctx, 
    withSpaces, 
    filter, 
    formatTime,
    asColoredLevel, 
    value
  }) + '\n'
}
```
This retains backwards compatibility. I'm not sure how this would impact performance, or if that's even a concern when it comes to `pretty.js`? If performance is a concern, another alternative is to add another `option` such as `extendedFormatter` that includes the additional features?

With a change like this, pino web framework plugins could then easily provide a range of pre-defined formatter options and make it much easier to adopt pino for development purposes with Koa, express, etc... similar to how [morgan](https://github.com/expressjs/morgan) provides a range of default log formatters.

I'd be interested in your thoughts. 

If only a simple change like that suggested above is acceptable, I'm happy to submit a PR.

Adam.

**Comment by jsumners** [comment]
Actually, I was just attempting to do such things yesterday with https://www.npmjs.com/package/@jsumners/git-user-config . So I do think it would be nice to have. A PR would be very nice to see.
