### ISSUE TITLE
Error serializer "hostname" property clash

### ISSUE THREAD

**Issue by brainsiq** [pinojs/pino#322]
Node's ENOTFOUND error has a "hostname" property which get's added into the log message by the error serializer, so when logging this type of Error we end up with two hostnames.

```
const http = require('http');
const pino = require('pino')();

const url = `http://fgghfgh`;

http.get(url, res => {}).on('error', err => {
    pino.error(err, 'Check out my error!');
})
```

This logs:

{"pid":25825,"hostname":"brainsiq","level":50,"time":1509380500036,"msg":"Check out my error!","type":"Error","stack":"Error: getaddrinfo ENOTFOUND fgghfgh fgghfgh:80\n    at errnoException (dns.js:28:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"fgghfgh","host":"fgghfgh","port":80,"v":1}

Duplicate keys are technically "valid" in JSON, but it'd be nice if there was a way of avoiding this as a lot of JSON consumers (Logstash for example) might reject this.

**Comment by jsumners** [comment]
See https://github.com/pinojs/pino/issues/230

**Comment by brainsiq** [comment]
Thanks. I should have remembered reading that. I've ended up wrapping pino in an object with a similar interface that sniffs for Error objects passed to the log functions and automatically wraps them.
