### ISSUE TITLE
Can I listen the log event like winston?

### ISSUE THREAD

**Issue by chuyik** [pinojs/pino#325]
In winston we can listen on the `logged` event, intercept it and do something like sending an email to developer.
But I can't find any documentation of pino similar to it.

**Comment by mcollina** [comment]
There isn't. You can use https://github.com/pinojs/pino-multi-stream and define another destination stream to send your developer an email.

**Comment by davidmarkclements** [comment]
Or you can pipe to another process, which picks up the incoming stream and analyses for log messages to email out - another option would be to use an email notifications feature from a log processing tool (e.g. http://docs.splunk.com/Documentation/Splunk/7.0.0/Alert/Emailnotification)
