### ISSUE TITLE
Use CRLF on Windows

### ISSUE THREAD

**Issue by tniessen** [pinojs/pino#326]
pino seems to always emit `\n`, but it should at least be configurable to emit `\r\n` on Windows, or even make it a default.

This seems to be caused by https://github.com/pinojs/pino/blob/ce10ba1075791d57977bc01cfc5db6aac0b25bf4/pino.js#L277
and by multiple other occurrences in https://github.com/pinojs/pino/blob/master/pretty.js.

**Comment by jsumners** [comment]
Hmm, I was prepared to shoot this down, but it looks like the spec allows for `\r\n`:

http://specs.okfnlabs.org/ndjson/
> Each JSON text MUST conform to the [RFC7159] standard and MUST be written to the stream followed by the newline character \n (0x0A). The newline charater MAY be preceeded by a carriage return \r (0x0D). The JSON texts MUST NOT contain newlines or carriage returns.

Would you like to submit a PR to enable this option?

**Comment by tniessen** [comment]
And by multiple other occurrences in https://github.com/pinojs/pino/blob/master/pretty.js

**Comment by davidmarkclements** [comment]
any tools built around pino at this point may be relying on just `\n` - in there interest of not breaking ecosystem libs let's make this an opt-in setting

**Comment by tniessen** [comment]
@davidmarkclements Yes, #327 makes it completely optional. I would actually prefer to always use `\n` but some Windows tools were designed for `\r\n`.
