### ISSUE TITLE
Error: write EPIPE on windows

### ISSUE THREAD

**Issue by ridakk** [pinojs/pino#330]
I am getting EPIPE error as below.

λ node pino.js | pino
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at Socket._writeGeneric (net.js:711:26)
    at Socket._write (net.js:730:8)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Socket.Writable.write (_stream_writable.js:243:11)
    at Socket.write (net.js:657:40)
    at EventEmitter.pinoWrite (D:\...\node_modules\pino\pino.js:207:12)
    at EventEmitter.LOG (D:\...\node_modules\pino\lib\tools.js:102:10)
    at Object.<anonymous> (D:\...\pino.js:15:10)

λ node -v
v6.11.3

λ npm -v
3.10.10

I am using cmder 161206 and getting this error but if i tun the code from VSC terminal, it is ok.

My test code;
pino.js
```
const pino = require("pino");

const logger = pino({
  name: "test",
  level: "trace"
});

for (let i = 0; i < 10000; i++) {
  logger.fatal(i);
  logger.error(i);
  logger.warn(i);
  logger.info(i);
  logger.debug(i);
  logger.trace(i);
}
```

**Comment by mcollina** [comment]
Unfortunately we are all unix developers. I think it might be a windows issue. Are you using powershell?

**Comment by ridakk** [comment]
I am using cmder (http://cmder.net/) on windows, and yes it seems to be a windows issue, but nearly %40-50 of our development teams are using windows.

**Comment by mcollina** [comment]
@ridakk which version of node are you using? is this happening all the time, or just with a long number of logged lines?

**Comment by mcollina** [comment]
Can you verify if you have the same issue with Node 8?

**Comment by ridakk** [comment]
same with node6 and node8, and happening all the time.

**Comment by mcollina** [comment]
I think the `|` operator is probably not working correctly on Windows, and I don't know exactly how to fix that. A quick & dirty solution to this for development is:

```js
pino({
  prettyPrint: process.env.NODE_ENV === 'production'
})
```

You will need to specify `NODE_ENV=production` when running in production after.

**Comment by ridakk** [comment]
Damn i found the cause :)

it was because i named my test file as pino.js and running it as 
```
node pino.js | pino
```

renaming the test script to pino_test.js solved everything.

**Comment by jsumners** [comment]
:) Loops!
