### ISSUE TITLE
Papertrail support

### ISSUE THREAD

**Issue by anonrig** [pinojs/pino#331]
Is there a papertrail transporter for pino?

**Comment by mcollina** [comment]
not as far as I know, but you can write one!

**Comment by CoolHandLuke88** [comment]
noooooooo

**Comment by jsumners** [comment]
Because we don't use every system that is available and can't be expected to write everything ourselves. This is open source software, written to meet our needs, that is provided as-is. Contributions for desired functionality is encouraged and welcomed.

**Comment by davidmarkclements** [comment]
@CoolHandLuke88 if you want to build it, we'll even review and help you make it as performant as it can be

**Comment by CoolHandLuke88** [comment]
Hey guys love what you have done with Pino. @jsumners I completely understand. @davidmarkclements I am considering it, if time will allow me. I would love for you guys to review and assist if I do it. You guys will be first to know of the repo. Thanks for all the hard work.

**Comment by brandonmp** [comment]
i'm just trying papertrail for the first time, but ostensibly it's already supported via `pino-syslog` + `pino-socket`.

i'm running:
`$ node index.ts | pino-syslog | pino-socket -a logs.papertrailapp.com -p xxxx`

and this seems to show up fine in my papertrail dashboard. 

Is this a full solution?

**Comment by davidmarkclements** [comment]
Ok so that's straight forward 

For convenience what you could do is create pino-papertrail module that combines pino-syslog and pino-socket 

Give it both CLI interface and programmatic (for use with pino-multistream for those who have constrained environments that don't allow for for shell piping), add unit tests and we can make it an official module if you like

**Comment by brandonmp** [comment]
thanks @davidmarkclements 

one apparent limitation i noticed is that the output sent to papertrail is in the raw json format. i.e., this arrangement of CLI args:

`$ node index.js | pino | pino-syslog | pino-socket -a logs.papertrailapp.com -p xxxx`

doesn't send any content to papertrail. 

In general it looks like putting `pino` before `pino-syslog` breaks the latter. is that a hard constraint of `pino-syslog` or a design choice that could be reconsidered? would be cool to have stuff in papertrail pretty-printed

**Comment by jsumners** [comment]
@brandonmp yes. `pino-syslog` is for parsing the newline delimited JSON log lines into traditional syslog format. Piping those log lines into `pino` transforms them into human readable information.

**Comment by mcollina** [comment]
Good work! Would you mind sending a PR to https://github.com/pinojs/pino/blob/master/docs/transports.md as well?
