### ISSUE TITLE
pino not working with ES6 modules

### ISSUE THREAD

**Issue by agentframework** [pinojs/pino#338]
Thank author for such fast logger, I am trying to use pino in my framework, but didn't success.

got the following message when working on a framework bundle with Rollup and TypeScript.

```typescript
import * as pino from 'pino'
pino(config)
```

Error: Cannot call a namespace ('pino')

OR, if you do like this

```typescript
const pino = require('pino');

pino(config)
```

semantic error TS1202 Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

BTW. bunyan don't have this problem.

**Comment by mcollina** [comment]
If you would like this to be solved, why don't you provide a full example to reproduce your problem? Even better, why don't you send a PR to fix it?
We have used this extensively with React and Webpack, so it sounds like a TypeScript or Rollup issue.

> BTW. bunyan don't have this problem.

If you think Bunyan (or anything else) solves your needs in a better way, feel free to use them.

**Comment by agentframework** [comment]
to reproduce

```bash
git clone https://github.com/agentframework/agentstack.git
cd agentstack
yarn install
yarn run build
```

**Comment by mcollina** [comment]
You might want to install https://www.npmjs.com/package/@types/pino.

**Comment by agentframework** [comment]
webpack is working. But the bundle generate by webpack is not beautiful. Rollup just not works.

**Comment by agentframework** [comment]
close this issue because I implemented a pure es6 logger with 100% typescript to replace pino.

**Comment by jsumners** [comment]
Transpiling server-side code is a waste of time.

**Comment by agentframework** [comment]
> Transpiling server-side code is a waste of time.

Agreed. if put into wrong hands and using wrong tools.

**Comment by tldrjumps** [comment]
How about the parcel bundler


file.js

```
import * as pino from 'pino'
var logger = pino()
logger.info("test")
```

parcel file.js


TypeError: pino is not a function

Should install 
npm install --save @types/pino
instead of
npm install --save pino

Totally clueless about the compile tools now

**Comment by mcollina** [comment]
If you find the problem, feel free to send a PR.
There are so many bundlers out there that testing all of them is probably too much work for us.

**Comment by jfahrenkrug** [comment]
@nevf I get the same with webpack. Did you find a solution?

**Comment by nevf** [comment]
@jfahrenkrug No, I'm afraid not. I am using [consola](https://github.com/nuxt/consola) in the Browser and am pretty happy with it. It also works in Node but I haven't tried that yet.

**Comment by davidmarkclements** [comment]
if anyone can provide a reproducible example as a repo I'll look into it
