### ISSUE TITLE
Replace extreme mode with SonicBoom

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#341]
Check out https://github.com/mcollina/sonic-boom.
I did some preliminary tests, and I got the _exact same performace_.

Moreover, this requires less handling of system events as it does only one level of buffering. I think we could replace the _default_ with this. Check it out.

**Comment by jsumners** [comment]
You are using the `class` syntax in SonicBoom (😞 ). Would that affect the minimum supported Node version for Pino?

Also, simply out of personal curiosity, is a SonicBoom instance compatible with https://github.com/marko-js/async-writer?

**Comment by mcollina** [comment]
Oh, it takes 5 minutes to go to prototypes again. It might end up faster!

Regarding async-writer, you should try. It might work! The major problem is if you want to use it to reply to a HTTP response, and making that work would be way harder.

**Comment by jsumners** [comment]
It looks like `class` goes back as far as 4.8.7 http://node.green/#ES2015-functions-class . And according to our Travis configuration, we are still supporting 4.y.z https://github.com/pinojs/pino/blob/master/.travis.yml .

I completely disagree with the keyword/syntax being added to the language, but if that's how you want to maintain your module then so be it. As long as Pino continues to work on our advertised supported Node versions, I am a completely fine with this.

**Comment by jsumners** [comment]
Any movement on integration?

**Comment by mcollina** [comment]
I'm currently snowed under for work.
We might start assembling out a pino@5, with the new fast-safe-stringify and sonic-boom.

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/projects/1 updated.

**Comment by jsumners** [comment]
> Moreover, this requires less handling of system events as it does only one level of buffering.

@mcollina I'm not sure how this would be implemented. Are you still too busy to work on this?

**Comment by mcollina** [comment]
@jsumners sonic-boom has https://www.npmjs.com/package/sonic-boom#sonicboomflushsync.

**Comment by mcollina** [comment]
I might have time later on in the month, but I can't guarantee anything.

**Comment by mcollina** [comment]
Done in #394 for pino@5.
