### ISSUE TITLE
Pretty child bindings

### ISSUE THREAD

**Issue by philmoss543** [pinojs/pino#343]
When using 

```const pino = require('pino')
const pretty = pinos.pretty()
pretty.pipe(process.stdout)
const log = pino({
    name: 'app',
    safe: true
}, pretty)

log.child({ widget: 'foo' }).info('hello')
log.child({ widget: 'bar' }).warn('hello 2')
```

My output looks like this:

```
[2018-01-04T22:34:33.047Z] INFO (TITLE/13044 on MacBook-Pro-2.local): hello
    widget: "foo"
[2018-01-04T22:34:33.047Z] WARN (TITLE/13044 on MacBook-Pro-2.local): hello 2
    widget: "bar"
```

It's very disruptive to "pretty" logs to have the extra info on another line. Is there a way to reformat to get it all on the same line? 

My use case is I want to attach a jobId to the logs, so it's easy to tell what process is happening with what job. The non-pretty log output looks great, and that's what I'm using for log files and other logging databases. It would be helpful to have debug logs look more formatted with the extra information.

Thanks!

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/c77d8ec5ce37f56cbdf1689d4ec9ac585eb6b74b/docs/API.md#pretty

**Comment by philmoss543** [comment]
Okay. I'm using typescript and didn't see the 'opts' param in the index.d.ts 
I am using:
```
"name": "@types/pino",
"version": "4.7.0"
```

The formatter in the PrettyOptions interface only has the one param
```
 formatter?(log: LogDescriptor): string;
```

I saw the documentation, but figured it was outdated or I was just missing something. Thank you for the help

**Comment by jsumners** [comment]
I can't help you out with TypeScript. The documentation is the definitive reference.

**Comment by philmoss543** [comment]
Got it all set up, thanks!
