### ISSUE TITLE
Remove dependency on `this`

### ISSUE THREAD

**Issue by grantcarthew** [pinojs/pino#345]
Hi,

I'm just starting to use `pino` now and it will not work in my project because of references to `this` within the generated `Log` function.

The following line of code from within `pino` is the one causing the issue:
https://github.com/pinojs/pino/blob/c77d8ec5ce37f56cbdf1689d4ec9ac585eb6b74b/lib/tools.js#L88

The code that is causing the error is coming from the [sequelize](https://github.com/sequelize/sequelize) package at the following line:
https://github.com/sequelize/sequelize/blob/d4a34ae5233cadc721adcaa55314859121ddf8ea/lib/sequelize.js#L1077

As you can see, `sequelize` is using `apply` for the log function invocation and is setting the `this` reference to `null`.

As a fix for this issue I suggest passing into the `getLog` function the required values.

This problem may be an issue elsewhere in `pino`.

Looks great otherwise. Nice work.

**Comment by jsumners** [comment]
I would call that a bug in the other library.

**Comment by grantcarthew** [comment]
Hi @jsumners. I tried to raise an issue in the sequelize repository and it would not let me.
I have posted on their forum here:
https://groups.google.com/forum/#!topic/sequelize/yp1ZgrjCmo0

**Comment by mcollina** [comment]
how so you configure all of this? It seems logging is expected to be a function. You should pass a function which calls pino internally.

**Comment by grantcarthew** [comment]
I'm not sure how sequelize is transpiled if at all. They should be using the spread operator now days rather than the `apply` function call.

**Comment by mcollina** [comment]
I would not call that a workaround. Sequelize expects a function, not a logger. Pino is a logger.
You can use logger.debug.bind(logger) in Node 8+ (for perf reason).

**Comment by grantcarthew** [comment]
```js
node
> const n = require('pino')()
undefined
> typeof n.debug === 'function'
true
>
```

**Comment by mcollina** [comment]
Using this is pretty normal in the JS language. It is what differentiate a function from a method. JS also add a bind operator, too!

I’m locking this conversation now.
