### ISSUE TITLE
Can we modify the key "level" in the log messages ?

### ISSUE THREAD

**Issue by kishoresanke** [pinojs/pino#346]
* Can we modify the key "level" in the log messages ?
For example - { "level": "info" } to { "severityLevel": "info" }

**Comment by mcollina** [comment]
Unfortunately no, this is not possible atm.

**Comment by kishoresanke** [comment]
Thanks @mcollina , do you know of any other node logging libraries that allows this ?

**Comment by mcollina** [comment]
Unfortunately I do not know. The best option for you is to postprocess those log with something like LogStash or another Node process to shape them the format your logging system requires.

**Comment by grantcarthew** [comment]
@kishoresanke Have a look at my [perj](https://github.com/grantcarthew/node-perj) module. Supports completely changing the levels. Sorry for the late notice. Just found this issue because of #563
