### ISSUE TITLE
Is there any way to print log to stdout with prettyPrint and print log file with JSON format?

### ISSUE THREAD

**Issue by CrisLi** [pinojs/pino#347]
I want to have two streams of my logs. One is process.stdout and other is a file stream. I am using pino-multi-stream to implement this requirement. But now I want to have prettyPrint for process.stdout and use JSON format for the file stream. Is there any way to implement it?

My config is below, but the error would be thrown `cannot enable pretty print when stream is not process.stdout`

```js
const fs = require('fs');
const path = require('path');
const pino = require('pino');
const { multistream } = require('pino-multi-stream');

const logDir = path.resolve(__dirname, '../logs');

if (!fs.existsSync(logDir)) {
  fs.mkdir(logDir);
}

const streams = [
  { stream: fs.createWriteStream(path.resolve(logDir, 'app.log')) },
  { level: 'error', stream: fs.createWriteStream(path.resolve(logDir, 'error.log')) },
  { level: 'info', stream: process.stdout, prettyPrint: true }
];

const logger = pino({
  prettyPrint: true
}, multistream(streams));

module.exports = logger;

```

**Comment by mcollina** [comment]
You can't, that option is a shortcut. However, you can create a pretty stream directly pass it through, as below (not tested):

```
const fs = require('fs');
const path = require('path');
const pino = require('pino');
const { multistream } = require('pino-multi-stream');

const logDir = path.resolve(__dirname, '../logs');

if (!fs.existsSync(logDir)) {
  fs.mkdir(logDir);
}

const pretty = pino.pretty()
pretty.pipe(process.stdout)

const streams = [
  { stream: fs.createWriteStream(path.resolve(logDir, 'app.log')) }, // you should probably specify a log level here
  { level: 'error', stream: fs.createWriteStream(path.resolve(logDir, 'error.log')) },
  { level: 'info', stream: pretty }
];

const logger = pino(multistream(streams));

module.exports = logger;
```

(side note, I would not recommend to store the logger a singleton).

**Comment by CrisLi** [comment]
@mcollina It works. Thanks,

BTW, why store the logger a singleton is not a good idea? Any suggestion on that?

**Comment by mcollina** [comment]
Because then you cannot divide your application safely into separate modules, as they will all need to resolve the right module for the logger.
Moreover this is a bad practice because even if pino can be instantiated synchronously, other libraries can't (e.g. databases) and storying them 
Finally you can't place assertions on what is logged easily, you will have to resort to use proxyquire or the like.

Injecting your dependencies is the best way to hook up your application.

(Side note, using pretty logging this way is not suitable for production logging, you should really log as JSON).

**Comment by mcollina** [comment]
Closing as it's resolved!

**Comment by Dacredible** [comment]
> You can't, that option is a shortcut. However, you can create a pretty stream directly pass it through, as below (not tested):
> 
> ```
> const fs = require('fs');
> const path = require('path');
> const pino = require('pino');
> const { multistream } = require('pino-multi-stream');
> 
> const logDir = path.resolve(__dirname, '../logs');
> 
> if (!fs.existsSync(logDir)) {
>   fs.mkdir(logDir);
> }
> 
> const pretty = pino.pretty()
> pretty.pipe(process.stdout)
> 
> const streams = [
>   { stream: fs.createWriteStream(path.resolve(logDir, 'app.log')) }, // you should probably specify a log level here
>   { level: 'error', stream: fs.createWriteStream(path.resolve(logDir, 'error.log')) },
>   { level: 'info', stream: pretty }
> ];
> 
> const logger = pino(multistream(streams));
> 
> module.exports = logger;
> ```
> 
> (side note, I would not recommend to store the logger a singleton).

I'm facing a similar situation here. Basically I'm trying to have pretty print for stdout stream and JSON format for stackdriver stream. But got error pino.pretty is not a function. Is the API renamed?

**Comment by reach009** [comment]
Guys, I have been trying trial and error with this log setting. I have found a way to print the log to stdout and file.

Basically, you just need to specify 

`{ stream: process.stdout },` for terminal output

`var multistream = require("pino-multi-stream").multistream;
var streams = [
  { stream: process.stdout },
  { level: "error", stream: process.stderr },
  {
    level: "debug",
    stream: require("file-stream-rotator").getStream({
      filename: `${logPath}/debug.log`,
      frequency: "daily",
    }),
  },
  {
    level: "fatal",
    stream: require("file-stream-rotator").getStream({
      filename: `${logPath}/fatal.log`,
      frequency: "daily",
    }),
  },
];`

This is one of my project setting code to configure what need to print out on terminal and file based on the log level. 

Info -> Terminal
Error-> Terminal
Debug -> Log
Fatal -> Log
