### ISSUE TITLE
Is there an option to enable printing of src file information ? 

### ISSUE THREAD

**Issue by kishoresanke** [pinojs/pino#348]
Is there an option to enable printing of src file information ? 
I have read the usage docs and do not see any flag related to this.

**Comment by jsumners** [comment]
I think you are looking for https://github.com/pinojs/pino-caller

**Comment by kishoresanke** [comment]
thanks @jsumners . is there any performance test results that you can share that tells what is the performance degradation when src file information is logged ?

**Comment by jsumners** [comment]
Not that I'm aware of, but they wouldn't be spectacular.

**Comment by davidmarkclements** [comment]
the warning the in description (https://github.com/pinojs/pino-caller#description) would suggest that it's quite heavy. This is just the nature of V8, stack collection is heavy. 

You could try setting `Error.stackTraceLimit = 1` to limit the overhead, and just get the latest callframe/src 

Closing as the question has been answered
