### ISSUE TITLE
Why no prettyPrint to stderr or file?

### ISSUE THREAD

**Issue by kevinoid** [pinojs/pino#349]
Due to the change in #321 (and subsequent fix in 2ad701ff) it is possible to enable `prettyPrint` for `process.stdout` but not `process.stderr`.  It's also possible to redirect stdout to a file, but not to enable `prettyPrint` for a file stream.  Could you clarify why this was forbidden?

Thanks,
Kevin

**Comment by mcollina** [comment]
Mainly three reasons:

1.`pretty: true`  is a shortcut for something more complex. If you want to do more complex things you have to use the stream APIs.
2. lazyness, if you would like to change this, send a PR. It's definitely ok to support `process.stderr`
3. sending logs sto stderr is not a really good practice IMHO

**Comment by kevinoid** [comment]
Thanks for the response!  I'm afraid I still don't understand.  Why the stream whitelisting at all?  Why not allow `prettyPrint: true` on any stream?  What was the incompatibility you mentioned in #298?

**Comment by mcollina** [comment]
Because `pretty()` __should not be used in production__, but only for dev. It's a limit put in place for you to do the right thing.

**Comment by kevinoid** [comment]
Thanks for clarifying.
