### ISSUE TITLE
Add greenkeeper.

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#352]
I think it can help us catching regression as #351 showed.

**Comment by jsumners** [comment]
The same failure is shown in #280.

However, I'm not terribly fond of Greenkeeper. All it really does is annoy the maintainers of a project. It doesn't actually remove any burden; it instead adds burden. And there's no guarantee it would catch the current error with CI. When I run the tests locally (both `npm test` and `npm run ci`) I get completely passing tests. So this doesn't even seem to be a dependency issue.

**Comment by mcollina** [comment]
Ouch, maybe it's a bad idea.

**Comment by mcollina** [comment]
Anyway, it was a dependency issue. I had to force a `npm update` and then I got a failing test locally.

**Comment by jsumners** [comment]
Weird. I cloned the repo to an empty directory and did a fresh install before I finished posting my above comment.
