### ISSUE TITLE
Data property for stringified objects

### ISSUE THREAD

**Issue by grantcarthew** [pinojs/pino#355]
Hi guys,

I have been reading the code and can not see a method for placing the serialized objects into a root log property.

As an example, let say I run the following:
```js

pino.debug({ a: 1, b:2 })

```

With the above log statement it will produce the following:

```js
{
  level: 20,
  pid: 1234,
  time: 1234,
  v: 1,
  hostname: 'host',
  msg: 'some message',
  name: 'some name',
  a: 1,
  b: 2
}
```

What I would like to achieve is this:

```js
{
  level: 20,
  pid: 1234,
  time: 1234,
  v: 1,
  hostname: 'host',
  msg: 'some message',
  name: 'some name',
  data: { a: 1,  b: 2 }
}
```

I know I could call the log function passing in an object with a data property each time however this seems a little verbose. I know I could also wrap the pino logger in a custom logger to achieve the same thing.

Is there a way of putting the JSON objects into a root property using pino? A catch all serializer for example?

**Comment by davidmarkclements** [comment]
@grantcarthew no we currently don't support that, and it could be logged more performantly with a root key if implemented in pino core with string concatenation. It would require at least one conditional check for a different logic branch, which shouldn't affect performance in any significant way (unless it puts us over the complexity threshold). So if you'd like to PR you're more than welcome, I can see how this would be useful

**Comment by grantcarthew** [comment]
Ok, thanks @davidmarkclements 
What would be the best solution?
A catch all serializer or an option?
I don't think I would be the only one interested in this in which case an option would be better?

**Comment by grantcarthew** [comment]
I decided to go with an option. Just writing some tests. Will send a PR for initial review when I get time.
