### ISSUE TITLE
pino cli for custom error

### ISSUE THREAD

**Issue by ilyaztsv** [pinojs/pino#359]
Hello!

**pino: 4.11.0**

I have the following custom error on may server:

```
class ServerError extends Error {
  constructor(message, statusCode = 500, originalError) {
    const msg =
      message +
      (originalError && originalError.message ? originalError.message : '');
    super(msg);
    this.statusCode = statusCode;
    Error.captureStackTrace(this, ServerError);
    this.originalStack = originalError ? originalError.stack : null;
  }
}
```

I use pino as follows (`index.js`):

```
const stream = process.stderr;
const logger = pino({}, stream);

try {
  throw new Error('source message');
} catch (err) {
  const serverError = new ServerError('server message: ', 500, err);
  logger.error(serverError);
}
```

Output (`node index.js 2>&1 >/dev/null | pino -l`):

```
ERROR [2018-02-18T07:32:09.490Z] (41225 on PC.local): server message: source message
    Error: server message: source message
        at Object.<anonymous> (/Users/ilyaztsv/projects/ngs/jtnews/qwe.js:13:23)
        at Module._compile (module.js:660:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
        at tryModuleLoad (module.js:513:12)
        at Function.Module._load (module.js:505:3)
        at Function.Module.runMain (module.js:701:10)
        at startup (bootstrap_node.js:193:16)
        at bootstrap_node.js:617:3
```

As u can see that output does not contain `statusCode` and `originalStack` from `ServerError` object. Is It possible to output all properties from custom error using `pino cli`?

**Comment by mcollina** [comment]
Would you like to send a PR to add this info? I think it would be valuable.

**Comment by jsumners** [comment]
Wouldn't this be better as a custom error serializer?

**Comment by ilyaztsv** [comment]
@mcollina I've created PR: https://github.com/pinojs/pino/pull/360, please see it :)

P.S. close this issue.

**Comment by tizzyapunkt** [comment]
I really appreciate this new feature but I recognized that it does work only with non-nested properties.
If the additional property is an nested object the output is `errors: [object Object]`.
It would be nice if this gets also parsed and prettyfied. 

Also it would be quite nice if one could simply pass --errorProps * as argument to print any extra property. (In case I do not exactly know what library XY adds to the base Error object. )

**Comment by ilyaztsv** [comment]
@tizzyapunkt thanks for the replay.

I think that will be better to create new issue about this behavior and discuss it there are.

**Comment by tizzyapunkt** [comment]
@ilyaztsv opened #371
