### ISSUE TITLE
npm ci 

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#366]
I'm not saying we should do this, I'm just creating the issue before somebody else does

New npm command `npm ci` will install from the `package-lock.json` file, and throw an error if `package.json` and `package-lock.json` are out of sync. 

We decided a while back to not use a `package-lock.json` file. 

My take: I don't think we should use `npm ci` in the CI.

**Comment by jsumners** [comment]
What I'm reading is "`package.json` and `package-lock.json` get out-of-sync so we had to invent a new way to get them in-sync because stupid lock files."

Yeah, I don't see any reason to use `npm ci`.

**Comment by mcollina** [comment]
Same here. Not needed.
Il giorno dom 25 feb 2018 alle 14:56 James Sumners <notifications@github.com>
ha scritto:

**Comment by davidmarkclements** [comment]
closing, consensus is conclusive
