### ISSUE TITLE
CI checking Node 7?

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#367]
https://github.com/pinojs/pino/blob/04351416cd4d1723fbc872fa37c87e453731298d/.travis.yml#L3-L8

Is there a reason we continue to check against Node 7?

**Comment by davidmarkclements** [comment]
no, I think it should be removed – as should 9 when 10 is released

**Comment by mcollina** [comment]
I would keep it until it fails / or it become a problem.
I think we should drop both 7 and 9 when/if we bump the major.
Il giorno dom 25 feb 2018 alle 15:53 David Mark Clements <
notifications@github.com> ha scritto:

**Comment by rimiti** [comment]
I'm totally agree to remove node 7 from CI. 
+1

**Comment by jsumners** [comment]
Resolved by #370
