### ISSUE TITLE
property name `name` overwrite log name

### ISSUE THREAD

**Issue by zyf0330** [pinojs/pino#368]
I create a logger using `logger = log.child({name: name})`, and then I log a obj using `logger.debug({name: 'myName'})`, I find that `DEBUG (name/29577 on host): ` becomes `DEBUG (myName/29577 on host): `.
It is that logger name is overwritten by obj property name `name`.

**Comment by mcollina** [comment]
This is expected. all properties are merged in the same object. You should name in another object if you do not want this to happen.

**Comment by zyf0330** [comment]
Is there any comment or doc about this?

**Comment by mcollina** [comment]
I'm not sure, feel free to send a PR if not.

**Comment by zyf0330** [comment]
I don't find any doc about it after searching.
Actually, I think name of `log.child({name: name})` is a label to mark log of it. This overwrite action may misunderstand people. At least, I don't hope this happens.

**Comment by jsumners** [comment]
Yes, it is documented quite clearly -- https://github.com/pinojs/pino/tree/04351416cd4d1723fbc872fa37c87e453731298d#duplicate-keys

**Comment by davidmarkclements** [comment]
resolved :D

**Comment by zyf0330** [comment]
I still think that name should be special like level.

**Comment by davidmarkclements** [comment]
Cool - we'd be happy to consider a proposal. If you'd like to put together a PR demonstrating your idea, with benchmarks proving that your changes aren't detrimental to performance, with updated unit tests we can kick off a review process around the changes you'd like

**Comment by zyf0330** [comment]
I think it doesn't matter.
This situation happens when I use `prettyPrint` and in non-production environment, so it is not related to performance.

**Comment by grantcarthew** [comment]
@zyf0330 I thought it was strange how the logged objects are merged with the log properties also. I send a PR https://github.com/pinojs/pino/pull/356 which added the option of nesting the data under a named property. I decided to wrap pino to ensure object data is nested. Have a look at that code and work with a fork @zyf0330 or wrap the logger.

**Comment by zyf0330** [comment]
@grantcarthew I don't feel too much strange with this feature. Sorry, I just need a little optimization in development environment.
