### ISSUE TITLE
Logging Format

### ISSUE THREAD

**Issue by grantcarthew** [pinojs/pino#369]
This one is a little out there however may be worth considering.

Move the log output from `pino` to a logging standard such as [GELF](http://docs.graylog.org/en/2.4/pages/gelf.html). _Note the deprecated fields._

It doesn't have to be GELF as the standard, however that seems to be a simple one that is well supported.

By following that standard, all additional fields of information are prepended with an underscore. This in itself would solve a few issues.

This would be a major change to the logger.

**Comment by jsumners** [comment]
What issues would it solve? Why not use a transport?

**Comment by davidmarkclements** [comment]
hey @grantcarthew you'd use a transport as @jsumners points out, see https://www.npmjs.com/package/pino-gelf 

making changes to core output would break a lot of the ecosystem around pino, and would break current user expectations

closing

**Comment by grantcarthew** [comment]
Ok, thanks @davidmarkclements.
I thought it was a long shot.
