### ISSUE TITLE
Improving pino cli --errorProps

### ISSUE THREAD

**Issue by tizzyapunkt** [pinojs/pino#371]
I really appreciate this new feature but I recognized that it does work only with non-nested properties.
If the additional property is an nested object the output is errors: [object Object].
It would be nice if this gets also parsed and prettyfied.

Also it would be quite nice if one could simply pass --errorProps * as argument to print any extra property. (In case I do not exactly know what library XY adds to the base Error object. )

**Comment by mcollina** [comment]
Can you make an output example of what you are proposing?

**Comment by tizzyapunkt** [comment]
Currently, when the pino CLI prettyfies a throw'n error instantiated from the Error class , it only prints the message property from the error object.
Some libraries like Sequelize extend the standard Error class with additional properties which will be ignored by the pino CLI when prettyfying the message.
So if the error object would be
```
error: {
  message: "some string",
  stack: "stacktrace...",
  dataBaseSpecificError: "additional database specific error information",
  propX: "some more info",
  propY: "even more info",
}
```
then only the error.message property will be printed.

With the option --errorProps I am able to tell the CLI which properties I want to see in addition, but if I do not exactly know which properties are added by the library I use, it would be nice to just pass something like --errorProps '*' or --allErrorProps or something like that to tell pino to print out all error properties.

In addition when the error object looks like this
```
error: {
  message: "some string",
  stack: "stacktrace...",
  dataBaseSpecificError: {
    errorType: "some database error type",
    erroMessage: "some database error message",
    evenMoreSpecificStuff: {
      someErrorRelatedObject: {
        propx,
        propy,
      },
    },
  },
  propX: "some more info",
  propY: "even more info",
}
```
then pino would print out
```
message: some string,
stack: stacktrace,
dataBaseSpecificError: [object object] // the object here will not get parsed
propX: some more info,
propY: even more info,
```
It would be very nice, if pino parses and prints out even nested error objects.

**Comment by mcollina** [comment]
I don’t see a reason to not support a wildcard for errorProps. Would you
like to send a PR?
Il giorno gio 15 mar 2018 alle 12:18 Tizian Adam <notifications@github.com>
ha scritto:

**Comment by davidmarkclements** [comment]
Regarding nesting there might be cases where you don't want nesting so maybe instead of a wildcats, use JSON Path notation cf http://goessner.net/articles/JsonPath/index.html#e2

**Comment by jsumners** [comment]
Which would mean using something like https://github.com/dchester/jsonpath

**Comment by davidmarkclements** [comment]
yeah, or maybe that's too complex

maybe we should go with `*` and `**` where `**` shows all nested props

**Comment by davidmarkclements** [comment]
or maybe have `--errorPropsNestLevel` 🤷‍♂️

**Comment by ilyaztsv** [comment]
If I'll be have enough time on this weekend I'll create PR.

**Comment by ilyaztsv** [comment]
> yeah, or maybe that's too complex
> 
> maybe we should go with * and ** where ** shows all nested props

I think `*` adn `**` good choice for the case.

If I'll be have enough time on this weekend I'll create PR.

**Comment by ilyaztsv** [comment]
so I've created #372 PR for this issue.

**Comment by tizzyapunkt** [comment]
@ilyaztsv Nice, as soon as it get's merged, I will test it and give feedback! Thanks!
