### ISSUE TITLE
Improve stack traces for serialized errors in pretty mode

### ISSUE THREAD

**Issue by hbarcelos** [pinojs/pino#373]
This issue has bugged me for a while.

I often include error objects in log context and to make sure they are properly displayed, I use `pino.stdSerializers.err` or another error serialization tool.

However, those serialized errors stack traces are displayed as a single-line string with new lines converted to visible `\n` characters. While this might be ok for production, it is really suboptimal during development.

For example, given this configuration:

```javascript
const pino = require('pino');

const logger = pino({
  serializers: {
    err: pino.stdSerializers.err,
  }
});

const err = new Error('dummy error');

logger.error({ err });
```

Piping the output of the code above to `pino pretty` gives me:

![one_liner_stack_strace](https://user-images.githubusercontent.com/16565602/37601557-1300b4c8-2b69-11e8-8a04-59a38af5f693.png)

It's quite hard do read a stacktrace like that.

What was intriguing to me was that if I logged the error directly, it'd show a nicely formatted stack trace:

```javascript
logger.error(err);
```
![good_stack_strace](https://user-images.githubusercontent.com/16565602/37601858-d7d017e4-2b69-11e8-8c26-e5f782090b41.png)

---

It would be nice to be able to declare a whitelist of object keys which would be treated as errors by `pino pretty`, properly formatting their `stack` property, as it's already done when logging an `Error` object.

I already have implemented such feature, I can issue a PR at any time if you think this is a good feature for pino.

**Comment by mcollina** [comment]
Feel free to send a PR. Improving the prettifier is something on our radar.
