### ISSUE TITLE
Duplicate properties in nested child loggers

### ISSUE THREAD

**Issue by DonutEspresso** [pinojs/pino#375]
Tested on pino@4.14.0:

```javascript
'use strict';

const pino = require('pino');
const log = pino();

const child1 = log.child({
    component: 'bar'
})
child1.info('hi');

const child2 = child1.child({
    component: 'baz'
});
child2.info('hi');
```

Results in:
```
{"level":30,"time":1521509947993,"msg":"hi","pid":54305,"hostname":"nfml-aliu","component":"bar","v":1}
{"level":30,"time":1521509947994,"msg":"hi","pid":54305,"hostname":"nfml-aliu","component":"bar","component":"baz","v":1}
```

Is this intended behavior? I expected `child2` in this case to stomp over parent fields; the current output could cause all sorts of problems depending on how the systems (and runtimes) consuming them deal with duplicate fields.

**Comment by jsumners** [comment]
https://github.com/pinojs/pino#duplicate-keys

**Comment by DonutEspresso** [comment]
Not sure how I missed that section, sorry for not RTFM. :expressionless:

Understood re: this is the trade off for increased perf. It is worth noting that other runtimes may handle duplicate fields differently - so if you need consistent behavior or do log processing on other systems/runtimes it's probably best to avoid duplicate fields full stop. 

Thanks for the quick reply.
