### ISSUE TITLE
Add information automatically inside log

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [pinojs/pino#376]
Good morning,
I would like to know if is possible to add automatically more information inside log for example IP client address without add every time inside message string the IP address manually.

Example:

```
const pino = require('pino')();
pino.info('First log');
pino.info('Second log');
```

It will produce logs like this:

```
{"level":30,"time":"2018-03-26T08:10:13.634Z","msg":"data_attauale: 2018-03-26T08:10:13+00:00","pid":63,"hostname":"b90e328fb7d9","v":1, "ip":"100.100.100.100"}
{"level":30,"time":"2018-03-26T08:10:13.634Z","msg":"data_ora_vendita: 2018-02-22T17:00:00+00:00","pid":63,"hostname":"b90e328fb7d9","v":1, "ip":"100.100.100.100"}
```

Thanks

**Comment by mcollina** [comment]
You can create a child logger (https://getpino.io/#/docs/API?id=child) and add as many properties that you need.

**Comment by AlessandroMinoccheri** [comment]
Thanks a lot for the quick answer!
I'll try it!
