### ISSUE TITLE
Viewing log files

### ISSUE THREAD

**Issue by andreas-wagner** [pinojs/pino#384]
Viewing log files is not really well doc'd yet.
On Windows you'd do `pino < my.log` on linux/unix/mac `cat my.log | pino`.
Took me a while to understand that pino just transforms streams/stdout.

Now how do I only view errors from the logfile?

Also is it possible to show 1 to 3 lines before any error happened as well, as to not having to search the whole log, but conveniently see the errors and what lead to them at a glance?

Lastly is it possible to tell pino not to use stdout but read a file (by itself) instead?
This would make it's use (see 2nd line) the same on any platform...
Well maybe you know a little npm cli utility that does the same as cat?
That would be sufficient as well... I know I could write my own, but why reinvent the wheel ;-)

**Comment by jsumners** [comment]
Speaking of not reinventing wheels: use `cat` and `grep`. The readme also provides examples for using `jq`.

**Comment by davidmarkclements** [comment]
>  Now how do I only view errors from the logfile?

An error is just a log with the `level` key set to 50. 
As @jsumners alludes, you can `cat log.out | grep '"level": 50'

Or you can use `jq` which can essentially be used as a JSON aware grep tool.

> Also is it possible to show 1 to 3 lines before any error happened as well, as to not having to search the whole log, but conveniently see the errors and what lead to them at a glance?

As long as you're logging `Error` objects  (`logger.error(new Error())`) you're going to get a stack trace, in the `stack` property

> Lastly is it possible to tell pino not to use stdout but read a file (by itself) instead?

Feel free to create any such tool...but I'd just pipe into pino

Closing the issue for now, if you'd like to add any clarity to the docs a PR is welcome!
