### ISSUE TITLE
new prettifier boilerplate

### ISSUE THREAD

**Issue by unjello** [pinojs/pino#389]
After looking at new API, and reference prettifier by @jsumners (https://github.com/pinojs/pino-pretty), methods like `isObject` and `isPinoLog` seem like something each prettifier will have to basically copy&paste. Don't really have a good way to solve it, but I feel like this should be somehow passed from core to avoid repeating those helper methods in every prettifier. Maybe a wrapper object with type field or something?

**Comment by jsumners** [comment]
I think there's just going to some baseline code that each prettifier will have to implement. In the case of these two functions:

1. If the incoming data to parse is not an object, then we are assuming it is a string of JSON to parse. After parsing that JSON, we need to determine if it is something we can format or something we need to simply regurgitate to `stdout` (e.g. a `console.log('wtf is wrong here?')`).
2. If it *is* an object, then we are assuming it is a Pino log object directly from Pino's `.write()` invocation.

There are two things that can't really be abstracted out other than to give notice that prettifier authors need to consider them, as far as I can tell.

**Comment by unjello** [comment]
Ad 1 and 2 - as you say it is something all prettifiers will do, most likely the same way. I would think by definition it asks to be abstracted away, or at least hidden behind boilerplate client module - such that if someone decides to handle it differently, they can, but 99% cases can be covered by bootstrapping module e.g. `pino-pretty-base`, so the base takes care of unpacking json, and if it's something to regurgitate the base wouldn't even call formatting method provided by prettifier.

I think entire `bin.js` will most likely be identical from one prettifier to another.

**Comment by jsumners** [comment]
I can assure you that `bin.js` is not portable. Other prettifiers are not as interested in implementing more options -- https://github.com/lrlna/pino-colada/issues/17

I'm not opposed to a core module, I just don't think there is much to put in it.

**Comment by davidmarkclements** [comment]
just while we're thinking options extensibility (re lrlna/pino-colada#17) ... what if we had a straightforward way to compose prettifiers on the command line

For instance:

```
node app.js | pino pino-pretty pino-colada
```

Would apply both prettifiers, then a very small prettifier could be created which complimented pino-colada for that use case - leading to greater modularity 

A programmatic interface could be supplied, which allows for composition via requiring the prettifiers so that someone could, for instance bring the complimentary module and pino-colada together 

If we did do that, it may then be worth thinking about prettifier standardization

**Comment by unjello** [comment]
@jsumners there is some stuff redundant in `bin` too. `SIGINT` handler, pumping, creating transport through `through`. My `bin` right now has 30 lines, and only 4 of them are `args` specific to my prettifier. If not core module (or supporting module), I was thinking for a second - yo template? But there probably won't be that many prettifiers to justify that, so you may be right, maybe it's something that can be just documented, and interested parties will just copy chunks over to their prettifiers.

**Comment by jsumners** [comment]
@unjello I should have some time this week to work on some ideas from this conversation.

@davidmarkclements that seems very complicated for likely very little pay off. To the best of my knowledge, there's `pino-colada` and `pino-pretty-min` that exist outside of the core prettifier. I also like the thought that we give prettifier authors the freedom to implement whatever they want however they want.

**Comment by davidmarkclements** [comment]
@jsumners yeah you're probably right

**Comment by jsumners** [comment]
@unjello I think this has been resolved by #386. If not, feel free to re-open.

**Comment by unjello** [comment]
@jsumners sorry it took so long, but I've been swamped. Yes, indeed. It's exactly what I was looking for. Thank you!
