### ISSUE TITLE
Documentation about log content

### ISSUE THREAD

**Issue by mysticatea** [pinojs/pino#390]
Hello.

I'm looking for the specification of log outputs in [the documentation](https://getpino.io/#/). In [the Usage section](https://getpino.io/#/?id=usage), I can find the below log sample.

```
{"pid":94473,"hostname":"MacBook-Pro-3.home","level":30,"msg":"hello world","time":1459529098958,"v":1}
```

However, the explicit description about those properties doesn't look to exist. For example, the `"level": 30` seems to mean information, but I couldn't find the definition in the documentation. I guess that the level values come from [.levels.values](https://getpino.io/#/docs/API?id=levelsvalues) and it has implicit default values.

I'm happy if the documentation descrives the specification of log outputs explicitly. Especially, the level values are important to handle log outputs.

Thank you.

**Comment by mcollina** [comment]
I think that any help that improves the doc is very welcomed! Send a PR!
