### ISSUE TITLE
document the browser usage

### ISSUE THREAD

**Issue by dcharbonnier** [pinojs/pino#398]
It's not easy to understand that the feature provided by the browser are quite far from the nodejs version.
From what I understand the "child" on the browser implementation does not provide any functionality.
Reading the current documentation we could expect that the `write` function will receive the information sent to the `stream` in the nodejs implementation (and that would be nice) but it doesn't look like it's the case.

**Comment by davidmarkclements** [comment]
browser docs are  made clearer in next-major
