### ISSUE TITLE
Accessing object's properties from within msg

### ISSUE THREAD

**Issue by lgomez** [pinojs/pino#402]
Hi all,

Is it possible to somehow reference the log object's values from within the message string? I'm trying to achieve something like this:

```javascript
log.info({ name: 'Luis', last: 'Gomez' }, 'Hello my name is ${obj.name} ${obj.last}.')
```
I tried creating a serializer to achieve something similar but only for certain properties but not sure there is a way to return the `msg` from a serializer.

Thanks!

**Comment by jsumners** [comment]
The only way to do this would be to use the [metadata API](https://github.com/pinojs/pino/blob/701711e60065f9fd907c958a68efd383b2bb161a/docs/API.md#metadata) to implement your own stream. Within that stream you would implement your string interpolation. This would be an expensive operation, though.
