### ISSUE TITLE
onTerminate without extreme mode

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#411]
The `onTerminate` behavior is applied __also__ with `pino.destination(file)` or stdout.
We should apply just a limited version of this, just listening for `'exit'`.

**Comment by jsumners** [comment]
I'm okay with a basic `exit` listener. Registering one of those does not alter the standard shutdown procedure like the others we listen for under extreme mode.

**Comment by davidmarkclements** [comment]
Sgtm

**Comment by jsumners** [comment]
Title says it should be for non-extreme mode. Didn't we only implement for extreme? I'm fine with it being closed if this is solved.

**Comment by mcollina** [comment]
This is done ;).
