### ISSUE TITLE
remove the `silent` logger method

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#434]
We support `silent` as .a special public logger method, and test it but it's not in the docs

**Comment by mcollina** [comment]
whould we just remove it in the next semver-major?

**Comment by jsumners** [comment]
No. It’s really useful for tests.

**Comment by jsumners** [comment]
If you are testing a something that uses Pino for logging, and you don't want to see those logs all over your tests, it's helpful to be able to silence them.

**Comment by davidmarkclements** [comment]
Absolutely.. I think there's some confusion here. There's a method called logger.silent, its a no-op and there's no use case (that I can think of) for it. setting the level to silent, is different thing and the internal implementation doesn't rely on the existence of a silent method

**Comment by jsumners** [comment]
Cool.

**Comment by davidmarkclements** [comment]
Perfecto - let's remove
