### ISSUE TITLE
Pretty colorized example

### ISSUE THREAD

**Issue by rmuchall** [pinojs/pino#437]
I've just upgraded to the latest version v5.0.0-rc.4
Please could you provide a code example as to how I can colorize the log output in process.stdout?
I've tried using the example found at:
https://github.com/pinojs/pino-pretty#prettyasmetawrapperwritable
but the following error occurs:
`
SyntaxError: Unexpected token u in JSON at position 6
    at JSON.parse (<anonymous>)
    at Object.write (C:\Work\TypeScript\peardrop\peardrop-server\node_modules\pino-pretty\index.js:269:26)
    at Pino.write (C:\Work\TypeScript\peardrop\peardrop-server\node_modules\pino\lib\proto.js:101:15)
`

Thanks for an awesome library! :)

**Comment by davidmarkclements** [comment]
@rmuchall 

try: 

```
const factory = require('pino-pretty')
const pino = require('.')

// writable is any Writable stream
const writable = process.stdout

const logger = pino({
  prettyPrint: { colorize: true }
})

logger.info('hi')
```

Bear in mind that v5 is a release candidate (thanks for the feedback btw!), we still need to update the docs in pino core and supporting repos.

**Comment by davidmarkclements** [comment]
@rmuchall on a side note, we recommend against in-process prettification. 
If you use `pino-pretty` as CLI tool (`node app.js | pino-pretty -c`) instead this removes the possibility of accidentally deploying prettified logging in production (which we strongly recommend against for performance and log processing reasons).
