### ISSUE TITLE
pino-integration and ecosystem modules to align with next-major

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#439]
https://github.com/pinojs/pino-integration has a CI setup for running pino ecosystem modules against a given pino branch. 

The way it works is the branch on pino-integration matches against the branch on pino, so in this case `next-major`. If the ecosystem repo that's being tested also has a `next-major` the test will run against that branch, otherwise they'll run against master (notice in the screen shot, pino next-major is compared against pino-pretty next-major, whereas all others are compared against master). 

pino-integration has revealed the following modules need to be aligned with next-major:

* pino-caller
* hapi-pino
* pino-debug
* pino-multi-stream

pino-tee is broken generally, I've submitted a PR for a fix here: https://github.com/pinojs/pino-tee/pull/9 - after that pino-integration can run again. 

pino-clf fails intermittently on CI for some as yet undiscovered reason, however every time tests are manually run it passes 🤷‍♂️  – this behaviour *only* occurs with pino-clf, the confidence of the accuracy for the rest is high at this point. 

pino-integration is set to run every day, so any changes in the pino ecosystem and all dependents can be picked up on a daily basis. 

![image](https://user-images.githubusercontent.com/1190716/41656582-c15153f0-7490-11e8-9be1-725ef7725832.png)

**Comment by jsumners** [comment]
I think this is great. I whole heartedly endorse this effort.

**Comment by mcollina** [comment]
It would be awesome to have that run automatically for every PR - after the unit tests pass.

Can you open some issues on the relative repos?

**Comment by davidmarkclements** [comment]
I think we need to figure out a way to that, possibly here, and then have that installed as an executable for at the end of `npm run ci` in each repo. Triggering an associated CI requires making travis API's calls

**Comment by davidmarkclements** [comment]
Ok, all ecosystem modules (hopefully) are now aligned with v5:

![image](https://user-images.githubusercontent.com/1190716/42332363-0ec2c6c6-8078-11e8-9dfe-6b16a8ef7952.png)

**Comment by mcollina** [comment]
I'm ok in releasing new major releases for all modules.

**Comment by jsumners** [comment]
I'm on board with new majors for all packages.

**Comment by davidmarkclements** [comment]
Just to clarify - are we saying new majors for *all* modules as in, every single one whether they need to be altered or not 

Or are we saying *all affected* modules?

**Comment by jsumners** [comment]
Affected.

**Comment by mcollina** [comment]
I think we can close this now!
