### ISSUE TITLE
Serializers not acting on key 'level'

### ISSUE THREAD

**Issue by bhatanku1** [pinojs/pino#440]
I want to have levels as string, e.g. 'info', 'error'... instead of the integers. I already read the discussion [here](https://github.com/pinojs/pino/issues/279). But since I already have a custom serializer for the req and res objects, I wanted to use it to modify the 'level' as well and not use the [transport library](https://www.npmjs.com/package/pino-text-level-transport) mentioned in the discussion. But the serializer does not act upon the level although it works fine for other keys like req, res, responseTime, etc. 

This is my customSerializer:  

```
const customSerializers = {
  req: (req) => {
    // logic
    return formattedLog;
  },
  level: (l) => {
    // logic
   return formattedLog;
  },
};
```
This modifies the req in the logs but not the level.

**Comment by davidmarkclements** [comment]
A serializer is responsible for returning values from an object - there is no level property on a request or response object so this would not be an appropriate way to go about it. If you don't want to use a separate process you can use pino-multi-stream to and supply a transform stream to reformat  the log message
