### ISSUE TITLE
v5 proposal: adding `levels` option, removing implicit `level`+`levelVar` behaviour

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#446]
I think we should allow a new `levels` option:

```js
pino({levels: {label: 'foo', value: 100}})
```

And remove the following implicit behaviour: 
```
  pino({level: 'foo', levelVal: 100})`
```

I also think `levelVal` should be a static property, instead of a getter/setter

The benefits:

* It's explicit
* Allows for multiple levels to be added
* It's much easier to document (less conflation of concepts)
* Will allow for less code,
* **could** lead to faster child logger creation (possible removal of additional `isStandardLevel` and `isStandardLevelVal` checks)

**Comment by mcollina** [comment]
I'm not necessarily sure what you are asking. What would this do?

```js
pino({levels: {label: 'foo', value: 100}})
```

Does it create a custom level, or set the default level?

`pino({ level: 'info' })` set the default level.

**Comment by davidmarkclements** [comment]
`pino({ level: 'info' })` sets the default level, but `pino({ level: 'foo', levelVal: 100 })`  *creates a new level*. This is documented behaviour in v4. 

I don't think this in intuitive and instead suggest we allow for a `levels` option that allows for additional custom levels. I've messed up the syntax, it should be `{foo: 100}`.
 Maybe we should call it `customLevels`:

```
const logger = pino({
customLevels: {
   foo: 100, 
   bar: 110
  }
})

logger.foo('hi')
logger.bar('hi')
logger.info('hi')
```

**Comment by jsumners** [comment]
Go for it. I'm going to defend the current implementation as a backward compatible implementation. Yeah, that's the ticket.

**Comment by mcollina** [comment]
Go for it, but use `customLevels`.

**Comment by davidmarkclements** [comment]
done
