### ISSUE TITLE
About pretty mode

### ISSUE THREAD

**Issue by poppinlp** [pinojs/pino#448]
I find you use chalk in pretty mode. How about [kleur](https://github.com/lukeed/kleur) for performance reason? If you'd like it, i'll send a PR. :)

**Comment by davidmarkclements** [comment]
this is more an issue for https://github.com/pinojs/pino-pretty

if you can show benchmarks that make pino-pretty significantly faster without complicating implementation or losing functionality we'd certainly welcome a PR for pino-pretty

closing as wrong repo for issue
