### ISSUE TITLE
Send logs data to Fluentbit

### ISSUE THREAD

**Issue by mhf-ir** [pinojs/pino#451]
[Article for use case](https://dzone.com/articles/fluentd-vs-fluent-bit-side-by-side-comparison-logz)
Fluentbit is very lightweight zero dependency log collector best use case is store edge of logs tag them and interval flush to next log level aggregation 

How can i path throw logs to fluentd via pino:
Heres my file storage method:
```typescript
import { createWriteStream, existsSync, mkdirSync } from 'fs';
import { tmpdir } from 'os';

import * as pino from 'pino';

export default () => {
  const dir = `${tmpdir()}/logs`;
  if (!existsSync(dir)) {
    mkdirSync(dir);
  }
  const stream = createWriteStream(`${dir}/aasaam-app.log`, {
    flags: 'a+',
  });
  const logger = pino(stream);
  return logger;
};
```
For example above i can use input-tail plugin for fluentbit but if logs can directly into fluentbit tcp server will be awesome :smile: 

I need to do with script not using terminal piping and how to send json logs to fluentbit server:
https://fluentbit.io/documentation/0.14/input/tcp.html

**Comment by davidmarkclements** [comment]
hey looks like http://github.com/pinojs/pino-socket is exactly for you

if you're interested in additionally wrapping pino-socket and creating pino-fluentbit we'd be happy to review the repo and help you keep it performant etc. 

closing for now, as the answer to the question is: pino-socket

**Comment by jsumners** [comment]
Ugh, I just closed the issue on `pino-socket` because I didn't think it to be on topic for the module. `pino-socket` is designed to accept input on `stdin` *only*.
