### ISSUE TITLE
Logging data with undefined properties

### ISSUE THREAD

**Issue by ismaelRozas** [pinojs/pino#453]
When we have to debug any application and we want to log a message and some data with undefined properties, we found that if we have only one object with one undefined property, it doesn´t log it:

`const pino = require('pino');
  pino.debug({ property: undefined }, 'undefined properties object here');
`

The output in this case is:
[2018-07-17T07:29:12.752Z] DEBUG (MacBook-Pro): undefined properties object here

In this case, it could be interesting to have the complete object in the output in this case, to detect this kind of errors related to incomplete or wrong objects.

**Comment by mcollina** [comment]
Thanks for reporting, but I fear we can’t help you with this. Pino logs using newline delimited JSON, meshing all properties in the object. A property with value undefined is not rendered in JSON.
