### ISSUE TITLE
Invalid error JSON logged if stack is undefined

### ISSUE THREAD

**Issue by disintegrator** [pinojs/pino#456]
To reproduce:

```js
const logger = require('pino')();
const err = new Error();
delete err.stack;
logger.error(err);

/*
{"level":50,"time":1532087320790,"msg":"","pid":20631,"hostname":"dev.local","type":"Error","stack":undefined,"v":1}
*/
```
Note the section `"stack":undefined` which is not valid JSON.

Real world example: Apollo GraphQL has a custom error class called ApolloError that does not hold `stack` property. When logging an ApolloError we see the issue above which breaks pino's pretty printer among other things.

Pino version: 4.17.3

**Comment by disintegrator** [comment]
I'm guessing this line is the culprit: https://github.com/pinojs/pino/blob/v4.17.3/pino.js#L149

```js
data += ',"type":"Error","stack":' + this.stringify(obj.stack)
```
might have to change to:
```js
data += ',"type":"Error"'
data += obj.stack ? ',"stack":' + this.stringify(obj.stack) : ''
```

If that's the case then I'm happy to submit a PR

**Comment by mcollina** [comment]
Please do so! Would you mind adding a unit test as well?
Il giorno ven 20 lug 2018 alle 14:46 George Haidar <notifications@github.com>
ha scritto:

**Comment by davidmarkclements** [comment]
pino-integration has picked up that this broke a test in pino-pretty

![image](https://user-images.githubusercontent.com/1190716/43035202-9fa73e7c-8ceb-11e8-85d4-2ee29f26c95a.png)

![image](https://user-images.githubusercontent.com/1190716/43035203-a4d484fe-8ceb-11e8-9e57-7906f089cf1e.png)
