### ISSUE TITLE
flush & flushSync stdout

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#458]
Even in non extreme mode logs are not properly flushed during `process.exit`. See, https://github.com/nodejs/node/issues/6456

No sure how to resolve this? Should we send a cb to every `write` call to keep a `isFlushed` flag up to date?

**Comment by davidmarkclements** [comment]
is this relevant to the v5 release and the sonic-boom approach (cc @mcollina)

**Comment by ronag** [comment]
The sonic-boom approach does it correctly. This is more of a problem with the non extreme/sonic-boom approach.

**Comment by davidmarkclements** [comment]
yeah that's a node core issue - so it's a wont-fix for us - we recommend using `pino.destination` in the v5 docs and v5 use `pino.destination(1)` by default to supply stdout flushing

**Comment by ronag** [comment]
@davidmarkclements Fair enough. Though we might want to emphasize this in the docs?

**Comment by davidmarkclements** [comment]
absolutely - feel welcome to PR against next-major docs
