### ISSUE TITLE
v5 release

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#459]
Do we have any issue tracking what's left for a 15 release? The milestone seems to be complete. I'd be willing to help out.

**Comment by davidmarkclements** [comment]
thanks @ronag v5 is near release, it's mostly a case of aligning the ecosystem modules which I'm already on

**Comment by mcollina** [comment]
It's out!

**Comment by willdurand** [comment]
Hi @mcollina and all, thanks for this wonderful lib. Is there an upgrade guide from v4 to v5?

Also, are transports affected? I maintain two transports and I wonder if there is a way to make sure they are v5-compatible:

- https://github.com/willdurand/pino-devtools
- https://github.com/willdurand/pino-mozlog 

Thanks!

**Comment by mcollina** [comment]
@willdurand transport should be largely unaffected. 

The changes are listed in: https://www.nearform.com/blog/announcing-pino-5/.

If you would like to contribute a migration guide, please do so! Your code should be mostly unaffected if you are not using extreme mode (which was re-done). You might get some performance boost by switching to `pino.destination(file)` if you were writing to files.

**Comment by willdurand** [comment]
@mcollina awesome, thanks for the info!
