### ISSUE TITLE
Add `pino.log` method

### ISSUE THREAD

**Issue by niftylettuce** [pinojs/pino#460]
This library is missing `pino.log` as a method, can you please add it?  If not, can you elaborate why?

**Comment by davidmarkclements** [comment]
hey @niftylettuce – nope it's not missing. `pino` is not a `console` object substitute, it's a Log4J inspired NDJSON logger with a focus on performance. Each of the default methods have a value related to their priority as inferred from the semantics: so fatal is a higher priority than info, trace is a lower priority than error, and so on. The word `log` is neutral, it's difficult to prioritise without violating the principle of least surprise. You *could* replace the `info` method with `log`, but `info` is more descriptive and in keeping with Log4J. 

If you really want a log method you can use `addLevel` method (or `customLevels` option in the v5 release candidate) to add it a custom method.

**Comment by niftylettuce** [comment]
@davidmarkclements I tried to do `pino.addLevel('log', 30);` however `pino.log` is not a function.  V5 via `customLevels` makes sense but that's not available yet so I wanted to know if there's a bug here with V4 and `addLevel` that causes `pino.log` to not be defined?
