### ISSUE TITLE
res output clarification

### ISSUE THREAD

**Issue by arvi** [pinojs/pino#465]
Hello,

I've been trying out `pino` after watching videos about logging in YT and would like to clarify if the response body is not really a part of `res` output?
Does it mean I have to perform another log for the actual response body inside my `controller` logic? Or is there some kind of way of handling it in `pino`?

```js
import pino from 'pino';
export default pino({
  name: 'test',
  safe: true,
  serializers: {
    req: pino.stdSerializers.req,
    res: pino.stdSerializers.res,
  },
});
```

```js
import pino from './config/pino';

app.use((req, res, next) => {
  pino.info(
    {
      req,
      res,
    },
   'http request/response',
  );
 next();
});

app.use('/api', routes);
```

Thanks for the help.

**Comment by mcollina** [comment]
We are not including the response by default, mainly because it is expensive and it will slow things down significantly.

**Comment by arvi** [comment]
Thank you, it's making sense to me now 😅
