### ISSUE TITLE
docs: broken link, metadata api

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#477]
http://getpino.io/#/api?id=metadata

Linked from http://getpino.io/#/docs/pretty?id=prettifier-api

**Comment by davidmarkclements** [comment]
It's not missing, the link needs to be updated to http://getpino.io/#/docs/api?id=destinationsymbolfor39pinometadata39

**Comment by davidmarkclements** [comment]
and renamed to just "metadata api"
