### ISSUE TITLE
process.on('SIGINT')  pino.info() not log out 

### ISSUE THREAD

**Issue by ipengyo** [pinojs/pino#481]
pino.info() not log out 

![image](https://user-images.githubusercontent.com/9323722/44003277-9b0a5f4a-9e82-11e8-92f2-a2e545693e6f.png)

![image](https://user-images.githubusercontent.com/9323722/44003281-a5f51bb6-9e82-11e8-8fb5-c7b5da324bc1.png)

**Comment by davidmarkclements** [comment]
use pino.final, See docs

**Comment by ipengyo** [comment]
@davidmarkclements 

I'm not very convenient at the moment because my frame close code is use `pino.info`. Is there any other way?

**Comment by davidmarkclements** [comment]
you can still use info, you need to use pino.final to get a finalLogger instance based on your current logger instance. 

Please read the docs.
