### ISSUE TITLE
Setting `base: null` removes logger name

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#494]
http://getpino.io/#/docs/api?id=base-object

The docs claim that setting `base: null` will only remove the pid and the hostname from the output log but it is also removing the "name" field:

![image](https://user-images.githubusercontent.com/321201/44313226-5c316200-a3d2-11e8-9305-97b1c86090f2.png)

Is this a bug in the implementation or the documentation? I claim it to be a bug in the implementation.

**Comment by mcollina** [comment]
Considering why I’ve added that, it’s a problem in the docs IMHO.

**Comment by jsumners** [comment]
:(

**Comment by jsumners** [comment]
Fair enough. I can solve locally via `endSym`.
