### ISSUE TITLE
simple profiling mechanism ?

### ISSUE THREAD

**Issue by eran10** [pinojs/pino#497]
winston have simple option as logger.profile :
https://github.com/winstonjs/winston#profiling

does pino have any alternatives ?

**Comment by mcollina** [comment]
Unfortunately it does not offer anything similar. I think it would fit nicely in an ancilliary module, something like:

```js
const Profiler = require('pino-profiler')

const profiler = new Profiler(logger)

profiler.start('key')
profiler.stop('key')
```

It would be a nice module to write!

**Comment by eran10** [comment]
i agree, i just think that i require pino and will have this function (profile) it will be easier,
or allowing integrate it with pino option same as pretty pino, what do you think ?

**Comment by mcollina** [comment]
I would prefer not to, this functionality stays well in the ecosystem. Considering the fact that all child loggers inherits from the prototype of their parent, you could also:

```js
const logger = require('pino')()

logger.profile = function (key) {
  // implement your functionality
}

logger.child({ hello: 'world' }).profile('key')
```

which will be nicely incapsualted in:

```js
const logger = require('pino-profile')(require('pino')())
```

**Comment by davidmarkclements** [comment]
very very cool @gauravmk - would you be interested in

1) adding benchmarks and documenting the impact of the profiler on performance in the readme
2) sending a PR to the docs to add your module to https://getpino.io/#/docs/ecosystem
3) possibly adding a doc to the Help section "Profiling"

**Comment by gauravmk** [comment]
Sure thing. The winter holidays are a great time to harden this up so that I’d actually feel comfortable with people using it in production. + benchmarking and documentation
