### ISSUE TITLE
logger.write

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#505]
It would be nice to have a "raw" writer to that I can write pre-formatted objects directly into pino. Right now I have to do something like:

```js
            const obj = JSON.parse(message)

            const level = obj.level
            delete obj.level

            const msg = obj.msg
            delete obj.msg

            const label = logger.levels.labels[level]
            logger[label](obj, msg)
```

Instead of

```js
logger.stream.write(message)
```

Which was possible in v4.

**Comment by mcollina** [comment]
I'm a bit lost on the use case for this. Can you please iterate a bit on why you need it?

Given that you pass in the stream as an option, why would you need to access the internal stream?

**Comment by davidmarkclements** [comment]
yep I agree with Matteo, you can just write to the destination directly, it doesn't need to be exposed

Still if you're desperate:

```
logger[pino.streamSym].write(message) 
```

should do the trick
