### ISSUE TITLE
Improve prettifier documentation

### ISSUE THREAD

**Issue by felixheck** [pinojs/pino#510]
Hi there!

AFAIK, since the v5 release and the integration of `pretty-pino` the `prettyPrint.formatter` option is useless. 

Is there an easy way to migrate the `prettyPrint.formatter` option to v5 though? 😔

Cheers!

**Comment by mcollina** [comment]
what do you mean?

**Comment by felixheck** [comment]
There was a prettyPrint.formatter option in pino <=4 — this option is not available because pino-pretty doesn’t support such option. 

And since I try to stay up to date, I’m looking for an alternative way to format the output.

**Comment by mcollina** [comment]
Oh, we have internalized that functionality and forgot to write the docs: https://github.com/pinojs/pino/issues/478.

**Comment by mcollina** [comment]
Actually there is non-documented (mistake) API https://github.com/pinojs/pino/blob/master/lib/tools.js#L159-L170. passing a prettifier function would do the same function of `prettyPrint.formatter`.

Would you like to help and figure out the docs?

**Comment by felixheck** [comment]
Ah awesome 🙌🏼
Gonna try to fire a PR tomorrow in the plane — otherwise after my holiday 😊 

Thanks Matteo!

**Comment by jsumners** [comment]
Yes it is documented -- http://getpino.io/#/docs/pretty?id=prettifier-api

**Comment by mcollina** [comment]
I think we can do a bit better, the example is not really self-explanatory.

> The reference implementation of such a module is the pino-pretty module. To learn more about creating a custom prettifier module, refer to the pino-pretty source code.

We can actually explain this.
