### ISSUE TITLE
How to customise output of pino logger

### ISSUE THREAD

**Issue by stereobooster** [pinojs/pino#533]
I need to change `time` to `timestamp`, `reqId` to `request_id` (or this comes from fastify?) etc. I looked through examples with serialisers, but it seems you can only change serialisation of req/res/err not the whole thing

**Comment by davidmarkclements** [comment]
hey @stereobooster - see http://getpino.io/#/docs/api?id=serializerssymbolfor39pino39-function

However, we recommend massaging data out of process if possible

**Comment by stereobooster** [comment]
Thanks for the quick response, but I can't make it work

```js
const logger = pino(
  {
    level: "info",
    useLevelLabels: false,
    messageKey: "event",
    base: {}
  },
  pino.destination(path.join(__dirname, "../log/my.log"))
);
logger.genReqId = genReqId;
logger.serializers = {
  // just to check if it is called or not
  [Symbol.for("pino.*")]: () => process.exit(1)
};
```
