### ISSUE TITLE
SonicBoom crashing the logs after updating pino to v5

### ISSUE THREAD

**Issue by andersonleite** [pinojs/pino#535]
I'm facing an issue after updating pino from "pino": "^4.16.1" to "pino": "^5.8.0"

```
Error: EPIPE: broken pipe, write
Emitted 'error' event at:
    at SonicBoom.release (/app/node_modules/sonic-boom/index.js:62:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:643:5)

```
Looks like pino > 5 started using SonicBoom and the logs are crashing on the server for me.
Is this a good place to search for help on this topic?

Thanks!

**Comment by mcollina** [comment]
Can you please provide an example to reproduce?

**Comment by andersonleite** [comment]
> is pino-tee staying alive?

No.

**Comment by mcollina** [comment]
Does this happens on high throughput? How much does it happens?

It seems the destination is crashing because the pipe between the to processes is shut down.

**Comment by debianw** [comment]
hi I'm having the same issue. @mcollina I prepare a repo with a small app where you can reproduce the issue. #ref 539

Please take a look to my repo here: https://github.com/debianw/testing-pino
