### ISSUE TITLE
CPU Spike / EventLoop Block using pino.error

### ISSUE THREAD

**Issue by emhagman** [pinojs/pino#537]
Hi,

I am running into an issue where if I try to log an error from the https://github.com/axios/axios library, my entire NodeJS process is basically unusable for 10 seconds.

I noticed this issue https://github.com/pinojs/pino/issues/203 and appears to be the same type of error. I am currently on `pino 5.8.0`.

For now I've intercepted the error via Axios and created my own without the objects I believe are causing the issue.

```
function AxiosError(axiosError: Object) {
    this.name = 'AxiosError';
    this.message = axiosError.message;
    this.response = _.pick(axiosError.response, ['status', 'statusText', 'headers', 'data']);
    this.stack = axiosError.stack;
}

AxiosError.prototype = Object.create(Error.prototype);
AxiosError.prototype.constructor = AxiosError;
module.exports.AxiosError = AxiosError;
```

Any thoughts? It has been killing our server.

**Comment by mcollina** [comment]
Can you upload a full example that reproduce the problem?

Which version of Node.js is this happening on?

**Comment by davidmarkclements** [comment]
I'm going to close this as stale, but @emhagman please feel free to re-open with extra info
