### ISSUE TITLE
Would you like to add an example in our 'best practice' repo?

### ISSUE THREAD

**Issue by i0natan** [pinojs/pino#538]
Hey, we're now adding a new best practice - "Don't log to files, prefer stdout". [See here](https://github.com/i0natan/nodebestpractices/pull/272#pullrequestreview-171631060)

Would you like to PR a simple example of how easily this can be achieved with Pino?

p.s I wonder if you ever benchmarked for stdout vs file performance?

**Comment by jsumners** [comment]
The example really wouldn't be more than:

```js
const log = require('pino')()
log.info('foo')
```

Do you need one of us to contribute such?

**Comment by i0natan** [comment]
@jsumners hmm - No. Simple enough.

Any thoughts on stdout performance vs other targets?

**Comment by jsumners** [comment]
I could be mistaken, maybe @mcollina can verify, but with v5 Pino’s performance should be roughly equivalent to stdout or a file.

**Comment by mcollina** [comment]
On all my test the performance is pretty good. I didn't write things down, and I'd have little time.
However it would be great way to contribute.

The performance should be very similar. However, it depends on the throughput of the target.

**Comment by davidmarkclements** [comment]
I think this is resolved this it doesn't require a PR from us
