### ISSUE TITLE
Error: EPIPE: broken pipe, write | pino 5.8.0

### ISSUE THREAD

**Issue by debianw** [pinojs/pino#539]
NodeJS: v10.13
OS: MacOS 10.13.6
pino: 5.8.0

I'm doing a small transport test but after a benchmark I get this `broken pipe` exception.

Please take a look to this small demo where you can reproduce the issue: https://github.com/debianw/testing-pino

Just clone the repo and do

```
npm install
npm run start
autocannon -c 5 -p 5 -d 5 localhost:4001
```

You'll get this exception:

![screen shot 2018-11-05 at 1 11 50 pm](https://user-images.githubusercontent.com/1002407/48020906-c073e000-e0fc-11e8-9000-0343fd3ee4a6.png)

See the JSON it produce before the crash:
```
{
  "level": 30,
  "time": 1541445073817,
  "msg": "processing request",
  "pid": 9052,
  "hostname": "Walters-Mac-mini.{"level":30,"time":1541445073820,"msg":"processing request","pid":9052,"hostname":"Walters-Mac-mini.local","v":1}
```
That's not a valid JSON

**Comment by jsumners** [comment]
![testing-pino zsh 2018-11-05 19-10-23](https://user-images.githubusercontent.com/321201/48034755-a4893200-e12e-11e8-9e86-1393dc94b5f1.png)

I am unable to reproduce it with your sample repo.

**Comment by debianw** [comment]
@mcollina service in not crashing now in 5.8.1 but still the exception above before the crash is happening and logs stop working. #541
