### ISSUE TITLE
SyntaxError: Unexpected token in JSON | pino 5.8.1

### ISSUE THREAD

**Issue by debianw** [pinojs/pino#541]
NodeJS: v10.13
OS: MacOS 10.13.6
pino: 5.8.1

Please take a look to this small demo where you can reproduce the issue: https://github.com/debianw/testing-pino

Just clone the repo and do

```
npm install
npm run start
autocannon -c 5 -p 5 -d 5 localhost:4001
```

![screen shot 2018-11-06 at 8 52 59 am](https://user-images.githubusercontent.com/1002407/48072141-76910580-e1a1-11e8-9f56-6afee7cd89c6.png)

![screen shot 2018-11-06 at 8 53 54 am](https://user-images.githubusercontent.com/1002407/48072185-8dcff300-e1a1-11e8-8d12-5a4d5ffa157b.png)

After this exception logs stop working

#539

**Comment by mcollina** [comment]
This should be fixed with the latest sonic-boom release. Let us know.

**Comment by debianw** [comment]
@mcollina all good! thanks
