### ISSUE TITLE
pino prefix string to each log line

### ISSUE THREAD

**Issue by eran10** [pinojs/pino#544]
Hi,
is there any option to add some const string to pino logger so for every log line we use "info" for example so i may add some prefix string that will be added ?

e.g
pino.info(`${my prefix} some log line`);
pino.info(`${my prefix} some other log line`);

**Comment by mcollina** [comment]
Thanks for reporting! This is currently not possible.

**Comment by davidmarkclements** [comment]
I'd suggest creating a little library for this, you could call it `pino-prefix` or some such,
the following should get you started: 

```js
function pinoPrefix(prefix, pinoInstance) {
  const { levels } = pinoInstance
  const { values } = levels
  Object.keys(values).forEach((level) => {
     const LOG = pinoInstance[level].bind(pinoInstance)
     pinoInstance[level] = (msg, ...args) => { 
      return LOG(typeof msg === 'string' ? prefix + msg : msg, ...args)
     }
  })
  return pinoInstance
}
```

In terms of putting it in core, we're happy to review PR's but it would need to have the following properties

1. zero overhead when not in use
2. very low performance impact when in use
3. clearly defined parameters of what would happen in the case of an object logging
4. documentation
5. tests (100%)
6. benchmarks
