### ISSUE TITLE
Redact option is missing in type definitions

### ISSUE THREAD

**Issue by ranyefet** [pinojs/pino#546]
Hello,

I'm using the latest version of `pino` and `@types/pino`
```
"@types/pino": "^5.8.1",
"pino": "^5.8.1",
```

I'm trying to use the redact feature:
```
const logger = pino({
  redact: ['req.headers.authorization']
});
```

But I'm getting an error that `redact` is not part of `LoggerOptions`, so I can't use that feature.

How can I fix this issue?

Thanks,
Ran.

**Comment by mcollina** [comment]
You’ll need to send a PR to the @types/pino module. Those are maintained in
definitelytyped.

Il giorno dom 18 nov 2018 alle 16:50 Ran Yefet <notifications@github.com>
ha scritto:

**Comment by ranyefet** [comment]
Opened an issue for DefinitelyTyped
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30631

Closing this issue.
