### ISSUE TITLE
pino.extreme() on windows

### ISSUE THREAD

**Issue by ad34** [pinojs/pino#547]
Am I missing something ? I am trying to test the pino.extreme mode but get the following error

TypeError: pino.extreme is not a function
    at Object.<anonymous> (F:\xxxxx\extreme.js:2:19)

version : pino 4.17.6

os : windows 7

node : node 10.13

code : 

const pino = require('pino')
const dest = pino.extreme() // no arguments

**Comment by mcollina** [comment]
You'll need pino v5 to use `pino.extreme()`.
