### ISSUE TITLE
pino printing `pid` and `hostname` even after setting it to null

### ISSUE THREAD

**Issue by abuzarhamza** [pinojs/pino#549]
here my code
When priting the logs its also printing the `pid` and `hostname`. 
```

const pino = require('pino')({pid: null, hostname: null, name: 'FooBar' , level: 'debug', timestamp: false, useLevelLabels: true});
pino.debug('Hello')
```

pino version: 5.8.1

**Comment by davidmarkclements** [comment]
is there some documentation that lead you to use this approach? 
if so can you please let us know?

the correct way to achieve what you want is documented here: http://getpino.io/#/docs/api?id=base-object
