### ISSUE TITLE
Boost performance

### ISSUE THREAD

**Issue by KurtPattyn** [pinojs/pino#558]
Hi,

I was able to boost the performance of Pino by "quite a bit".  

Test | Before Optimization | After Optimization
---- | -------------------- | ------------------
Formatted string: ('hello "%s" %s "%d" %s' ,world,true,4,obj) | 432,179 ops/sec | 652,418 ops/sec
Plain text: ('"sadfs" "C:\\Users" fsdfa "ljl" jljljljl "jl" jljljllk"') | 337,495 ops/sec | 679,108 ops/sec
Small Object:({"obj":true}) | 1,286,019 ops/sec | 1,744,617 ops/sec
Deep Object: package.json | 58,178 ops/sec | 94,899 ops/sec 
Error Object: (new Error("Ooops")) | 31,818 ops/sec | 31,482 ops/sec
Normal log message: ({"id":3},'Everything is "fine".') | 473,725 ops/sec | 810,962 ops/sec

Tested on a MacBook Pro Mid 2015 with Nodejs 8.14.0.

I just added a flatstr call to the write method of `sonic-boom`:
```
SonicBoom.prototype.write = function (data) {
  if (this.destroyed) {
    throw new Error('SonicBoom destroyed')
  }

  flatstr(data);
  this._buf += data
  var len = this._buf.length
  if (!this._writing && len > this.minLength) {
    actualWrite(this)
  }
  return len < 16384
}
```
A similar gain (of course) can be reached by calling `flatstr` in proto.js:
`if (stream instanceof SonicBoom) stream.write(flatstr(s))`

Note:
1. I also detected an issue with `flatstr` in Node v10.x (calling `Number(str)` seems much faster than the V8 methods). Do you want me to add an issue over there?
2. I can add a PR to pino or to sonic-boom if you think that this is indeed an enhancement.

**Comment by jsumners** [comment]
🤔

**Comment by mcollina** [comment]
Can you please verify also with Node 10?
I’d say go ahead and open a PR against sonic-boom, we can discuss it there.

**Comment by KurtPattyn** [comment]
Hi @mcollina, these are tests on Node 10 (Dubnium) and Node 8 (Carbon):

 | Req/Sec     | Formatted String | Plain Text | Small Object | Deep Object | Error Object | Normal Message
 |--- | ----------------- | --------- | ------------- | ------------- | ------------ | -----------------
Node10 not optimized | 463563 | 329894 | 1308373 | 60748 | 28705 | 572058
Node10 flatstr | **738253** | **868596** | **1678430** | **87310** | **31190** | **990184**
Node10 Number | 730122 | 811340 | 1479740 | 80694 | 30477 | 859874
Node8 not optimized | 365098 | 264735 | 1069650 | 53629 | 26690 | 436352
Node8 flatstr | 605602 | 613289 | **1581419** | 82543 | 25005 | 711341
Node8 Number | **637174** | **650286** | 1517531 | **88127** | **29912** | **788879**

It is clear that introducing `flatstr` in the sonic-boom `write()` method has a significant effect on the requests per second for Node V10.
The same effect can be seen for Node V8, but there directly calling `Number` seems to have the biggest effect (which is strange because flatstr should exactly do the same).

However I am not convinced if this change should be introduced in sonic-boom or in pino.
I can imagine that calling `flatstr` for small strings could negatively impact sonic-boom for non-logging cases. In Pino we known that we always have 'appended' strings where a call to flatstr definitely has a significant impact. Okay, I will write a small test to see the effect of `flatstr` on literal non-concatenated strings and come back.

Note: I am using `benchmark` (https://github.com/bestiejs/benchmark.js/) for performance testing.

**Comment by KurtPattyn** [comment]
Okay will create an issue in sonic-boom. In the meanwhile I have been testing further and actually came to a consistent improvement **for the logging specific** case. I will close this issue.
