### ISSUE TITLE
feature request: permit key-value manipulation pre jsonification

### ISSUE THREAD

**Issue by cdaringe** [pinojs/pino#563]
# problem

i require certain keys/values to be added/changed, but pino gives me no support to format my log kv pairs

[similar issue](https://github.com/pinojs/pino/issues/346)

# discussion

a `pino({ preJson: obj => ({ ...obj, mySpecialKey: 'bananas'  })` would be an example of a helpful API.

i, for instance, need to add `tags: [ ... ]` and convert pino levels to syslog levels.  in #346 you suggested doing it downstream, but my downstream already expects this formatting to have been completed by each contributor

thanks for the consideration!

**Comment by grantcarthew** [comment]
@cdaringe Have a look at [perj](https://github.com/grantcarthew/node-perj). It may not be what you want though.

**Comment by mcollina** [comment]
@cdaringe thanks for asking! You can customize individual properties using [serializers](https://getpino.io/#/docs/api?id=serializers-object). If you prefer to process the whole object instead, you can add a [wildcard serializer](https://getpino.io/#/docs/api?id=serializerssymbolfor39pino39-function), like so https://github.com/pinojs/pino/blob/master/test/serializers.test.js#L184-L219.

Feel free to PR to update our docs, if you think finding this information was hard. It would be highly appreciated. It could go in https://github.com/pinojs/pino/blob/master/docs/help.md with some examples maybe.
