### ISSUE TITLE
Pino errors do not raise 'error' event

### ISSUE THREAD

**Issue by spazmodius** [pinojs/pino#565]
It seems that Pino does not raise it's `'error'` event.

```
const logger = pino(dest).on('error', (err) => {
  console.log('Never gets here', err)
})
```
How should one handle, say, a transport that goes away?  Is it expected that calls to Pino will be `try/catch`'d?  Even that would not catch errors that happen during an async write operation.

**Comment by mcollina** [comment]
Logging should be errorless. console.log does not error, and you should not expect that any logging call could error.

That being said, have you got a specific case to reproduce this? There is no error in pino: only the transport destination thaf you pass in could emit error, so you should listen to its error there.

**Comment by spazmodius** [comment]
Ah, of course.  Yes, I can hook the `'error'` event on the destination, assuming I opened it myself.  I suppose there's no way to hook it if I pass a path or fd directly to `pino()`?

**Comment by davidmarkclements** [comment]
@spazmodius - you can't pass an fd, and we recommend using `pino.destination`: 

```
const pino = require('pino')
const dest = pino.destination('/some/path')
dest.on('error', () => { ... })
const logger = pino(dest)
```

**Comment by davidmarkclements** [comment]
closing as there is a way to handle destination errors
