### ISSUE TITLE
Reason for merging into root

### ISSUE THREAD

**Issue by proSingularity** [pinojs/pino#568]
Hi,

In my project I think about moving the logged `mergingObject` into a property, e.g. `data` as described #355, This avoids most duplicate-key problems.

Why is the `mergingObject` merged into the root by default? Usually there is a good reason for the default settings of a library and I would like to know that before customizing.

Thanks a lot. Have a successful day.

**Comment by mcollina** [comment]
This was done mainly for backward compatibility with bunyan. Moreover, it makes `logger.info(obj, msg)` and `logger.child(obj).info(msg)` identical in behavior. We use that pattern quite a lot internally, and we recommend the use of child loggers. In addition, the serializers work only on first-level properties, making this extremely painful to change.

I think wrapping the passed in objects into well known property is a good pattern. In HTTP application, the well known `req` and `res` properties include the http request and response respectively. These are typically governed by serializers in an application.

**Comment by davidmarkclements** [comment]
I think @mcollina answers this question succinctly - closing 😃
