### ISSUE TITLE
Simple error log in file and file rotation

### ISSUE THREAD

**Issue by BofEmptiness** [pinojs/pino#575]
Is there a way to simple log only some crutial errors in file that will be rewrited every weak? On the same time log in console if in development.

I like how pino looks like and it's by default in fastify, but this simple action that i don't know how to do on windows force we to use winston instead, where i just do like that:

```
const logger = winston.createLogger({
  level: 'info',
  exitOnError: false,
  format: winston.format.combine(
    winston.format.timestamp()
  ),
  exitOnError: false,
  transports: [
    new winston.transports.DailyRotateFile({
      dirname: 'logs',
      filename: 'log.%DATE%',
      datePattern: 'YYYY-MM-DD-HH',
      maxSize: '20m',
      maxFiles: '14d'
    })
  ]
})
// Log in console if in development
if (!settings.env.isProd) {
  logger.add(
    new winston.transports.Console({
      format: winston.format.combine(
        winston.format.colorize({ all: true }),
        winston.format.printf(
          log =>
            `${log.level}: ${log.info}\n${JSON.stringify(log.req, null, 2)}\n${
              log.message
            }`
        )
      )
    })
  )
}
```

It's does not need to be fast, because i log only server errors.

**Comment by davidmarkclements** [comment]
So if I'm understanding correctly

1. In development you'd like to have formatted logs
2. In production you'd like to store errors to an error file

For formatted logging see http://getpino.io/#/docs/pretty

For storing error logs to a separate file see http://getpino.io/#/docs/help?id=multiple

**Comment by BofEmptiness** [comment]
If someone will need it, this is how i made logs rotation.
```
const dest = pino.destination('./logs/log')
const logger = pino({ level: 'info' }, dest)

setInterval(function() {
  let stats = fs.statSync('./logs/log')
  let fileSizeInBytes = stats['size']
  let fileSizeInMegabytes = fileSizeInBytes / 1000000

  if (fileSizeInMegabytes > 50) {
    fs.unlink('./logs/log', () => {
      dest.reopen()
    })
  }
}, 3600000)
```

**Comment by jsumners** [comment]
I _highly_ recommend you let your system utilities handle log rotation for you. http://getpino.io/#/docs/help?id=rotate

**Comment by BofEmptiness** [comment]
They only for linux/prodaction, and i'm on windows. Is there a problem with my approach? @jsumners

**Comment by BofEmptiness** [comment]
And little update if you will need log in console in dev and in file on prod:

```
settings.env.isProd = process.env.NODE_ENV == 'production'

const logOptions = settings.env.isProd
  ? {
      level: 'error'
    }
  : {
      level: 'info',
      prettifier: require('pino-pretty'),
      prettyPrint: {
        levelFirst: true,
        translateTime: true,
        messageKey: 'errStack'
      }
    }
const dest = settings.env.isProd
  ? pino.destination('./logs/log')
  : pino.destination(1)
const logger = pino(logOptions, dest)

settings.env.isProd && setInterval(function() {
  let stats = fs.statSync('./logs/log')
  let fileSizeInBytes = stats['size']
  let fileSizeInMegabytes = fileSizeInBytes / 1000000

  if (fileSizeInMegabytes > 50) {
    fs.unlink('./logs/log', () => {
      dest.reopen()
    })
  }
}, 3600000)
```

**Comment by jsumners** [comment]
I suspect Windows has ways to manage log files. The problem with your approach is it moves extraneous functionality into your application and reserves resources for log management that your application could be using. And that’s not considering all of the complexities that come along when dealing with files.

**Comment by mcollina** [comment]
I think there is something to explore in this idea. Dealing with files directly is tricky but doable, and a setInterval approach is not going to create measurable overhead if the the interval is high enough. Considering how much time it took to iron sonic-boom, this would require some time and testing.

(I’d still recommend to use something external).

**Comment by thw0rted** [comment]
I like Max's approach of using `destination` to create a separate direct-to-file logger and it's similar to what I'm doing.  (I needed separate loggers for CLI output and a persistent log file.)  I also went ahead and hooked `SIGHUP` to call `reopen()` because I figure then if somebody wants to run the program with logrotate, it'll work out of the box.  If I were to roll my own time-based "rotate" I'd probably approach it a bit differently but the above is a reasonable first pass.
