### ISSUE TITLE
 Chinese characters are not displayed properly

### ISSUE THREAD

**Issue by superwunc** [pinojs/pino#578]
```
const logger = require('pino')();
console.info("测试");
logger.info("测试");
```

console output

测试
{"level":30,"time":1547090723659,"msg":"娴嬭瘯","pid":18268,"hostname":"Lenovo","v":1}

os windows10
node v8.4.0

May be a problem with sonic-boom

```
const SonicBoom = require('sonic-boom')
const sonic = new SonicBoom(process.stdout.fd) 
console.log('测试')
sonic.write('测试')
```

console output

测试
娴嬭瘯

**Comment by mcollina** [comment]
This should do: http://getpino.io/#/docs/help?id=windows
