### ISSUE TITLE
"Converting circular structure to JSON" error.

### ISSUE THREAD

**Issue by ioanlucut** [pinojs/pino#600]
We are using `pino` in a project where we link locally to some internal `npm` modules (where our `pino` configuration lies, and we reuse it from there). 

While running the app, I got lots of crashes, see:
```
==== JS stack trace =========================================

Security context: 0x0e306ff1e6e1 <JSObject>
    0: builtin exit frame: stringify(this=0x0e306ff11a19 <Object map = 0xe30950042a9>,0x0e30169026f1 <undefined>,0x0e30169026f1 <undefined>,0x0e3098d1aa01 <DependenciesBlock map = 0xe30c7d9a829>,0x0e306ff11a19 <Object map = 0xe30950042a9>)

    1: stringify [0xe3061e0dc31] [../path../node_modules/fast-safe-stringify/index.js:11] [bytecode=0xe30541dbdd9 offset...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Those led me to the https://github.com/pinojs/pino/blob/master/lib/tools.js#L370 which is not guarded against the _circular structure_.

Could you, please, advise us regarding this issue?
Thank you.

**Comment by davidmarkclements** [comment]
Are you saying this happens when you run `npm link`?

**Comment by ioanlucut** [comment]
Hi @davidmarkclements. No, it doesn't happen _during_ linking.

It happens while I have linked `npm` modules. I am not sure if this is the only reason. Probably this is how the circular dependency issue occurs in my case.

**Comment by davidmarkclements** [comment]
So it doesn’t happen when just installed, only when linked? I’m not sure how that creates a circular reference..  fast safe stringify should be handling that circular reference though so there’s a bug there  

Are you able to create an isolated case?

**Comment by ioanlucut** [comment]
I can reproduce it locally but I am still not sure why it happens. I can say it happens only when I have linked modules. 

We use a similar structure like in the https://github.com/facebook/create-react-app, where the running scripts are located in a npm module, which we link during development.

I will close this issue.
