### ISSUE TITLE
Logging to console and database (performance/implementation)

### ISSUE THREAD

**Issue by bfelbo** [pinojs/pino#606]
We're currently using Bunyan with two streams to simultaneously log to console and our database. We use this data for analyzing customer interactions, training machine learning models etc. so it's important for us that we get it in the DB in addition to the console for immediate debugging.

We'd love to move to an actively maintained lightweight project like pino. I have two questions that we'd love to have answered before we make the switch:
1) Do you support logging to Postgres using `require("stream").Writable` and an implementation similar to https://github.com/fdesjardins/bunyan-postgres-stream/blob/master/index.js?
2) I read in https://github.com/pinojs/pino/issues/145 that there's substantial performance issues when having two streams, but it's an old issue. Is this still the case?

Here's our main logging file in case that's useful:

```
const bunyan = require("bunyan")
const logSerializers = require("./logSerializers")
const logPGStream = require("./logPGStream")

let DBStream = logPGStream({
  connection: {
    host: process.env.PGHOST,
    user: process.env.PGUSER,
    password: process.env.PGPASSWORD,
    database: process.env.PGDATABASE
  },
  tableName: "tango.logging_event"
})

let logger = bunyan.createLogger({
  name: "Tango API",
  streams: [{
    stream: process.stdout,
    level: "trace",
    serializers: {
      req: logSerializers.req,
      err: bunyan.stdSerializers.err
    }
  },
  {
    stream: DBStream,
    level: "trace",
    serializers: {
      req: logSerializers.req,
      err: bunyan.stdSerializers.err
    }
  }]
})

module.exports = logger
```

**Comment by mcollina** [comment]
> I read in #145 that there's substantial performance issues when having two streams, but it's an old issue. Is this still the case?

Yes. But there is also in bunyan. You are going to still benefit from pino, but to a less extent.

What is yours `logPGStream` file? You should use https://github.com/pinojs/pino-multi-stream to achieve the same behavior.

**Comment by davidmarkclements** [comment]
If performance is worth the investment to you, you might want to explore piping the logs (in their JSON format) to some intermediate processor that then logs to a console and to a db. Much in the same vein as what @mcollina just said, performance would benefit from doing this whether or not you use pino.

**Comment by bfelbo** [comment]
Thanks for the helpful comments!

We're using an implementation of `logPGStream` similar to https://github.com/fdesjardins/bunyan-postgres-stream/blob/master/index.js to transfer the logs to the DB. I'm assuming we'd have to use a combination of this file and https://github.com/pinojs/pino-multi-stream?

Interesting. It might be hard for us to do that as the console logs are handled by https://up.docs.apex.sh and AWS CloudWatch. We can explore that more, but it sounds good just to switch to pino and reap some performance gains for now.

**Comment by davidmarkclements** [comment]
yep pino-multi-stream should work with any writable stream

you might also want to explore https://github.com/pinojs/pino-tee as a way to redirect logs whilst also logging to stdout (you could redirect to a fifi/bash pipe that sends the logs to the db) - but again this would require operational flexibility

**Comment by bfelbo** [comment]
Thanks, we'll look into it!
