### ISSUE TITLE
An issue with a level number

### ISSUE THREAD

**Issue by turakvlad** [pinojs/pino#608]
Hello! 

I am using Pino a lot in my Serverless applications on AWS. I am using `nodejs8.10` runtime.

In my code I have:

```javascript
logger.warn({
  msg: 'Cannot match an Upsales contact.'
});
```

In AWS CloudWatch Logs in most cases I am getting a log message with a `level` set to `40` which is fine. But in very rare cases, I am getting a random number. I am using AWS CloudWatch Alerts to monitor Pino logs. If there is at least one log entity with a `level` greater than `40`, I am getting notification in Slack. Because of this weird bug, I am getting falsy notifications sometimes.

My log entity in AWS CloudWatch Logs looks this way:

```javascript
{
    "level": 402590798071,
    "executionContextId": "a8eca1c0-467c-11e9-89d8-9fcae7118a12",
    "invocationRequestId": "a0edbadf-a1c7-4a31-8e4c-611f243cfd66",
    "accountId": 11277,
    "msg": "Cannot match an Upsales contact.",
    "v": 1
}
```

Do you have any ideas what could be wrong and how I can fix it?

Thanks!

**Comment by mcollina** [comment]
Which version of pino are you using? Are your dependencies up to date? Are you using pino with a specific configuration?

**Comment by turakvlad** [comment]
@mcollina, hey. Thank you for such a prompt reply!

I am using Pino `^5.10.1`. Yes, all the dependencies are up to date. 

This is my `create-logger.js` file:

```javascript
'use strict';

// Crete a main logger's instance to track the Lambda's execution context.
// This will be executed only once during Lambda container's initialization.
const logger = require('pino')({
  base: {
    executionContextId: require('uuid/v1')()
  }
});

module.exports = (bindings = {}) => logger.child(bindings);
```

My Lambda handler:

```javascript
const createLogger = require('./utils/create-logger');

module.exports.handler = async ({ body }, context) => {
  // Create a temporary logger's instance based on a main one to track the Lambda's invocation context.
  // This will be executed N amount of times. It depends on a Lambda itself (whether it wants to reuse the same context or not).
  const tempLogger = createLogger({
      invocationRequestId: context.awsRequestId
  });

  // ... do some validations, make sure that `body.account` exists, etc.

  // Create one more logger based on a temporay one to track account ID.
  const logger = tempLogger.child({
      accountId: body.account.id
  });

  // In this logger we have executionContextId, invocationRequestId and accountId.
  // And sometimes this logger creates a random level's number.
  logger.warn({
    msg: 'Cannot match an Upsales contact.'
  });
}
```

Thanks for your help!

**Comment by mcollina** [comment]
Do normal lines include the time? Have you got any other form of line truncation/problem happening?

**Comment by turakvlad** [comment]
What do you mean by _normal lines_?

No, I haven't any other forms of line truncation.

I am sorry for such a long reply. I will prepare more information for you tomorrow. I will find all these occurrences in CloudWatch Logs and, maybe, we'll notice some patterns.

**Comment by mcollina** [comment]
As for normal lines, I intend lines that have a correct level:

```json
{
    "level": 40,
    "executionContextId": "a8eca1c0-467c-11e9-89d8-9fcae7118a12",
    "invocationRequestId": "a0edbadf-a1c7-4a31-8e4c-611f243cfd66",
    "accountId": 11277,
    "msg": "Cannot match an Upsales contact.",
    "v": 1
}
```

I don't know how this could happen. It would be good to have a way to reproduce the problem.

**Comment by turakvlad** [comment]
Hey, @mcollina!

I am monitoring CloudWatch Logs these weeks and I can still see this issue. Unfortunately, I cannot reproduce it.

<img width="1363" alt="Screenshot 2019-04-15 at 23 07 58" src="https://user-images.githubusercontent.com/7996184/56165458-5593d280-5fd3-11e9-9e28-206abde5c704.png">

I've noticed that it's the same log message each time. Our integration has a lot of "spots" where we're using Pino, but only for one of all we have this issue. So, answering your question above: yes, we have other log messages and they have the right level. Only one of them sometimes shows a wrong one.

In this place, we have some synchronous logic that runs quite fast and generates hundreds of logs per second. Maybe, this could be an issue?

**Comment by mcollina** [comment]
Can you try creating new pino instances instead of using child loggers? That’s not going to be a good solution, but I would like to test this. Another approach can be to not override base.

**Comment by davidmarkclements** [comment]
could something like this be happening?
```js
logger.info({level: 'oops'}, 'msg')
```

this would output something like: 

```json
{"level":30,"time":1558971239061,"pid":61713,"hostname":"x","level":"oops","msg":"msg","v":1}
```

this would be parsed and reserialized (via cloudwatch etc.) to:

```json
{"level":"oops","time":1558971239061,"pid":61713,"hostname":"x","msg":"msg","v":1}
```
