### ISSUE TITLE
Undefined variables are not logged

### ISSUE THREAD

**Issue by jcald1** [pinojs/pino#618]
If you execute:

`log.info({ msg: 'test', msgUndefined: undefined })`

pino logs:

`{"level":30,"time":1553633517657,"pid":1,"hostname":"a8455c8d7d8b","msg":"test","v":1}`

the properties with values of `undefined` are not logged.  These should be logged, or at the very least the option to log them should be configurable.

pino version: 5.11.3

**Comment by mcollina** [comment]
JSON does not include undefined values. pino is a json logger, and as such we cannot include them.

**Comment by jcald1** [comment]
@mcollina, would it make sense to optionally map them to null based on the pino configuration?

**Comment by jsumners** [comment]
`null` is a value in JavaScript whereas `undefined` is equivalent to the property not being present at all. So I wouldn’t think it makes sense to remap `undefined` to `null`.

**Comment by jcald1** [comment]
@jsumners , that is correct, but from a practical point of view, it is often useful in logging to know that a variable is undefined.  I wonder if it would make sense to have some reserved property name that can be used to convey information that normally gets dropped in a conversion to JSON.  Or to allow the user to have more control using more configuration options.
