### ISSUE TITLE
Remove `v` (was: Hide version when base is set to null)

### ISSUE THREAD

**Issue by thomasthiebaud** [pinojs/pino#620]
Pino is logging a version property called `v`. How is this property used? Is it necessary to have?

Shouldn't it be removed if `base` is `null`?

**Comment by mcollina** [comment]
It's the version format of the log line. It's an inheritance from Bunyan.

@jsumners @davidmarkclements what do you think?

**Comment by jsumners** [comment]
I think the only thing it is used for is to detect if a log line is a Pino log line in `pino-pretty`. I plan, at some point, to make `pino-pretty` a general purpose ndjson prettifier. So I don't see any reason to keep the `v` property when `base: null`. In fact, in a wrapper I have at work I have done `logger[pino.symbols.endSym] = `,"logger":"${name}"}\n` to remove the `v`.

**Comment by davidmarkclements** [comment]
if there's a time to do it, it's now. Dropping support for Node 6 will be a major, so it's a good window for breaking changes.

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/55233330-a7c8ab80-51fe-11e9-99c0-f815b2218583.png)

**Comment by mcollina** [comment]
Then.. should we remove it from everywhere?

**Comment by jsumners** [comment]
I'm having a hard time coming up with a good argument to keep it.

**Comment by mcollina** [comment]
Let's drop it!

@thomasthiebaud would you like to send a PR?

**Comment by davidmarkclements** [comment]
we can always re-introduce the `v` if the log format changes (of course.. technically the log format is changing because we're removing the `v` ... 😆 )

**Comment by jsumners** [comment]
Do we have a `next` branch for @thomasthiebaud to target?

**Comment by mcollina** [comment]
no but we change it easily later on.

**Comment by thomasthiebaud** [comment]
Sure, I can do a PR

**Comment by thomasthiebaud** [comment]
I have few comments on the PR, right now a test is still failing
