### ISSUE TITLE
Only one property from parent logger is logged in children

### ISSUE THREAD

**Issue by jcald1** [pinojs/pino#624]
# Summary
I set up two properties in the first child logger.  Then in the second child logger I set up two more properties.  Only see the parent's (first child's) first property binding.  In this code example I re-used a property name in the two loggers (the second child property overrides the first), but I'm getting the same results even when all of the property names are unique.

```
const logger = require('pino')()
logger.info('test')

const child = logger.child({a: 'prop', b: 'prop' })
child.info('test')

const child2 = logger.child({a: 'new prop', c: 'new prop' })
child2.info('test')
```

# Output
```
{"level":30,"time":1554155637672,"pid":8977,"hostname":"MLP-0U8HV2H","msg":"test","v":1}
{"level":30,"time":1554155637673,"pid":8977,"hostname":"MLP-0U8HV2H","a":"prop","b":"prop","msg":"test","v":1}
{"level":30,"time":1554155637673,"pid":8977,"hostname":"MLP-0U8HV2H","a":"new prop","c":"new prop","msg":"test","v":1}
```

**Comment by mcollina** [comment]
Ouch, this should not happen. Which version of pino are you using?

**Comment by jcald1** [comment]
@mcollina, looks like a bad test.  I spawned the second child off of the root logger not the first child.
