### ISSUE TITLE
Trouble printing a set?

### ISSUE THREAD

**Issue by jedahan** [pinojs/pino#627]
For some reason this only prints once?

```js
const Pino = require('pino')
const logger = new Pino()
const set = new Set(['a', 1])
logger.info(set)
console.info(set)
```

**Comment by mcollina** [comment]
You should not create pino with new.

(we should likely throw in that case)

**Comment by jedahan** [comment]
Still has the same issue 

```js
const logger = require('pino')()
const set = new Set(['a', 1])
logger.info(set)
```

**Comment by mcollina** [comment]
The current behavior is consistent with `JSON.stringify`:

```
> set = new Set([1, 2])
Set { 1, 2 }
> JSON.stringify(set)
'{}'
```

I don't think we should change this, as we log in JSON.

**Comment by jedahan** [comment]
Ahh, interesting Would it be that bad to use a custom replacer?

```js
> set = new Set([1, 2])
Set { 1, 2 }
> const set_to_array = (key, value) => {
...  if (typeof value === 'object' && value instanceof Set) return [...value]
...  return value
...}
undefined
> JSON.stringify(set, set_to_array)
'[1,2]'
```

**Comment by mcollina** [comment]
We recommend to do that manually. You can also specify a serializer if it’s a field in a complex object.

**Comment by stfp** [comment]
I ran into this yesterday and would like to suggest reconsidering as I don't think the JSON.stringify behavior makes sense in a logging system.

Here's my use case: some piece of code is using a Set to avoid duplicates, and this is sort of transparent downstream, except when I try to log it, with eg.:

```
logger.warn({ userid, userScopes, requiredScopes }, 'Permission denied');
```

Here the scopes are sets, so with the current behavior we get a very misleading log line showing both as empty like:
`{ userid: 1234, userScopes: {}, requiredScopes: {}, msg: 'Permission denied'}`

If the outcome was something like `userScopes: [Object]` or whatever, at least someone reading the logs would know we're not logging the right stuff, but showing an empty map is going to lead to lots of wasted time.

Of course people can do `[...userScopes]`, but again, considering how much confusion forgetting about it can lead to, I don't think this is a great solution.

**Comment by zamarawka** [comment]
@stfp I facing with this too.
It looks like `Map` objects affected too. I tested them and it's empty.
Are you found any solution for this (except [...someSetObject])?

**Comment by jsumners** [comment]
Any object that does not support `.toJSON` will "be affected".
