### ISSUE TITLE
Move away from Travis

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#629]
As expected after the acquisition, Travis is becoming slow and unreliable. Do we want to migrate? I've got some experiences with these two:

* https://circleci.com/
* https://azure.microsoft.com/it-it/services/devops/pipelines/

**Comment by jsumners** [comment]
I would accept CircleCI.

**Comment by davidmarkclements** [comment]
+1 for circle

**Comment by divmgl** [comment]
What's wrong with Travis? I've seen no slowness.

**Comment by zekth** [comment]
Why not using Github actions? I can help with that.

**Comment by mcollina** [comment]
Yes! Would you mind in sending a PR?
Il 17 nov 2019, 08:45 +0100, Vincent LE GOFF <notifications@github.com>, ha scritto:

**Comment by zekth** [comment]
> Yes! Would you mind in sending a PR? Il 17 nov 2019, 08:45 +0100, Vincent LE GOFF <notifications@github.com>, ha scritto:
> […](#)
> Why not using Github actions? I can help with that. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'll work on this. Will push it in next few days
