### ISSUE TITLE
Recursive Top-Level wildcard redaction

### ISSUE THREAD

**Issue by peterpod-c1** [pinojs/pino#631]
It would be useful if you could have a recursive top-level redaction key in the case where application log schemas are highly diverse and you can not always assume a specific parent key for the wildcard path.

Ex:
```
const request = { 
   "body": {
           "taxId": "123-45-6789"
   }
}
const log = require('pino')({redact: ['*.taxId']});
```

**Comment by peterpod-c1** [comment]
Or I suppose make every field by default perform a recursive search.

**Comment by mcollina** [comment]
That’s very costly to do. However if you would like to take a look and send a PR that does not compromise our current benchmarks it would be very welcome.

**Comment by davidmarkclements** [comment]
closing for now but we're absolutely still open to top level wildcard redaction with zero overhead PR's
