### ISSUE TITLE
IE 11 error: unsupported syntax

### ISSUE THREAD

**Issue by clementgalidie** [pinojs/pino#634]
Hello! :smiley: 

I've encountered an error on `IE 11`: `Expected ':'`.
I encountered it with the latest version of pino: `^5.12.0`.
It is related to this code (`pino/lib/symbol.js`):
```
module.exports = {
  setLevelSym,
  getLevelSym,
  levelValSym,
  ...
}
```
If I'm right, it's due to the fact that `IE 11` doesn't support that kind of syntax. It should be something like this:
```
module.exports = {
  setLevelSym: setLevelSym,
  getLevelSym: getLevelSym,
  levelValSym: levelValSym,
  ...
}
```

1. Are you aware of this problem?
2. Any upcoming solution?
3. Maybe I should use a `polyfill` as a workaround?

Thanks by advance.

**Comment by davidmarkclements** [comment]
I think in this case the thing to do would be to set up Babel to compile for your target

That is probably just the first syntax issue, once resolved there will likely be others (even the same kind elsewhere). 

Out of interest, what’s the market share of ie11 or even better what’s the market share of ie11 within your sector?

**Comment by mcollina** [comment]
How are you doing the bundling? We have a browser-specific version that should get picked up.

**Comment by clementgalidie** [comment]
Thanks to both of you for the answer!

We're using `Babel` for the building process.
I think I should add this rules: https://babeljs.io/docs/en/babel-plugin-transform-shorthand-properties to our following configuration:

```
{
    test: /\.(js|es6)$/,
    exclude: /node_modules/,
    loader: 'babel-loader',
    query: {
        plugins: [ 'transform-object-assign', 'transform-es2015-for-of' ],
    }
},
```

> Out of interest, what’s the market share of ie11 or even better what’s the market share of ie11 within your sector?

I asked some of my team members. I'll let you know when I'll get an answer.
But, I'm almost sure our market share of `IE 11` is quite low.

**Comment by mcollina** [comment]
This is the file you should be loading for browser usage: https://github.com/pinojs/pino/blob/master/browser.js.

This is configured in https://github.com/pinojs/pino/blob/master/package.json#L6.

**Comment by clementgalidie** [comment]
Thanks!
I gonna try out several things.
I'll keep you up to date.

**Comment by clementgalidie** [comment]
Hello!

Sorry for the late answer but I wanted you to know that the issue is fixed.
I did something wrong regarding our `package.json` files.
There is no issue on your side though!

Again, thanks for your time and help.
