### ISSUE TITLE
Change redaction at after logger instantiation 

### ISSUE THREAD

**Issue by AlexZeitler** [pinojs/pino#639]
Is it possibly to change the `redact` settings after logger instantiation (data to be redacted may change while service is running)?

Would it be possible to provide an async function instead? 
Performance overhead would then depend on the fn implementation (e.g. does it use caching etc.?) and not affect `pino` performance in general.

**Comment by mcollina** [comment]
Unfortunately it will as that’s a tight hotpath. Deferring even just for a microtick is going to cause a measureable slowdown.
Essentially, we should be writing things out as fast as possible, and depending on an external system for this processing can cause an excessive accumulation of data in memory. As a result, allowing async reduction is going to negate all benefit of using pino in the first place.

**Comment by AlexZeitler** [comment]
You're right. Would it be possible to modify the `redact` property itself after logger instantiation?

**Comment by mcollina** [comment]
That could be added. However it will be changed only on the current logger and its future children. The parent maintains no ties with its children.

**Comment by AlexZeitler** [comment]
Thanks, I'll play around with this topic for better understanding. 
Is modification of redaction something you would accept a PR for?

**Comment by mcollina** [comment]
I think so, yes.

@davidmarkclements @jsumners wdyt?

**Comment by jsumners** [comment]
I would be fine with it.

**Comment by davidmarkclements** [comment]
I think... that we could support async redaction as a transport if we go with worker thread transports in v6

**Comment by erikwlarsen** [comment]
Hey there, similar question about the `base` option object that is passed in during logger instantiation. Would you be open to a PR that allows that base log fields to be updated dynamically for a logger instance and/or a child logger instance?

**Comment by Fdawgs** [comment]
Closed by #1059 ?
