### ISSUE TITLE
Add custom property to each log entry

### ISSUE THREAD

**Issue by AlexZeitler** [pinojs/pino#640]
What is the best way (in a pluggable manner) to add a custom property to each log entry without specifying it in the params?

`pino.info({hello: 'world'});`

by default results in:

```
{"level":30,"time":1554750752789,"pid":16517,"hostname":"mbp.local","hello":"world","v":1}
```

The desired result should be:

```
{"property":"somevalue",level":30,"time":1554750752789,"pid":16517,"hostname":"mbp.local","hello":"world","v":1}
```

**Comment by mcollina** [comment]
just pass it to the factory, or maybe there is an option.

**Comment by jsumners** [comment]
Are you looking for child loggers? http://getpino.io/#/docs/child-loggers

**Comment by AlexZeitler** [comment]
@mcollina What is the factory?

**Comment by mcollina** [comment]
You should use https://getpino.io/#/docs/api?id=base-object, or child loggers.

**Comment by AlexZeitler** [comment]
Thanks

**Comment by AlexZeitler** [comment]
I need to re-open this issue, because I tried this:

```
const pino = function () {
  return require('pino')({
    base: {
      property: new Date()
    }
  })
};
```

`property` never updates - is there a way to make get it updated on every log entry?

**Comment by jsumners** [comment]
Define it as a property instead of a field.

**Comment by AlexZeitler** [comment]
@jsumners Did you mean that way?

```
const pino = function () {
  return require('pino')({
    base: {
      get property() {
        return new Date();
      }
    }
  })
};
```

**Comment by jsumners** [comment]
Yes. But it should be enumerable.

**Comment by mcollina** [comment]
That approach will not work for anything mutable. `base` is evaluated once at startup, as this seemed the ask.

Given your question in https://github.com/fastify/fastify/issues/1578, the actual solution is:

```js
cont pino = require('pino')()
const logger = pino.child({ transactionId })
logger.info('hello world')
```

**Comment by simo-eskalera** [comment]
@mcollina 
Also in the context of Fastify, I would like to add a `type` property with values `TxnStart` and `TxnEnd` to correspond to the request and response log output.

I tried customizing the serializers.req/res but that puts the prop inside the req,res objects, not at the root level.

**Comment by jsumners** [comment]
Supply your own Pino instance to Fastify.

**Comment by simo-eskalera** [comment]
@jsumners Sure, what I still need to understand is how to insert the conditional prop. Passing a customer logger is step 2, after I figure out how to insert the conditional prop.

Btw, type will be one of 3 values TxnStart, TxnLog, TxnEnd, TxnError, to help identify the log type.

**Comment by simo-eskalera** [comment]
PS, I logged an issue with Fastify to see if they can make customize the child logger to accept additional props:
https://github.com/fastify/fastify/issues/1893
