### ISSUE TITLE
Inconsistent Error logging

### ISSUE THREAD

**Issue by jcald1** [pinojs/pino#642]
I've observed a few inconsistencies in logging of Error objects.  

code
```
const pino = require('pino')({level: 'debug'})
const verror = require('verror')

let err1 = new Error('err1')
console.error(err1)
pino.error(err1)
pino.error({ err1 })
```

output:
```
Error: err1
    at Object.<anonymous> (/Users/jcalderon/temp/temp2/index.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
{"level":50,"time":1554858902091,"pid":13788,"hostname":"MLP-0U8HV2H","msg":"err1","stack":"Error: err1\n    at Object.<anonymous> (/Users/jcalderon/temp/temp2/index.js:5:12)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","type":"Error","v":1}
{"level":50,"time":1554859690038,"pid":13967,"hostname":"MLP-0U8HV2H","err1":{},"v":1}
```
* The first output is the console output for comparison.
* In the second output, pino is logging the `Error.message` as as `msg`, which is fine to stay consistent with other messages in pino, but I wonder if it's best to log to both msg and message. There's an example further down where logging both are logged at the same time, but it doesn't happen in this case here.
* In the third log statement, I nested the Error myself in an object to avoid using the external library.  The results are the same (empty object for the Error).

code:
```
let err2 = new verror.VError(err1, 'err2')
console.error(err2)
pino.error(err2)
```

output:
```
{ VError: err2: err1
    at Object.<anonymous> (/Users/jcalderon/temp/temp2/index.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  jse_shortmsg: 'err2',
  jse_cause:
   Error: err1
       at Object.<anonymous> (/Users/jcalderon/temp/temp2/index.js:5:12)
       at Module._compile (internal/modules/cjs/loader.js:701:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
       at Module.load (internal/modules/cjs/loader.js:600:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
       at Function.Module._load (internal/modules/cjs/loader.js:531:3)
       at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
       at startup (internal/bootstrap/node.js:283:19)
       at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3),
  jse_info: {},
  message: 'err2: err1' }
{"level":50,"time":1554859690038,"pid":13967,"hostname":"MLP-0U8HV2H","jse_shortmsg":"err2","jse_cause":{},"jse_info":{},"message":"err2: err1","msg":"err2: err1","stack":"VError: err2: err1\n    at Object.<anonymous> (/Users/jcalderon/temp/temp2/index.js:9:12)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","type":"Error","v":1}
```
* console output again in the first line for reference.
*verror library is used, which wraps the original Error in the jse_cause property.  When logging using VError instead of Error, pino this time does print out both msg and message (same value) at the root level.  However, the jse_cause is still just populated with only an empty string, even though it contains an actual Error object.  I was able to print err2.jse_cause.message even though jse_cause is blank in the log.

code:
```
err1.stdout = '123'
err1.stdin = '456'
err2.stdout = '123'
err2.stdin = '456'
pino.error( { response: err1 })
pino.error( { response: err2 })
```

output:
```
{"level":50,"time":1554860583748,"pid":14209,"hostname":"MLP-0U8HV2H","response":{"stdout":"123","stdin":"456"},"v":1}
{"level":50,"time":1554860583748,"pid":14209,"hostname":"MLP-0U8HV2H","response":{"jse_shortmsg":"err2","jse_cause":{"stdout":"123","stdin":"456"},"jse_info":{},"message":"err2: err1","stdout":"123","stdin":"456"},"v":1}
```
* Modifying the original error to add properties results in the Error and VError objects results in having those additional properties logged. But it looks like the standard "message" and "stack" properties are ignored for both Error and VError.

pino v5.12.2
node v10.15.3

**Comment by mcollina** [comment]
If you use “err1” as a property, there is no serializer, and it hits the default object serializer that only includes enumerable properties. If you pass Error directly, we check that it is an Error with instanceof.

If you use “err” as a property, you should hit the error serializer, and everything should be rendered correctly. We might to add support for VError there as well.

You can install the same serializer to “err1” if you prefer.

**Comment by jcald1** [comment]
@mcollina , for serializing Error objects, I would just do pino.stdSerializers.err(err1)?

Have you experimented with https://www.npmjs.com/package/serialize-error?  It seems to work with VError also.

**Comment by mcollina** [comment]
I didn’t know about that module. You can use it instead the normal error serializer, we should add a test and mention it in the docs.

Would you like to send a PR?

**Comment by jcald1** [comment]
@mcollina , for the PR, I haven't looked through the pino code itself, I've just been a user, but I could take a look to see how the current serializer is used.

**Comment by mcollina** [comment]
That would be nice!

**Comment by jcald1** [comment]
@mcollina , I swapped it out and some tests are failing due to the tests expecting the "type" property in the serialized Error to be populated with 'Error'.  I added that property, but then the nested Error doesn't have it.  I wonder if we really even need 'type' or this should be a breaking change to use serialize-error as is by default.  If so, should we keep the old one as an optional one to use?

**Comment by mcollina** [comment]
> @mcollina , I swapped it out and some tests are failing due to the tests expecting the "type" property in the serialized Error to be populated with 'Error'. I added that property, but then the nested Error doesn't have it. I wonder if we really even need 'type' or this should be a breaking change to use serialize-error as is by default. If so, should we keep the old one as an optional one to use?

That's a good idea. I would be happy to have a single test mentioning it and a mention in the doc.

**Comment by jcald1** [comment]
@mcollina , when I swapped out the serializer, I noticed that the serialize-error library maintains the "name" property in the underlying Error object (in my case it's value is 'Error'), whereas the current pino serializer does not.  The current pino serializer adds a 'type' property with a value of 'Error', which is not part of the original Error.  So it seems to me that it's probably best to go with the serialize-error and not add a type.  Other than that they seem to work the same.  I tested with VError.

When you log the Error directly without { err: error }, then it doesn't use the Error serializer and I see that 'type' is being populated even after swapping out the serializers.  I think adding 'type' anywhere just increases the change of colliding with objects being logged.  I ran into a situation where a custom Error object had a "time"property that collided with the standard pino time property.  I think the instructions should encourage people to nest their objects (not just for Error) and to nest Errors under the "err" property so that the Error serializer is used.   Should req and res also be logged as { req } and { res} ?

Should pino stop adding 'type' to any object?

**Comment by mcollina** [comment]
I think we should encourage people to log lines as { req } or { err }, etc. The reason why we log “type” instead of “name” is that “name” is often used to name an individual subsystem. An alternative approach could be to detect if it’s an error/req/res and automatically wrap them.

This behavior was inherited from Bunyan and it has served us well for so long. Changing it is definitely a semver-major change.

**Comment by jcald1** [comment]
@mcollina , our team is actually creating a helper function .err() that does exactly that, wraps it in  { err }.  Maybe we just need that, a few other helper functions for req and res, and better documentation.

As far as serialize-error goes, would you support switching it out in a semver-major change, or you really think it should stay the way it is with the type?  I figure that a serialized Error should match the Error object properties as much as possible.

**Comment by jsumners** [comment]
I am unclear what the current issue is and what the proposed solution is. I thought the docs were pretty clear that plain objects will only encounter a serializer on a per-property basis. If we need clearer documentation, please supply a PR.

But if any change is going to be made to how Pino logs errors, a subsequent PR should be made to https://github.com/pinojs/pino-pretty to support the change.

**Comment by jcald1** [comment]
@jsumners , @mcollina , the primary problem  I'm encountering at the moment is that the `originalError` below does not get logged, even though I'm logging using the 'err' property.  When I swapped out pino's serializer for a JSON-stringified serialize-error one, it does log it.

```
const err5 = new Error('Test Error');
err5.debug = {
  originalError: new Error('Original Error')
}
logger.error({ err: err5 })
```

**Comment by jsumners** [comment]
Because the standard error serializer only serializes known standard properties. It doesn't enumerate others.

**Comment by jcald1** [comment]
@jsumners  so do you think it would be worth swapping out the serializer implementation with the serialize-error package?  Or provide it as an optional serializer that can be set up in the pino configuration?

**Comment by jsumners** [comment]
I think what is shipped in Pino is a good generic serializer. What you are encountering is why we support supplying custom serializers. In this case, I recommend simply supplying your own serializer. You can extend our generic serializer with your own functionality using https://github.com/pinojs/pino-std-serializers#exportswraperrorserializercustomserializer . That way you retain the current feature set and simply expand upon it.

**Comment by davidmarkclements** [comment]
This logger was always built with performance in mind. I'm happy to update a serializer which enumerates properties as long as all benchmarks (and any added benchmarks that hit the specific code paths in question) are the same or faster (this is unlikely).

I personally don't see a need to remove `type` - this may cause disruption for users (even as a semver major) for no compelling reason that I can see

**Comment by mcollina** [comment]
The change I would like to see in v6 is the ability to use the user-specified serializer when passing in an Error object. If we do so, we are pretty sure that the name property of Error is going to collide with the name property of the logger itself. 

Given the discussion above, it seems there is no consensus in moving to another standard serializer. There are three choices that we can make:

1. leave things as they are
2. change pino so that it calls the serializer for error passed as first parameters - if there are property collision, it’s the problem of the developer after all.
3. make pino always wrap an error in an object with an “err”

I think in v6 we should do either 2 or 3 to fix this issue and enable the use of other error serializers.

**Comment by davidmarkclements** [comment]
I think if you do `logger.info(Error('msg'))` it should be converted to `{ err }` internally and then serialized. This is smallest, sanest fix and avoids all the issues with non-enumerables and key collisions.

**Comment by jsumners** [comment]
I think we should leave things as they are. Doing some sort of magic around detection of whether or not the first parameter is an `Error` instance will lead to unexpected results. I think the user should be explicit that they want the error to be serialized by providing an object that will match against a serializer.

Regardless, some work is done on this in branch `issue-642`. Others are welcome to try and make it workable, but I'm just going to cull the branch if it is the last outstanding issue by the time we decide to release v6.

**Comment by mcollina** [comment]
@jsumners this is the last outstanding issue before v6.

Do we want to move this forward?

**Comment by jsumners** [comment]
As I said, if this is the only blocker then my position is to kill it and leave things as-is. No one has attempted to pick up the work I started, so it doesn't seem that important.
