### ISSUE TITLE
Logging using slowTime (migrating from Bunyan + no need for performance)

### ISSUE THREAD

**Issue by bfelbo** [pinojs/pino#643]
I'm trying to migrate our logging from Bunyan. We're not particularly concerned with speed/performance, but want to use pino as it seems like a great actively-maintained improvement over Bunyan.

We're logging directly into a Postgres DB as we don't need to care about performance and need to query the logs in many different ways afterwards. I need to insert the timestamp into the DB rather than the Unix time and would rather incur the performance penalty of formatting it in my node instance than for the DB to convert it.

I know that `slowTime` was deprecated and removed because it was slow, but is there any way to use it for these use cases where performance doesn't matter?

Any guidance would be really appreciated.

**Comment by bfelbo** [comment]
I just found https://github.com/pinojs/pino/blob/master/docs/legacy.md and I guess I'll just use the function there. At some point, if our logging needs to scale, I'll remove the timestamp function.

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/master/docs/api.md#timestamp-boolean--function
