### ISSUE TITLE
Provide transpiled browser version

### ISSUE THREAD

**Issue by StarpTech** [pinojs/pino#647]
Hello,
I'm trying to use pino in a regular next.js project and it fails due to missing polyfills for IE11. Babel does not transpile node_modules by default and the integration is a bit hacky. I recommend to provide a build for the recent most used browsers http://gs.statcounter.com/.

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/issues/634https://github.com/pinojs/pino/issues/311

**Comment by StarpTech** [comment]
Hi,
to be more precise I'm talking about to add support for IE11 and IE edge. I got errors regarding symbols and missing es6 functions like `includes`.

> #634 #311

What's the result of the issues you are referenced? I propose to provide a polyfilled  `dist` version which works in all recent browsers.

**Comment by StarpTech** [comment]
Same as [here](https://github.com/isaachinman/next-i18next/issues/107) isaachinman and resolved by transpiling with babel prior publishing.

**Comment by jsumners** [comment]
Frankly, I don't see any problem with Pino. It sounds like a problem in another package.

**Comment by StarpTech** [comment]
@jsumners which package? Pino browser version uses es6 features without polyfilling. What's your solution without to go into detail for every app setup?

**Comment by jsumners** [comment]
See the Pino issues I linked. We don't do any transpiling. It is up to the consumer to do that.

https://github.com/pinojs/pino/blob/248be4eaf990cec1f06b648df1d3f41f2e503329/docs/browser.md

**Comment by davidmarkclements** [comment]
I would accept a PR to pino browser to make it use es5

**Comment by StarpTech** [comment]
> See the Pino issues I linked. We don't do any transpiling. It is up to the consumer to do that.

Modules under `node_modules` aren't polyfilled by default and this is not daily practice. In my opinion we should just add to the readme how a user can polyfill it in order to support IE11 and IE Edge.

I could fix it by importing

```js
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/array';
```
in my app.

The alternative would be to rewrite it as @davidmarkclements mentioned or to polyfill the features by a babel-env preset.

**Comment by davidmarkclements** [comment]
yeah similar to @jsumners I'm not into transpiling this package - it's extra workflow overhead and against our philosophy.  

I would accept a PR to the docs on preparing pino-browser to work with older browsers
OR a altering pino browser (it wouldn't need to be a rewrite, just handling the cases)

Alterations for symbols would be something like adding this to the top of lib/symbols
```
const Symbol = (typeof Symbol !== 'undefined') ? global.Symbol : (label) => '_symbol_' _ label
```

Any object assign or array unsupported methods etc. just convert to  procedural

**Comment by davidmarkclements** [comment]
that would be the path to the least bloat as well.

**Comment by joshuadiablito** [comment]
> I'm not into transpiling this package - it's extra workflow overhead and against our philosophy.
What's your philosophy?

**Comment by davidmarkclements** [comment]
1. applications should transpile
2. avoid module transpilation overhead by writing code that works in all target browsers

**Comment by joshuadiablito** [comment]
Fair enough, I think it is helpful to provide your code in any way that it can be used by people, it is a little less opinionated, and then you can gather feedback about how people are using it to determine what you build in the future.
