### ISSUE TITLE
It's possible to use pino with fastify and next.js (in react component) and log the reqId?

### ISSUE THREAD

**Issue by hectordavila64** [pinojs/pino#654]
I am using fastify with next.js and I need to include tracing (requestId is the problem so far). What I am doing right now is creating a fastify onRequest hook and generating a requestId value and setting it in request object (could be as a request header as well). What I want is to get access to this request object for two reasons:

1. In logger object (pino in this case, I want to include the requestId in all custom server-side logs).
2. In all request that needs to be made to other services need to include the requestId in headers.
Maybe I am missing something trivial and I'm not doing it the best way.

**HERE SOME SNIPPETS**

**This how I am generating the reqId**
```js
const fastify = fastifyFactory({
  logger, // logger configuration (Pino instance with custom configuration)
  genReqId: () => {
    return Math.random()
      .toString(36)
      .slice(-6);
  }
});
```

**This is a plugin to gets the reqId generated and setting it to a query property within request object**

```js
const tracing = function tracing(fastify, opt, next) {
  fastify.addHook('onRequest', (req, res, nextRequest) => {
    const { id } = req;
    const logger = fastify.log.child({ reqId: id });
    req.query.reqId = id;
    fastify.log = logger; //overrides the current fastify logger to include the reqId in all custom logs
    nextRequest();
  });
  next();
};
tracing[Symbol.for('skip-override')] = true;
module.exports = tracing;
```

I have no problem when using fastify.log.info(...) because how logger is overridden in each request, it will include the reqId as a child log. The problem is that I want to create a generic logger to use at any part and fastify logger is not available in React components (for example to write logs at getInitialProps). Another important thing is that I need to include this reqId in all request I send to other services (ex: when fetching data), this is why I tried to store this value in request object but need to get it. I tried to use cls-hooked to store the child logger but didn't work when tried to use it in a react component

**Comment by Eomm** [comment]
More info on [SO](https://stackoverflow.com/questions/56232466/its-possible-to-get-next-js-request-object-globally/56238345#56238345)

**Comment by mcollina** [comment]
Can you upload a full project?

Have you got access to Node req/res object in Next?

**Comment by hectordavila64** [comment]
@mcollina I can't upload the full project for legal reasons (sorry). I have access to res object in next but only in getInitialProps (don't know if it's possible in other places), suppose that it's possible to get req object as well.

**Comment by jsumners** [comment]
@hectordavila64 he said "_**a**_ full project" not "_**your**_ full project". Something that boils the issue down into an easy to view test case.

**Comment by mcollina** [comment]
You should be able to access the right logger with `res.log` there.

**Comment by hectordavila64** [comment]
@mcollina yes but how do I get the reqId generated in log to pass it to all the request I need to make to get data?

**Comment by mcollina** [comment]
`res.log.info({ hello: world })` would print the id as well in fastify.

**Comment by hectordavila64** [comment]
Sorry for my english, I am not able to explain my problem. With `res.log.info({ hello: world })` am logging the message with the reqId, that's ok. The problem is that I need to make some requests to other services to get page information and I need to pass it via headers the reqId that was generated in logger, so the question is how to get this reqId from logger?

**Comment by davidmarkclements** [comment]
@hectordavila64 you're looking for `req.raw.id`.
