### ISSUE TITLE
browser.js is using ES6 fat arrow

### ISSUE THREAD

**Issue by dhalbrook** [pinojs/pino#656]
Unfortunately we have to still support IE11 in our application, and so we need the browser.js file to be ES5 compliant.  However, there's an ES6 fat arrow in the pfGlobalThisOrFallback method which causes failure on IE11. 

Ideally our Babel config with the env plugin (together with browserslist) would be able to compile this to our target needs, but it seems webpack doesn't run "browser" specified dependencies though the compile step, and there doesn't seem to be a way to specify this on a per-module level.

I'd appreciate any suggestions for getting around this issue.

**Comment by davidmarkclements** [comment]
send a PR that changes it to a function and I'll accept it, and release immediately

**Comment by dhalbrook** [comment]
Here you go.  Thanks for jumping on this so quickly. 

https://github.com/pinojs/pino/pull/658
