### ISSUE TITLE
Option to customize timestamp field name

### ISSUE THREAD

**Issue by kibertoad** [pinojs/pino#657]
There is already an option for customizing message field name, would be great to have same one for timestamp. Reason for this -> we'd like to be able to store it as `@timestamp` for convenience of consumption from Kibana, but currently pino is not aware that this is a timestamp, so during pretty print it displays `[undefined]` as time.

If there is an approval for this feature, I can implement it.

**Comment by mcollina** [comment]
I don't understand the issue. Is that an issue on https://github.com/pinojs/pino-pretty? It would be great to add an option there.

**Comment by kibertoad** [comment]
Ah, yes, it is, didn't realize it has separate repo. Probably it should be option on both, actually same way as is with `message`. Will open PRs today.

**Comment by kibertoad** [comment]
Closing in favour of https://github.com/pinojs/pino-pretty/issues/66, as nothing needs to be done on pino side, it supports all the necessary customization using `timestamp` parameter.
