### ISSUE TITLE
Pino can't build with webpack

### ISSUE THREAD

**Issue by doanthai** [pinojs/pino#661]
I use webpack to build production version, but a error occur and it make process build failed:

> ERROR in [at-loader] ./node_modules/@types/pino/index.d.ts:52:27 
>    TS2694: Namespace '"http"' has no exported member 'IncomingHttpHeaders'.

This is my webpack config:

```js
 module.exports = {

    mode: "development",
    entry: path.resolve(__dirname, "src/main/nodejs/Server.ts"),
    output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, "dist")
    },
    target: "node",
    devtool: "source-map",
    resolve: {
        extensions: [".ts", ".js", ".json"]
    },
    module: {
        rules: [
            {
                test: /\.ts?$/,
                exclude: /node_modules/,
                include: path.resolve(__dirname, "src/main"),
                use: { loader: "awesome-typescript-loader" }
            },
            { enforce: "pre", test: /\.js$/, loader: "source-map-loader" },
            { test: /\.pug?$/, use: ["pug-loader"], exclude: /node_modules/ }
        ]
    },
}
```

When run project in develop mode with cli "nodemon --exec ts-node src/main/nodejs/Server.ts" every thing run normal and that error only show when build production version with webpack.

How to fix this error?

Thanks so much.

**Comment by mcollina** [comment]
Your problem is with the typescript integration. Pino does not support typescript directly, and you are using community-provided types. Remove them, and things should work (with less typing).
