### ISSUE TITLE
Bump `flatstr`

### ISSUE THREAD

**Issue by chaffeqa** [pinojs/pino#662]
For more info, see https://github.com/mcollina/sonic-boom/issues/26

**Comment by davidmarkclements** [comment]
the dep is specified with a caret - there is no actual need to bump. If you're experiencing an issue you should be able to rm node_modules and reinstall. If you have a package-lock that also could be locking to a particular version. However, this isn't an issue with pino

**Comment by chaffeqa** [comment]
oh derp right... i just was stuck on the latest patch version... which would resolve with a new lockfile creation.  Thanks!
