### ISSUE TITLE
Capture pino output in-memory

### ISSUE THREAD

**Issue by vdms-mark** [pinojs/pino#663]
Hello!

So, Pino produced output in JSON format, like this:
`{"level":30,"time":1531171074631,"msg":"hello world","pid":657,"hostname":"Davids-MBP-3.fritz.box","v":1}`

Is there some way to capture that JSON object before it is written to a log file or to standard out?

Thanks!

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/blob/master/docs/api.md#destinationsymbolforpinometadata may help you out.

**Comment by vdms-mark** [comment]
I'll take a look, thanks

**Comment by vdms-mark** [comment]
Definitely got me in the right direction.  Somehow I did not understand that I could use a custom writable stream.  So, I handled it like this (Typescript, and minus any safety checking):
```
import { LogDescriptor } from "pino"
import stream = require("stream")
import { WritableOptions } from "stream"
import pinoms = require("pino-multi-stream")

class CustomWritableStream extends stream.Writable {
    constructor(options?: WritableOptions) {
        super(options)
    }

    public _write(chunk: any, _encoding: string, _callback: (error?: Error | null) => void) {
        const logDescriptor = JSON.parse(chunk.toString()) as LogDescriptor
        // Do stuff with the logDescriptor
    }
}

const streams = [
    { stream: new E2eLoggingResultsWriter() },
    { stream: process.stdout },
]
export const pinoLogger = pinoms({ streams })

```
