### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by shresthaal** [pinojs/pino#667]
```
//common/logger.js
const pino = require('pino')
const l = (name = 'default') => pino({
    name,
    level: 'info',
    enabled: process.env.ENABLE_LOGGER === 'yes' ? true : false,
    prettyPrint: { levelFirst: true }
  });

module.exports = l;

```
So wherever i need the logger I do
```
const logger = require('common/logger')('name');
```

I am getting this warning
(node:26482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:26482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
(node:26482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:26482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
(node:26482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:26482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by mcollina** [comment]
Can you upload a full snippet?

**Comment by davidmarkclements** [comment]
can you also please start your process with the `--trace-warnings` flag and post output

**Comment by davidmarkclements** [comment]
hey @shresthaal did you resolve this?

**Comment by koxu1996** [comment]
He just made more than 10 loggers. In such cases setting higher limit with `setMaxListeners()` is required
