### ISSUE TITLE
timestampKey option to customize  timestamp field name

### ISSUE THREAD

**Issue by ilya-mim** [pinojs/pino#669]
Is it possible to add option for customizing timestamp field name?
Reason is that now `destination.lastTime` value calculated wrong if custom `timestamp` function is supplied. It extracts a section of a string begin from 8th character. 

https://github.com/pinojs/pino/blob/master/lib/proto.js#L133

```
timestamp: () => `,"myTime":${Date.now()}`,

destination[Symbol.for('pino.metadata')] = true;
destination.lastTime // <- wrong value
```

**Comment by mcollina** [comment]
Fixed in https://github.com/pinojs/pino/pull/675.
