### ISSUE TITLE
Redaction doesn't work on Browser

### ISSUE THREAD

**Issue by riggerthegeek** [pinojs/pino#670]
# Versions:
Pino: 5.12.6
Node: various, including 10.15.3
Browser: various, including Firefox 67, Chrome 75

I'm running Pino for both my front end and back end apps and the redaction doesn't seem to work in browser mode.

# Backend

```js
const pino = require('pino');
const logger = pino({
  name: 'test',
  level: 'info',
  redact: [
    'password'
  ]
});

logger.info({ password: 'pass1', hello: 'world' }, 'Password test');
```

This outputs:

```json
{
  "level":30,
  "time":1561304419142,
  "pid":8064,
  "hostname":"hostname",
  "name":"test",
  "password":"[Redacted]",
  "hello":"world",
  "msg":"Password test",
  "v":1
}
```

However, the same code in a browser displays the `password` as `pass1` without redaction, even with the `browser` config options:

```js

const pino = require('pino');
const logger = pino({
  name: 'test',
  level: 'info',
  redact: [
    'password'
  ],
  browser: {
    asObject: true,
    serialize: true
  }
});
```

From looking through the code, it doesn't seem to be applied at all but the documentation for redaction implies that this should work the same for browser and server.

**Comment by davidmarkclements** [comment]
The docs are probably not worded correctly. I didn’t think there would be a
demand for redaction in the browser, since you’d probably want to send any
relevant info over the wire. However, it’s definitely doable if you have a
need for it, and if you send a PR I’ll review it ASAP.

**Comment by riggerthegeek** [comment]
Nah, I don't have any particular need for it. I was trying something out and noticed that the redaction doesn't work. All it probably needs is a one-liner in the docs (will raise PR with this in soon)

**Comment by amcdnl** [comment]
I would like to upvote need for redaction in browser. 

Use case: Application that is a react app that needs to log errors/etc and then dump for remote debugging logs.

**Comment by davidmarkclements** [comment]
@amcdnl a PR would be more than welcome
