### ISSUE TITLE
How do you correctly log an Error object?

### ISSUE THREAD

**Issue by Morgul** [pinojs/pino#673]
So, I'm moving from Bunyan to Pino. For the most part, everything is working, however, logging errors is not. This is how I log errors all over my code:

```javascript
const logger = require('pino')({ name: 'fooModule' });

function doStuff() {
    // ...A lot of code...
    try {
        throw new Error('Some error!');
    }
    catch(error) {
        logger.error('An error occurred:', error);
    }
}
```

That outputs this:

```json
{"level":50,"time":1561683500581,"pid":5965,"hostname":"dante.local","name":"example","module":"logging-example.js","msg":"An error occurred: {}","v":1}
```

I've seen #642, but it wasn't clear from the documentation listed there how I could write a serializer to handle errors correctly; I'm not passing in an object as a second parameter, I'm just passing the raw object. If I read the docs correctly, the serializers simply match the keys on objects.

Changing my entire codebase (it's actually 30+ projects) is probably a non-starter for me, so I need to find a way to solve this via configuration of some kind.

**Comment by davidmarkclements** [comment]
I think you can use the global serializer for this 

https://getpino.io/#/docs/api?id=serializerssymbolfor39pino39-function

Closing for now, feel free to reopen if that doesn’t work

**Comment by Morgul** [comment]
@davidmarkclements So, I tried that as you suggested, however, it looks like that serializer is called too late. This is what it gets called with:

```javascript
[ { msg: 'An error occurred: {}' } ]
```

Full code:

```javascript
const logger = require('pino')({
    name: 'fooModule',
    serializers: {
            [Symbol.for('pino.*')]: function(...args)
            {
                console.log('ARGS?', args);
                return args[0];
            }
        }
});

function doStuff() {
    // ...A lot of code...
    try {
        throw new Error('Some error!');
    }
    catch(error) {
        logger.error('An error occurred:', error);
    }
}

// Output:
// ARGS? [ { msg: 'An error occurred: {}' } ]
// {"level":50,"time":1561831987228,"pid":10431,"hostname":"dante.local","name":"example","module":"logging-example.js","msg":"An error occurred: {}","v":1}
```

**Comment by davidmarkclements** [comment]
hmm yeah.. I remember now. So the reason we don't support this in core is because checking the instance of every input (and the instance of nested values) is going to be generally expensive, which is why the `{err: Error('msg')}` pattern was supported instead, and then later we allowed for `log.error(Error('msg'))` (e.g. error has to be in first position)

I would just do a search and replace to switch the error into first place, but if that's too burdensome, here's a little wrapper function you can use:

```js
function wrap (logger) {
  const { error, child } = logger
  function errorRearranger (...args) {
    if (typeof args[0] === 'string' && args.length > 1) {
      for (let i = 1; i < args.length; i++) {
        const arg = args[i]
        if (arg instanceof Error) {
          const [ err ] = args.splice(i, 1)
          args.unshift(err)
        }
      }
    }
    return error.apply(this, args) 
  }
  function childModifier (...args) {
    const c = child.apply(this, args)
    c.error = errorRearranger
    c.child = childModifier
    return c
  }
  logger.error = errorRearranger
  logger.child = childModifier
  return logger
}
```

Use like so:

```
const logger = wrap(require('pino')({name: 'fooModule'}))
```


This will be the most efficient way to approach this, as it will only apply when incurring error cases (which will be slow anyway, due to the stack creation).
