### ISSUE TITLE
Q: Best way to change time key?

### ISSUE THREAD

**Issue by naseemkullah** [pinojs/pino#674]
Hi,
the key `time` conflicts with another key of the same name in Elasticsearch, where logs eventually end up. To avoid the conflict the key needs to be renamed to `epochTime` . I was wondering what is the most efficient way of doing so? At the moment I am doing it like this:

```
const pino = require('pino')({
  useLevelLabels: true,
  prettyPrint: isLocal ? {} : false,
  timestamp: () => `,"epochTime":"${Date.now() / 1000.0}"`,
});
```

Is there a better way?
I'm concerned by the warning msg from http://getpino.io/#/docs/api?id=opt-timestamp:
> Caution: attempting to format time in-process will significantly impact logging performance.

**Comment by davidmarkclements** [comment]
Nope you got it, while ugly that is the most efficient way.

**Comment by naseemkullah** [comment]
Thanks!

**Comment by gleissonmattos** [comment]
The pino has some functions that can be useful. You can use something like:

```javascript
const pino = require('pino')

pino({
  name: app,
  nestedKey: 'data',
  timestamp: pino.stdTimeFunctions.isoTime,
  redact: ['category', 'name', '*'],
})
```

you can see here:
https://getpino.io/#/docs/api?id=pinostdtimefunctions-object
