### ISSUE TITLE
Add support for filtering

### ISSUE THREAD

**Issue by zdila** [pinojs/pino#681]
We know that log filtering can be done by eg. `pino-pretty` but for our case we need to change it dynamically while the process is running.

For our needs we need to dynamically set min. level of the message to be logged for all the loggers (including childs). The usecase is that in production we log only `info` messages but if we sometimes need to debug an issue then we temporarily set it to `debug` (without restarting the process).

Our current workaround looks like this:
```javascript
let level = 30;

// called externally
function setLogLevel(lvl) {
  level = lvl;
}

const appLogger = proxyLogger(pino({ ... }));

function proxyLogger(logger) {
  return new Proxy(logger, {
    get(targetObj, propertyName) {
      const value = targetObj[propertyName];
      switch (propertyName) {
        case 'child':
          return new Proxy(value, {
            apply(targetFn, thisArg, argumentsList) {
              return proxyLogger(targetFn.apply(thisArg, argumentsList));
            },
          });
        case pino.symbols.writeSym:
          return new Proxy(value, {
            apply(targetFn, thisArg, [_obj, msg, num]) {
              if (num >= level) {
                targetFn.apply(thisArg, [_obj, msg, num]);
              }
            },
          });
        default:
          return value;
      }
    },
  });
}
```

**Comment by mcollina** [comment]
Can you explain a little bit more your setup? What I am doing when I have these requirements is to:

1. create a new child logger for each incoming request
2. change the log level if needed in the new child loggers

This is not going to require leveraging a `Proxy`. 

The trick is nice btw!

**Comment by zdila** [comment]
Our app has many modules. Every module takes `appLogger` (from my example) and extends it (using `child`). Every module logs to its logger messages with various levels. In production we want only to log `INFO` and higher, but in some case we send command to the app to switch logging to `DEBUG` so we can trace the problem. It would be too much code to track all the (child) loggers in the app to change their levels.

**Comment by mcollina** [comment]
I know it’s hard to keep track of those, and that’s why we are not doing this in pino itself. However if you know you have a limited number, that’s way more doable. Maybe you could craft a module to do that.

**Comment by zdila** [comment]
OK, we can try also that approach (or stick with proxy where we can add also more complex filtering if needed).

Feel free to close this issue if you think the solution is satisfactory :-). Thanks.
