### ISSUE TITLE
overriding/extending log methods

### ISSUE THREAD

**Issue by sirpy** [pinojs/pino#686]
On nodejs I'm trying to send error message also to Rollbar logger.
I tried to overwrite the logger error method like so
```
logger = new Pino()
const logError = logger.error
logger.error = function()
{
rollbar.error(arguments)
logError(arguments)
}
```
this works fine for the logger instance but doesn't work for child loggers
if I do
```
let child = logger.child({from:'child'})
child.error()
```
the child error method is no longer the overwritten one.

Is there a way to achieve this?

**Comment by mcollina** [comment]
This is not supported, as we dynamically change the methods when the level is changed - this enable us to avoid a (costly) if check, and it enable V8 to optimize the function call away.

**Comment by AckerApple** [comment]
I arrived at this issue needing to override pino and extend it's functionality.... I have since solved my issue and here is my working override code:

**TypeScript**
```
import pino from 'pino'
const myPino = pino()
const orgChildMethod = myPino.child
myPino.child = function(this: any, details: any) {
  const newPino = orgChildMethod.call(this, details)
  newPino.info = function(logMeta: any): void {
    logger.info({...logMeta, ...details}) // custom override
  }
  newPino.warn = function(logMeta: any): void {
    logger.warning({...logMeta, ...details}) // custom override
  }
  return newPino
}
```

**JavaScript**
```
const myPino = require('pino')()
const orgChildMethod = myPino.child
myPino.child = function(details) {
  const newPino = orgChildMethod.call(this, details)
  newPino.info = function(logMeta) {
    logger.info({...logMeta, ...details}) // custom override
  }
  newPino.warn = function(logMeta) {
    logger.warning({...logMeta, ...details}) // custom override
  }
  return newPino
}
```
