### ISSUE TITLE
consider using simpler array format

### ISSUE THREAD

**Issue by ORESoftware** [pinojs/pino#692]
Instead of:

```
{"level":30,"time":1531171074631,"msg":"hello world","pid":657,"hostname":"Davids-MBP-3.fritz.box","v":1}
```

you can just use:

```bash
["@pino:v1", "INFO", 1531171074631, 657, "Davids-MBP-3.fritz.box", "hello world"]
```

as long as you configure the order of the params, it's no different than knowing which property maps to what.

I did a test and it's 

1.  faster to JSON.stringify the simple array
2. it also takes up only about 2/3 of the original size...so you save some diskspace etc
3. The raw JSON for an array is also much easier to read (much less line-wrapping in a terminal, etc).

**Comment by jsumners** [comment]
Thank you for the suggestion but it would be far more difficult to implement ecosystem tooling with such a format. It would also be very difficult to guarantee the order of parameters. Additionally, it's easy for the human to understand the logs when they are reading the object style logs without having to know anything about how the logger builds them.
