### ISSUE TITLE
Add timestampKey option to customize timestamp field name

### ISSUE THREAD

**Issue by tlvince** [pinojs/pino#694]
A corollary to `messageKey` for time (e.g. `timestampKey`) would be useful. I'm aware that this can be achieved using the [timestamp option](http://getpino.io/#/docs/api?id=opt-timestamp), however, this requires passing in a function, whereas passing in a string (per `messageKey`) is a simpler API for those who are otherwise happy with the default time format (epoch).

Related to #669, #657.

**Comment by mcollina** [comment]
Would you like to send a PR?

Il giorno lun 12 ago 2019 alle 15:52 Tom Vincent <notifications@github.com>
ha scritto:
