### ISSUE TITLE
Pino error log is empty, although error object contains information

### ISSUE THREAD

**Issue by rstoermer** [pinojs/pino#702]
I have written a small error handling function, which is invoked after an AXIOS request, like so:

```
    try {
     ...
    } catch (error) {
        handleAxiosError(error);
    }
```

The function is as follows:

```
    function handleAxiosError(error) {
        if (error.response !== undefined) {
            logger.error(`Received a HTTP error. Status code: ${error.response.status}, Data: ${error.response.data}`);
        } else if (error.request !== undefined) {
            logger.error(error.request);
        } else {
            logger.error(error.message);
        }
        throw new Error(error);
    }
```

Although an error is thrown:

(node:94324) UnhandledPromiseRejectionWarning: Error: Error: connect ECONNREFUSED 127.0.0.1:6557
    at handleAxiosError (C:\pathtoapp\utils\utils.js:66:11)

Pino only saves the following to the log. I can't find the problem. Is this an async issue?

{"level":50,"time":1567435455281,"pid":94324,"hostname":"host","name":"app","res":{},"v":1}

Thanks!

**Comment by mcollina** [comment]
You have an async function or a promise that is rejecting and you are not catching the result.

Can you upload a full runnable snippet to reproduce?

**Comment by rstoermer** [comment]
Sadly I can't share the full code. 

The function which receives the error is invoked in the catch block and the error definitely results from a refused connection, as I shut down the service running under 6557..

function handleAxiosError(error) {
    logger.error(error.message);
    throw new Error(error);
}

seems to work however: 

{"level":50,"time":1567500624166,"pid":42220,"hostname":"host","name":"app","msg":"connect ECONNREFUSED 127.0.0.1:50000","v":1}

**Comment by mcollina** [comment]
I don't really understand your issue.

**Comment by davidmarkclements** [comment]
closing as this a separate rejection handling issue which is unrelated to pino
