### ISSUE TITLE
How can I create a logger that outputs BOTH in the `console` and dumps it into a file?

### ISSUE THREAD

**Issue by lffg** [pinojs/pino#704]
Hello guys,

I recently discovered this library, but I couldn't find any way to create a pino instance that outputs to the console (pretty) and into a file.

Is there a way to do that?

I tried this (and works), but it not pretty-prints into the console:

```ts
import { spawn } from 'child_process';
import path from 'path';
import { PassThrough } from 'stream';
import pino from 'pino';

const logPath = path.join.bind(undefined, __dirname, '..', 'temp', 'logs');

const logThrough = new PassThrough();

export const log = pino(
  {
    name: 'thod'
    // prettyPrint: {
    //   colorize: true,
    //   levelFirst: true,
    //   translateTime: true
    // }
  },
  logThrough
);

const child = spawn(
  process.execPath,
  [
    require.resolve('pino-tee'),
    'warn',
    logPath('warn.log'),
    'error',
    logPath('error.log'),
    'fatal',
    logPath('fatal.log')
  ],
  {
    cwd: process.cwd(),
    env: process.env
  }
);

logThrough.pipe(child.stdin);
```

When I uncomment those lines, the logger stops dumping into the files...

How can I solve that problem?

PS: I want to log into the console when `process.env.NODE_ENV === 'development'`.

Thanks in advance for any help or guiding. :)

**Comment by mcollina** [comment]
check out https://github.com/pinojs/pino-multi-stream

**Comment by lffg** [comment]
Thanks! o/
