### ISSUE TITLE
No way to distinguish between null and undefined

### ISSUE THREAD

**Issue by NikxDa** [pinojs/pino#706]
Using `pino.info(null)` vs `pino.info(undefined)` results in the same JSON output. This is really unfortunate for debugging logs that might print objects or similar data where a value can be undefined or null. Distinguishing between these values can save lots of time when debugging.

**My suggestion:**
I suggest adding a type property that holds a stringified version of the type present, e.g. `object`, `string`, `undefined` and (even though `typeof` would print `object`) `null`.

I can open a PR for this if needed.

Thanks!

**Comment by jsumners** [comment]
Duplicate — https://github.com/pinojs/pino/issues/618

**Comment by NikxDa** [comment]
@jsumners That one certainly didn't get a lot of attention, sadly. Didn't find it initially, thanks for pointing it out. I still think having an option to detect when undefined or null are being logged is really needed, especially when doing development.

Also, JSON _does_ have a `null` value, so adding that will in turn solve the `undefined` issue, too (because one can work back and check all the keys; if `msg` isn't present and there are no non-default keys, it must've been `undefined`. At the moment this behaviour is also present when logging `null`.)

**Comment by davidmarkclements** [comment]
I agree. I think we should log `"msg": null` when `null` is passed

**Comment by davidmarkclements** [comment]
@NikxDa would you like to create a PR?

**Comment by NikxDa** [comment]
@davidmarkclements Will open a PR within the next couple of days that should fix this. Tight schedule, but should be able to complete it sooner rather than later.
