### ISSUE TITLE
Destination reopen causes unhandled `EBADF` error

### ISSUE THREAD

**Issue by thw0rted** [pinojs/pino#710]
I'm trying to clear a log file during execution, which I figured was pretty close to the [reopening suggestion in the docs](https://github.com/pinojs/pino/blob/master/docs/help.md#reopening).  My first attempt was to use `unlinkSync` to delete the current log file then immediately call `reopen` on the destination.  Doing this causes the following error:

>Error: EBADF: bad file descriptor, write
    at Object.writeSync (fs.js:588:3)
    at actualWrite (sonic-boom\index.js:266:24)
    at sonic-boom\index.js:34:7
    at FSReqCallback.oncomplete (fs.js:153:23)

I've put together [a simple repro](https://github.com/thw0rted/issue-examples/tree/pino-reopen).  It's possible that I misunderstand how I'm supposed to be using this pattern, so please let me know if I should be handling this differently.

**Comment by mcollina** [comment]
The exception arises because the file is not open yet. I'll send a PR to add a more explanatory exception in that case.

**Comment by thw0rted** [comment]
In my real code I'm exporting a (singleton) logger instance from a module.  I'd like to avoid having all callers have to check if the underlying `destination` is stable before starting to log.  Is that going to be a problem?  Is there another way I can accomplish this -- basically, having a "truncate log file" function -- that doesn't wind up with race conditions like this?  I don't care if a log call made around the same time as the truncate call gets lost, if that makes a difference.

**Comment by mcollina** [comment]
A tentative PR to solve this is in https://github.com/mcollina/sonic-boom/pull/30. Would you mind in checking that out and see if it solves your problem?
