### ISSUE TITLE
During redaction, allow paths to be ignored, instead of just fields

### ISSUE THREAD

**Issue by mickeyyawn** [pinojs/pino#713]
There may already be a solution for this, apologies if there is one. I am trying to ignore logging on certain express routes (e.g. /healthz). In redaction it only looks like I can redact fields, but the path hit still gets logged. Is there a way to to do this currently?

**Comment by davidmarkclements** [comment]
logging conditional on route would more be a feature of pino-http (which express-pino-logger depends on), feel free to open an issue (and even better PR) there so that an option of ignored routes can be supplied

however in you want a quick solution instead of `app.use(expressPino)` do something like:

```js
const app = require('express')
const logger = require('pino')()
const pino = require('express-pino-logger')({logger})

app.use((req, res, next) => {
  const ignore = /healthz/.test(req.url)
  const { level } = logger
  if (ignore) logger.level = 'silent'
  pino(req, res, next)
  if (ignore) logger.level = level
})

```

closing as this is an issue for https://github.com/pinojs/pino-http

**Comment by tnguyen14** [comment]
@davidmarkclements what would be the recommended way to achieve this (ignore logs for certain paths) for fastify?

**Comment by davidmarkclements** [comment]
Pass an option object to the route with logLevel set to silent:

```js
fastify.get('/healthz', { logLevel: 'silent' }, async () => ({status:'ok'))
```

**Comment by tnguyen14** [comment]
Thanks for the quick response!

That did the trick. However, when I did that, I got the following warning:

```
(node:15176) [FSTDEP001] FastifyDeprecation: You are accessing the Node.js core request object via "request.req", Use "request.raw" instead.
```

Is that expected?

**Comment by jsumners** [comment]
Open an issue in the Fastify repo and provide a reproduction test case.

**Comment by muuhoffman** [comment]
I was still struggling with this and this worked well for me in the `pino-http` or `express-pino-logger` (which just uses `pino-http`) library:
```
const expressLogger = expressPino({
  autoLogging: {
    ignorePaths: ["/_next"],
    getPath: (req) => {
      if (/_next/.test(req.url)) {
        return "/_next"
      }
      return req.url
    }
  },
});
```
