### ISSUE TITLE
Logging a symbol throws a TypeError

### ISSUE THREAD

**Issue by Zirak** [pinojs/pino#715]
```js
pino().info('hello', Symbol('foo'))
```

```
TypeError: Cannot convert a Symbol value to a string
    at format (/path/to/pino/node_modules/quick-format-unescaped/index.js:98:18)
    at Pino.LOG [as info] (/path/to/pino/lib/tools.js:37:33)
```

Note that "forcibly" stringifying the symbol does the job:

```js
pino().info('hello %s', Symbol('foo')
// => {"level":30,"time":42,"pid":42,"hostname":"hostnamerio","msg":"hello Symbol(foo)","v":1}
```

This is due to lack of support for Symbols in `quick-format-unescaped`, which I filed a PR for in https://github.com/davidmarkclements/quick-format-unescaped/pull/25 only to promptly completely forget about it until encountering a symbol a few days ago. Thought it might be useful to also tack it on here.

Maybe a regression test would also be good once the PR is merged down (up?) stream?

**Comment by mcollina** [comment]
Adding a test here would be great, yes!

Il giorno lun 30 set 2019 alle ore 14:42 Zirak <notifications@github.com>
ha scritto:

**Comment by Zirak** [comment]
I have no problem branching and adding that test in, but it won't pass until the linked issue is applied and pino's dependencies are updated. Still interesting?

**Comment by Zirak** [comment]
In related news, while writing the test, something interesting cropped up:

```js
pino().info(Symbol('foo'));
// => {"level":30,"time":42,"pid":42,"hostname":"hostnamerio","v":1}
```

Digging a bit further (ignore this entire block if you wish, tl;dr at the end): the call to [`quick-format-unescaped` here](https://github.com/pinojs/pino/blob/c0dc89dba3cf491fc86ad40aadd0c650d75708e8/lib/tools.js#L37) returns the symbol itself (seeing as it has nothing to format). Going into [the implementation of `writeSym`](https://github.com/pinojs/pino/blob/c0dc89dba3cf491fc86ad40aadd0c650d75708e8/lib/proto.js#L115-L140) shows that it doesn't do much with the symbol, and passes it along to `asJsonSym`. In [its implementation](https://github.com/pinojs/pino/blob/c0dc89dba3cf491fc86ad40aadd0c650d75708e8/lib/tools.js#L94-L115), it hits the `default` case, and calls the stringifier, which is by default `stringifySym`, [defined here](https://github.com/pinojs/pino/blob/c0dc89dba3cf491fc86ad40aadd0c650d75708e8/lib/tools.js#L345-L351), basically `JSON.stringify`.

For some reasons I can only speculate, and the Lords of the Spec wherever they be know better, per spec, [`JSON.stringify`](https://tc39.es/ecma262/#sec-serializejsonproperty) just seems to fall through and return `undefined` for Symbols and all Symbol properties. So we effectively get `undefined` when trying to string the symbol, and the `msg` key isn't populated.

In other circumstances I would've blindly opened a PR adding a `case 'symbol'`, but it seems like very extra care is taken in [`asString`](https://github.com/pinojs/pino/blob/c0dc89dba3cf491fc86ad40aadd0c650d75708e8/lib/tools.js#L41-L69). Would you be interested in a PR which defers to that? Or perhaps something else?
