### ISSUE TITLE
Provide easy way to use console.log in node

### ISSUE THREAD

**Issue by BrendanBall** [pinojs/pino#718]
I'm not sure what other test runners are like, but jest has special logic for `console.log` when passing `jest --silent` to hide the logs. This obviously breaks when using pino because it writes straight to `process.stdout`. It would be nice if there is an easy way to specify for pino to use `console.log` instead of `process.stdout`. I know you can pass a custom stream to pino as a second argument, however it seems non trivial to implement a stream interface for console.log especially because a stream chunk might not correspond one to one with a single console.log.

What do you think is the best way to support this feature?

**Comment by mcollina** [comment]
Unfortuantely pino is built to provide a performant and flexible logger for production use case. Passing through `console.log` would likely be against all of this.

I would recommend to ask the jest team to have a way to query the status of the `--silent` flag from code, so that you could do something similar.

```js
pino({
  level: jest.isSilent ? 'error' : 'info'
})
```

If you prefer a more hacky solution, you might try:

```js
pino({
  stream: {
    write(str) { console.log(str) }
  }
})
```

(I have not tried this, nor I recommend it).

**Comment by jsumners** [comment]
I don't know why a testing framework would have any impact on application logging. Your application's logging should be setup in such a way that it only writes logs when running in a "real" environment.

If you use environment variables:

```js
pino({ level: process.env.LOG_LEVEL || 'silent' })
```

**Comment by BrendanBall** [comment]
@jsumners we still use logs for debugging and fixing tests, it's just that that's only normally done when running a single test. When running all the tests the output is useless and noisy.

It's weird that pino supports browsers which use console.log, but that functionality is simply not available in node. I would think it would be nice for that to be less fragmented.

I will also look into getting the flag from jest.

**Comment by KODerFunk** [comment]
@jsumners, hi amer, wtf "real" environment.

**Comment by mcollina** [comment]
Unlocked because I have received a private email asking for adding some more info on their end.

**Comment by mcollina** [comment]
(I'm closing the issue anyway, this is not relevant to pino)
