### ISSUE TITLE
Automatic enrich generated log

### ISSUE THREAD

**Issue by opravil-jan** [pinojs/pino#719]
Hi,

is it possible in pino to automatically enrich every log message. For example to every log message add source for ELK to know which system generated the log message.

Thank you
Jan Opravil

**Comment by mcollina** [comment]
You can use `log.child({ system: 'hello' })`

**Comment by opravil-jan** [comment]
In my opinion I have to place the code you mention on more than one place. I want something which handles all log requests and enrich them in one place. Maybe I'm mistaken

**Comment by mcollina** [comment]
I don't really understand what is the ask, this seems something very specific to your project structure.

**Comment by opravil-jan** [comment]
Sorry for the confusion. You were right. log.child can be used for easy use case. In my use case I want to migrate from hapi/good which allowed on event for example "request" to call function which make transformation to log message and also enrich the log message. I'm looking something similar in pino. Is it more understandable now?

**Comment by mcollina** [comment]
That's not possible with pino at this point in time. This is likely the http framework responsibility, so it might be an addition to hapi-pino.
