### ISSUE TITLE
Access to pino instance from prettifier function

### ISSUE THREAD

**Issue by SkeLLLa** [pinojs/pino#720]
Hi. Are there any method that will allow to get pino instance from formatter? Probably we can bind it to `this` somewhere when prettifier is constructed?

It could be utilized, for example, for getting levels (especially if there are custom levels).

**Comment by mcollina** [comment]
I don't know.. you might have to scavenge the code. However, it would be cool to have. We do have it in the meta protocol for `pino-multi-stream`, so I'll be open to have a PR adding it if it's not there.
