### ISSUE TITLE
unwanted extra spacing in log output

### ISSUE THREAD

**Issue by mschipperheyn** [pinojs/pino#731]
When I moved pino to the top of the chain I started getting extra spacing in my log output
I'm also not able to remove the time variable

```
[1571339804500] INFO : [ 3 2 m L o a d i n g   g r a p h q l   a c c o u n t / g r a p h q l . j s [ 3 9 m
[1571339804500] INFO : [ 3 2 m L o a d i n g   g r a p h q l   c a c h e / g r a p h q l . j s [ 3 9 m

```
```
import pino from 'pino';
import chalk from 'chalk';

const isProduction = process.env.NODE_ENV === 'production';

const pinoOptions = {
	name: 'TMP',
	base: null, 
	useLevelLabels: true,
	prettyPrint: isProduction ? false : { colorize: true },
	ignore: isProduction ? undefined : 'time,pid,hostname',
};

const loggerImpl = pino(pinoOptions);

console.error = loggerImpl.error.bind(loggerImpl);
console.log = loggerImpl.info.bind(loggerImpl);
console.info = loggerImpl.info.bind(loggerImpl);
console.warn = loggerImpl.warn.bind(loggerImpl);
console.debug = loggerImpl.debug.bind(loggerImpl);
console.trace = loggerImpl.trace.bind(loggerImpl);

export default console;

```

**Comment by mcollina** [comment]
This is a very interesting setup. would you mind sharing the log lines
without prettyPrint enabled?

Il giorno gio 17 ott 2019 alle 20:17 Marc Schipperheyn <
notifications@github.com> ha scritto:

**Comment by mschipperheyn** [comment]
@mcollina "Very interesting setup", is a polite way of saying "No, you idiot!", right? :-D

Actually, the problem goes away if you uninstall pino-debug

**Comment by mcollina** [comment]
I’m always intrigued by everybody that customize the output of piñon in such a significant manner. I have not tested all combinations of those options, as I never felt the need (I’m very happy with the default!). The result for all of this is that there might be some combinations of flags that leads to unexpected output.

It looks like a bug with pino-debug then, right? I do not see pino-debug in your example.

**Comment by mschipperheyn** [comment]
Yeah, it's prob a bug in pino-debug. This is my first attempt at using Pino so if someone with more experience on it, suggests this is a significant change to the common use, I wonder if I'm doing something fundamentally wrong. 

My use case is basically, I want to replace console.log etc to a more performant approach, I already use `debug` and like it, so I figured I would hook that up. And then I have to save in a Kibana compatible format for production. Since I don't want to be surprised in production by implementation differences, I want to use pretty print in dev and get basically what I already had (without the time)

**Comment by mcollina** [comment]
Your setup looks ok, I just never saw that same combination of options passed in.

**Comment by mschipperheyn** [comment]
The one thing I learned is that I should use `timeStamp: false` to remove the timestamp.

But I'm having a very hard time getting Kibana compatible output written to a log file based on my configuration (which I need in production mode). Any suggestion on how to get that set up?

**Comment by mcollina** [comment]
What do you mean by kibana-compatible? I have always used pino logs as-is with ES and Kibana, loading them in JSON format.

**Comment by mschipperheyn** [comment]
@mcollina Well, the logs will end up in Kibana, but the client has a pattern where they load them from a disk in a Kibana specific format. So, I can't write directly to the Kibana server, but have to store in a disk log that they will import.
