### ISSUE TITLE
"flatstr": "^1.0.9"

### ISSUE THREAD

**Issue by ezlo-octaviano** [pinojs/pino#734]
Please update flatstr to latest to avoid memory issues,  https://github.com/davidmarkclements/flatstr/issues/7

**Comment by mcollina** [comment]
npm should pick it up automatically. remove your package-lock and
node_modules, and it should all work.

Il giorno lun 28 ott 2019 alle 18:24 ezlo-octaviano <
notifications@github.com> ha scritto:
