### ISSUE TITLE
where is a compiled es5 version?

### ISSUE THREAD

**Issue by cekvenich** [pinojs/pino#735]
I'd like to use this, but I see browser.js has module and such.
Is there a working es5 version in the repo?

**Comment by mcollina** [comment]
you can compile that using browserify or webpack

Il giorno lun 28 ott 2019 alle 22:20 Vic C <notifications@github.com> ha
scritto:

**Comment by jsumners** [comment]
I believe this question is answered. If you need further information feel free to reopen.

**Comment by cekvenich** [comment]
when accessed via CDN, neither git nor npmjs contains the needed file.

**Comment by jsumners** [comment]
We don’t offer a CDN for this package. This is a utility library and as such it is meant to be bundled with the application.

**Comment by cekvenich** [comment]
Anything released on npm or github release is auto-CDN, eg https://www.jsdelivr.com/features
That is how libs/assets are accessed on the web, via http, from the cached edge. hth.
This lib is rare in that it does not offer a build - so it does not work w/ a CDN. And that is why I opened the issue.

**Comment by jsumners** [comment]
Assets are indeed accessed on the web via HTTP. But that doesn't mean everyone creating a library supports every arbitrary third party _service_ that serves assets over HTTP.
