### ISSUE TITLE
How to disable JSON format?

### ISSUE THREAD

**Issue by Mexman2Rowen** [pinojs/pino#737]
How do I disable JSON format for development purpose?

---

Edit: I just found `pino-pretty`, and I will use it in development.

However, in production I use PM2 log management, which is also JSON format. 

Is there any way I can print like Winston format to compatible with PM2's log?

**Comment by mcollina** [comment]
Unfortunately no.

**Comment by jsumners** [comment]
You should have pm2 direct your app’s stdout to a file.
