### ISSUE TITLE
Exporting logger instance as singleton

### ISSUE THREAD

**Issue by dparkerfmts** [pinojs/pino#738]
I'm trying to use a logger instance as a singleton so I can do my setup once and re-use the logger instance throughout my code base.  
However, the level I set when I create the logger instance is reset when I require it from another module:

**logger.js:**
```js
const pino = require('pino');
const logger = pino({base: null, level: 'warn'});

console.log(logger.level); // 40

module.exports = logger;
```

**module.js:**
```js
const logger = require('./logger');

console.log(logger.level); // 20
```

Is this expected behaviour?  
Do I have to configure the logger in every module?

**Comment by jsumners** [comment]
No, this looks like you are doing a `logger.level = 'debug'` somewhere in between the two requires.

**Comment by dparkerfmts** [comment]
Yep. Just found that someone has overridden the level :(
