### ISSUE TITLE
"EAGAIN: resource temporarily unavailable, write" on fatal

### ISSUE THREAD

**Issue by allevo** [pinojs/pino#739]
Before https://github.com/pinojs/pino/pull/730, the use of `fatal` was safe.
After that version, my application crash with `EAGAIN: resource temporarily unavailable, write`.

The linked lines live in sonicboom repo:

https://github.com/mcollina/sonic-boom/blob/e1b31fb93c5a8c306cdc16021e81b4995056a5aa/index.js#L245-L248

This behaviour was considered a patch but the behaviour changes.

Can I may send a PR with a patch (maybe a configuration flag)?

**Comment by mcollina** [comment]
Sure thing
Il 11 nov 2019, 10:25 +0000, Tommaso Allevi <notifications@github.com>, ha scritto:
