### ISSUE TITLE
Drop support for EOL Node versions

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#747]
https://github.com/pinojs/pino/blob/29ceca49cfa0a0610cc7f26cdf2782ccd8edf169/.travis.yml#L4-L5

It is time.

**Comment by mcollina** [comment]
Definitely. We should bump the major as well. Are there any other things we'd like to land?

**Comment by pebo** [comment]
Will the `v` key be dropped in next version (https://github.com/pinojs/pino/issues/620)? It would also be great if pinojs played nicely with StackDriver ( https://github.com/pinojs/pino/issues/726) 👍

**Comment by jsumners** [comment]
Please keep issue discussion relevant to the issue at hand. You linked to the relevant issues for the questions you are asking in a completely unrelated thread.
