### ISSUE TITLE
Grafana Loki

### ISSUE THREAD

**Issue by ManuCart** [pinojs/pino#749]
Hi,
What the way to send data to Grafana/Loki?

**Comment by mcollina** [comment]
I’ve never used them for logs, I’m sorry I cannot be of help.

**Comment by ManuCart** [comment]
Thanks, so what is the best browser viewver log  for pino?

**Comment by mcollina** [comment]
Use https://github.com/pinojs/pino-elasticsearch and Kibana!

**Comment by ManuCart** [comment]
@mcollina thanks for your help
