### ISSUE TITLE
Proposal: Change default time key to `eventTime`

### ISSUE THREAD

**Issue by naseemkullah** [pinojs/pino#750]
In order to distinguish between [event time, processing time and ingestion time](https://ci.apache.org/projects/flink/flink-docs-release-1.2/dev/event_time.html#event-time--processing-time--ingestion-time), where the latter two can be added by other parts of the logging pipeline (log aggregator may add processing time, log sink may add ingestion time).

**Comment by mcollina** [comment]
I don't think it's a great idea, as it's more verbose.. more bytes to write. Whoever process the log line can actually make the change.

**Comment by naseemkullah** [comment]
Hi!

IMHO 5 characters is not considerable overhead in most cases, and in extreme cases that it is we could probably rename the time key to `t` or perhaps not even use a JSON logger at all to avoid that added double quotes and so on.

It is slightly more verbose but reduces ambiguity IMHO

**Comment by naseemkullah** [comment]
@davidmarkclements any thoughts on this?

**Comment by davidmarkclements** [comment]
I'm happy to allow it as an option, but I don't think it's worth a breaking change 

An option for this actually already exists:

```js
const logger = pino({
  timestamp() {
    return `,"eventTime":${Date.now()}`
  } 
})
```

**Comment by naseemkullah** [comment]
Alright, thank you both for your input.
