### ISSUE TITLE
remove all fields except msg

### ISSUE THREAD

**Issue by dcsan** [pinojs/pino#753]
Is there a formatter that will just leave me with the content of my debug messages (eg the `msg` field)

currently I get so much metadata it pushes the content of the debug message to wrap around like this:

```
[2019-12-07T23:05:06.782Z]  INFO: smooch-middleware/11713 on dcboom.hsd1.ca.comcast.net: http (msg)
```

if nothing I can simply pipe output to, a hint on how to write and use such a very simple formatter would be appreciated!
can I create an extra stream and pipe output through my formatter somehow to extract the fields I want before outputting and still use all the pino transports etc?

**Comment by jsumners** [comment]
It looks like you are using `pino-pretty`. Have you looked at the `ignore` option? https://github.com/pinojs/pino-pretty

**Comment by jsumners** [comment]
Closing this due to lack of response. However, log formatters in v6 should also make this possible.

**Comment by dcsan** [comment]
thanks! I switched to another project in the end so didn't get to follow further on this.
