### ISSUE TITLE
Exit logging fails with standard pino

### ISSUE THREAD

**Issue by JaneJeon** [pinojs/pino#761]
Hi, I'm using pino v5.16 (though the same seems to happen with v5.15 as well) and I'm getting this error:

```
final requires a stream that has a flushSync method, such as pino.destination and pino.extreme

  15 |   .on(
  16 |     'uncaughtException',
> 17 |     pino.final(logger, (err, finalLogger) => {
     |          ^
  18 |       finalLogger.fatal(err, 'uncaughtException')
  19 |       process.exit(1)
  20 |     })
```

even though I'm not using `pino-pretty` or any nonstandard streams in my logger:

```js
const pino = require('pino')
const pick = require('lodash/pick')

const logger = pino({
  serializers: {
    err: pino.stdSerializers.err,
    req: req => pick(req, ['id', 'method', 'url', 'user'])
  },
  base: null,
  level: process.env.LOG_LEVEL || 'info'
})

process
  .on(
    'uncaughtException',
    pino.final(logger, (err, finalLogger) => {
      finalLogger.fatal(err, 'uncaughtException')
      process.exit(1)
    })
  )
  .on(
    'unhandledRejection',
    pino.final(logger, (err, finalLogger) => {
      finalLogger.fatal(err, 'unhandledRejection')
      process.exit(1)
    })
  )

module.exports = logger
```

What's going on? I followed the instructions on the documentation :(

**Comment by mcollina** [comment]
how are you running node? Certain environments (aws lambda, pm2, possibly nodemon) alter the stdout/stderr streams and flush is not possible.

**Comment by JaneJeon** [comment]
Running this on node 13. It seems to only fail when run using jest & supertest though.

**Comment by jsumners** [comment]
> It seems to only fail when run using jest & supertest though.

I know nothing of these tools, but I'm willing to bet several dollars that they modify `stdout`.

**Comment by mcollina** [comment]
jest definitely is.
Il 13 gen 2020, 16:06 +0100, James Sumners <notifications@github.com>, ha scritto:

**Comment by JaneJeon** [comment]
Hmm, so the advice is to turn off final logging for jest/mocha?

That's fine, but if that's the case, then could you add this to the docs, especially in the section about final logging? Thanks!

**Comment by jsumners** [comment]
PRs are welcome. But I think this is already covered by the docs that say the final logging requires streams with file descriptors.

I think a more appropriate doc addition would be a recommendation to disable logs during testing. Unless you actually need to test what the log line is, they are not useful during tests. And if you _do_ need to do that, then it's far better to supply your own destination stream so that you can intercept the logs and inspect them.

**Comment by JaneJeon** [comment]
@jsumners I'll draft up a PR during lunch, so let's keep this open for now.

**Comment by Fdawgs** [comment]
@JaneJeon Did you manage to resolve this?

**Comment by JaneJeon** [comment]
Err, I never got around to doing it.
