### ISSUE TITLE
Documentation says silent, but it didn't work.

### ISSUE THREAD

**Issue by katlimruiz** [pinojs/pino#763]
```
level (String)
Default: 'info'
One of 'fatal', 'error', 'warn', 'info', 'debug', 'trace' or 'silent'
```
however when using `pino-http`, `this.log['silent']` returns undefined. So is it supported? If not this way, then how?

**Comment by mcollina** [comment]
The level is silent, but there is no silent method: silent means nothing is logged, so why should we add a noop?

**Comment by jsumners** [comment]
```
const log = pino({level: 'silent'})
log.info('foo') // nothing is logged
```
