### ISSUE TITLE
Proposal: add format support

### ISSUE THREAD

**Issue by delvedor** [pinojs/pino#764]
Hello everyone!
At Elastic, we have a custom format for JSON logs named [ECS](https://www.elastic.co/guide/en/ecs/current/index.html), it helps us run some automation behind the scenes and improve the user experience.
I'm working on a set of libraries that make the most commonly used logging frameworks to log directly into an ECS compliant format, but currently, it is not possible doing it for Pino, since the json structure is fixed, and the serializers are not powerful enough for solving the issue.

What do you think about introducing the `format` concept?
It would be an object that allows you to hook into Pino and specify how you want the data to be serialized.
Following an example, so it's more clear what I would like to implement.
```js
const Pino = require('pino')({
  format: {
      // called everytime createChild is executed
      onChild (level, pid) {
        return `'{"level":"${level}","pid":"${pid}"}`
      },
      // what the user logs via log.info(‘messge’, { data })
      onLog (mergingObject, message, ...interpolationValues) {
        // return serialized data
      },
      onTime (time) {
        return `'{"@timestamp":"${new Date(time).toISOString()}"`
      }
  }
})
```

With this feature, we can also start logging format different than JSON:
```js
const Pino = require('pino')({
  format: {
      onBase (level, pid) {
        return `'level: ${level} - pid ${pid}`
      },
      onLog (mergingObject, message, ...interpolationValues) {
        // return serialized data
      },
      onTime (time) {
        return `@timestamp - ${new Date(time).toISOString()}`
      }
  }
})
```

What do you think? If you would like to move forward with this feature, I can work on it.

Some additional points:
- This can simplify the meta protocol defined in http://getpino.io/#/docs/api?id=destinationsymbolfor39pinometadata39 as it should be designed to potentially side-step the internal rendering, simplifying the implementation of https://github.com/pinojs/pino-multi-stream for example.
- This will simplify the implementation of the “prettifierMetaWrapper” https://github.com/pinojs/pino/blob/6068257bbc8e3ebb73fe8f941e0e56a3eadb75d1/lib/tools.js#L168
- This will likely be a semver-major change

**Comment by jsumners** [comment]
I suspect this will incur undesirable performance impacts. But it also feels related to https://github.com/pinojs/pino/pull/614

However, we are not opposed to any improvements that do not negatively impact performance.

**Comment by nuragic** [comment]
Ciao Tomas @delvedor,

Is there any work in progress on this proposal? Just in case you have any experimental branch or something like that, and you would like to let people test it out... I'd be interested... 😄 Thanks!

**Comment by delvedor** [comment]
Hello @nuragic! Not yet, I'll keep you posted in this issue :)

**Comment by nuragic** [comment]
🙏 Many thanks!

**Comment by zekth** [comment]
> I suspect this will incur undesirable performance impacts. But it also feels related to #614

The performance impact is not a problem IMO as if you're implementing it you're aware of the cost of the formating. Like mentionned for the Date format for ISO for example.

**Comment by delvedor** [comment]
Closed in https://github.com/pinojs/pino/pull/775.
