### ISSUE TITLE
change log level globally or on root logger

### ISSUE THREAD

**Issue by geekflyer** [pinojs/pino#766]
This is somewhat related to #681 

I'd like to bring this discussion up again.

Let's say I have a bunch of loggers:

```js
const rootLogger = pino({level: 'info'});

const childLogger = rootLogger.child({name:'thechild'});
```

Currently one change the log level at runtime doing
`parentLogger.level = 'debug'`

Unfortunately this change in level doesn't propagate to the child logger and in order to really change the log level on the root logger and all children one has to somehow keep track of the children or use a proxy hack as described in #681.

I'm wondering if we can change pino to make level changes propagate to all children of a root logger or define the log level globally?

I think the current behaviour of the log level change not propagating to children is confusing and not useful.

I have a good enough understanding of the code base that I could create a PR that would change this so that level changes on the root propagate to children.

Also for reference, this actually **works** the way I described in winston@3:
```js
const winston = require("winston");

const rootLogger = winston.createLogger({
  level: "info",
  format: winston.format.json(),
  transports: [
    new winston.transports.Console({
      format: winston.format.json(),
    }),
  ],
});

const childLogger = rootLogger.child({ name: "child" });

rootLogger.level = "debug";

childLogger.debug("this is a debug message that will be logged");
```

cc @zdila

**Comment by mcollina** [comment]
Tracking all created child loggers _was_ extremely expensive when we started working on pino. I'm not sure if it is still the case.

I see how this can be a pain point when using pino. Maybe this can be done in a plugin/accessory module?

**Comment by geekflyer** [comment]
Well, I don't think you have to "track" child loggers for this feature to happen.

There's generally 2 alternatives how this could be implemented from an API point of view:
1. Only allow setting the log level globally
2. Only allow setting the log level on root loggers

Currently the log level can be set on root logger and child loggers, each individually.

Let's just talk about how option 2. could be implemented:

Generally speaking the `level` setter could be only on the root instance and the child instances inherit the level through the prototype chain.

Currently all child loggers already inherit their ancestors through the prototype chain.

I created a quick and dirty implementation of this approach in #767 which demonstrates that this is absolutely possible.

In this example basically a root logger instance and all it's children share a log level through the prototype chain.

This was just a quick n dirty implementation but I doubt that this would have any negative impact on performance. Also I believe if the log level could only be set on the root instance, a lot of the complex code in the level.js could be deleted (I didn't do that yet in my PR, but while glancing over the code I realized that a lot of code with regards to log level changes would become obsolete). 

Side Note: In my implementation there can be still multiple root loggers, since this alternative 2.

**Comment by mcollina** [comment]
Being able to set the log level in child logger is a very important feature of pino. As an example, we use it to log different HTTP routes at different severity, or ignore them altogether. Removing this feature is a no-go. Could this be implemented without removing it?

**Comment by geekflyer** [comment]
hmm, personally my use case is very similar to @zdila use-case in #681 , i.e. I want to temporarely enable more verbose logging in production at runtime on a global level in order to debug issues, but I don't really have the need to control the log verbosity by route (I can just filter out the extra logs via my log aggregator), although I guess that could be useful.

Anyways, I think one of way of combining both worlds would be to make it such that that root logger has a log level and all it's children up the prototype chain inherit that level, unless they override it.

That would mean changing the level of the root logger would only affect children which haven't overriden / set the level explicitly.

I think from a technical and performance point of view that's totally possible, my only concern would be that this may be a bit surprising / complex API for the user.

Anyways what do you think?

**Comment by mcollina** [comment]
Note that it should work on multiple levels (> 2), so that the level can be changed at any step in-between.

I think it would be a nice addition to pino as long as we do not lose throughput.

**Comment by jsumners** [comment]
I think this issue appears when one keeps a child logger around for an extended period of time instead of the child logger living for only the duration of an event (e.g. http request).

I suspect https://github.com/pinojs/pino-arborsculpture will solve this for you.

**Comment by geekflyer** [comment]
@jsumners Unfortunately I think pino-arborborsculpture won't really solve my issue. It will only change the log level of all the loggers passed to it and not their children (unless I I have a fixed set of children and I carefully pass in all children at initialization).

Yes, generally speaking this issue appears when a child logger is kept around for an extended period of time, but that's imho not too unusual if you're using node for things other than simple http APIs. In our case we use it partially for background job processing.

@mcollina cool, so if I send a pr for this feature you'd be open to it?

**Comment by jsumners** [comment]
> (unless I I have a fixed set of children and I carefully pass in all children at initialization)

PR a `trackLogger` method...

**Comment by alexey-sh** [comment]
So important and cool feature stays in issue for more than 1 year. How many years devs should wait for it? 😃

**Comment by mcollina** [comment]
> So important and cool feature stays in issue for more than 1 year. How many years devs should wait for it? 😃

I assume you are volunteering to work on this. i'd be happy to review a pull request that does not lower our throughput.

**Comment by alexey-sh** [comment]
@mcollina I thought PR was already exist. tbh it's a bit hard to get out what's going on here.
![image](https://user-images.githubusercontent.com/1584156/110221364-01eb4480-7edd-11eb-8284-62be93a6db9b.png)

> does not lower our throughput.

I do not trust your perfomance tests. For example, from [your benchmark](https://github.com/pinojs/pino/pull/969/checks) PR check
```
benchWinstonObj*10000: 688.952ms
benchBoleObj*10000: 337.514ms
benchLogLevelObject*10000: 722.588ms
benchPinoObj*10000: 278.258ms
```

While I'm getting different results when I write object + message into a file. My result - pino is faster than winston by 5%.

> i'd be happy to review a pull request

After some time I realized that I can solve my issue with changing log level by simple wrapper over the pino.

Something like this

```
class MyLogger() {
  constructor() {
    this.logger = pino(etc);
    this.children = {};
  }
  getChild(name, opts) {
    if (this.children[name] == null) 
      this.children[name] = this.logger.child({mod: name, ...opts});
    return this.children[name];
  }
  changeLogLevel(level, name) {
    this.children[name].level = level;
  }
}

```

I'm not sure that it can solve Christian's issue but it works fine for me.
