### ISSUE TITLE
Stringify speed

### ISSUE THREAD

**Issue by lukiano** [pinojs/pino#773]
Hi there, if I knew that my logs follow a defined schema, would using `fast-json-stringify` be an improvement in logging to console over regular `JSON.stringify` ?

**Comment by mcollina** [comment]
Yes and no. This module already leverages most of the principles that make fast-json-stringify _fast_. In fact, it’s its precursor.

It would be helpful for serializers and in general for big objects.

**Comment by delvedor** [comment]
https://github.com/pinojs/pino/issues/764 could address this.

**Comment by jsumners** [comment]
I think this is sufficiently answered. Feel free to reopen if you still have questions.
