### ISSUE TITLE
Not working in catch

### ISSUE THREAD

**Issue by polRk** [pinojs/pino#784]
Working
```
catch(reason => { 
   ctx.logger.error(reason) 
})
```

Not working
```
catch(ctx.logger.error)
```

**Comment by mcollina** [comment]
Functions are not bound to their objects for perf reasons. You'll need to `catch(ctx.logger.error.bind(ctx.logger))`.

**Comment by polRk** [comment]
@mcollina Bind works for functions, do you even understand what you wrote ?
