### ISSUE TITLE
Set different value for standard levels

### ISSUE THREAD

**Issue by e-serebriakov** [pinojs/pino#787]
Hello!

How can i set different values for standard levels?

Default values are 
```
const levels = {
  trace: 10,
  debug: 20,
  info: 30,
  warn: 40,
  error: 50,
  fatal: 60
}
```

I need it to be with different values.
Tried to change it in config object, but it didn't work. 
```
const logger = pino({
  ...get('logger'),
  messageKey: 'short_message',
  useOnlyCustomLevels: true,
  customLevels: {
    fatal: 0,
    error: 3,
    warn: 4,
    info: 6,
    debug: 7,
    trace: 7,
  },
});
```

Logs just don't be written with this config.

**Comment by mcollina** [comment]
Can you please expand "it didn't work"?

**Comment by e-serebriakov** [comment]
Sorry.
In this case i don't see any logs in my console. 
There are no errors, code works properly but without any log entries.

There are something like this in the console without levels overwritting.
```
{"level":30,"time":1583940761325,"pid":2960,"hostname":"local","name":"backend","worker":"currency-rates","appVersion":"1.0.0","timestamp":1583940761325,,"short_message":"End synchronization","v":1}
```

**Comment by davidmarkclements** [comment]
what does `...get('logger')` return

**Comment by davidmarkclements** [comment]
![image](https://user-images.githubusercontent.com/1190716/76435339-2d654d00-63b7-11ea-9ceb-3ce1a5de0761.png)

**Comment by davidmarkclements** [comment]
I suspect that whatever `get('logger')` returns is setting an option that silences the logger in some way

**Comment by e-serebriakov** [comment]
You are right! :clap:
It returns logging level from yaml config file.
In my case values of logging levels sorting in opposite order :grimacing:

**Comment by davidmarkclements** [comment]
glad you got it fixed  👍- closing
