### ISSUE TITLE
Did pino support correlation id?

### ISSUE THREAD

**Issue by wizardnet972** [pinojs/pino#788]
Sometimes I want to give the user some sort of correlation id instead of "we will fix your problem", So I thinking if pino have a way to generate correlationId for every log and return correlationid from the logger function like this:
  
```
const logger = pino({
  levelKey: 'priority'
});
const correlationId = logger.info('hello world'); //output: <correlationId> hello world.
console.log({ correlationId }); 
```

The idea is pino will generate `correlationId` because I don't want every developer in my team will have to do it, and I don't want to wrap pino in my methods.

Can I do that with pino?

**Comment by mcollina** [comment]
pino has everything it is needed to support generating correlation id/request ids. However, it does _not_ do it by default as it should be integrated with your framework. Check out https://github.com/pinojs/pino-http as an example (`genReqId` option).
