### ISSUE TITLE
About transports

### ISSUE THREAD

**Issue by cocobiz** [pinojs/pino#801]
Hi guys,

I want to know how to achieve the below transports in pm2? [related links](https://github.com/pinojs/pino/blob/HEAD/docs/transports.md)
`node my-app-which-logs-stuff-to-stdout.js | node my-transport-process.js`

As i know, pm2 will log its standard output, thus we will not have a **separate process** to transports the pino's output as pm2 share the same process with app (also share same event loop etc), and this can cause performace issue (which cut down pino's feature), am i right?

This confuses me a long time :(

Has anyone else encountered the same issue?

**Comment by mcollina** [comment]
I would recommend to not use pm2, or instrument pm2 to distribute logs. They monkey-patch the `process.stdout` to support their own logging mechanism, so you should refer to their guidance for all your logging practices.

A significantly better option is to log to a file and have some other process read from there and ship it somewhere else, and completely sidestep pm2 logging facility.

**Comment by cocobiz** [comment]
@mcollina thanks for your replay, and i have one more question do you have any recommended library about process management, thanks a lot!

**Comment by mcollina** [comment]
I would recommend to use systemd and logrotate.

**Comment by cocobiz** [comment]
Yes, systemed is an option for process management, but how to achieve cluster load balance? Please forgive me for keeping asking questions
I think i need both process management and load balance :D 
@mcollina

**Comment by mcollina** [comment]
https://nodejs.org/api/cluster.html.

Overall I would _not_ recommend to use cluster at all,  but rather scale your application horizontally via mulitple servers

**Comment by cocobiz** [comment]
Okay, thanks for your patience @mcollina

**Comment by valonhaliti** [comment]
@cocobiz did you end up using systemd or did you find a solution with PM2?
