### ISSUE TITLE
Support `method(string, obj)`?

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#803]
Currently, the primary signature for the logging methods is `method(obj, [string])`:

https://github.com/pinojs/pino/blob/529906ed868ec362d66b228dbc10bd201b766202/docs/api.md#L385-L430

This means we hit a different serialization path if one does `method(string, obj)`:

https://github.com/pinojs/pino/blob/529906ed868ec362d66b228dbc10bd201b766202/lib/tools.js#L31-L53

This is another vestige of the Bunyan inspiration - https://github.com/trentm/node-bunyan/blob/fe31b83e42d9c7f784e83fdcc528a7c76e0dacae/README.md#L171-L175

This is causing me issues. At my company we have established `method(string, obj)` as the logical way of logging a message with a metadata object. Indeed, I would use the new log formatter hook to wrap up that metadata into a "data" property in the log line. I can accomplish this by wrapping the log methods like so:

```js
function wrapMethods(instance) {
  Object.keys(pino.levels.values).forEach(level => {
    if (instance[level].name === 'noop') {
      return;
    }
    const method = instance[level];
    instance[level] = logWrapper.bind({ logger: instance, method });
  });
}

function logWrapper(...args) {
  const logger = this.logger;
  const method = this.method;

  if (args.length === 1) {
    return method.apply(logger, args);
  }
  if (args.length === 2) {
    const param1 = args.shift();
    const param2 = args.shift();
    if (typeof param1 === 'string' && isObject(param2) === true) {
      if (/(%j|%o|%O)/.test(param1) === true) {
        return method.apply(logger, [param1, param2]);
      }
      return method.apply(logger, [param2, param1]);
    }
    return method.apply(logger, [param1, param2]);
  }

  return method.apply(logger, args);
}
```

However, this will not work with children. When we create a child logger we iterate the log methods and rebind the logger methods, thereby losing the wrapper:

https://github.com/pinojs/pino/blob/529906ed868ec362d66b228dbc10bd201b766202/lib/proto.js#L119

^ ends up hitting the `genLog` of:

https://github.com/pinojs/pino/blob/529906ed868ec362d66b228dbc10bd201b766202/lib/levels.js#L92-L98

So I would have to wrap the children in some fashion like:

```js
function wrapChild(instance) {
  const instanceChild = instance.child;
  instance.child = function(...childArgs) {
    const childInstance = instanceChild.apply(instance, childArgs);
    wrapMethods(childInstance);
    wrapChild(childInstance);
    return childInstance;
  };
}
```

The issue with this is that it creates a recursive child function that unrolls up to the first wrapper whenever new children are created from child instances. This causes the bindings to be lost. For example:

```js
const proto = require('pino')()
const rootLogger = proto.child({some: 'set', of: 'base', meta: 'data'})
// some time later, e.g. in a request
const logger = rootLogger.child({req: 'foo'})
// ^ this will not include the bindings set on `rootLogger` because
// the wrapper will unwrap to the `proto` bindings
```

So, my question is, should we attempt to support `method(string, obj)`? Notice that my wrapper does this by checking to see if there is an interpolation token for serializing the second parameter into the string. If not, it will be used as a metadata object.

**Comment by mcollina** [comment]
I would say that no, we cannot support this easily because adding it will cause `log.info('%d - %d', 42, 24)` to not work anymore. I would recommend against supporting that pattern, because I think that using printf-like syntax is powerful.

I'll be happy to add a sync hook/callback to let you intercept the child logger creation and/or other places as needed.

**Comment by jsumners** [comment]
🤔 I'll have to ruminate on that.

**Comment by jsumners** [comment]
My current thinking is a log method hook. Something along the lines of:

```js
const log = pino({
  hooks: {
    logMethod (args, method) {
      // do something with the `args` array
      method.apply(this, args)
    }
  }
})
```

With `genLog` looking something like:

```js
function genLog(level, hook) {
  if (hook) {
    // return a function that wraps `hook`
    // and the normal `LOG` function
  }

  return LOG(...) {}
}
```

**Comment by jsumners** [comment]
Or maybe:

```js
function genLog(level, hook) {
  if (hook) {
    return function (...logArgs) {
      const updatedArgs = hook(logArgs)
      LOG.apply(this, updatedArgs)
    }
  }

  return LOG

  function LOG(...) {}
}
```

**Comment by mcollina** [comment]
That would work. I'd love to see if it impacts any benchmarks (it shouldn't).

**Comment by jsumners** [comment]
Which version do you prefer? The user supplied hook function returning the mutated arguments (A) or the user supplied hook function mutating the arguments and then invoking the log method itself (B)?

**Comment by mcollina** [comment]
What do you think of?





```js
const log = pino({
  hooks: {
    genLog (method) {
      return function (a, b) {
        method.call(this, b, a)
       }
    }
  }
})
```

**Comment by jsumners** [comment]
That's my original idea where the user hook method is doing the invocation, i.e. (B) from my last post. It can't be as simple as a two parameter swap because the log function actually accepts an arbitrary number of parameters. So the hook needs to be passed an array of arguments that it will use in an `apply` invocation.

**Comment by mcollina** [comment]
True.
