### ISSUE TITLE
Pretty print does not respect formatters.log

### ISSUE THREAD

**Issue by giannisp** [pinojs/pino#804]
I have found two issues while using `prettyPrint: true` and `formatters.log`.
- First one is straight-forward, pretty print does not apply `formatters.log` function (like it does with serializers and redact functions).
- Second one seems more complicated. While using formatters.log and returning a modified log message (even by doing something like `{ ...log }`), pretty print doesn't print the actual log message, it only prints the log object.  

I cloned the repo locally, and could easily fix the first one, however I was stuck on the second one as I am not familiar with all repo mechanics.

Here is a test that can illustrate both issues:

**test/fixtures/pretty/formatters.js**
```js
global.process = { __proto__: process, pid: 123456 }
Date.now = function () { return 1459875739796 }
require('os').hostname = function () { return 'abcdefghijklmnopqr' }
var pino = require(require.resolve('./../../../'))
var log = pino({
  prettyPrint: true,
  formatters: {
    log (obj) {
      // return obj
      return { foo: 'formatted_' + obj.foo }
    }
  }
})
log.info({ foo: 'bar' }, 'h')
```

**test/pretty.test.js**
```js
test('applies formatters', async ({ is, isNot }) => {
  var actual = ''
  const child = execa(process.argv[0], [join(__dirname, 'fixtures', 'pretty', 'formatters.js')])

  child.stdout.pipe(writer((s, enc, cb) => {
    actual += s
    cb()
  }))
  await once(child, 'close')
  isNot(strip(actual).match(/\(123456 on abcdefghijklmnopqr\): h/), null)
  isNot(strip(actual).match(/foo: "formatted_bar"/), null)
})
```

**Comment by mcollina** [comment]
I'd recommend you to send a PR with a a failing test, I'm not following.

I'm not sure that `prettyPrint` can understand the `formatters` at all. It would probably need some change as well. Note that prettyPrint lives in its own module https://github.com/pinojs/pino-pretty

@delvedor  you implemented the formatters, wdyt?

**Comment by giannisp** [comment]
Yes, formatters are not being evaluated at `prettyPrint: true` I think.  
They should be handled on this function if I understand the codebase correctly:
https://github.com/pinojs/pino/blob/master/lib/tools.js#L242

On my initial post ^ I have attached a new test, if that helps you to try it out locally.
Plus check my second bullet point.

**Comment by mcollina** [comment]
I would recommend sending a Pull Request.
