### ISSUE TITLE
too many open files error

### ISSUE THREAD

**Issue by divyanagrath** [pinojs/pino#806]
With pino logger, on running the load test on the application, I'm getting too many open files error. Also, buffer/cache increases drastically. Like for 1 hr of load test, 1.5gb of buffer/cache increases. I'm logging every on every API hit. Do I need to close the logger or something else is the issue?

**Comment by mcollina** [comment]
Would you mind to include some code to reproduce the issue?
You should not create a new pino instance of each request, but rather share it and create child loggers.

**Comment by divyanagrath** [comment]
fastify.addHook('onResponse',async function(request,reply,done) {
 cont logger = require('pino')('/log/hits.log')
 logger.info(request)
})

Have instantiated the logger in onResponse event.

**Comment by mcollina** [comment]
Check out https://www.fastify.io/docs/latest/Logging/. You should not instatiate pino directly, but rather rely on Fastify management.

**Comment by divyanagrath** [comment]
What if I have to write 4 log files. How to instantiate multiple loggers for an application?

**Comment by mcollina** [comment]
you create them top level and decorate it to your fastify instance.

**Comment by divyanagrath** [comment]
With fastify logger enabled, in addition to my log message I can see 'incoming request' and 'request completed' enteries as well. How can I disable them?
