### ISSUE TITLE
Is `prettifier` missing in the TS option type in Pino constructor ?

### ISSUE THREAD

**Issue by mbreton** [pinojs/pino#812]
Hello Guys,

I'm actually giving a try to Pino for our NestJS projects, and I would like to write my own prettyfier.

If I refer to the [documentation](http://getpino.io/#/docs/pretty), there is a property `prettifier` in pino constructor. The unit tests cover it too: https://github.com/pinojs/pino/blob/0bb7a06b6e726c23e14878789066a4ece285bb63/test/pretty.test.js#L69

Nevertheless, it seems missing in the TypeScript definition in the version 6.1.1 of Pino:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pino/index.d.ts#L196

I'm ok to make a PR, but I just need to confirme with you the prettifier signature:
 ```typescript
type Prettifier = (input: string | object) => string;
```

**Comment by mcollina** [comment]
We do not maintain those types :/

**Comment by cmckni3** [comment]
Appears to have been fixed.  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44642

The latest version of `@types/pino` 5.17.0 removed `redact` for some reason which lead me here.

> We do not maintain those types :/

Any plans to supply TypeScript types with pino?

**Comment by mcollina** [comment]
No, there are no such plans.
