### ISSUE TITLE
Cannot find changelog or other information about changes from v5 to v6

### ISSUE THREAD

**Issue by openreply-dleinhaeuser** [pinojs/pino#816]
Npm shows that a new major version of pino is out but I cannot find information about the (breaking) changes between v5 and v6, which makes it very hard to judge what would be involved in upgrading.

There does not appear to be a changelog. There is information about how to migrate from v4 to v5 (and v3 to v4 if I am not mistaken), but none about v5 to v6 that I could find.

Would it be possible to document the differences between v5 and v6 somewhere?

**Comment by mcollina** [comment]
Please see https://github.com/pinojs/pino/releases/tag/v6.0.0. What is missing from your point of view?
