### ISSUE TITLE
How to log errors with custom message

### ISSUE THREAD

**Issue by robertsLando** [pinojs/pino#819]
I would like to log errors like

```js
var err = Error('Error message')
logger.error('Custom message' , err)
```

Output:

```bash
ERROR [1586513163739] (daniel-innovation): Custom message
```

Expected output: 

```bash
ERROR [1586512758036] (daniel-innovation): My custom message
    Error: Error message
        at Object.<anonymous> (/logger.js:9:13)
        at Module._compile (internal/modules/cjs/loader.js:955:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
        at Module.load (internal/modules/cjs/loader.js:811:32)
        at Function.Module._load (internal/modules/cjs/loader.js:723:14)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
        at internal/main/run_main_module.js:17:11
```

**Comment by jsumners** [comment]
Use the error serializer. `log.info('foo', {err})`

**Comment by robertsLando** [comment]
@jsumners The result is the same:

```js
var err = new Error('Error message')
logger.error('Custom message', {err})
```

Output:
```
ERROR [1586513163739] (daniel-innovation): Custom message
```

**Comment by robertsLando** [comment]
Seems serializers are not working as expected? @mcollina @jsumners

**Comment by mcollina** [comment]
The correct way to log an object is log.info({ err }, “something”).

@jsumners remember you are inverting the parameters in your codebase :P.

**Comment by jsumners** [comment]
> The correct way to log an object is log.info({ err }, “something”).
> 
> @jsumners remember you are inverting the parameters in your codebase :P.

Yes 😞 . I was just about to reply with a correction. Thank you.

**Comment by robertsLando** [comment]
Ok that is working but I think that the old method was far more clear and clean then this one. Maybe also this should be added to docs...

**Comment by jsumners** [comment]
You are welcome to write such a guide and provide a PR for it. We have already called out all of the major breaking changes in https://github.com/pinojs/pino/releases/tag/v6.0.0

"The old way" relied on surprising behavior (as discussed in https://github.com/davidmarkclements/quick-format-unescaped/pull/27). The current implementation adheres to the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by robertsLando** [comment]
Thanks for the explanation @jsumners 

Another thing that is not really clear, why isn't this working too?

```js
var err = Error('Error message')
logger.error("Message %o", err)
```

Output:

```
ERROR [1586513163739] (daniel-innovation): Message {}
```

Is using `logger.error("Message %o", {err})`

Output: 

```
ERROR [1586513163739] (daniel-innovation): Message {err: {}}
```

**Comment by mcollina** [comment]
Note that the “previous method” did not apply serializers or redaction at all. That caused leak of personal info in the logs :/.

**Comment by robertsLando** [comment]
I'm ok with that I'm just tring to figure out if everything works like expected. Today I will refator all my codebase to meet new standards

**Comment by robertsLando** [comment]
Also I have just find out that this is even better:

`logger.error(err, 'Custom message')`

**Comment by jsumners** [comment]
@robertsLando `log.error('foo %o', {err})` doesn't apply Pino's standard error serializer and standard `Error` object instances JSON stringify to `{}`.
