### ISSUE TITLE
Example to redirect error logs to stdError

### ISSUE THREAD

**Issue by robertsLando** [pinojs/pino#820]
By default pino uses stdOut as destination. I would like him to use stdError for all `error` logs levels. By digging in docs I found the only way is to use `pino-tee` but I cannot find any example for this

Update: Found here:

```js
var pinoms = require('pino-multi-stream')
var streams = [
  {stream: fs.createWriteStream('/tmp/info.stream.out')},
  {level: 'fatal', stream: fs.createWriteStream('/tmp/fatal.stream.out')}
]
var log = pinoms({streams: streams})

log.info('this will be written to /tmp/info.stream.out')
log.fatal('this will be written to /tmp/fatal.stream.out')
```

**Comment by vajahath** [comment]
This should be in the docs.

**Comment by robertsLando** [comment]
It is, at least I think I added a PR to update logs with this example

**Comment by mcollina** [comment]
This has been added to pino core and will be part of pino@7.

**Comment by robertsLando** [comment]
BTW, it's here: https://getpino.io/#/docs/help?id=log-to-different-streams
