### ISSUE TITLE
Port to TS

### ISSUE THREAD

**Issue by naseemkullah** [pinojs/pino#823]
Hi, It seems like the pino types are out of sync (LoggerOptions does not include formatters).

Would it be possible to port pino to TS?

**Comment by mcollina** [comment]
No, we are not Typescript developer. Moreover Pino relies on a lot of prototypical inheritance which is not well supported in TS.

Please send a PR to update the types to DefinitelyTyped.

**Comment by naseemkullah** [comment]
Very well.

**Comment by naseemkullah** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43847 created
