### ISSUE TITLE
Drop all references to pino.extreme

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#825]
As titled, this as been included inside pino.destination().

**Comment by AleksandrSl** [comment]
I started working on this. Should we preserve term `extreme mode`, or it could be renamed to something like `asynchronous mode`? 
There are also a bunch of `extreme` variables in tests and `pino.extreme` usage. Should they also be replaced?

**Comment by mcollina** [comment]
Please replace! It would be super helpful.

**Comment by AleksandrSl** [comment]
Should calls to `pino.extreme` be replaced using `minLength: 4096`, if so maybe there is some sense in providing function wrapper?

**Comment by mcollina** [comment]
> Should calls to pino.extreme be replaced using minLength: 4096, if so maybe there is some sense in providing function wrapper?

just replace them. The current API is more flexible.

**Comment by AleksandrSl** [comment]
Can be closed, I think
