### ISSUE TITLE
pino-pretty

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#83]
Should we break the pretty print out into it's own module, it seems to be getting a relatively sizeable portion of PR's

**Comment by mcollina** [comment]
@davidmarkclements I'm not 100% with you. I think the `pino` executable should stay within `pino`. However, we might try to get https://www.npmjs.com/package/chop from NPM, and release it as a tool for `pino`, `bole`, `bunyan`, etc.

**Comment by davidmarkclements** [comment]
Agree that the executable should stay in pino, but the prettifying part could be extracted into it's own module (chops a good name) - then wrap pino exec around it (and keep custom stuff here, like the date transform)

**Comment by mcollina** [comment]
https://github.com/mcollina/chops
