### ISSUE TITLE
child logger redaction

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#831]
I've been thinking about redaction in child loggers and that this is actually a really powerful use case, especially if you think about how it ties in with fastify plugins. 

Like a plugin (or route) will be responsible for data that is specific to that plugin, being able to spawn a child specifically for a plugin (or route) that has redaction set up for the data being handled within that context seems like the right thing to do

related issues: 

https://github.com/pinojs/pino/issues/639
https://github.com/pinojs/pino/issues/703
https://github.com/pinojs/pino/issues/752

I think what we should do is go with #752 - add a second options arg to `child`, but  initially JUST for overriding redact settings

@mcollina @jsumners wdyt?

**Comment by mcollina** [comment]
It would be pretty neat, yes.

**Comment by jsumners** [comment]
Are you suggesting 1 or 2?

1. `log.child({ foo: 'bar', redact: { /* redact options */ } })`
2. `log.child({ foo: 'bar' }, { redact: { /* redact options */ } })`

**Comment by mcollina** [comment]
I think 1. is coherent with the basic factory API.

**Comment by jsumners** [comment]
I'm not thrilled about 1, but it is how we currently pass in the child log level if it is to be different.

**Comment by osher** [comment]
option n# 1 is more coherent with the API. 
that's what I intuitively tried in the duplicate #869.

**Comment by mcollina** [comment]
@davesteinberg would you like to send a PR?

**Comment by davesteinberg** [comment]
@mcollina I'd like to, but I'm not sure if I'll have the chance to work on it. I'll comment again if/when I'm able to dig in.

**Comment by South-Paw** [comment]
I could be mistaken, but I don't think I changed anything with my logger implementation and the child loggers I have seem to be inheriting their parents redaction list now since I updated to `v6.6.1`

**Comment by mcollina** [comment]
What @davidmarkclements is asking for is to have child-specific redactors, e.g. redactors that are applied only to child loggers.

**Comment by South-Paw** [comment]
Ah my mistake, I had this issue saved believing it was just that child loggers didn't receive their parents context. :laughing: sorry

**Comment by AviBueno** [comment]
Hey all, in case you need more use cases, here's mine in a [discussion about child logger redaction inside Fastify plugins](https://github.com/fastify/fastify/discussions/2663#discussioncomment-118322).

I'd love to see this feature integrated into pino (and before being asked: I'm currently working on weekends as well so I won't have the capacity to introduce a PR).
