### ISSUE TITLE
How to test pino logging output? (jest)

### ISSUE THREAD

**Issue by matyashlavacek** [pinojs/pino#837]
I am trying to test logging output from pino, but to no avail.

This is my setup, which does not work:

`logging.ts`
```typescript
import * as pino from 'pino';
export const log = pino();
```

`index.ts`
```typescript
import { log } from './logging';
log.info('Something to log');
```

`index.test.ts`
```typescript
import { log } from './logging';

test('test logging', () => {
  cosnt spy = jest.spyOn(log, 'info').mockImplementation((msg) => msg);
  import('./index');
  expect(spy).toHaveBeenCalled();
  expect(spy).toBeCalledWith('Something to log');
});
```

---

When I replace pino in the code above with `console.log()`, the test works without an issue.

Does anybody have any idea on how to test pino logging output with jest? Any help would be greatly appreciated.

**Comment by mcollina** [comment]
I'm not sure how import works with ts, but you might have to await it.

Are you looking to mock pino or are you looking to test the logs that come out of pino?

**Comment by matyashlavacek** [comment]
Now that was a really silly mistake on my part. `await`ing the import indeed fixed my issue. Thanks a lot for help!

My intention was to get the logs that come out of pino.

**Comment by KODerFunk** [comment]
And? How? Commn!)))
