### ISSUE TITLE
Help building `httpRequest` from log object.

### ISSUE THREAD

**Issue by pietvanzoen** [pinojs/pino#846]
I'm working on tailoring the logging of the http request/response in a Fastify project to work with stack driver. (I can't use pino-stackdriver because I need logs to go to stdout).

I'd like to be able to build an object that resembles this spec: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest

Can't seem to find a sensible way to do this with the `log` formatter nor the `req/res` serialisers. 

Does anyone have suggestions as to how to achieve this?

**Comment by mcollina** [comment]
Please check out https://github.com/pinojs/pino/issues/726#issuecomment-633744801. You'd need to use pino v6 (Fastify@2 ships with pino v5).

**Comment by pietvanzoen** [comment]
Hi. thanks for the response. 

This issue doesn't seem to mention handling `httpRequest` logging, only severity.

I'd like to find out how I could achieve the `httpRequest` object. 

I need to be able to combine data from the `res` and `req` into a new object on the top level of the log (`httpRequest`). It's not clear to me how to achieve this. Using a `log` formatter does not seem to have the required data. I suppose ideally there's a final formatter that contains the `res` and `req` where I could construct the `httpRequest` object per the specs I linked to. Is this possible?

**Comment by mcollina** [comment]
You might want to open that on Fastify. This is likely more related to how fastify works rather than pino.

**Comment by pietvanzoen** [comment]
Ok thanks! Will try there
