### ISSUE TITLE
Documentation to replace useLevelLabels with formatters.level option to replicate string logging levels in 5.x

### ISSUE THREAD

**Issue by climberjase** [pinojs/pino#848]
I currently have a production and staging ElasticSearch cluster setup with indexes and logs parsed with log levels as strings out of Pino, Python and Java services. We are unable to support log levels as numbers.

I cannot find in the documentation or anywhere on SO how to resolve this deprecation warning error message that showed up after upgrading Pino 6 last week:

[PINODEP001] Warning: useLevelLabels is deprecated, use the formatters.level option instead

Can someone clarify how we can get Pino to continue to support the previous behavior with `useLevelLavels: true`? I've tried formatters.level experiments, but can't seem to get something to work following the docs that gets me the same result.

**Comment by mcollina** [comment]
Can you please include the code you want to migrate and what you have tried with formatters.level?

**Comment by jsumners** [comment]
How is the example in the documentation not clear? 

https://github.com/pinojs/pino/blob/015bb6078fd3f2a8057bc198a3a9cd5e0172167d/docs/api.md#level

**Comment by claabs** [comment]
I found this to be a suitable replacement for `useLevelLabels: true`:

```javascript
    formatters: {
      level: (label) => {
        return { level: label };
      },
    },
```
