### ISSUE TITLE
Clarify documentation on `msg` and `message`

### ISSUE THREAD

**Issue by niftylettuce** [pinojs/pino#854]
If you pass an object to pino with a `message` property, then a `msg` property on the pino output is not created, but a `message` property will exist on the log.  However if you pass simply a string to pino, then a `msg` property is created.  I think that the property `msg` should be renamed to `message` in order to keep it `1:1`.  If you agree, then this would need a major semver bump.

**Comment by niftylettuce** [comment]
My example usage that works (note I have the one line commented out in order for it to be in parity with single arg string usage):

```js
const pino = require('pino');
const { Signale } = require('signale');

const env = require('./env');

module.exports = {
  showStack: env.SHOW_STACK,
  showMeta: env.SHOW_META,
  name: env.APP_NAME,
  level: 'debug',
  capture: false,
  logger:
    env.NODE_ENV === 'production'
      ? pino({
          customLevels: {
            log: 30
          },
          hooks: {
            // pino expects (meta, message) similar to bunyan
            // so we have to flip the arguments per options
            // <https://github.com/pinojs/pino/blob/master/docs/api.md#logmethod>
            logMethod(inputArgs, method) {
              return method.call(this, {
                // <https://github.com/pinojs/pino/issues/854>
                // message: inputArgs[0],
                msg: inputArgs[0],
                meta: inputArgs[1]
              });
            }
          }
        })
      : new Signale()
};
```

This is per my work with [CabinJS](https://cabinjs.com) where we recommend to use pino as the pluggable logger in production (e.g. vs [Signale](https://github.com/klaussinani/signale) in dev).

**Comment by niftylettuce** [comment]
Closing as I highly doubt the `msg` property would get changed to `message`.

**Comment by jsumners** [comment]
Please see http://getpino.io/#/docs/api?id=messagekey-string
