### ISSUE TITLE
What's the best way to pipe a part of log to stdout?

### ISSUE THREAD

**Issue by kehvynko** [pinojs/pino#859]
I've looked for a long time and I can't figure out how to do this. I want to write all logs with metadata to a log file and also output the log's message field to stdout. Does anyone have an example of how to do this? 

I've tried using pino-multi-stream but I ran into issues with custom level labels and printing format for stdout.

**Comment by mcollina** [comment]
pino-multi-stream should enable all of this on the base case. I’m not sure which problem you are facing with custom levels.

**Comment by kehvynko** [comment]
Is there a way to write different things for multi stream? I want to prettify and only print one part of the log to stdout while writing the entire log to file.

**Comment by mcollina** [comment]
You’d need to prettify things yourself. A stream is essentially a node stream, so you can parse the line and do what you want with it.

**Comment by davidmarkclements** [comment]
node app.js | tee file.log | grep level | pino-pretty
