### ISSUE TITLE
Error: sonic boom is not ready yet

### ISSUE THREAD

**Issue by kaeyon** [pinojs/pino#871]
my minimal code to reproduce the error:

```javascript
const pino = require("pino");
const fs = require("fs");
const logger = pino(
  pino.destination({
    dest: "./my-log.txt",
    // fd: fs.openSync("./my-log.txt",'a'),
  })
);

process.on("uncaughtException", (err) => {
  // handle some error
  pino.final(logger, (err, finalLogger) => {
    finalLogger.error(err, "uncaughtException");
    // process.exit(1);
  })(err);
});

logger.info("app start");
throw new Error("some err happened")
```

then i get the 'sonic boom is not ready yet' error

from the stack info,I find it could be fixed by adding a tryCatch

```javascript
// tools.js
const finalLogger = new Proxy(logger, {
  get: (logger, key) => {
    if (key in logger.levels.values) {
      return (...args) => {
        logger[key](...args)
        try {                          // +
          stream.flushSync()
        } catch (error) {              // +
            // console.log(error);     // +
        }                              // +
      }
    }
    return logger[key]
  }
})
```

After checking the code sonic-boom,I found that it's the underlying asynchronous function `fs.open` that cause the problem.
So then I figured out using `fd` option instead of `dest` in `pino.destination` function should bypass the problem.
As commented in the first code block, `fd` option could be fetched by using `fs.openSync`

**Comment by mcollina** [comment]
I think we should be using `fs.open()` or `fs.openSync()` based on the value of the `sync` option. Would you like to send a PR?

**Comment by kaeyon** [comment]
The `fs.open()` is used in the dependent module `sonic-boom`. I could think of two possible ways to fix:
1.If `sync` option is true, transfer dest to fd as fetched by fs.openSync() in module `pino`.
2.As `fs.open()` is called in `sonic-boom`, fix it there according to `sync` option.

Fix No.1 might be a bit improper if module `sonic-boom` changes its behavior in the future.
Which way do you recommend? @mcollina

**Comment by mcollina** [comment]
`sync` is an option of sonic-boom. Let's send a PR to sonic-boom instead, I'll review it asap.
