### ISSUE TITLE
Option for logging just the message (not json)

### ISSUE THREAD

**Issue by hypexr** [pinojs/pino#873]
Logging the message as JSON is not idea for my production environment.  My logs go to AWS cloudwatch and the "msg" section doesn't get formatted as prettified JSON in the cloudwatch console.  I can use the pino-pretty, but it states that it should not be used for production environments.

It would be ideal if I could specify that it should just log the message and not the JSON with the extra information or if pino-pretty was suitable for production environments.

**Comment by jsumners** [comment]
Pino is an ndjson logger. If you just want to log a string to the console, you might as well just use `console.log`.

**Comment by davidmarkclements** [comment]
@hypexr you can use pino-toke to implement whatever format you like 

Closing
