### ISSUE TITLE
Including `msg` in object and string leads to silent data loss

### ISSUE THREAD

**Issue by markstos** [pinojs/pino#874]
To reproduce:

```
const pino = require('pino')();
pino.info({"msg":"OBJ"},"STRING")
```

The result is that "STRING" is logged and "OBJ" is silently discarded.

This could happen when you use `pino.info(obj)` on an object that happens to have a `msg` property.

The recommended fix when `msg` appears in the object and the string is to throw an error. The current behavior is silent data loss.

There's nothing worse than going to check your logs for some critical detail about a past event only to find it was silently discarded by your logging library and you can't retroactively fix it. If you've got an object that contains a msg property that you want to log, instead of:

    log.info(obj)

You can do:

    log.info({obj}).

The error thrown for the duplicate `msg` case could explain that.

**Comment by mcollina** [comment]
Unfortunately this contradicts one of the key principles of pino (and likely logging in general): loggers should not throw and do their best given the circumstances. Having a logger throw could make it hide a bad situation.

**Comment by jsumners** [comment]
FWIW, this is documented:

https://github.com/pinojs/pino/blob/613d700fc2b77768bbbc84095a5cc28fb745b10d/docs/api.md#message-string
> The `message` parameter takes precedence over the `mergedObject`. That is, if a `mergedObject` contains a `msg` property, and a `message` parameter is supplied in addition, the `msg` property in the output log will be the value of the `message` parameter not the value of the `msg` property on the `mergedObject`.

I agree with @mcollina. The logger should not ever throw errors. If it did, every log statement across a whole codebase will need to be wrapped in a `try/catch`. That goes against the purpose of a logger: to be a solid library that a developer can rely on to write logs as quickly as possible.

I also agree that this caveat is buried deep in our documentation. We seem to have dropped our "caveats" section that would surface this in a more visible manner. I would not mind seeing a PR that adds such a section back to the top-level readme. It should include this caveat and the fact that duplicate keys will clobber each other.

**Comment by markstos** [comment]
Thanks for the replies.

I distinguish between coding errors and unexpected runtime failures.

A syntax error or violating an API is a coding error. I want those to fail fast and noisily so I can catch the error during development. No need for a try/catch-- let the app crash so I can fix it and move in.

Even with a philosophy of "don't throw", this is still likely a coding-error situation and one the developer would prefer to be notified about instead of silent data loss. There are some options to do that: 

 1. Inject a "warning" log or even "error" log into the stream that explains the mistake and also includes the log that would have been dropped. 
  2. Append the dropped "msg" to the retained message so it's not lost. 
  3. Rename the `msg` key that would be dropped to `originalMsg`.

**Comment by jsumners** [comment]
You are welcome to wrap Pino for your specific needs. We even provide a hook in v6 that will aid you -- https://github.com/pinojs/pino/blob/613d700fc2b77768bbbc84095a5cc28fb745b10d/docs/api.md#logmethod

**Comment by mcollina** [comment]
> A syntax error or violating an API is a coding error. I want those to fail fast and noisily so I can catch the error during development. No need for a try/catch-- let the app crash so I can fix it and move in.

Unfortunately a lot of developers do not test the error paths of their code or reach 100% code coverage. As a result, a log line might suffer from this problem in production.

> Rename the `msg` key that would be dropped to `originalMsg`.

I guess this won't be too breaking or cause many issues. If you'd like to send a PR for this, go ahead. We'll be happy to land as long as it does not regress the benchmarks.

**Comment by markstos** [comment]
The related PR was reverted, but for others who might end up here looking to solve the same problem, I'm noting that the same goal of avoiding data loss when `msg` values conflict can be met by using the `nestedKey` config value. This puts all the logged object keys in their own namespace: 

https://github.com/pinojs/pino/blob/master/docs/api.md#nestedkey-string
