### ISSUE TITLE
Intercept console logging

### ISSUE THREAD

**Issue by ncjones** [pinojs/pino#877]
Sometimes third-party libraries log directly via the console API. Pino should provide a simple way to reliably redirect all such logging via a Pino logger. Ideally the console method invoked would map to an appropriate log level, the console method name and all its arguments would be logged and error objects would be handled appropriately.

For example, `console.error('hello')` would result in a Pino log entry like:

```json
{"level":50, "time": 1594766781550, "msg": "hello", "consoleMethod": "error" }
```

Enabling interception could be exposed as a logger option like `logger = pino({ interceptConsoleLogging: true })` or perhaps as a static like `pino.interceptConsoleLogging(logger)`.

**Comment by jsumners** [comment]
I am a big 👎 on patching objects we do not own as a first-class feature.

You should be able to do this in your own application without needing Pino itself to do it. Something like:

**index.js**
```
const log = require('pino')
console.log = log.info.bind(log)
console.error = log.error.bind(log)
```

**Comment by davidmarkclements** [comment]
I agree with James - however feel free to create a repo (pino-console) that does this, and we'll review and add to our org if you want
