### ISSUE TITLE
How to use with ES6 import

### ISSUE THREAD

**Issue by PlkMarudny** [pinojs/pino#879]
Hi,

`const logger = require('pino')();`

How to use it with "import" syntax (it will be transpiled using Rollup)?

`import pino from "pino";
const logger = pino();` 

seems not to work.

**Comment by mcollina** [comment]
What error are you getting?
Is this for server-side or the browser support?

**Comment by KatBillington** [comment]
import * as pino from 'pino';
const logger = pino();

**Comment by PlkMarudny** [comment]
This works, thank you very much

**Comment by jasonswearingen** [comment]
> 
> 
> import * as pino from 'pino';
> const logger = pino();

doesn't work with typescript (using the ```@types/pino``` package)   but this does:

```typescript
import pino from "pino"
const logger = pino()
```
