### ISSUE TITLE
Properly handling the 'nestedKey' option

### ISSUE THREAD

**Issue by mihai1voicescu** [pinojs/pino#883]
Let me start by congratulating you guys on this awesome project and by saying I have read #872, #771 and #792 and the docs available [here](https://github.com/pinojs/pino/blob/master/docs/api.md#nestedkey-string).

Personally what I understand from the docs (and what I would expect to happen) is that the serializers will still receive the original object, not the one after the 'nestedKey' transformation (as the base is static, the dynamic part is the passed object and the serializers register only on root level properties, making the serializers register feature pointless when used with 'nestedKey'). But this is my opinion and is subject to interpretation.

However, activating the 'nestedKey' option breaks the standard serialization of errors (because the detection fails) which is a bug (standard options should not break each other).

The problem seems to be that the passed object is transformed [here](https://github.com/pinojs/pino/blob/83d80f63888aa0b68479d460706644c58257131c/lib/tools.js#L47) and afterwards is checked for it's type [here](https://github.com/pinojs/pino/blob/83d80f63888aa0b68479d460706644c58257131c/lib/proto.js#L144) effectively transforming all Errors into plain objects so the detection is never true.

I think it would be a good idea to do the transformation after the check.

If you guys agree I would be happy to make a PR.

**Comment by mcollina** [comment]
Sure, go ahead with the PR.

**Comment by mihai1voicescu** [comment]
I seem to be having problems with running the http tests on my local machine. The rest seem to succeed on my local machine.

They just time out and do nothing... Any tips?

**Comment by mihai1voicescu** [comment]
Solved in #885
