### ISSUE TITLE
Redacting hostname

### ISSUE THREAD

**Issue by brentkirkland** [pinojs/pino#886]
I am trying redact hostname, but am running into some weird behavior

```
const logger = pino({
  redact: {
    paths: ['hostname'],
    remove: true,
  },
});
```

```
logger.info('empty') // this will remove hostname
logger.info({ key: 1 }, 'data') // this will not remove hostname
```

Is there any way to remove hostname when providing a mergingObject?

Thank you!

**Comment by mcollina** [comment]
You need to configure a new `base` for your logger, see https://github.com/pinojs/pino/blob/master/docs/api.md#base-object.

**Comment by brentkirkland** [comment]
@mcollina 

Same issue applies
```
const logger = pino({
  base: null,
});
```

```
logger.info('empty') // hostname will be missing
logger.info({ key: 1 }, 'data') // hostname will still exist
```

Something I am missing?

**Comment by brentkirkland** [comment]
![image](https://user-images.githubusercontent.com/5922765/89828724-49a81a00-db0e-11ea-8325-044a86940cf9.png)
