### ISSUE TITLE
Transports and multiple node instances

### ISSUE THREAD

**Issue by quetzalsly** [pinojs/pino#887]
I am a bit confused on how piping works with my case.

I have a project with multiple commands (using commander.js), most of these commands are single run -> do some work -> end.
One of the commands however launches an endless 'for' loop and a server, so this command never really exits.
My plan was to have 2 node cmd shells open on a VPS, one for managing the single use commands and one just running the server command.

How do I go about having all of these reliably log to say google cloud logging?

`node foo | pino-stackdriver --project bar --credentials /credentials.json`

Does the pipe operator pipe only on program end or contiously?
Can multiple node cmd shells pipe to the same transport?
What if the transport is pretty-print for file based access?
What if something crashes somewhere? will any logs be lost?

**Comment by mcollina** [comment]
> Does the pipe operator pipe only on program end or contiously?

Continuously, read more about it at https://swcarpentry.github.io/shell-novice/04-pipefilter/index.html

> Can multiple node cmd shells pipe to the same transport?

Not easily

> What if the transport is pretty-print for file based access?

I do not recommend running this in production. Run it in case a human needs to read a file.

> What if something crashes somewhere? will any logs be lost?

Undelivered/inflight logs will be lost any of the commands crash. You can redirect it to a file first to avoid this problem

**Comment by quetzalsly** [comment]
Thanks a lot for the answers, so what is a way for me to run multiple node cmd shells in production without pretty print? Is it possible to somehow duplicate the instance of the transport? what about some kind of queue where everything pushes into a single transport and it sends off the messages to google cloud logging one by one? Never worked with this kind of project with javascript before so would really appreciate some tips thanks.

**Comment by mcollina** [comment]
https://www.npmjs.com/package/pino-multi-stream might do the trick if I understand your problem correctly. However I would recommend to keep things simple and just send everything to gcp.

**Comment by quetzalsly** [comment]
My problem is more like if I have 2 node shells both trying to write to the cloud or to local files, I don't need a single node shell to output to multiple streams. I am just not sure how all of it works, does each node shell launch its own transport process?

**Comment by jsumners** [comment]
This sounds like a system design issue which is outside of the scope of this project. However, we would generally recommend that each process be its own system.

**Comment by quetzalsly** [comment]
Right ok thanks, I will continue experimenting.
