### ISSUE TITLE
Set the repository's website setting to use https

### ISSUE THREAD

**Issue by gr2m** [pinojs/pino#888]
It currently points to http://getpino.io/, and the website does not automatically redirect to https

<img width="253" alt="image" src="https://user-images.githubusercontent.com/39992/89830733-89bccc00-db11-11ea-9e57-687a55110720.png">

Just wanted to let you know about it, you can fix it in https://github.com/pinojs/pino/settings

Thanks for the great tool!

**Comment by mcollina** [comment]
Done, good spot!
