### ISSUE TITLE
Error logs with `msg` loose the `message` property of the error potentially loosing valuable information

### ISSUE THREAD

**Issue by mihai1voicescu** [pinojs/pino#889]
To replicate:

```
const p = require('./pino')

const logger = p()

logger.error(new Error('message')) // logs {"level":50,"time":1597149182151,...,"type":"Error","msg":"message"}
logger.error(new Error('message'), 'msg message') // logs {"level":50,"time":1597149182152,...,"type":"Error","msg":"msg message"}
```

As you can see the seccond message does not log the `Error#message`.

This is because [this Object.assign](https://github.com/pinojs/pino/blob/83d80f63888aa0b68479d460706644c58257131c/lib/proto.js#L150) will not copy the property from the Error.

Another thing I find strange is that when receving an Error as the `obj` (first argument) this is processed differently then if sending a `obj` with the format `{err: Error}`. This means the err serializer will work only on the latter no? If so is this OK?

**Comment by mcollina** [comment]
See http://getpino.io/#/docs/help?id=avoid-message-conflict. My generic recommendation would be to use `{ err }`.

**Comment by mihai1voicescu** [comment]
This does not relate to the shadowing (duplication) of a property. The `message` property is taken from the `obj` if it's type is Error and placed in the `msg` property, but if `msg` is present it's ignored (it doesn't event appear multiple times in the log as is the behavior with other properties...).

There is a detection and a special flow for Error, why not transform it to an {err: Error} automatically so the 2 flows meet?

Are you sure this is the desired behavior?
