### ISSUE TITLE
怎么输出对象？

### ISSUE THREAD

**Issue by magdsnail** [pinojs/pino#891]
eg:
const pino = require('pino');
const logger = pino({
  name: 'test',
level: 'debug'
});

logger.info({index: 1, name: 'test'});
{"level":30,"time":1597242669489,"pid":44395,"name":"a","index":1,"name":"test"}

应该为
{"level":30,"time":1597242669489,"pid":44395,"hostname":"wangkjdeMacBook-Pro.local","name":"a",
{"index":1,"name":"test"}
}

**Comment by mcollina** [comment]
Please open a new issue in English.

**Comment by magdsnail** [comment]
> 请用英语打开新一期。

ok

**Comment by magdsnail** [comment]
> Please open a new issue in English.

ok  thank you
