### ISSUE TITLE
Provide support for lazy evaluation

### ISSUE THREAD

**Issue by matthewadams** [pinojs/pino#900]
Similar to https://deno.land/std@0.66.0/log#lazy-log-evaluation & https://www.npmjs.com/package/@northscaler/bunyaner.

In the event that there is an expensive calculation performed in order to log something, and the current log level is such that the log statement wouldn't result in any output, allow the user to pass a function to the log level method.  The function would only be evaluated if the log level method would produce output given the current log level.  Any log level method that is given a function should return `undefined`.

Example:
```
const log = pino()()
log.debug(() => expensiveOperation()) // function only evaluated if current level is at or below debug
```

NOTE: This feature should _not_ be used with the proposed [inline logging feature](https://github.com/pinojs/pino/issues/899).  In other words, once inline logging is supported, don't do this:
```
// BAD -- DON'T DO THIS
const log = pino()()
const it = log.debug(() => expensiveOperation()) // function is not evaluated if current level is at or below debug, so you'd get `undefined`
```

**Comment by xamgore** [comment]
One could write a helper function like

```ts
logger.debugLazy = (expensiveComputation: () => unknown) => {
  if (log.isLogLevelEnabled('debug')) log.debug(expensiveComputation())
}

// types.d.ts
interface Pino {
  debugLazy: (expensiveComputation: () => unknown) => void
}
```

But that would be problematic with child loggers, wouldn't it? As I see, there is no way to patch the [Pino's prototype](https://github.com/pinojs/pino/blob/e616c1c7fa8cce2f7071ed7ba14cf68f2997f4b5/lib/proto.js#L47) from the end user's side and call `isLogLevelEnabled`.

**Comment by jsumners** [comment]
It's easy to wrap a Pino instance. There's no need to mess with its prototype.

**Comment by Fdawgs** [comment]
Closing due to lack of support from maintainers.
