### ISSUE TITLE
Using Pino with Express, memory leak

### ISSUE THREAD

**Issue by cvburgess** [pinojs/pino#901]
Hey there! We switched to Pino from Winston and took advantage of the elasticsearch plugin.

Overall the ecosystem and tool have been great but new relic alerted us to a memory leak that we traced back to Pino.

At first we disabled only the ES plugin and saw no difference.

Disabling Pino completely ( we left the import intact but never called the pino fns ) resulted in no more leak.

Is this a known issue? We handle a massive amount of requests so we noticed this happen quite quicly in our production environment but have had no issues in our low-traffic QA environment.

Here is a snippet, the usage is pretty standard ( a lot of code is omitted from other serivces like sentry and new relic that are also configured in this file ):

```js
const pino = require("pino");
const pinoHttp = require("pino-http");
const pinoElastic = require("pino-elasticsearch");
const ecsFormat = require("@elastic/ecs-pino-format")();

const {
  DISABLE_LOGGING,
  ES_US_HOST,
  ES_US_PORT = 9200,
  ES_US_USERNAME,
  ES_US_PASSWORD,
  ES_US_VERSION = 7,
} = process.env;

let logger;
const monitoringMiddleware = [];

if (!DISABLE_LOGGING) {
  const autoLogging = {
    ignorePaths: ["/admin/queues/queues/"],
    getPath(req) {
      return req.url.replace(/\?.*/, "");
    },
  };

  if (ES_US_HOST) {
    const node = `http${
      ES_US_USE_SSL ? "s" : ""
    }://${ES_US_HOST}:${ES_US_PORT}`;
    const streamToElastic = pinoElastic({
      index: ".logs-integration-service-%{DATE}",
      node,
      auth: {
        username: ES_US_USERNAME,
        password: ES_US_PASSWORD,
      },
      "es-version": parseInt(ES_US_VERSION),
    });

    logger = pino(
      {
        ...ecsFormat,
        formatters: {
          ...ecsFormat.formatters,
          log(obj) {
            const log = ecsFormat.formatters.log(obj);
            log.app = npm_package_name;
            return log;
          },
        },
        timestamp: () => `,"timestamp":"${new Date().toISOString()}"`,

        prettyPrint: false,
      },
      streamToElastic
    );

    const elasticLogger = pinoHttp({
      logger,
      autoLogging,
      customSuccessMessage(res) {
        const { method, originalUrl } = res?.req ?? {};
        return `${method} ${originalUrl} ${res.statusCode}`;
      },
      reqCustomProps: {
        log: {
          level: "info",
          logger: "incoming-request",
        },
      },
    });

    monitoringMiddleware.push(elasticLogger);
  } else {
    logger = pino({ prettyPrint: true });

    const httpLogger = pinoHttp({
      logger,
      autoLogging,
    });

    monitoringMiddleware.push(httpLogger);
  }
}

app.use(monitoringMiddleware);
```

Versions in package.json:

```json
{
    "@elastic/ecs-pino-format": "^0.1.0",
    "express-pino-logger": "^5.0.0",
    "express": "^4.16.4",
    "pino": "^6.4.0",
    "pino-elasticsearch": "^5.2.0",
    "pino-http": "^5.2.0",
    "pino-pretty": "^4.0.3",
}
```

Below is a graph from New Relic with the deploys marked.

![screen_shot_2020-09-01_at_15 55 19](https://user-images.githubusercontent.com/2141199/91905912-45869c80-ec75-11ea-8175-205509fc241e.png)

**Comment by mcollina** [comment]
Here are a few questions:

1) does the process crash for an out of memory error?
2) prettyPrint: true is not suitable for production usage, why is it set like so?
3) why are you keeping pino-elasticsearch in process? The best option is to use a separate process.

My 2 cents are on pino-elasticsearch accumulating a lot of log lines while delivering, you might look into enabling batching.

**Comment by cvburgess** [comment]
Wow thanks for a quick reply!

1. Not that I'm aware of; eventually the box becomes unresponsive and we just nuke and reboot the cluster
2. Will disable, didn't know that, sorry
3. Is there an example somewhere we can reference? that sounds like the right move

Of note, this happens even without pino-elasticsearch running, and pino logging to console.

**Comment by cvburgess** [comment]
Update: turning off prettyPrint and ES seemes to have resolved the issue so i think youre correct!

Thank you so much.

Any advice about moving pino off the main thread?

**Comment by davidmarkclements** [comment]
@cvburgess see https://github.com/pinojs/pino/pull/614

**Comment by cvburgess** [comment]
Thanks @davidmarkclements
