### ISSUE TITLE
"timestamp" option is ignored in Browser environment

### ISSUE THREAD

**Issue by acro5piano** [pinojs/pino#903]
Hi, thank you for the great library.

I've run the following code.

I expected time should become ISO String, but actually the output is still epochTime.

```typescript
import pino from 'pino'

const logger = pino({
  timestamp: () => `,"time":"${new Date(Date.now()).toISOString()}"`,
  browser: {
    asObject: true,
  },
})

logger.info('Running app')
```

![image](https://user-images.githubusercontent.com/10719495/92297012-a95edd00-ef75-11ea-8056-e0242bed7eb3.png)

is this intensional? Thanks in advance.

**Comment by mcollina** [comment]
Yes, this is intentional. In the browser some of the internals are different :( and we cannot have the same features. We might want to add something analog to this. Would you like to send a PR?

**Comment by acro5piano** [comment]
@mcollina 

Thanks for the reply. The code is located here, right? I'll try to work on it :)

https://github.com/pinojs/pino/blob/master/browser.js#L211

**Comment by mcollina** [comment]
Yes

**Comment by dariolongo** [comment]
Hi,
First of all, thanks for Pino!

Hope this can help others...

Using the timestamp function and browser.asObject true:
```js
timestamp: () => `,"time":"${new Date(Date.now()).toISOString()}"`,
browser: {
  asObject: true
}
```
it's ok on stdout:
```node
{"level":30,"time":"2021-11-03T10:59:59.348Z","msg":"Running app"}
```

but it's not totally correct in the browser:
<img width="558" alt="Schermata 2021-11-03 alle 12 02 08" src="https://user-images.githubusercontent.com/16292050/140049186-77c7eae2-b42e-4d62-975e-59f47294296e.png">

Using this:
```js
timestamp: pino.stdTimeFunctions.isoTime,
```
work well for both!

Bey
