### ISSUE TITLE
Access log level in logMethod hook

### ISSUE THREAD

**Issue by gzaripov** [pinojs/pino#909]
I want to collect logs number statistics and I want also to categorize them by levels.
For now I cant get level from logMethod hook, so I cant collect info about method types, lets add it to logMethod hook:

```javascript
const hooks = {
  logMethod (inputArgs, method, { level }) {
    metrics.registerEvent(`log_${level}`);
    return method.apply(this, inputArgs)
  }
}
```

**Comment by mcollina** [comment]
It is not needed as you can get it with https://github.com/pinojs/pino/blob/83d80f63888aa0b68479d460706644c58257131c/docs/api.md#levels.

```js
logger.levels.values[method]
```

**Comment by gzaripov** [comment]
@mcollina could you provide exact solution? I try to call `this.levels.values[method]` inside function and I get undefined.
Here is reproduction https://codesandbox.io/s/funny-shannon-e8elg?file=/src/start.js

**Comment by mcollina** [comment]
Actually I was wrong, that's not feasible right now.

What's your use case exactly?

**Comment by jsumners** [comment]
Support would need to be added at: 

https://github.com/pinojs/pino/blob/95856d1198a4067f9916a2b7e636b71f58bebeb2/lib/tools.js#L30-L35

**Comment by gzaripov** [comment]
> What's your use case exactly?

I want to provide more info about what kind of logs we are logging in node server. It will help us to track new problems when error logs count was increased. For now I can track only total amount of logs.

**Comment by gzaripov** [comment]
I suggest this solution:
```
function genLog (level, hook) {
  if (!hook) return LOG

  return function hookWrappedLog (...args) {
    hook.call(this, args, LOG, { level })
  }
```

**Comment by mcollina** [comment]
Please avoid creating a new object, e.g. `level` not `{ level }`.

**Comment by mojavelinux** [comment]
FYI, this appears to have been resolved but never closed.
