### ISSUE TITLE
Don't log props over x bytes

### ISSUE THREAD

**Issue by wjabbour** [pinojs/pino#911]
Hi Pino Team!

I looked in docs a bit but couldn't verify if you provided this feature. Is there a feature to configure Pino such that it won't log properties over a certain byteLength? My team would like to switch to Pino but we have a need to avoid logging properties over 3k bytes, say. Could something like this be done if it isn't already?

**Comment by jsumners** [comment]
Pino does not inspect data in this manner. That would be up to the user to avoid logging things that exceed size requirements. You may be able to solve this with the `logMethod` hook, however.

**Comment by wjabbour** [comment]
Thanks for the quick reply! I'll try out `logMethod` then, thanks.
