### ISSUE TITLE
method to track time difference between calls

### ISSUE THREAD

**Issue by basaran** [pinojs/pino#912]
Hello,

Is there anyway with the current implementation to track difference between each call to pino log?

**Comment by mcollina** [comment]
This is not implemented. You can do it using the formatters, or maybe send a PR to implement it in pino-pretty (if you need it only for development).

**Comment by jsumners** [comment]
I would say this is outside of Pino's scope. You can use Node's native perf api to do this.

**Comment by basaran** [comment]
Thank you, I managed to add the logic into pino but like you said it's probably better to incorporate it around pino so it doesn't impact the performance.

```javascript
function w() {
    pino.info( "logging" );
    setTimeout( () => {
        w();
    }, Math.random() * 1000 );
}
```

![image](https://user-images.githubusercontent.com/30809170/93688057-f2905000-fa90-11ea-9a80-4e570fcfa016.png)

My intention is to keep this for permanent logging to Loki, Elastic etc. I will look into the performance api, thank you for the direction.

**Comment by jsumners** [comment]
See https://medium.com/the-node-js-collection/timing-is-everything-6d43fc9fd416

**Comment by basaran** [comment]
Arigato : )
