### ISSUE TITLE
Cannot use namespace 'SonicBoom' as a type.

### ISSUE THREAD

**Issue by SteeleDesmond** [pinojs/pino#914]
After migrating the base image of my dockerfile it started failing with this error. This could be an issue on my end but I thought I'd make an issue here to see if anyone has had this issue before or might know a solution. My base image went from using node 12.18.2 to 12.18.3. 

```
Install-Agent-API@2.5.0 build /app/build
> tsc
node_modules/@types/pino/index.d.ts(194,122): error TS2709: Cannot use namespace 'SonicBoom' as a type.
node_modules/@types/pino/index.d.ts(202,57): error TS2709: Cannot use namespace 'SonicBoom' as a type.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! CSPLab-Install-Agent-API@2.5.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the CSPLab-Install-Agent-API@2.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-22T23_02_02_618Z-debug.log
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 2
```

I have tried doing a clean install and updating my packages, @types/pino to ^6.3.1 and pino to ^6.6.1. I also tried installing the sonic-boom package. Sorry if this is a newbie issue, any help is appreciated. Thanks!

**Comment by mcollina** [comment]
Fixed in sonic-boom@1.3.0.
