### ISSUE TITLE
Please Document Redact Path as Case Sensitive

### ISSUE THREAD

**Issue by shellscape** [pinojs/pino#915]
While there are wider issues with `fast-redact` https://github.com/davidmarkclements/fast-redact/issues/28, I believe it would be advantageous to the userbase of pino to document clearly and boldly that `redact` paths are case-sensitive, perhaps on this document https://github.com/pinojs/pino/blob/master/docs/redaction.md.

**Comment by mcollina** [comment]
Sure, would you like to send a PR?

**Comment by shellscape** [comment]
I've done my duty by reporting it, I think you all can handle a docs addition and will know best where to put it. (When I can find the time between babies to contribute, I'm pretty caught up maintaining the Rollup plugins repo and [a host of other projects I maintain](https://github.com/shellscape?tab=repositories). I get the _why_ for asking, but I tend not to ask that from prolific oss contributors assuming that if they had the time, they'd have already opened one)

I'll be asking from work later today if I can be granted the time to contribute a fix for case insensitivity for https://github.com/davidmarkclements/fast-redact/issues/28.

**Comment by mcollina** [comment]
That would truly be fantastic.

**Comment by davidmarkclements** [comment]
closed by #915
