### ISSUE TITLE
how to access all log levels at all times?

### ISSUE THREAD

**Issue by RoniFinTech** [pinojs/pino#918]
This looks like a very limiting thing that if I can log log.info(), I can't log log.debug unless I change the log level under 'child'.
Am I missing anything? how do I access all log levels at all times?
For example, if I have 1 log object and I want to log 'info', 'debug' and 'error' without constantly changing the level in the child options.

**Comment by mcollina** [comment]
It seems we are laking a fair bit of documentation for how levels works. All string levels are mapped to a numeric value, in a way that if you set the level to `'debug'`, all levels "above" it are printed.

**Comment by RoniFinTech** [comment]
Ahhh it makes sense to me... thanks for the explanation...
