### ISSUE TITLE
Redacting should preserve original object when the first logger call is precensored

### ISSUE THREAD

**Issue by adrianolek** [pinojs/pino#919]
When the logger is configured with `redact` and the first log write has the redacted property value equal `"[Redacted]"` then subsequent log write calls will not restore the redacted property in the original object.

I've added a test case, please have a look:

https://github.com/adrianolek/pino/blob/redact-precensored/test/redact.test.js#L313

Wdyt, is it a bug in pino?

**Comment by mcollina** [comment]
I think it's a bug in fast-redact.

**Comment by adrianolek** [comment]
I'll try to reproduce it in fast-redact then.

**Comment by adrianolek** [comment]
It is in fact a bug in fast-redact. Closing in favor of https://github.com/davidmarkclements/fast-redact/issues/29
