### ISSUE TITLE
fatal() shows warning "pino.final with prettyPrint does not support flushing"

### ISSUE THREAD

**Issue by rijkvanzanten** [pinojs/pino#920]
I've seen the root cause of the warning over here: https://github.com/pinojs/pino-pretty/issues/37 However, I don't think it should show a warning about `pino.final` when using `pino.fatal. I understand that flushing logs isn't a thing when using a prettifier, but it's also a little distracting to see these warnings while in development mode with a prettifier enabled 🤔

**Comment by jsumners** [comment]
That's the whole point of the warning: to inform the user that it isn't supported in the running configuration.

I'd recommend not embedding prettification into the application and instead pipe the process's `stdout` into `pino-pretty` (or other).

**Comment by rijkvanzanten** [comment]
Right, but in the current configuration (dev) I don't care that it's not supported, but I'd still like to use `.fatal()` at the appropriate times 🤔 

> I'd recommend not embedding prettification into the application and instead pipe the process's stdout into pino-pretty (or other).

I generally agree, but for reasons beyond the scope of this issue that's not possible for me

**Comment by mcollina** [comment]
I think you can easily resolve this with:

```js
if (process.env.NODE_ENV !== 'development') {
   pino.final(...)
}
```

**Comment by davidmarkclements** [comment]
this seems to have been addressed
