### ISSUE TITLE
Including a BigInt in the merging object throws an exception

### ISSUE THREAD

**Issue by Mossop** [pinojs/pino#921]
Pino seems unable to handle BigInts. Tested in 6.7.0:

```
> const logger = require('pino')();
> logger.info({ t: 10n }, "Hello");
Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at stringify (/Users/dave/workspace/pixelbin/node_modules/fast-safe-stringify/index.js:14:16)
    at stringify (/Users/dave/workspace/pixelbin/node_modules/pino/lib/tools.js:403:12)
    at Pino.asJson (/Users/dave/workspace/pixelbin/node_modules/pino/lib/tools.js:139:45)
    at Pino.write (/Users/dave/workspace/pixelbin/node_modules/pino/lib/proto.js:165:28)
    at Pino.LOG [as info] (/Users/dave/workspace/pixelbin/node_modules/pino/lib/tools.js:55:21)
```

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/96325519-70933880-0ff6-11eb-9ac7-ded55885acb6.png)

**Comment by kf6kjg** [comment]
@jsumners Yes, this and related issues are due to JSON.stringify being purposefully ignorant on how to serialize these special types and BigInt not specifying a toJSON method - and for arguably good reasons.  However I'm not seeing a nice way of informing Pino how to serialize these: JSON.stringify I can send a _replacers_ function to specify how to solve the problem, but there's no corresponding interface in Pino.

I could use the `logMethod` hook, but then I have to manually recurse and replace.  Yuck.

**Comment by davidmarkclements** [comment]
this is problematic across the board I think. 

How would one expect a big int to be serialized, as a normal Number (but then you'll lose resolution), as a string but then you have to know that it's a big int when deserializing. As an array where each element represents a 32bit piece of the big int? 

E.g. if you serialize a Buffer object you get `{type: 'buffer', data: []}`

This makes me think we can do` {type: 'bigint', data: []}`

But you still have to then convert it after parsing (same as buffer objects). 

Really, we need a universal JSON format for BigInt - does anything like that exist?

**Comment by kf6kjg** [comment]
@davidmarkclements  Nope. Hence each application's dev team needs to decide for itself how to serialize these types and add it to their documentation.  Hence I'm not looking for Pino to figure it out, but to provide an interface that allows me to decide how I want it done - a la JSON.stringify's _replacers_ field.

**Comment by jsumners** [comment]
Sounds to me like you should provide a custom serializer -- https://getpino.io#/docs/api?id=serializers-object

**Comment by davidmarkclements** [comment]
what @jsumners suggests works if you always use the same key name for a bigint

if you need to check by type, you'll need to use a formatter https://getpino.io/#/docs/api?id=formatters-object

This is a really sucky situation though. The JSON spec needs to be updated at this point for ArrayBuffers and BigInt imo.

**Comment by davidmarkclements** [comment]
what we could do is add another `hooks` option (currently there's only logMethod). We could all it bigInt with a default way to handle bigints that can be overridden.

**Comment by davidmarkclements** [comment]
the implementation would be *hard* to do without perf loss. 

We'd have to use an approach similar to fast-redact (or pino-noir) (or even hook it into fast-redact somehow which.. yeah that's architecturally terrible) and then we'd have to make it consistent with interpolation as well (which would be in quick-format-unescaped).

**Comment by kf6kjg** [comment]
@jsumners as @davidmarkclements noted a serailizer won't work for my general case: the keys are not, and cannot be, known ahead of time.

@davidmarkclements a formatter could work but has the same basic problem as the hook workaround I proposed: I have to recurse the tree myself instead of just tapping into the recursion that stringify is already doing.

Any clean way to tap into _replacers_ would be a nice way to solve this.

**Comment by davidmarkclements** [comment]
here's an idea that's horrible: what if you overload `JSON.stringify` - if you're comitted to serializing bigints the same way across the project create a module with something like:

```js
'use strict'
const { stringify } = JSON
const replacer = (k, v) => {
  if (typeof v === 'bigint') return {type: 'bigint', data: convertBigIntToArray(v)}
  return v
}
JSON.stringify = (val, replacer, space) => {
  return stringify(val, wrapReplacer(replacer), space)
}
```


Then preload it

```sh
node -r the-custom-serializer app.js
```

**Comment by kf6kjg** [comment]
That's... indeed horrible. lol :P  But yes, that could work too - adding to my bag of occasionally useful hacks!

**Comment by kf6kjg** [comment]
Here's the hack I just finished, and yes the logMethod hook wasn't the right spot so I switched to the log formatter.

```typescript
import Pino from "pino";

function replacer<T>(entry: T): T | string;
function replacer<T>(entry: T[]): (T | string)[];
function replacer<T>(entry: T | T[]): T | string | (T | string)[] {
	switch (typeof entry) {
		case "bigint":
			return entry.toString(); // Works for me for now. There are alternatives.
		case "object":
			if (Array.isArray(entry)) {
				return entry.map((e): T | string => replacer(e));
			} else if (entry) {
				return Object.entries(entry).reduce(
					(result, [key, value]) => ({ ...result, [key]: replacer(value) }),
					{} as T
				);
			}
	}
	return entry;
}

export const Logger = Pino({
	formatters: {
		log: replacer,
	},
});
```

You can see what I mean by having to recurse the data structure myself. I don't know how much of a perf hit that hits me with, but I'm sure it's worse than somehow tapping into the existing recursion done by stringify.

**Comment by jsumners** [comment]
A new hook sounds like a good feature.

**Comment by bhamon** [comment]
I've had the same problem.

As pointed by @kf6kjg, for better performances, the ugly way could be:
```js
BigInt.prototype.toJSON = function() { return this.toString() };
```

But the global prototype poisoning could be harmful.
So I found an alternative way based on that:
```js
const pino = require('pino');
const pinoSymbols = require('pino/lib/symbols');
const log = pino();
log[pinoSymbols.stringifySym] = function(_obj) {
  const original = BigInt.prototype.toJSON;
  BigInt.prototype.toJSON = function() { return this.toString() }; // Change with whatever serialization you want
  const res = JSON.stringify(_obj);
  BigInt.prototype.toJSON = original;
  return res;
}
```

For 10M `log.info({test:{}})` calls on my system:
* Without the patch: 40.090 ms
* With the patch: 42.227 ms

That's a 5% overhead.

**Comment by nicolasburtey** [comment]
the code above is returning this: `Property 'toJSON' does not exist on type 'BigInt'` on nodejs 14

**Comment by davidmarkclements** [comment]
@nicolasburtey are you transpiling code at all?

FWIW I think we need to solve the broader problem as per https://twitter.com/davidmarkclem/status/1357739228436774912?s=20

**Comment by alexey-sh** [comment]
@bhamon @davidmarkclements 
```
log[pino.symbols.stringifySym] = function(_obj) {
  if (typeof _obj === 'bigint') {
     return `${_obj}n`;

  return JSON.stringify(_obj);
}
```

**Comment by bhamon** [comment]
@alexey-sh Your suggestion fails for my use-case (`log.info({obj:{id:112n}})`).

**Comment by alexey-sh** [comment]
@bhamon 
maybe this 😁
```
    log[pino.symbols.stringifySym] = function(_obj) {
      if (typeof _obj === 'bigint') {
        return `${_obj}n`;
      }
      return JSON.stringify(_obj, (key, value) => {
        if (typeof value === 'bigint') {
          return `${value}n`;
        }
        return value;
      });
```

**Comment by bhamon** [comment]
@alexey-sh That's an interesting solution. With your patch there is a 10% overhead for 10M calls, but without the global prototype poisoning. So I'll use this instead.
Thank you :)

**Comment by alexey-sh** [comment]
I think the right solution is to use another logger 😂
for example, [winstonjs/winston](https://github.com/winstonjs/winston) works well with bigint.

Also I've [compared perfomance for my case](https://github.com/alexey-sh/pino-vs-winston) and it seems like pino and winston have almost the same result

![image](https://user-images.githubusercontent.com/1584156/108396609-13b7c100-7228-11eb-89e9-09b74ad5b8e3.png)

**Comment by jsumners** [comment]
As @davidmarkclements said, this needs a larger ecosystem solution:  https://github.com/pinojs/pino/issues/921#issuecomment-776050692

The PR that has been created to address this internally to Pino resulted in unacceptable performance degradation regardless of the presence of a `BigInt` in the data to be logged.

I am locking this discussion for now.
