### ISSUE TITLE
Merge error flows instead of doing a special serialisation handling

### ISSUE THREAD

**Issue by mihai1voicescu** [pinojs/pino#923]
I see you are planning to fix the error serialisation in #896 in the upcoming v7.

I submitted a bug a while ago #889 which addressed the loosing of the `message` property when a `msg` is present. Your recommendation was to use `{ err }`. I asked a question there but never got an answer.

I see in #896 you are detecting the error and running the serialiser manually. Why not just wrap the object in `{ err }` if it is an error and merge the 2 flows?

This will have the following advantages:
* less edge case programming
* `message` property is not lost
* logs with errors will be easily detected (especially in stuff like Elasticsearch)

**Comment by mcollina** [comment]
Would you like to send a follow-up PR to merge the two flows? It sounds like a good idea!

**Comment by mihai1voicescu** [comment]
I would be happy too.

**Comment by mihai1voicescu** [comment]
Solved in #924
