### ISSUE TITLE
pino fails to emit parsable json on large blocks of text

### ISSUE THREAD

**Issue by cdaringe** [pinojs/pino#925]
# Problem

```js
// bug.js
const pino = require("pino");
const logger = pino();
const bigOlString = (c) => Array.from(Array(100)).join(c);

const logme = {
  a: {
    b: {},
    c: Array.from(Array(500)).map((_, i) =>
      bigOlString(String.fromCharCode(128))
    ),
  },
};

logger.info(logme);
//console.log(JSON.stringify(logme));
```

```
$ node bug.js | jq . 
# parse error: Unfinished string at EOF at line 1, column 65536
```

Swap `logger.info(logme)` with `console.log(logme)`, and parseable content is emitted.

> Maybe jq is the problem here

Indeed. Perhaps so. I can't say with certainty. It _is_ technically `jq` that is being _uncool_ parsing something around the 16 bit max mark. But, the fact that it has _no problem_ with console output suggests that whatever pino serializer is being used may be doing something ...undesirable?

**Comment by jsumners** [comment]
Did you write it to a file to determine that it is written correctly?

`node foo.js | tee output.json`

**Comment by mcollina** [comment]
I tried

```bash
node bug.js > out.json
jq . < out.json
```

and it does not exhibit the problem.

However, it looks like `node bug.js | cat - | jq .` has the same problem.

It seems `jq` is not liking how sonic-boom is splitting the data out: https://github.com/mcollina/sonic-boom/blob/1178b1446aef498c76b1cdc4b69d61c794956b71/index.js#L297-L319. I'm inclided to say it's a `jq` problem because the problem show itself through `cat -`.

**Comment by cdaringe** [comment]
What prompted this bug was a real-life usage where at the the 16 bit max mark, two chars (at least as rendered by editor) were dropped. Based on that failure + the above failure, the fact that console _is_ behaving, and that we know sonic boom is doing special processing at a factor of 16, I'd say that sonic-boom is seeming like the most likely candidate. is [this](https://github.com/mcollina/sonic-boom/blob/1178b1446aef498c76b1cdc4b69d61c794956b71/index.js#L302) a lossy line?

**Comment by mcollina** [comment]
What do you mean?

It's totally possible that a char is lost somewhere in the process. I find it weird that it works through different destinations.

Would you like to make some test and send a PR?

**Comment by Fdawgs** [comment]
@cdaringe Did you manage to resolve this?
