### ISSUE TITLE
ES version of modules

### ISSUE THREAD

**Issue by budarin** [pinojs/pino#931]
Could you provide es version of modules with modern syntax with using native spread instead of Object.assign, for an example, please?

**Comment by jsumners** [comment]
Could you please give an example of what you're asking? I really don't understand the request.

**Comment by budarin** [comment]
In the library code, Object. assign is very common, which is quite slow compared to the native spread in recent versions of Node

**Comment by jsumners** [comment]
Can you provide benchmarks to support this assertion?

**Comment by budarin** [comment]
no^ I have not - I heard this in a report at a meetup
am I wrong?

**Comment by jsumners** [comment]
I don't know. I haven't run any benchmarks on this.

**Comment by budarin** [comment]
sorry
