### ISSUE TITLE
How to log custom req object that changes between middlewares?

### ISSUE THREAD

**Issue by no-name420** [pinojs/pino#932]
My problem is that if I mount the ```app.use(logger)``` before I set the data in my custom ```req.user``` object then pine doesn't include the ```req.user``` in the logs, and if I move the middleware that updates the ```req.user``` to run before I mount the logger to express then pine logs the same initial ```req.user``` object in all the logs, which means that if in some middleware I change the ```req.user``` value the logs that comes after the update do not show the new object's value and they log the initial values that were set.

**Expected flow:**
1. In a middleware I add some values to my custom ```req.user``` object
2. I mount the pine logger to express
3. I log some info/errors
4. I change some values in my custom ```req.user``` object
5. I do some additional logging
6. Each of the logs represent the values that ```req.user``` had at the time of logging

**Actual flow:**
1. In a middleware I add some values to my custom ```req.user``` object
2. I mount the pine logger to express
3. I log some info/errors
4. I change some values in my custom ```req.user``` object
5. I do some additional logging
6. All the logs show the initial values that ```req.user``` had and non of the logs represent the changed/updated values

**Comment by mcollina** [comment]
Are you using `pino-http`? You can add the logger _after_ all the properties are being set. You can also do: `req.log = req.log.child({ user })` to create a child logger with the user data.

**Comment by no-name420** [comment]
> Are you using `pino-http`? You can add the logger _after_ all the properties are being set. You can also do: `req.log = req.log.child({ user })` to create a child logger with the user data.

I use ```express-pino-logger```
And I'm having 2 problems with your solution:
1. The automatic log of request completion / failure still doesn't contain that info (which means it will require a lot of messing around with the logs to find the rest of the ```req``` info)
2. Sometimes I change the custom ```req.*``` objects in the different middlewares (for example in one middleware I set the ```req.user``` and in another I set the ```req.redis``` or update/sanitize the ```req.body```, and it's gonna be really annoying to have to also re-apply the ```req.log = req.log.child(...)``` every time I wanna set/update values in my custom ```req.*``` objects.

**Comment by mcollina** [comment]
Everything here was designed so that `req` logging should include _only_ the information about the request - not everything else the user might want to add - conditionally. The `reqId` that is added enable to track all the log lines added for a given request, so you can even just log things on multiple lines.

Your use case is not supported as it would be _extremely slow_ as all the added request details would need to be serialized again for every log line. We do not encourage approaches that are slow by their design.

**Comment by no-name420** [comment]
@mcollina 
Understandable, but I still think it would've been useful to have the option to force re-serializing certain values every time a new log is written, or at least have as a second param (to the ```log.error``` function for example) an array of keys which will be re-serialized while creating the current log

**Comment by mcollina** [comment]
Thanks for the feedback, we'll think about it.
