### ISSUE TITLE
Message encapsulation in logs

### ISSUE THREAD

**Issue by shennan** [pinojs/pino#933]
Is there a reason why arguments passed through logging functions are not encapsulated somehow within the logs themselves? Things like `level`, `time`, `pid` and `hostname` should have special meaning within the logging data, but any other data passed seems to be spread into the root object rather than encapsulated in another key (such as `msg`).

Example:

```js
logger.info('Hello world')
logger.info({foo: 'bar'}, 'Hello world')
logger.info({msg: 'End of World'}, 'Hello World')
```

```
{"level":30,"time":1607015478941,"pid":43304,"hostname":"iMac","msg":"Hello world"}
{"level":30,"time":1607015478942,"pid":43304,"hostname":"iMac","foo":"bar","msg":"Hello world"}
{"level":30,"time":1607015478942,"pid":43304,"hostname":"iMac","msg":"Hello World"}
```

In the second log, `foo` is not encapsulated, so in theory you can override top-level properties. Is there a reason for this?

In the third log, we are losing `msg`. In my use case, I occasionally log WebSocket messages or errors which could contain a `msg` key in them. This data could be lost in situations where I also added a string message as a last argument.

I get that you guys [don't de-dupe](https://github.com/pinojs/pino/blob/3a78dbc8fa29dac1ad242b9d564abb9399c055bd/docs/child-loggers.md#duplicate-keys-caveat) for performance reasons; but I'm more interested in why you don't encapsulate arguments from logging functions into a specific key on the raw json data?

**Comment by jsumners** [comment]
That's the original design of the logger that inspired this one. To encapsulate your information:

```js
const myData = { foo: 'foo' }
logger.info({ myData }, 'hello')
```

**Comment by jsumners** [comment]
Additionally, you can use the `logMethod` hook to do this automatically if you truly wish. The example included in the documentation can be tweaked to do this:

https://github.com/pinojs/pino/blob/3a78dbc8fa29dac1ad242b9d564abb9399c055bd/docs/api.md#logmethod

**Comment by shennan** [comment]
Ok, I'd not used Bunyan before so perhaps that is what had confused me. Thanks for the extra info.
