### ISSUE TITLE
Upgrading v5 to v6

### ISSUE THREAD

**Issue by fcanela** [pinojs/pino#938]
I am considering upgrading to the latest version of `pino` but I find no changelog or checklist.

For older versions, there is documentation available at https://github.com/pinojs/pino/blob/master/docs/legacy.md, but it seems the v5 to v6 upgrade was not documented.

Have I missed any documentation? Is it safe to upgrade?

Thanks! :)

**Comment by mcollina** [comment]
You can find the release notes at https://github.com/pinojs/pino/releases/tag/v6.0.0.

**Comment by fcanela** [comment]
Thanks, @mcollina! :+1:  I am closing the issue.

**Comment by fcanela** [comment]
Good point! I will. Thanks for the suggestion, @mcollina
