### ISSUE TITLE
Pino showing the wrong time (one hour too early)

### ISSUE THREAD

**Issue by pandaniell** [pinojs/pino#945]
I am using WSL2, I have `"pino": "^6.9.0"` and `"pino-pretty": "^4.3.0"`installed and I am using the following config
```typescript
import pino from "pino"

const prettyPrint: pino.LoggerOptions["prettyPrint"] = {
  colorize: true,
  ignore: "hostname,pid",
  translateTime: "yyyy-mm-dd HH:MM:ss",
}

export const logger = pino({
  name: process.env.npm_package_name,
  ...(process.env.NODE_ENV === "development" && { prettyPrint }),
})
```
I noticed that the time in my logs is not the right time, when I run `date +"%T"` I get `23:17:16` while pino outputs `[2021-01-01 22:17:16] INFO       (my-project-name): Hello`

Also small question: would `node dist/index.js | pino-redis -U redis://username:password@localhost:6379` be enough for your recommendation? `In Pino parlance we call all log processors "transports", and recommend that the transports be run as separate processes, piping the stdout of the application to the stdin of the transport.`

**Comment by mcollina** [comment]
In which timezone are you in?

**Comment by pandaniell** [comment]
> In which timezone are you in?

Europe/Amsterdam

**Comment by mcollina** [comment]
Pino logs in UTC. I think you are not printing the timezone.

**Comment by pandaniell** [comment]
Thanks I will look into this
