### ISSUE TITLE
Improve documentation about passing errors

### ISSUE THREAD

**Issue by vassbence** [pinojs/pino#948]
Hi!

We should improve docs about when and where can/should one pass an `Error` to be correctly serialized, for example `.error(new Error("test"))"` and `.info({err: new Error("test")})` works but `.warn(new Error("test"))` does not.

Would a dev be so kind as to list out all the possible variations? So that I can submit a PR and make it clear in the docs that when does pino serialize errors and when it not.

**Comment by mcollina** [comment]
What you listed is all of it! Thanks for offering to send a PR.

What's not working with `.warn(new Error("test"))`? This should work as expected (an error logged at the "Warn" level).

**Comment by vassbence** [comment]
Submitted the PR.

About `.warn()`: I think I just messed something up on my end, checked it again and passing errors works as expected.
