### ISSUE TITLE
readme mixin doc: wrong sample code

### ISSUE THREAD

**Issue by hraban** [pinojs/pino#951]
The section on mixins in the readme has the following code:

```js
const mixin = {
    appName: 'My app'
}

const logger = pino({
    mixin(obj) {
        return {
          description: obj.description
        }
    }
})

pino.info({
    description: 'Ok'
}, 'Message 1')
// {"level":30,"time":1591195061437,"pid":16012,"hostname":"x","appName":"My app","description":"Ok" "msg":"Message 1"}
pino.info('Message 2')
// {"level":30,"time":1591195061437,"pid":16012,"hostname":"x","appName":"My app","description":"Ok","msg":"Message 2"}
// Note: the second log contains "description":"Ok" text, even if it was not provided.
```

but (after fixing the last two `pino` references to `logger`), the prophecy in the logs doesn't actually come to be.

What was this bit of code intended to illustrate?

https://github.com/pinojs/pino/blob/master/docs/api.md#mixin-function

**Comment by jsumners** [comment]
https://github.com/pinojs/pino/pull/857

**Comment by hraban** [comment]
Interesting. That snippet made sense as merged in that PR, but has since been edited to lose its intended meaning.

**Comment by mcollina** [comment]
I think we made a mistake in https://github.com/pinojs/pino/pull/928. Would you like to send a PR to fix?

**Comment by hraban** [comment]
PR: #952
