### ISSUE TITLE
Redacting headers in express

### ISSUE THREAD

**Issue by BryanDollery** [pinojs/pino#955]
Hi,

Pino seems quite nice and relatively easy to use. But, I really don't want to be logging my Authorization bearer token. I've searched and searched and can't find any reference to how to redact it. I do have other redactions, for the password in my auth method for example, but the express-pino-logger doesn't seem to log the request body anyway. 

I'd love to know how to redact that token so that I can push my software to production. I can't go to prod like this -- I'd get slaughtered for logging that (I'm meant to be a professional ;).

TIA

**Comment by mcollina** [comment]
It would be good if you included a full example to reproduce, thanks! You should be able to redact it by using `req.headers.authorization` as a redaction key.

**Comment by BryanDollery** [comment]
That fixed it for me, thanks. Sample code wouldn't really help much because it's not a bug in the code, rather it's a lack of documentation I think. I couldn't find a reference anywhere that explained the technique you've just explained to me. And I tried; I really did. But I couldn't find that in the redaction docs for pino or express-pino-logger. Of course, its always possible that I missed it.

Thanks for the tip though, it solved the problem instantly. I appreciate the help.

**Comment by jsumners** [comment]
The docs explain how to configure redaction -- https://github.com/pinojs/pino/blob/eca5800eb924788e987900a762a48f78d12d57e8/docs/redaction.md

What is unclear about them?

**Comment by BryanDollery** [comment]
The docs don't seem to mention how to redact a header, and there is no mention of res.headers. Unless I'm going blind in my old age :)

I have searched that page for the word 'header' and it is nowhere to be found. Am I just reading it wrong?

**Comment by mcollina** [comment]
An HTTP header is just a property in the `req.headers` object. The doc describe the generic case of redacting an object property.

**Comment by BryanDollery** [comment]
Yes, it does that, you're right. But it isn't made clear in the express-pino-logger documents that the request object is available for use in a path. I suppose if one were an expert in express middleware this might be obvious, but I'm not. I googled this for quite a while before raising an issue asking for help, but couldn't find anything along the lines of the solution offered here.

I'm busy right now, but when I'm done maybe I'll contribute some recipes to the express-pino-logger docs and issue a pull request for them. I'm the one who had the problem, so I should perhaps be the one who fixes it.

Thanks again for the help.

**Comment by mcollina** [comment]
Thanks, those will be greatly appreciated!
