### ISSUE TITLE
Reorder / dictate the order of output params?

### ISSUE THREAD

**Issue by AviBueno** [pinojs/pino#958]
Attached is a screenshot of AWS logs:
* The left (blue) part is given.
* The right (green) part is the meat of the log and is the most interesting part, having the "message" field being last, although it should probably be the first one.
* The middle (red) part is a list of default Fastify-Pino attributes. This is the least interesting part, yet it occupies most of the line's real-estate.

### The question:
Is there any way (some hook perhaps) that would allow manipulating the logged object just before being output, making it possible to reorganize the order of the params?

Thanks.

![image](https://user-images.githubusercontent.com/5699730/105577016-8d6ea300-5d7f-11eb-9c14-43f7404d12bc.png)

**Comment by jsumners** [comment]
One of the primary ways Pino achieves its speed is by constructing the JSON manually. We are unlikely to be able to support this sort of feature efficiently. I would suggesting browsing your logs through an interface that can interpret the JSON data and present the fields you are interested in clearly.

**Comment by AviBueno** [comment]
Fair enough.
Thanks.
