### ISSUE TITLE
Update all child loggers levels simultaneously 

### ISSUE THREAD

**Issue by avaly** [pinojs/pino#959]
From the docs and source code, I understand that the child loggers get their log level at the time they are created. 

Is there any way to update all child loggers' log level at the same time?

My use case is the following code:

```
const logger = pino({ level: 'info' });
logger.info('hello world');

const child = logger.child({ a: 'property' });
child.debug('hello child');
```

At some point in time during the app's runtime, I'd like to enable/disable a "debug" mode for my app. The expected outcome would be that all child loggers get an updated log level and they start logging with the `debug` level.

I could wrap the `logger.child` method probably and store a reference to all child loggers in my app and update the level in those logger instances.

But I thought that maybe there's something more friendly in the library that allows me to achieve this. Is there?

**Comment by jsumners** [comment]
https://github.com/pinojs/pino-arborsculpture

**Comment by avaly** [comment]
Unfortunately `pino-arborsculpture` requires that all loggers be known upfront. My use case is a complex app with hundreds of child loggers scattered through out the codebase.

**Comment by jsumners** [comment]
Then you'll need to come up with an alternate approach. Probably one where you wrap `pino.child` to register the created loggers so that you can mutate them when necessary.
