### ISSUE TITLE
How to use in NodeJS Worker?

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#968]
`process.stdout.fd` is `undefined` in workers and thus `pino.destination` fails.

**Comment by jsumners** [comment]
What output stream _is_ defined in a worker? Can you pass that as the destination?

**Comment by ronag** [comment]
> What output stream _is_ defined in a worker? Can you pass that as the destination?

I'm not sure I understand the question? Can't a worker write to stdout?

**Comment by jsumners** [comment]
I haven't ever used a worker. I'm going on the information you provided.

**Comment by ronag** [comment]
> What output stream is defined in a worker?

stdout is defined

**Comment by ronag** [comment]
Figured it out. Pass stdout as stream.
