### ISSUE TITLE
Question: Best way to avoid printing buffer contents

### ISSUE THREAD

**Issue by jmealo** [pinojs/pino#974]
I would like to avoid printing the content of buffers. I know I can do this globally (with possible side effects) by overriding the prototype. Is there a better way to override this behavior in pino? I don't control the structure of the logs; so if I made any kind of custom serializer, I'd have to iterate over every property.

**This works with pino:**
```javascript
Buffer.prototype.toJSON = function toJSON() {
    return {
        type: 'buffer',
        length: this.length,
        data: '<redacted>'
    }
}
```

**This does not work with pino (but works with `debug` and similar):**
```javascript
const inspect = Symbol.for("nodejs.util.inspect.custom");
const { Buffer } = require("buffer");
Object.assign(Buffer.prototype, {
  [inspect]() {
    return "<Buffer>";
  }
});
```
As suggested in: https://github.com/Azure/azure-sdk-for-js/issues/13824#issuecomment-786133617

**Use case:** I've redirected logging from Azure's SDK to Pino. They're working on proper structured logging support, in the meantime, I've noticed that logging from AQMP operations often includes a buffers of the encoded message. These buffers are lengthy and when using `pino-pretty` they consume many lines. It's disruptive during development because it blows your terminal buffer out and could eat up space in production. This may be useful enough to add as a configuration option if there is a reasonably performant way to do this.

**I'd like to figure out a way to do this without adding iteration or impacting performance. :)**

**Comment by mcollina** [comment]
Pino creates structured JSON logs. console.log and debug use util.inspect from Node.js, which does not generate JSON. I'm afraid we can't help much in this... your solution would be how I would implement this.
