### ISSUE TITLE
First class doc about arguments of logging methods

### ISSUE THREAD

**Issue by glensc** [pinojs/pino#978]
Currently, in [https://github.com/pinojs/pino#usage](https://github.com/pinojs/pino/tree/ca600fc423fdf402ab67ae4bbd63e76db36cdd8e#usage) there is not even covered how non-string arguments and objects must be passed.

So I wrote:
```ts
logger.error("Here be dragons: ", e);
logger.error("Dragons be gone", { e });
```

But this (with prettier) results in:

```
[1614854677187] ERROR (75398 on rocinante): Here be dragons:
[1614854677190] ERROR (75398 on rocinante): Dragons be gone
```

I was expecting it to behave like [`console.log`](https://developer.mozilla.org/en-US/docs/Web/API/Console/log#syntax):
```js
console.log(obj1 [, obj2, ..., objN]);
console.log(msg [, subst1, ..., substN]);
```

however, seems pino expects object (only one?) to be specified as first argument:

```ts
logger.error(e, "Here be dragons: ");
logger.error({ e, f: e }, "Dragons be gone", "forever");
```

Even the code above itself seems oddly reversed,
it outputs like the console.log style code was shown above:

```
[1614854750142] ERROR (75439 on rocinante): Here be dragons:
    Error:
        at logger.test.ts:6:11
        ...
[1614854948285] ERROR (75537 on rocinante): Dragons be gone
    e: {}
    f: {}
```

**Comment by mcollina** [comment]
> I was expecting it to behave like console.log:

What did you make it expect so?

FYI, this has not parity with `console.log()`, it's a different library.

**Comment by jsumners** [comment]
The "Usage" section of the main Readme is an example. Do you expect the full documentation there? The full documentation is at https://github.com/pinojs/pino/blob/ca600fc423fdf402ab67ae4bbd63e76db36cdd8e/docs/api.md#logger

**Comment by glensc** [comment]
@jsumners hence the issue, I read frontpage I see a partial example I go away. There's not even 'read more' link right now. Maybe it's cleverly hidden, so people don't go away? start using it and then find the awkward api, and then it's too late to go away?

@mcollina why would I expect something else? People start with `console.log` in their code, and later find need more control where the logs go, so start looking for frameworks. other logging frameworks. I've come contact to, follow a similar principle, first is message and then optional arguments, arguments can be objects.

In my opinion, the example of library readme use must include example of how to print any objects and `Error` objects.

**Comment by jsumners** [comment]
Pull requests that improve documentation are always welcome.

**Comment by glensc** [comment]
@jsumners there's no explanation of what `%j`, etc formatters do.

**Comment by glensc** [comment]
1. for arguments loss, this patch is needed: https://github.com/pinojs/pino/pull/979/files

not sure how to behave on `console.log('see this error', e);` equivalent, there's example hook, but now this needs to be combined with the above hook.
