### ISSUE TITLE
After upgrade the msg field is missing from the logs

### ISSUE THREAD

**Issue by budarin** [pinojs/pino#983]
After last upgrade pino deps have noticed that msg field is missing from all my logs

I do log like this:
`logger.info({ msg: 'Log something...', params, options })`

I see in loki
`{..., msg: "", params, options }`

my pino configuration
```
const formatters = {
    level(label) {
        return { level: label };
    },
};
const options = {
    formatters,
    ...(__DEV__ && !CI && prettyPrint),
    level: "info",
    base: null,
};

 let logger!;

if (__DEV__) {
    logger = pino(options, pino.destination(1));
}

if (__PROD__) {
    logger = pino(
        options,
        pino.destination({
            minLength: 4096,
            sync: false,
        }),
    );

    setInterval(function () {
        logger.flush();
    }, logFlushInterval).unref();
}

module.exports = logger;
```

"pino": "^6.11.1",
"pino-pretty": "^4.7.1",

What is changed ? I have not found any in releases about it

**Comment by jsumners** [comment]
What was the prior version and the version you upgraded to?

**Comment by budarin** [comment]
@jsumners 

"pino": "^6.11.1",
"pino-pretty": "^4.7.1",

judging by the logs, the versions of pink-pretty have changed, but this module is not enabled in prod mode, although in dev mode is also `msg=""`

**Comment by jsumners** [comment]
What does `pino-pretty` have to do with this issue? Which version of `pino` were you using before the upgrade that worked as expected?

**Comment by budarin** [comment]
![image](https://user-images.githubusercontent.com/8055157/110851373-fffcf900-82c1-11eb-9193-df3ae81dd055.png)

**Comment by budarin** [comment]
I noticed a missing one today, and the latest pino updates were only in the pino-pretty part for the last 3 days

**Comment by jsumners** [comment]
I am unable to help you if you cannot provide answers to my questions. Showing me screenshots of logs does not tell me the version of the libraries you were using that worked as you expected. Without that information, I cannot begin to determine any cause.

**Comment by budarin** [comment]
I need time to investigate what changes and when led to this - I will roll back in git to find when everything was ok

**Comment by budarin** [comment]
@jsumners 
while tracing code  `pino/lib/tools.js`
```
function LOG (o, ...n) {
    if (typeof o === 'object') {
      let msg = o
      if (o !== null) {
        if (o.method && o.headers && o.socket) {
          o = mapHttpRequest(o)
        } else if (typeof o.setHeader === 'function') {
          o = mapHttpResponse(o)
        }
      }
      if (this[nestedKeySym]) o = { [this[nestedKeySym]]: o }
      let formatParams
      if (msg === null && n.length === 0) {
        formatParams = [null]
      } else {
        msg = n.shift()
        formatParams = n
      }
      this[writeSym](o, format(msg, formatParams, this[formatOptsSym]), level)         <----- msg always = ""
    } else {
      this[writeSym](null, format(o, n, this[formatOptsSym]), level)
    }
  }
```
msg always is empty when `o` is `object` like `o = {msg: "API call duration", duration: 41.74085000157356}`

**Comment by budarin** [comment]
I've found - `quick-format-unescaped` has been changed - it rerurns different result for the input params
`f = undefined, args = [], opts = {stringify: ƒ}` 

before
```
function format(f, args, opts) {
  var ss = (opts && opts.stringify) || tryStringify
  var offset = 1
  if (typeof f === 'object' && f !== null) {
    var len = args.length + offset
    if (len === 1) return f
    var objects = new Array(len)
    objects[0] = ss(f)
    for (var index = 1; index < len; index++) {
      objects[index] = ss(args[index])
    }
    return objects.join(' ')
  }
  if (typeof f !== 'string') {
    return f                                 <-returns `undefined`
  }
  var argLen = args.length
  if (argLen === 0) return f
  var x = ''
  ...
 ```

after
```
function format(f, args, opts) {
  var ss = (opts && opts.stringify) || tryStringify
  var offset = 1
  if (typeof f === 'object' && f !== null) {
    var len = args.length + offset
    if (len === 1) return f
    var objects = new Array(len)
    objects[0] = ss(f)
    for (var index = 1; index < len; index++) {
      objects[index] = ss(args[index])
    }
    return objects.join(' ')
  }
  var argLen = args ? args.length : 0
  if (argLen === 0) return f === undefined ? '' : f     <-- returns ""
  var str = ''
....
```

**Comment by jsumners** [comment]
> I dont understand why 4.0.2 is included in my project

Because it is a dependency of `pino`.

@davidmarkclements 4.0.2 of `quick-format-unescaped` results in a change in `pino`:

```js
'use strict'

const log = require('pino')()

log.info('foo %s', 'bar')
log.info({ msg: 'foo bar' })
```

With qfu@4.0.1:
```json
{"level":30,"time":1615551910825,"pid":75515,"hostname":"mini2018","msg":"foo bar"}
{"level":30,"time":1615551910825,"pid":75515,"hostname":"mini2018","msg":"foo bar"}
```

With qfu@4.0.2:
```json
{"level":30,"time":1615551862376,"pid":75370,"hostname":"mini2018","msg":"foo bar"}
{"level":30,"time":1615551862376,"pid":75370,"hostname":"mini2018","msg":""}
```

**Comment by davidmarkclements** [comment]
sorry everyone - my fault this time

thanks to @mcollina 4.0.3 should fix this if you reinstall
