### ISSUE TITLE
Base config for field `name`

### ISSUE THREAD

**Issue by alexpts** [pinojs/pino#993]
```
  let logger = pino({
       base: {
          'index': 'some_base'
      },
  });
  ```
  
I have field `name` in log. How I can remove `name` field with custom base config?

**Comment by jsumners** [comment]
I do not understand the question, but it seems like you are asking about duplicate keys -- https://github.com/pinojs/pino/blob/853818ce51e34c4e9ae1522bf94ecc2a43be2fec/docs/child-loggers.md#duplicate-keys-caveat

**Comment by alexpts** [comment]
How I cat write log without field `name`?
