### ISSUE TITLE
Benchmark very confusing

### ISSUE THREAD

**Issue by jpambrun** [pinojs/pino#994]
Looking at https://getpino.io/#/docs/benchmarks:

```
pino.info('hello world'):

BASIC benchmark averages
Bunyan average: 662.904ms
Winston average: 564.752ms
Bole average: 301.894ms
Debug average: 361.052ms
LogLevel average: 330.394ms
Pino average: 246.336ms
PinoAsync average: 129.507ms
PinoNodeStream average: 276.479ms
```

It looks like I can expect to log 'hello world' about 4 time per second (given the 246ms average..).

Then, running `time npm run bench-basic` locally:
```
Running BASIC benchmark
benchBunyan*10000: 416.372ms
benchWinston*10000: 470.126ms
benchBole*10000: 163.395ms
benchDebug*10000: 271.555ms
benchLogLevel*10000: 268.904ms
benchPino*10000: 120.047ms
benchPinoAsync*10000: 76.02ms
benchPinoNodeStream*10000: 160.221ms
benchBunyan*10000: 381.766ms
benchWinston*10000: 403.257ms
benchBole*10000: 134.792ms
benchDebug*10000: 273.633ms
benchLogLevel*10000: 242.456ms
benchPino*10000: 114.168ms
benchPinoAsync*10000: 71.516ms
benchPinoNodeStream*10000: 143.469ms
```
I can sort of understand that I can log "hello world" 4 * 10,000 = 40,000 time per second. (Looks like my computer is twice as fast, but I am keeping the 4 for consistency)

Yet looking at the [implementation](https://github.com/pinojs/pino/blob/master/benchmarks/basic.bench.js#L45-L48): 
``` js 
const max = 10
// ...
    for (var i = 0; i < max; i++) {
      blog.info('hello world')
    }
```

It looks like it really is 4 * 10,000 * 10.. It's probably best to reword the documentation of benchmark output a little bit.

**Comment by mcollina** [comment]
Would you like to send a PR? Thanks!
