### ISSUE TITLE
unable to try/catch error from creating the logger

### ISSUE THREAD

**Issue by jchip** [pinojs/pino#995]
I may be missing some options here.

The following code to create a logger:

```js
const pino = require("pino");

try {
  pino({}, "/bad/test");
} catch (err) {
  console.log("create pino failed", err.message);
}
```

It seems even though the code caught the error, somewhere down the Pino code path, the error is being emitted as an uncaught error.

Is this intended?

Is there some options to turn off this behavior?

Is there a way to gracefully handle this (other than may be installing an uncaught exception handler?)

**Comment by jsumners** [comment]
This is down to the automatic creation of the destination stream and whatever it causing the destination path to be inaccessible (cc: @mcollina). As a solution, I would suggestion using `pino.destination` yourself to create the stream before passing it to Pino if you need this arbitrary output destination -- https://github.com/pinojs/pino/blob/853818ce51e34c4e9ae1522bf94ecc2a43be2fec/docs/api.md#destination

**Comment by mcollina** [comment]
I'll fix this

**Comment by mcollina** [comment]
@jsumners could you review https://github.com/mcollina/sonic-boom/pull/64? It solves this.

**Comment by jsumners** [comment]
Done.

**Comment by mcollina** [comment]
This is fixed in the latest release of sonic-boom, update your deps!
