### ISSUE TITLE
Map not displayed as the console.log does

### ISSUE THREAD

**Issue by tommy-v** [pinojs/pino#997]
**Version 6.11.1**

I thought it could be interesting to display the Map as the console.log does in this example:

```js
const map = new Map();
map.set('test', 'value');

console.log(map);
this.logger.info({ msg: 'stuff', map }); // Pino
```

**Console result**
```console
console.log: Map(1) { 'test' => 'value' }

Pino: [2021-03-31 18:26:41] INFO (972): stuff
Pino:     map: {}
```

It is confusing to see the Map as an empty object.

**Comment by jsumners** [comment]
Pino != `console.log`

The `console.log` implementation uses [util.inspect](https://nodejs.org/dist/latest-v14.x/docs/api/util.html#util_util_inspect_object_options). That is a very expensive operation.

I recommend adding a serializer to handle your case. Or you can use the `logMethod` hook to do inspections and rewriting. Again, that would result in disastrous performance but it's up to you.

**Comment by jarstelfox** [comment]
Hey @tommy-v,

Take a look at https://stackoverflow.com/questions/29085197/how-do-you-json-stringify-an-es6-map. In short, Maps are not easily turned into json. 
```js
const map = new Map();
map.set('foo', 'bar');
map.set('baz', 'quz');

const jsonText = JSON.stringify(map); // {}
```


You will likely need to handle this edge case in logging yourself. If you have a 1D Map then `JSON.stringify(Array.from(map.entries()));` works great.

---

I suspect this may always be the case with pino. It's up to the developer to handle how to render a map in all browsers
